fluid-cloudnative/fluid

docs/en/samples/machinelearning.md
docs/zh/samples/machinelearning.md

Fix format of docs for machine learning

---

.circleci/config.yml
README-zh_CN.md
README.md
vendor/github.com/json-iterator/go/.codecov.yml

add badges
.
1. 向中文和英文README中添加了badges。
2. 删除了vendor/github.com/json-iterator/go/.codecov.yml，它之前导致codecov需要token才能正常上传。
NONE
circleci添加项目需要写权限,需要owner来完成，操作如下：
1. 使用github账号登录https://circleci.com/
2. 访问https://circleci.com/gh/fluid-cloudnative/fluid ,然后点击set up project。

add badges

---

api/v1alpha1/alluxioruntime_types.go
pkg/common/constants.go
pkg/controllers/v1alpha1/dataload/implement.go
pkg/controllers/v1alpha1/dataset/dataset_controller.go
pkg/csi/fuse/driver.go
pkg/ddc/alluxio/create_volume.go
pkg/ddc/alluxio/dataset.go
pkg/ddc/alluxio/node.go
pkg/utils/charts.go
pkg/utils/kubeclient/volume.go

Signed-off-by: Li Yi <denverdino@gmail.com>
Fix some typos and warnings found by static check
https://staticcheck.io/
```staticcheck ./...```

Fix some typos and warnings found by static check

---

Makefile

Makefile should use tab as indentation.

Let Makefile use tab indent

---

docs/en/userguide/install.md
docs/zh/userguide/install.md

[Doc]Make install.md install Fluid from releases

---

.circleci/config.yml

Add circleci test

---

.circleci/config.yml

Update unit test

---

docs/en/userguide/get_started.md
docs/en/userguide/troubleshooting.md
docs/zh/userguide/get_started.md
docs/zh/userguide/troubleshooting.md

Fix doc error

---

README-zh_CN.md
README.md

Add travis badge

---

Makefile

Update Makefile to use vendor only
NONE

Update Makefile to use vendor only

---

README.md

add concepts in readme

---

docs/en/dev/how_to_develop.md
docs/en/userguide/get_started.md
docs/zh/dev/how_to_develop.md
docs/zh/userguide/get_started.md
docs/zh/userguide/troubleshooting.md

修正了markdown中部分有序列表的缩进，这曾经导致有序列表在jekyll上渲染错误。
NONE
在使用common markdown标准的编辑器(比如goland)中打开docs/zh/dev/how_to_develop.md,其中有序列表序号都为1.

markdown lint

---

cmd/csi/main.go
pkg/csi/fuse/controller.go
pkg/csi/fuse/nodeserver.go
pkg/ddc/alluxio/cache.go
pkg/ddc/alluxio/create_volume.go
pkg/ddc/alluxio/label.go
pkg/ddc/alluxio/node.go
pkg/ddc/alluxio/replicas.go
pkg/ddc/alluxio/shutdown.go
pkg/ddc/alluxio/types.go
pkg/ddc/alluxio/utils.go
pkg/utils/dataset_condition.go
pkg/utils/kubeclient/exec.go
pkg/utils/runtime_condition.go

Fix the golang-ci linit: https://travis-ci.org/github/fluid-cloudnative/fluid/jobs/723445815
NONE

Clean up the code

---

.travis.yml

Add static go code check and markdown linter.
NONE
1.添加了go静态检查工具golangci-lint，可以参考https://golangci-lint.run/usage/linters/    ，目前有些检查项存在误报(比如errcheck，可以通过设置来关闭。
2.添加了markdown检测工具mdl，错误信息可以参考https://github.com/markdownlint/markdownlint/blob/master/docs/RULES.md。

Modify CI tests in .travis.yml

---

docs/en/userguide/get_started.md
docs/zh/userguide/get_started.md

Remove 'minikube' parts from get started. Use standard cloud Kubernetes services as default choices for new coming users. minikube is not recommended for deploying Fluid due to its limited functionalities.
NONE

[DOC]Rewrite get_started.md

---

docs/en/dev/how_to_develop.md
docs/zh/dev/how_to_develop.md
pkg/controllers/v1alpha1/alluxio/suite_test.go
pkg/controllers/v1alpha1/dataset/suite_test.go

- Add description on how to run unit tests
- Fix CRDDirectoryPaths in controller tests
@cheyang  @biubiu-biub

Update docs for dev

---

docs/en/dev/how_to_develop.md
docs/en/samples/machinelearning.md
docs/zh/dev/how_to_develop.md
docs/zh/samples/machinelearning.md

Add clean step for machinelearning.md

---

Dockerfile
Dockerfile.csi
config/samples/data_v1alpha1_alluxioruntime.yaml
docs/en/dev/how_to_develop.md

- Remove `go-delve` part in Dockerfiles. `go-delve` may be inaccessible due to some network issue, which may cause a image build error.
- Fix typo in `how_to_develop.md`
- Update sample for develop use
NONE

Update developer's guide

---

README.md

update project logo

---

README.md

update logo size

---

config/samples/data_v1alpha1_alluxioruntime.yaml
docs/en/samples/accelerate_data_accessing.md
docs/en/samples/data_co_locality.md
docs/en/samples/machinelearning.md
docs/en/userguide/get_started.md
docs/zh/samples/accelerate_data_accessing.md
docs/zh/samples/data_co_locality.md
docs/zh/samples/machinelearning.md
docs/zh/userguide/get_started.md
samples/accelerate/runtime.yaml
samples/co-locality/runtime.yaml
samples/dawnbench/runtime.yaml
test/testcase1/testcase1_runtime.yaml
test/testcase2/runtime.yaml

Delete annotation fields in doc, the fields will be use in the future? if yes, i will close the pr ：）
NONE
@cheyang

Fix doc: delete annotation fields

---

charts/fluid/fluid/values.yaml
docs/zh/samples/hostpath.md
pkg/ddc/alluxio/const.go
pkg/ddc/alluxio/engine.go
pkg/ddc/alluxio/operations/local_test.go
pkg/ddc/alluxio/transform.go
pkg/ddc/alluxio/transform_ufs_test.go
pkg/ddc/alluxio/trasform_optimization.go
pkg/ddc/alluxio/trasform_optimization_test.go
pkg/ddc/alluxio/utils.go

Fix non root issue 

---

charts/alluxio/CHANGELOG.md
charts/alluxio/Chart.yaml
charts/alluxio/templates/fuse/daemonset.yaml
pkg/ddc/alluxio/transform.go

Translate the user id

---

charts/alluxio/templates/master/statefulset.yaml
charts/alluxio/templates/worker/daemonset.yaml
charts/fluid/fluid/values.yaml
docs/zh/samples/hostpath.md
pkg/ddc/alluxio/const.go
pkg/ddc/alluxio/transform.go
pkg/ddc/alluxio/transform_permission.go

Support Non root for hostpah

---

.github/ISSUE_TEMPLATE/bug-report.md
.github/ISSUE_TEMPLATE/feature-request.md
docs/zh/samples/hostpath.md

Update issue template

---

.travis.yml
Makefile
pkg/ddc/alluxio/operations/base_test.go

Use different test flags in CI and local enviroment.
None

use different test flags in CI and local enviroment

---

Makefile

fix Make issue

---

Makefile
charts/fluid/fluid/values.yaml

Build new images

---

docs/zh/samples/hostpath.md

Add hostpath demo doc(zh version)
Fixes #158

Add hostpath demo doc(zh version)

---

Makefile
charts/alluxio/CHANGELOG.md
charts/alluxio/Chart.yaml
charts/alluxio/docker/init-users/chmod_tierpath.sh
charts/alluxio/values.yaml
charts/fluid/fluid/values.yaml
docs/en/userguide/troubleshooting.md
docs/zh/userguide/troubleshooting.md

Update helm chart version and docker image

---

docs/zh/samples/accelerate_pvc.md

Add docs for accelerating pvc

---

charts/fluid/fluid/VERSION
charts/fluid/fluid/values.yaml
docs/zh/samples/hostpath.md
pkg/ddc/alluxio/transform.go
pkg/ddc/alluxio/transform_fuse.go
pkg/ddc/alluxio/transform_fuse_test.go
pkg/ddc/alluxio/transform_test.go

Fix the issue that Non-root users could not access the dataset
fixes #191

Fix Non-root users could not access the dataset

---

docs/en/userguide/troubleshooting.md
docs/zh/userguide/troubleshooting.md
tools/diagnose-fluid.sh

- by default, always collect logs of controller
- collect release info of fluid and runtime
fixes #178

Improve diagnose

---

charts/fluid/fluid/values.yaml

update docker images for non-root support

---

Makefile
charts/alluxio/CHANGELOG.md
charts/alluxio/templates/master/statefulset.yaml
charts/alluxio/templates/worker/daemonset.yaml
charts/alluxio/values.yaml
charts/fluid/fluid/values.yaml
docs/zh/samples/hostpath.md
pkg/common/constants.go
pkg/ddc/alluxio/engine.go
pkg/ddc/alluxio/transform_fuse_test.go
pkg/ddc/alluxio/transform_init_users.go
pkg/ddc/alluxio/transform_optimization.go
pkg/ddc/alluxio/transform_test.go
samples/ufspath/app.yaml
samples/ufsvolume/dataset.yaml

1. Enable host PID
2. Optimize Alluxio
- max_readahead=0 
- passive = false

Optimize Fluid

---

docs/en/samples/accelerate_data_accessing.md
docs/en/samples/data_co_locality.md
docs/zh/TOC.md
docs/zh/samples/accelerate_data_accessing.md
docs/zh/samples/data_co_locality.md
docs/zh/samples/nonroot_access.md
samples/accelerate/runtime.yaml
samples/co-locality/runtime.yaml

Update demo docs:
- Update demo doc "accelerate data accessing"
- Update demo doc "data co-locality"
- Add demo doc "guide for non-root users"
- Update related samples
- Update TOC
fixes #185 
`hostpath.md` should also be updated. Working on it

Update demo docs

---

docs/en/samples/accelerate_pvc.md
docs/zh/samples/accelerate_pvc.md

- [docs] accelerate pvc(en)
fixes #157

Add docs for pvc accelerating (en)

---

docs/zh/samples/hostpath.md

Update hostpath demo doc

---

CHANGELOG.md

Update Change log

---

CHANGELOG.md

Fix release note

---

docs/zh/samples/nonroot_access.md

Update docs 

---

README-zh_CN.md
README.md
docs/zh/TOC.md

Update info of new release

---

README-zh_CN.md
README.md

Add quick demo for accelerate PVC with Fluid
NONE
For reviewers, you can see my [head repository](https://github.com/TrafalgarZZZ/fluid/tree/update_pvc_demo) for a quick review

Add quick demo for accelerate PVC with Fluid

---

Makefile
charts/fluid/fluid/CHANGELOG.md
charts/fluid/fluid/Chart.yaml

Update chart to v0.4.0

---

docs/en/samples/accelerate_data_accessing.md
docs/zh/samples/accelerate_data_accessing.md

Update accelerate data accessing doc
NONE

Update accelerate data accessing doc

---

charts/fluid/fluid/templates/csi/daemonset.yaml
charts/fluid/fluid/values.yaml
config/fluid/bases/csi-plugin.yaml
csi/deploy/csi-fluid-daemonset.yaml
pkg/ddc/alluxio/const.go

Fix gke readonly issue

---

docs/en/userguide/troubleshooting.md
docs/zh/userguide/troubleshooting.md
tools/diagnose-fluid.sh

- Let diagnose script collect more resources
- Do not use `getopt` to parse parameters because of compatibility problems
- Update diagnose docs
fixed #215

Let diagnose script collect more resources

---

charts/fluid/fluid/values.yaml

Build docker images

---

Makefile
charts/fluid/fluid/values.yaml
version.go

Update docker image for csi version

---

charts/fluid/fluid/values.yaml

Update docker image

---

pkg/ddc/alluxio/master.go

Fix bug 224 by removing duplicated code
fixes #224 
No test case added, since the PR is only to remove duplicated code and the method is already covered.
The code change is verified by running UT and integration test

Fix bug 224 by removing duplicated code

---

pkg/ddc/alluxio/operations/base.go
pkg/ddc/alluxio/operations/cached.go
pkg/ddc/alluxio/operations/local.go
pkg/ddc/alluxio/shutdown.go
pkg/ddc/alluxio/status.go
pkg/ddc/alluxio/ufs.go
pkg/utils/byte_size.go
pkg/utils/crtl_utils.go
pkg/utils/dataset_condition.go
pkg/utils/helm/helm.go
pkg/utils/kubeclient/configmap.go
pkg/utils/kubeclient/exec.go
pkg/utils/kubeclient/namespace.go
pkg/utils/kubeclient/pod.go
pkg/utils/kubeclient/volume.go
pkg/utils/mount.go
pkg/utils/runtime_condition.go

Add or modify comments for multiple methods
NONE

Add or modify comments for multiple methods

---

charts/fluid/fluid/values.yaml

Update docker images

---

charts/fluid/fluid/values.yaml
pkg/ddc/alluxio/transform_optimization.go

Fix readonly issue

---

pkg/ddc/alluxio/transform_optimization.go

change `alluxio.user.file.create.ttl.action` to `FREE` rather than default `DELETE`
Fixes https://github.com/fluid-cloudnative/fluid/issues/234

Update default TTL action in Alluxio

---

charts/fluid/fluid/VERSION
pkg/ddc/alluxio/transform.go
pkg/ddc/alluxio/transform_fuse.go

Use Alluxio branch `branch-2.3-fuse`(latest commit id `7fa8e27`) as default Image
NONE

Update Alluxio default image for optimizing metadata management

---

charts/fluid/fluid/values.yaml

Update docker image for metadata optimization

---

charts/alluxio/templates/config/alluxio-conf.yaml

Remove Jvm options in ALLUXIO_USER_JAVA_OPTS
NONE

Remove Jvm options in ALLUXIO_USER_JAVA_OPTS

---

charts/alluxio/CHANGELOG.md
charts/alluxio/Chart.yaml
charts/fluid/fluid/values.yaml

Docker images 1025

---

charts/fluid/fluid/values.yaml

Update alluxio helm chart version

---

pkg/utils/helm/utils.go

Standardize the comment of `func CheckRelease` in pkg/utils/helm/utils.go
mapreduce课程作业，完成Task 5，将pkg/utils/helm/utils.go中的方法`func CheckRelease`上的注释规范化
NONE
Just fix comments
NONE
mapreduce课程作业，完成Task 5

Task 5：Standardize the comment of `func CheckRelease` in pkg/utils/helm/utils.go

---

pkg/utils/helm/utils.go

I normalized the comment on pkg/utils/helm/utils.go:ListReleaseMap function.
None.
These is no test cases because this task just modifies a comment, and does not do anything on original codes.
Verify the comments with stardard Go's Comment Standard.
None.

Normalize comment on pkg/utils/helm/utils.go:ListReleaseMap function.

---

pkg/ddc/alluxio/operations/base.go

I normalized the comment on pkg/ddc/alluxio/operations/base.go:IsExist function.
No
These is no test cases because this task just modifies a comment, and do nothing on original codes.
Verify the comments with stardard Go's Comment Standard.
None

Normalize the comments of IsExist function

---

pkg/utils/yaml.go

Add comment to ToYaml function in pkg\utils\yaml.go.
NONE

add comment to yaml.go

---

pkg/utils/crtl_utils.go

Normalize the comment on 'RequeueImmediatelyUnlessGenerationChanged' function. (pkg/utils/crtl_utils.go)
None.
Just normalize the comment.
Just check the comment.
None.

normalize the comment on 'RequeueImmediatelyUnlessGenerationChanged' function

---

pkg/ddc/alluxio/worker.go

This PR standardizes comments on function **SetupWorkers** in the file pkg/ddc/alluxio/worker.go.

standardize comments on function SetupWorkers

---

pkg/utils/dataset.go

I normalize comment on pkg/utils/dataset.go:GetDataset function.
NONE
NONE
Just read it.
NONE

Normalize comment on pkg/utils/dataset.go:GetDataset function

---

charts/fluid/fluid/values.yaml

Refactor the runtime and controller

---

pkg/utils/random.go

I have regularized the commit on "RandomString" function.
Only a commit have been changed, so no tests are needed.  
The change has been described in the log, just scan the file to verify it.

regularize commit on 'RandomString' function

---

pkg/utils/kubectl/configmap.go

I have normalized the comment on `CreateConfigMapFromFile` function.
NONE
No tests needed.
Just read the comment.

normalize the comment on `CreateConfigMapFromFile` function

---

docs/en/userguide/install.md
docs/zh/userguide/install.md

Edit the install doc of fluid.
Because the installation method we provide to users is charts, the change of Installation procedure is not very big.
fixes #276

edit install doc

---

pkg/utils/unix.go

Add comment to function SplitSchemaAddr().
No

add comment to 'SplitSchemaAddr' function

---

charts/fluid/fluid/templates/role/dataset/rbac.yaml
pkg/controllers/v1alpha1/dataload/implement.go
pkg/utils/dataset_runtime.go
pkg/utils/random.go

- Remove unnecessary metadata check for target dataset
- Directly check runtime status
NONE

Add patch for DataLoad controller

---

docs/en/samples/accelerate_data_accessing_by_hdfs.md

Document translation. (docs/en/samples/accelerate_data_accessing_by_hdfs.md)

document translation, line [190,221)

---

pkg/ddc/alluxio/master.go

Normalize the comment of func CheckMasterReady in pkg/ddc/alluxio/master.go

Normalize the comment of func CheckMasterReady

---

pkg/ddc/alluxio/engine.go

Formalize the comment of the AlluxioEngine struct.

formalize-the-comment-for-pkg/ddc/alluxio/engine.go

---

charts/fluid/fluid/VERSION
pkg/controllers/v1alpha1/dataload/implement.go
pkg/ddc/alluxio/transform.go
pkg/ddc/alluxio/transform_fuse.go

Update default Alluxio image
NONE

Update default Alluxio image

---

pkg/utils/kubeclient/node.go

modify the comments of func **IsReady** under the path : **pkg/utils/kubeclient/node.go**
fixes #297

modify comments of func IsReady

---

pkg/common/constants.go
pkg/controllers/v1alpha1/dataload/implement.go
pkg/dataload/constants.go

Update dataload phase "Loaded" to "Complete"
Fixes #308

Update dataload phase from "Loaded" to "Complete"

---

pkg/ddc/alluxio/master.go

Normalization of annotations on func SetupMaster(pkg/ddc/alluxio/master.go)
fixes #311

<Normalize_comments_on_func_SetupMaster>

---

pkg/utils/helm/utils.go

Normalize comments on func ListAllReleasesWithDetail (pkg/utils/helm/utils.go)
fixes #312

Normalized comment on ListAllReleasesWithDetail  Fixes #312

---

docs/en/samples/accelerate_data_accessing_by_hdfs.md

translation part of the file, 
fixes #319 
docs/zh/samples/accelerate_data_accessing_by_hdfs.md
follow the ppt

traslate part of accelerate_data_accessing_by_hdfs 

---

pkg/runtime/context.go

Standardize the comment on ReconcileRequestContext struct.(pkg/runtime/context.go)
NONE.
One comment was changed.

Standardize one comment on a struct.

---

charts/fluid/fluid/values.yaml

Fix non-root regression issue

---

pkg/utils/helm/helm.go

Remove remove redundant comment on GenerateHelmTemplate function.(pkg/utils/helm/helm.go)
fixes #301

Remove redundant comment task2

---

docs/zh/TOC.md
docs/zh/samples/data_warmup.md
samples/dataload/dataload.yaml
samples/dataload/dataset.yaml

Add demo guide about how to use DataLoad CRD
Fixes #277 
Fixes #278

Add demo guide about how to use DataLoad CRD

---

docs/en/dev/how_to_develop.md
docs/en/samples/accelerate_data_accessing.md
docs/en/samples/accelerate_data_accessing_by_hdfs.md
docs/en/samples/data_co_locality.md
docs/en/userguide/install.md
docs/zh/dev/how_to_develop.md
docs/zh/samples/accelerate_data_accessing.md
docs/zh/samples/accelerate_data_accessing_by_hdfs.md
docs/zh/samples/data_co_locality.md
docs/zh/samples/multi_dataset_same_node_accessing.md
docs/zh/userguide/install.md

Upgrade the docs of install and update fluid
fix some mistake in docs

upgrade docs of install and upgrade

---

charts/fluid/v0.4.0/.helmignore
charts/fluid/v0.4.0/CHANGELOG.md
charts/fluid/v0.4.0/Chart.yaml
charts/fluid/v0.4.0/VERSION
charts/fluid/v0.4.0/crds/data.fluid.io_alluxiodataloads.yaml
charts/fluid/v0.4.0/crds/data.fluid.io_alluxioruntimes.yaml
charts/fluid/v0.4.0/crds/data.fluid.io_dataloads.yaml
charts/fluid/v0.4.0/crds/data.fluid.io_datasets.yaml
charts/fluid/v0.4.0/templates/_helpers.tpl
charts/fluid/v0.4.0/templates/controller/alluxioruntime_controller.yaml
charts/fluid/v0.4.0/templates/controller/dataset_controller.yaml
charts/fluid/v0.4.0/templates/csi/daemonset.yaml
charts/fluid/v0.4.0/templates/csi/driver.yaml
charts/fluid/v0.4.0/templates/role/alluxio/rbac.yaml
charts/fluid/v0.4.0/templates/role/dataset/rbac.yaml
charts/fluid/v0.4.0/values.yaml

Create snapshot package

---

Makefile
README-zh_CN.md
README.md
charts/fluid/fluid/CHANGELOG.md
charts/fluid/fluid/Chart.yaml
charts/fluid/fluid/values.yaml

V0.5.0 started

---

docs/en/samples/nonroot_access.md

I translated the content in docs/zh/samples/nonroot_access.md to  docs/en/samples/nonroot_access.md
Fixes #330
No tests needed.
Just read the comment.

document-translation

---

pkg/utils/dataset_condition.go

It normalizes the annotation on `IsDatasetConditionExist` function. (pkg/utils/dataset_condition.go)
fixes #329
No tests are needed, one comment was changed.

normalize comment on `IsDatasetConditionExist` function

---

api/v1alpha1/dataset_types.go

modify two code comments

---

Makefile
README-zh_CN.md
README.md
charts/fluid/v0.4.0/VERSION
charts/fluid/v0.4.0/values.yaml
pkg/utils/helm/utils.go

Update alluxio image for v0.4.0

---

Makefile
charts/fluid/v0.4.0/values.yaml
pkg/ddc/alluxio/transform_optimization.go

Update docker image for v0.4.0

---

api/v1alpha1/dataset_types.go

Modify comments on `CanbeBound` function.(api/v1alpha1/dataset_types.go)
fixes #342

normalize comment

---

docs/en/userguide/get_started.md
docs/zh/userguide/get_started.md

Update get started

---

pkg/ddc/alluxio/status.go

Comment normalization for func CheckAndUpdateRuntimeStatus.
Fixes #352 

comment normalization for func CheckAndUpdateRuntimeStatus

---

pkg/ddc/alluxio/ufs.go

normalize comment on `FreeStorageBytes` function.(pkg/ddc/alluxio/ufs.go)
fixes #356

normalize comment on `FreeStorageBytes` function

---

docs/en/samples/nonroot_access.md

文档翻译（中译英） 翻译后文档位置： docs/en/samples/nonroot_access.md  从二级标题“运行示例”到加粗小标题(Line 13)“创建Dataset和AlluxioRuntime资源对象(Line 45)”之前的部分。
fix #354

translation task 53, non-root-access

---

pkg/utils/crtl_utils.go

add comment for function Now() which in pkg/utils/crtl_utils.go
fixes #355

add comment for function Now()

---

pkg/utils/helm/utils.go

Normalization of comments on func `ListReleases` in `pkg/utils/helm/utils.go`
fixes #360 
This is a comment, so test is not necessary.

normalize comment on func ListRelease fix #360

---

pkg/ddc/alluxio/operations/local.go

standardize the comments(pkg/ddc/alluxio/operations/local.go).
fixes #364 
None
No
See the describe

standardize_SyncLocalDir_comments

---

charts/fluid/fluid/CHANGELOG.md
charts/fluid/fluid/VERSION
charts/fluid/fluid/templates/controller/alluxioruntime_controller.yaml
charts/fluid/fluid/templates/controller/dataset_controller.yaml
charts/fluid/fluid/values.yaml
pkg/controllers/v1alpha1/dataload/implement.go
pkg/ddc/alluxio/transform.go
pkg/ddc/alluxio/transform_fuse.go
pkg/ddc/alluxio/transform_optimization.go

Update alluxio image with the latest fix

---

README-zh_CN.md
README.md

Add the video of demo4

---

tools/diagnose-fluid.sh

update diagnose-fluid.sh due to architecture changed
fixes #357
I have verified by excuting to  get tar.gz for diagnostics

fix diagnose-fluid.sh

---

pkg/ddc/alluxio/ufs.go

normalize the comment on 'UsedStorageBytes' function
Fixes #370

normalize the comment on 'UsedStorageBytes' function

---

pkg/utils/helm/utils.go

I normalized the comment on pkg/utils/helm/utils.go:DeleteRelease function.
fix #362 
These is no test cases because this task just modifies a comment, and does not do anything on original codes.
Verify the comments with stardard Go's Comment Standard.
None.

normalize comment on DeleteRelease function

---

pkg/utils/home.go

add comments to func home
fix #373 
pkgs/utils/home.go

Remove redundant comment

---

pkg/utils/helm/helm.go

normalize the comment on 'GetChartVersion' function in pkg/utils/helm/helm.go.
fixes #376

normalize comment on 'GetChartVersion' function

---

docs/zh/userguide/faq.md

…egistered CSI drivers
Add FAQ about csi error: fuse.csi.fluid.io not found in the list of registered CSI drivers
#214

Add FAQ about csi error

---

charts/fluid/fluid/VERSION
charts/fluid/fluid/templates/controller/alluxioruntime_controller.yaml
charts/fluid/fluid/templates/controller/dataset_controller.yaml
charts/fluid/fluid/values.yaml
docs/zh/dev/how_to_develop.md
pkg/common/alluxio.go
pkg/common/constants.go
pkg/controllers/v1alpha1/dataload/implement.go
pkg/ddc/alluxio/transform.go
pkg/ddc/alluxio/transform_fuse.go
pkg/ddc/alluxio/transform_optimization.go
pkg/ddc/alluxio/utils.go
pkg/utils/docker/image.go
pkg/utils/docker/image_test.go
pkg/utils/helm/utils.go

Make alluxio image configurable

---

docs/en/dev/profiling.md

translate doc in docs/zh/dev/profiling.md

translate doc

---

docs/en/samples/data_warmup.md
docs/zh/samples/data_warmup.md

Add DataLoad CRD guide doc (en version)
NONE

Add DataLoad CRD guide doc (en version)

---

tools/alluxio/build-image.sh
tools/alluxio/readme.md

update the script so that users can set their own image names and push images to their own repositoris. 
fixes #340

support to set the image name

---

charts/fluid/fluid/values.yaml
pkg/ddc/alluxio/transform_optimization.go
tools/alluxio/build-image.sh

Update job retention period

---

docs/en/samples/multi_dataset_same_node_accessing.md
docs/en/userguide/faq.md

add English docs which are "faq.md" and "multi_dataset_same_node_accessing.md". 
NONE

add English docs

---

api/v1alpha1/dataset_types.go
charts/fluid/fluid/crds/data.fluid.io_datasets.yaml
config/crd/bases/data.fluid.io_datasets.yaml
pkg/controllers/runtime_controller.go
pkg/ddc/alluxio/dataset.go
pkg/ddc/alluxio/operations/base.go
pkg/ddc/alluxio/ufs_internal.go
pkg/ddc/alluxio/utils.go

Show number files of the underlying file system in the status of dataset
fix #299

issue 299 add-file-num-status

---

charts/fluid/fluid/values.yaml

Add file count, To #30961382

---

pkg/controllers/v1alpha1/alluxio/implement.go

fix the function RemoveEngine() so that make the key representation correspond to the fuction GetOrCreateEngine().
fixes #332

fix RemoveEngine()

---

charts/fluid/fluid/values.yaml
pkg/controllers/v1alpha1/alluxio/implement.go
pkg/ddc/factory.go

Fix engine destroys and updates image

---

docs/en/userguide/get_started.md

Fix doc error mentioned in #402 
Fixes #402 
Follow the doc and complete all steps.
Follow the doc to create AlluxioRuntime

fix yaml error

---

charts/fluid-dataloader/templates/configmap.yaml
charts/fluid/fluid/values.yaml
pkg/common/alluxio.go
pkg/common/constants.go
pkg/controllers/v1alpha1/dataload/implement.go
pkg/ddc/alluxio/const.go
pkg/ddc/alluxio/transform_ufs.go
pkg/ddc/alluxio/utils.go
pkg/ddc/alluxio/utils_test.go
pkg/utils/mount.go
pkg/utils/mount_test.go

Update the CSI image

---

docs/zh/TOC.md
docs/zh/dev/runtime_dev_guide.md

introduce how to develop new runtime.

add doc o how to develop new runtime

---

config/samples/data_v1alpha1_alluxioruntime.yaml
config/samples/data_v1alpha1_dataset.yaml
config/samples/workload.yaml
docs/zh/dev/how_to_develop.md

I update the "how to develop.md" and modify some sample filses being used in it.
fixes #387

Update dev doc

---

docs/en/samples/nonroot_access.md

文档翻译（中译英） 待翻译文档位置： docs/zh/samples/nonroot_access.md 翻译后文档位置： docs/en/samples/nonroot_access.md 内容： 从加粗小标题“登录应用”(Line 158)至文档末尾(Line 212)
fixes #412

translation task 56 nonroot_access.md

---

pkg/utils/crtl_utils.go

Add comment on 'GetOrDefault' function. (pkg/utils/crtl_utils.go)

add comment on 'GetOrDefault' function

---

pkg/ddc/alluxio/ufs.go

I normalized the comment of func TotalFileNums in pkg/ddc/alluxio/ufs.go
fixes #389

Normalized the comment of func TotalFileNums

---

docs/en/samples/nonroot_access.md

translating the partition of "Create Dataset and AlluxioRuntime resource object"

---

charts/fluid/fluid/values.yaml

Update docker image with storage class fix

---

pkg/utils/helm/utils.go

Normalization of comments on func InstallRelease(pkg\utils\helm\utils.go)
fixes #429

Normalization of commets on func InstallRelease

---

pkg/utils/kubeclient/namespace.go

I have regularized the commit on "func EnsureNamespace‘(pkg/utils/kubeclient/namespace.go).
fixes #431
Just fix comments
None

Task 11 : Standardize the comment of `func EnsureNamespace`

---

charts/fluid/fluid/values.yaml
pkg/utils/kubeclient/pod.go

Fix static check issue

---

charts/fluid/fluid/values.yaml
pkg/controllers/runtime_controller.go
pkg/controllers/v1alpha1/dataset/dataset_controller.go
pkg/utils/crtl_utils.go
pkg/utils/kubeclient/volume.go

Fix format issue

---

docs/en/samples/hostpath.md

Translate hostpath.md zh to en on line201-231, other lines just be copied from hostpath.md(zh).
fixes #451

use zh version to trans 201-231 lines

---

charts/fluid/fluid/values.yaml
pkg/csi/fuse/nodeserver.go
pkg/ddc/alluxio/transform_fuse_test.go
pkg/ddc/alluxio/transform_optimization.go
pkg/ddc/alluxio/transform_test.go

Support readonly 

---

pkg/utils/helm/helm.go

modify the comment of the function GenerateValueFile in the file pkg/utils/helm/helm.go

task#1_modift_comment

---

docs/en/samples/accelerate_data_accessing_by_hdfs.md

…zh to en
Translate from zh to en. (docs/en/samples/accelerate_data_accessing_by_hdfs.md -- first 39 lines)

Translate Demo Doc

---

pkg/utils/kubeclient/exec.go

I have standardize the comment of `func ExecCommandInPod` (pkg/utils/kubeclient/exec.go).
Fixes #458 
Just fix comments
None

Task 68 : Standardize the comment of `func ExecCommandInPod`

---

docs/en/samples/accelerate_data_accessing_by_hdfs.md

translate annotations from chinese to english.
Fixes #51

Annotation translation.(chinese to english)

---

pkg/utils/crtl_utils.go

add commit on “ContainsString” function
Fix #460 
add commit

add commit on ContainsString

---

pkg/utils/charts.go

Normalize the annotation on SaveConfigMapToFile function.(pkg/utils/charts.go)
fixes #457

assignment17

---

charts/fluid/fluid/templates/csi/daemonset.yaml
charts/fluid/fluid/values.yaml

make csi-address can be configurable
fixes #378

make csi-address can be configurable

---

charts/fluid/fluid/templates/csi/daemonset.yaml
csi/shell/entrypoint.sh

add env KUBELET_ROOTDIR in csi container
#378

add env KUBELET_ROOTDIR in csi container

---

pkg/ddc/alluxio/engine.go

位置： pkg/ddc/alluxio/engine.go 内容： 将func Build上的注释规范化
fixes #475

<Task 38: modify comments in engine.go>

---

api/v1alpha1/alluxioruntime_types.go
charts/alluxio/templates/master/service.yaml
charts/alluxio/values.yaml
docs/zh/dev/api_doc.md
docs/zh/userguide/monitoring.md
monitoring/fluid-prometheus-grafana-monitor.json
monitoring/prometheus.yaml
pkg/ddc/alluxio/const.go
pkg/ddc/alluxio/transform.go
pkg/ddc/alluxio/types.go
pkg/utils/charts.go
pkg/utils/crtl_utils.go
pkg/utils/kubeclient/exec.go

[x] 1. 监控唯一标识 runtime
[x] 2. worker 数据暂时不展示
[x] 3. prometheus 过滤 target 逻辑优化
fixes #473

Enhance Monitoring

---

pkg/utils/kubeclient/node.go

NormalizeCommentsOnFuncGetNode

---

pkg/utils/kubeclient/exec.go

normalized comment on 'ExecShellInContainer' function in pkg/utils/kubeclient/exec.go
fixes #489

normalize comment on 'ExecShellInContainer' function

---

docs/zh/userguide/get_started.md

English version is correct, but Chinese version lacks` Spark-3.0.1`

fix No such file or directory error when copying test file

---

pkg/ddc/alluxio/const.go

Delete editer annotation , my fault.

Delete editer annotation

---

tools/monitoring/fluid-prometheus-grafana-monitor.json
tools/monitoring/prometheus.yaml

Fix grafana variable namespace can not update error.

Fix grafana namespace can not update error

---

docs/en/samples/use_encryptoptions.md
docs/zh/samples/use_encryptoptions.md

add english doc for "support secrets for dataset"
NONE

add english doc for supporting secret in Dataset

---

docs/zh/operation/monitoring.md

Fix monitoring doc error

---

charts/jindofs/templates/config/jindofs-conf.yaml
charts/jindofs/values.yaml
pkg/ddc/jindo/transform.go

transform fuse parameter to arg

---

pkg/ddc/jindo/transform.go

enhance jindofs with secret encryptOption

---

pkg/utils/kubeclient/configmap.go

I have standardized the comment on "func DeleteConfigMap‘(pkg/utils/kubeclient/configmap.go).
NONE

Task 69 : Standardize the comment of `func DeleteConfigMap `

---

pkg/ddc/jindo/transform.go

change jindofs encryptOption without decode

---

pkg/ddc/jindo/transform.go

transfrom jindofs fuse arg to default

---

charts/fluid/fluid/values.yaml

Update Fluid docker image

---

pkg/utils/random.go

added function name on comment of 'RandomAlphaNumberString' funcion
Fixed Issue #511 
//
//
//

added function name on comment of 'RandomAlphaNumberString' funcion

---

charts/fluid/fluid/values.yaml
pkg/ddc/alluxio/transform_optimization.go

Avoid creating folder ext

---

charts/fluid/fluid/values.yaml
pkg/ddc/alluxio/engine.go
pkg/ddc/alluxio/runtime_info.go
pkg/ddc/alluxio/shutdown.go
pkg/ddc/alluxio/transform_resources_test.go
pkg/ddc/base/runtime.go
pkg/ddc/jindo/engine.go
pkg/ddc/jindo/runtime_info.go
pkg/utils/random.go

Fix exclusive option when dataset is not set

---

api/v1alpha1/constant.go
api/v1alpha1/dataset_types.go
charts/fluid/fluid/crds/data.fluid.io_datasets.yaml
charts/fluid/fluid/values.yaml
config/crd/bases/data.fluid.io_datasets.yaml
pkg/ddc/base/runtime.go
pkg/utils/dataset/lifecycle/node.go

Set Placement mode

---

pkg/ddc/alluxio/runtime_info.go
pkg/ddc/jindo/runtime_info.go

Fix dataset be failed to delete

---

charts/jindofs/Chart.yaml
charts/jindofs/README.md
charts/jindofs/templates/master/statefulset.yaml
charts/jindofs/templates/worker/daemonset.yaml
charts/jindofs/values.yaml
go.sum
pkg/ddc/jindo/cache.go
pkg/ddc/jindo/dataset.go
pkg/ddc/jindo/operations/base.go
pkg/ddc/jindo/transform.go
pkg/ddc/jindo/ufs.go
pkg/ddc/jindo/utils.go

fix jindofs report summary and upgrade to 3.2.0 version

---

charts/fluid/fluid/values.yaml

build docker image for jindo

---

pkg/ddc/jindo/cache.go

fix calculate cache size issue

---

docs/en/samples/multi_dataset_same_node_accessing.md
docs/zh/samples/multi_dataset_same_node_accessing.md
tools/monitoring/fluid-prometheus-grafana-monitor.json

e2e test for shared mode for dataset and change grafana json more clear
cc @cheyang

e2e test for shared mode for dataset and change grafana json more clear

---

pkg/ddc/jindo/cache.go
pkg/ddc/jindo/dataset.go
pkg/ddc/jindo/shutdown.go
pkg/ddc/jindo/transform.go
pkg/ddc/jindo/ufs.go
pkg/ddc/jindo/utils.go

fix ufsTotalSize and remove exclusive label

---

charts/fluid/fluid/values.yaml
pkg/ddc/jindo/cache.go
pkg/ddc/jindo/shutdown.go
pkg/ddc/jindo/utils.go

Build docker image

---

docs/zh/TOC.md

Update dev docs

---

api/v1alpha1/jindoruntime_types.go
charts/fluid/fluid/crds/data.fluid.io_jindoruntimes.yaml
config/crd/bases/data.fluid.io_jindoruntimes.yaml
pkg/ddc/jindo/cache.go
pkg/ddc/jindo/dataset.go
pkg/ddc/jindo/master.go
pkg/ddc/jindo/master_internal.go
pkg/ddc/jindo/shutdown.go
pkg/ddc/jindo/transform.go
pkg/ddc/jindo/ufs.go
pkg/ddc/jindo/utils.go

fix jindoruntime and dataset format issue

---

charts/fluid/fluid/values.yaml
pkg/utils/dataset/lifecycle/node.go
pkg/utils/dataset/lifecycle/schedule.go

Build multiple levels

---

api/v1alpha1/dataset_types.go
charts/fluid/fluid/crds/data.fluid.io_datasets.yaml
config/crd/bases/data.fluid.io_datasets.yaml
pkg/common/types.go
pkg/ddc/alluxio/cache.go
pkg/ddc/alluxio/const.go
pkg/ddc/alluxio/engine.go
pkg/ddc/alluxio/operations/base.go
pkg/ddc/alluxio/status.go
pkg/ddc/alluxio/types.go
pkg/ddc/alluxio/ufs.go

Add cache hit ratio for dataset
fixes #526

Add cache hit ratio for dataset

---

charts/fluid/fluid/values.yaml

Build new image for cache hit

---

docs/en/samples/tieredstore_config.md
docs/zh/samples/tieredstore_config.md

Add tieredstore configuration documents, the guide introduces users how to configure tieredstores in a declarative way in Fluid. Three parts are included:
- Single-Tier Configuration
- Single-Tier Multi-Directory Configuraiton
- Multi-Tier Configuration
Both en and zh version guide are included in this PR.
NONE

Add tieredstore configuration documents

---

api/v1alpha1/dataload_types.go
charts/fluid/fluid/crds/data.fluid.io_dataloads.yaml
config/crd/bases/data.fluid.io_dataloads.yaml
pkg/controllers/v1alpha1/dataload/implement.go

show dataload duration time in a simple way.
NONE

Show dataload duration time

---

charts/fluid/fluid/values.yaml

Build image for data load

---

charts/fluid/fluid/values.yaml

Add event info for deleting dataset

---

charts/fluid/fluid/CHANGELOG.md
charts/fluid/fluid/templates/controller/dataset_controller.yaml
charts/fluid/fluid/templates/controller/jindoruntime_controller.yaml
charts/fluid/fluid/templates/csi/daemonset.yaml

Avoid running controller on virtual kubelet

---

charts/fluid/fluid/values.yaml
pkg/controllers/v1alpha1/databackup/implement.go
pkg/databackup/value.go

Build docker image with latest code

---

CODE_OF_CONDUCT.md
GOVERNANCE.md
MAINTAINERS.md
code-of-conduct.md

Add Governance Principle

---

docs/en/TOC.md
docs/en/samples/tieredstore_config.md
docs/zh/TOC.md
docs/zh/samples/tieredstore_config.md

- Polish docs for tieredstore configurations
- Update TOC
NONE

Polish docs for tieredstore configuration

---

charts/fluid/fluid/values.yaml

Update alluxio image to fix security problem reported by trivy scan
fixes #566 
run trivy scan
```shell
trivy image registry.cn-huhehaote.aliyuncs.com/alluxio/alluxio:2.4.1-1-SNAPSHOT-d0434d1
```
get result without critical invulnerability
```text
registry.cn-huhehaote.aliyuncs.com/alluxio/alluxio:2.4.1-1-SNAPSHOT-d0434d1 (alpine 3.9.4)
==========================================================================================
Total: 187 (UNKNOWN: 0, LOW: 98, MEDIUM: 72, HIGH: 17, CRITICAL: 0)

Update alluxio image to fix security problem reported by trivy scan

---

pkg/ddc/alluxio/shutdown.go

fix issue 553 label not delete error
#553

fix issue 553 label not delete error

---

Makefile
docs/en/dev/api_doc.md
docs/zh/dev/api_doc.md

- Add makefile task for api doc update
- Update api doc based on 4be7c32(master branch)
- Add makefile task for api doc update
NONE

Update api doc

---

charts/fluid/fluid/values.yaml

Support HDFS config

---

api/v1alpha1/jindoruntime_types.go
api/v1alpha1/zz_generated.deepcopy.go
charts/fluid/fluid/crds/data.fluid.io_jindoruntimes.yaml
charts/jindofs/Chart.yaml
charts/jindofs/README.md
charts/jindofs/values.yaml
pkg/ddc/jindo/transform.go
pkg/ddc/jindo/types.go

upgrade jindofs to 3.3.2

---

.github/workflows/go.yml

Integrate Github Actions with Fluid
NONE
You can get a preview at https://github.com/TrafalgarZZZ/fluid/tree/Github-actions-test-PR

Integrate Github Actions with Fluid

---

api/v1alpha1/dataset_types.go
api/v1alpha1/zz_generated.deepcopy.go
charts/alluxio/CHANGELOG.md
charts/alluxio/templates/fuse/daemonset.yaml
charts/alluxio/templates/master/statefulset.yaml
charts/alluxio/templates/worker/daemonset.yaml
charts/alluxio/values.yaml
charts/fluid/fluid/crds/data.fluid.io_databackups.yaml
charts/fluid/fluid/crds/data.fluid.io_datasets.yaml
charts/fluid/fluid/values.yaml
config/crd/bases/data.fluid.io_databackups.yaml
config/crd/bases/data.fluid.io_datasets.yaml
docs/zh/TOC.md
docs/zh/samples/data_toleration.md
pkg/common/constants.go
pkg/ddc/alluxio/cache.go
pkg/ddc/alluxio/shutdown.go
pkg/ddc/alluxio/transform.go
pkg/ddc/alluxio/transform_resources.go
pkg/ddc/alluxio/types.go
pkg/ddc/jindo/shutdown.go
pkg/utils/dataset/lifecycle/node.go
pkg/utils/dataset/lifecycle/schedule.go
pkg/utils/dataset/lifecycle/schedule_utils.go
pkg/utils/excluisve.go

Support toleration and fix exclusive label deletion issue

---

charts/fluid/fluid/values.yaml
pkg/ddc/alluxio/metadata.go
pkg/ddc/alluxio/operations/base.go
pkg/ddc/alluxio/transform.go

Build docker image 0209

---

charts/fluid/fluid/VERSION
charts/fluid/fluid/values.yaml

Upgrade alluxio image with arthas

---

charts/fluid/fluid/values.yaml
pkg/ddc/alluxio/metadata.go

Add logging info to restore

---

docs/en/dev/api_doc.md
docs/zh/dev/api_doc.md

update api docs

---

charts/fluid/fluid/VERSION
charts/fluid/fluid/values.yaml

Add async-profiler for problem determination

---

charts/alluxio/CHANGELOG.md
charts/alluxio/templates/worker/daemonset.yaml
charts/fluid/fluid/values.yaml
pkg/ddc/alluxio/transform_resources.go

Fix unknown field tolerationseconds

---

charts/fluid/fluid/values.yaml
pkg/common/types.go
pkg/ddc/alluxio/transform_fuse.go
pkg/ddc/alluxio/worker.go

Make fuse to wait master ready when enabled global

---

charts/fluid/fluid/templates/controller/jindoruntime_controller.yaml

Fix jindo runtime chart

---

charts/fluid/fluid/Chart.yaml
charts/fluid/fluid/values.yaml
tools/diagnose-fluid.sh

Fix diagnose script issue

---

docs/en/userguide/get_started.md
docs/zh/userguide/get_started.md
samples/accelerate/dataset.yaml
samples/co-locality/dataset.yaml
samples/dataload/dataset.yaml

The url "https://mirror.bit.edu.cn" has changed to "https://mirrors.bit.edu.cn", so I change it.
fixes #602

change url

---

api/v1alpha1/databackup_types.go
charts/alluxio/CHANGELOG.md
charts/fluid-databackup/templates/configmap.yaml
charts/fluid/fluid/Chart.yaml
charts/fluid/fluid/crds/data.fluid.io_databackups.yaml
charts/fluid/fluid/templates/controller/jindoruntime_controller.yaml
charts/fluid/fluid/values.yaml
config/crd/bases/data.fluid.io_databackups.yaml
docs/en/userguide/get_started.md
docs/zh/samples/backup_and_restore_metadata.md
docs/zh/userguide/get_started.md
pkg/common/types.go
pkg/controllers/v1alpha1/databackup/databackup_controller.go
pkg/controllers/v1alpha1/databackup/implement.go
pkg/controllers/v1alpha1/dataload/implement.go
pkg/ddc/alluxio/metadata.go
pkg/ddc/alluxio/operations/base.go
pkg/ddc/alluxio/transform_fuse.go
pkg/ddc/alluxio/transform_resources.go
pkg/ddc/alluxio/worker.go
pkg/utils/databackup.go
samples/accelerate/dataset.yaml
samples/co-locality/dataset.yaml
samples/dataload/dataset.yaml
test/testcase_basic/dataset.yaml
test/testcase_basic/instructions.md
test/testcase_basic/runtime.yaml
test/testcase_basic/test.sh
tools/diagnose-fluid.sh

When the Databackup was finished, it will tell user the TimeCost of backup job (whether successful or not
).
the result is as the follow:
```
kubectl get databackup
NAME            DATASET   PHASE      BACKUPPATH                BACKUPNODENAME             TIMECOST   AGE
hbase-backup2   hbase     Complete   local:///data/subpath1/   cn-beijing.192.168.1.147   28s        30s
```
#556

add the status of time cost to databackup

---

charts/fluid/fluid/Chart.yaml
charts/fluid/fluid/values.yaml

Update docker images with pvc fix

---

charts/fluid/fluid/Chart.yaml
charts/fluid/fluid/values.yaml
pkg/controllers/namespace_test.go
pkg/controllers/v1alpha1/alluxio/suite_test.go
pkg/controllers/v1alpha1/dataset/suite_test.go
pkg/controllers/v1alpha1/jindo/suite_test.go
pkg/csi/fuse/nodeserver.go
pkg/csi/fuse/utils.go

Fix failed mount

---

charts/jindofs/Chart.yaml
charts/jindofs/README.md
charts/jindofs/values.yaml
pkg/ddc/jindo/transform.go

upgrade jindofs chart version to 3.3.5

---

test/testcase_basic/dataload.yaml
test/testcase_basic/runtime.yaml
test/testcase_basic/test.sh

add more testcases for fluid, which include:
- get the latest fluid
- uninstall old fluid
- install latest fluid
- create dataload
- check dataload running status
NONE

Add more testcases for fluid

---

charts/fluid/fluid/Chart.yaml
charts/fluid/fluid/values.yaml

Build docker image 0307

---

api/v1alpha1/alluxioruntime_types.go
charts/fluid/fluid/Chart.yaml
charts/fluid/fluid/crds/data.fluid.io_alluxioruntimes.yaml
charts/fluid/fluid/values.yaml
config/crd/bases/data.fluid.io_alluxioruntimes.yaml
docs/en/dev/api_doc.md
docs/zh/dev/api_doc.md
docs/zh/operation/monitoring.md
pkg/ddc/alluxio/transform.go
pkg/utils/dataset/lifecycle/schedule.go
pkg/utils/dataset/lifecycle/schedule_test.go

Refactor monitoring

---

charts/fluid/fluid/Chart.yaml
charts/fluid/fluid/values.yaml

Build docker image for scaling in

---

docs/zh/TOC.md
docs/zh/samples/dataset_scaling.md

- Add demo doc for dataset scaling
- Update TOC
NONE

Add demo doc for dataset scaling

---

docs/en/userguide/faq.md
docs/en/userguide/install.md
docs/zh/userguide/faq.md
docs/zh/userguide/install.md

update the doc of installing fluid, such as upgrading to v0.5, the new CRDs, etc.

update the installing doc

---

docs/en/samples/accelerate_data_accessing_by_hdfs.md
docs/zh/samples/accelerate_data_accessing_by_hdfs.md
samples/hdfs/pom.xml
samples/hdfs/src/main/java/io/fluid/demo/HDFSClient.java

fix fix the bug of hdfs testing sample and update doc
#627

fix the bug of hdfs testing sample and update doc

---

CHANGELOG.md
README-zh_CN.md
README.md

Signed-off-by: RongGu <gurongwalker@gmail.com>

update what's new for fluid v0.5

---

README-zh_CN.md
README.md

Update readme with new demos.

---

docs/en/userguide/install.md
docs/zh/userguide/install.md

Providing users a command to check wheather Custom Resource Objects about fluid have been deleted completely
fixes #640

uninstall fluid safely

---

charts/fluid/fluid/Chart.yaml
charts/fluid/fluid/values.yaml

Update latest docker image

---

charts/fluid/fluid/VERSION
charts/fluid/fluid/values.yaml
tools/alluxio/build-image.sh
tools/alluxio/tarball.sh

Alluxio 2.5.0 1

---

README.md
ROADMAP.md

Add roadmap page

---

docs/zh/TOC.md
docs/zh/dev/use_go_create_resource.md

add link in `TOC.md` for `use_go_create_resource.md`
NONE

update fluid docs

---

ADOPTERS.md

add adopter pages

---

pkg/ddc/alluxio/health_check.go

fixes issue #631 
fixes issue #631

Fix check workers healthy

---

charts/fluid/fluid/Chart.yaml
charts/fluid/fluid/values.yaml

build docker images for down to zero

---

ADOPTERS.md

add use case of fluid

---

ADOPTERS.md

update adopter pages

---

ADOPTERS.md
README.md

Optimize adopter page

---

ADOPTERS.md

Update ADOPTERS.md.
NONE
No tetsts are needed.

Update adopter pages.

---

CODE_OF_CONDUCT.md
CONTRIBUTING.md
README-zh_CN.md
README.md

update conduct of code

---

ADOPTERS.md

Add TencentCloud to adopters

---

ADOPTERS.md

update use case

---

ADOPTERS.md

add adopter

---

README-zh_CN.md
README.md
charts/fluid/README.md

- register fluid on Artifact Hub
- Add "Deploy with Helm" part to README
NONE

Register Fluid on Artifact Hub

---

api/v1alpha1/databackup_types.go
api/v1alpha1/dataload_types.go
api/v1alpha1/status.go
charts/fluid/fluid/crds/data.fluid.io_alluxioruntimes.yaml
charts/fluid/fluid/crds/data.fluid.io_databackups.yaml
charts/fluid/fluid/crds/data.fluid.io_dataloads.yaml
charts/fluid/fluid/crds/data.fluid.io_jindoruntimes.yaml
config/crd/bases/data.fluid.io_alluxioruntimes.yaml
config/crd/bases/data.fluid.io_databackups.yaml
config/crd/bases/data.fluid.io_dataloads.yaml
config/crd/bases/data.fluid.io_jindoruntimes.yaml
pkg/controllers/runtime_controller.go
pkg/controllers/v1alpha1/databackup/databackup_controller.go
pkg/controllers/v1alpha1/databackup/implement.go
pkg/controllers/v1alpha1/dataload/implement.go
pkg/ddc/alluxio/status.go
pkg/utils/crtl_utils.go

optimize  the implementation  of  calculating duration
including databackup, dataload the the setup duration of alluxioruntime
#595

optimize  the implementation of calculating duration

---

charts/fluid/fluid/Chart.yaml
charts/fluid/fluid/crds/data.fluid.io_alluxioruntimes.yaml
charts/fluid/fluid/crds/data.fluid.io_databackups.yaml
charts/fluid/fluid/crds/data.fluid.io_dataloads.yaml
charts/fluid/fluid/values.yaml
config/crd/bases/data.fluid.io_databackups.yaml
config/crd/bases/data.fluid.io_dataloads.yaml

update crd spec

---

.github/workflows/go.yml

- Add "make manifests` to Gtihub Actions for checking crd generating
NONE

Add crd generating check to github actions

---

charts/fluid/fluid/values.yaml
pkg/common/constants.go
pkg/common/storage.go
pkg/ddc/alluxio/label.go
pkg/ddc/alluxio/shutdown.go
pkg/ddc/jindo/label.go
pkg/ddc/jindo/shutdown.go

refactor label name to reduce the length of label

---

charts/fluid/fluid/Chart.yaml
charts/fluid/fluid/values.yaml
pkg/common/deprecated/storage.go
pkg/ddc/alluxio/depericated_label.go
pkg/ddc/alluxio/label.go
pkg/ddc/alluxio/node.go
pkg/ddc/alluxio/shutdown.go
pkg/ddc/base/label.go
pkg/ddc/base/runtime.go
pkg/ddc/jindo/depericated_label.go
pkg/ddc/jindo/label.go
pkg/ddc/jindo/node.go
pkg/ddc/jindo/shutdown.go
pkg/utils/dataset/lifecycle/node.go

Adopt deprecated labels

---

charts/fluid/fluid/Chart.yaml
charts/fluid/fluid/values.yaml

Add cronhpa hpa, To #33889330

---

Makefile
charts/fluid/fluid/Chart.yaml
charts/fluid/fluid/values.yaml
tools/alluxio/build-image.sh
tools/alluxio/readme.md

Unify image repo

---

charts/fluid/fluid/Chart.yaml
charts/fluid/fluid/values.yaml

Update docker image version

---

pkg/ddc/jindo/cache.go
pkg/ddc/jindo/shutdown.go

remove clean cache

---

pkg/utils/dataset/volume/deprecated.go

Refine logging info

---

charts/fluid/fluid/Chart.yaml
charts/fluid/fluid/values.yaml
pkg/ddc/alluxio/transform_permission.go

Refactor for overwriting permission

---

docs/en/userguide/faq.md

This PR checks the spelling and grammar in faq.md in the English version.

Modify the faq.md in the English version

---

pkg/ddc/jindo/transform.go

JindoRuntime add ns to the cache path

---

charts/fluid/fluid/Chart.yaml
charts/fluid/fluid/VERSION
charts/fluid/fluid/values.yaml
tools/alluxio/build-image.sh
tools/alluxio/tarball.sh

Upgrade alluxio to 2.5.0-2

---

pkg/ddc/alluxio/transform.go

Fix issue 715

---

charts/fluid/fluid/Chart.yaml
charts/fluid/fluid/values.yaml
pkg/ddc/alluxio/utils.go
pkg/ddc/jindo/utils.go

Clean up unused code

---

api/v1alpha1/status.go
pkg/common/constants.go
pkg/ddc/alluxio/replicas.go

This PR adds the conditions and events when the runtime scaled out and in.
fixes #700

Add the events and conditions

---

ADOPTERS.md

添加了 Adopter 信息

---

pkg/ddc/alluxio/status.go
pkg/ddc/alluxio/worker.go

show "DESIRED FUSES" correctly when fuse in global mode and make it be synchronized.
fixes #628

Show desired fuse number correctly

---

docs/zh/dev/use_go_create_resource.md

add codes to judge whether the dataset is bound.
fixes #734

add code to judge whether the dataset is bound

---

charts/fluid/fluid/Chart.yaml
charts/fluid/fluid/values.yaml

Update docker images, To #33889330

---

pkg/controllers/v1alpha1/databackup/databackup_controller.go

fix event info of backup
Before, the message of success and failure of databackup is confused

fix event info of backup

---

pkg/ddc/alluxio/metadata.go
pkg/ddc/base/pv.go
pkg/ddc/base/template_engine_test.go
pkg/utils/dataset/lifecycle/node.go
pkg/utils/dataset/lifecycle/schedule.go
pkg/utils/dataset/lifecycle/schedule_test.go
pkg/utils/dataset/lifecycle/schedule_utils.go
pkg/utils/dataset/volume/create.go
pkg/utils/dataset/volume/delete.go
pkg/utils/dataset/volume/deprecated.go

Add copyright

---

pkg/controllers/v1alpha1/databackup/implement.go

bug fix of nonroot
if alluxioruntime is nonroot, databackup will fail

bug fix of nonroot

---

pkg/ddc/jindo/const.go
pkg/ddc/jindo/create_volume.go
pkg/ddc/jindo/runtime_info.go

fix jindoruntime pv fuse global

---

charts/fluid/fluid/Chart.yaml
charts/fluid/fluid/values.yaml

Fix global fuse for jindo runtime

---

pkg/controllers/runtime_controller.go
pkg/ddc/alluxio/master.go
pkg/ddc/alluxio/metadata.go
pkg/ddc/alluxio/operations/base.go
pkg/ddc/alluxio/ufs.go
pkg/ddc/alluxio/ufs_internal.go
pkg/utils/dataset/lifecycle/schedule.go

Fix some errors I found when reading the codes. These errors do not affect functionality, which are mainly spelling errors, syntax errors or some unused codes.

fix some errors

---

docs/en/userguide/get_started.md
docs/zh/samples/dataset_scaling.md

This PR modifies the docs of the get_started.md and dataset_scaling.md

Modify the docs of the get_started.md and dataset_scaling.md

---

charts/fluid/fluid/Chart.yaml
charts/fluid/fluid/templates/controller/alluxioruntime_controller.yaml
charts/fluid/fluid/templates/controller/dataset_controller.yaml
charts/fluid/fluid/templates/controller/jindoruntime_controller.yaml
charts/fluid/fluid/values.yaml

Increase memory limits

---

docs/en/userguide/faq.md
docs/zh/userguide/faq.md

This PR adds the volume attachment in the faq.md.

Add the volume attachment problem in faq.md

---

.gitignore
docs/en/TOC.md
docs/en/dev/dev_with_kind.md

Tutorial for setting up the fluid development environment with kind on mac

add build fluid depvelopment env with kind on mac doc

---

ADOPTERS.md

Add Qihoo 360 to ADOPTERS.md

---

README.md

polish document for some typos and incomprehensible descriptions in README.md
None
No need
No need

polish document for some typos and incomprehensible descriptions

---

Dockerfile.webhook
Makefile
charts/fluid/fluid/Chart.yaml
charts/fluid/fluid/values.yaml
pkg/webhook/mutatingwebhook.go

Refactor Makefile, To #33889330

Refactor Makefile

---

charts/fluid/fluid/Chart.yaml
charts/fluid/fluid/values.yaml

Support webhook

---

pkg/utils/kubeclient/pod_test.go
pkg/utils/kubeclient/volume.go
pkg/webhook/certificatehandler.go
pkg/webhook/mutatingwebhook.go
pkg/webhook/plugins/plugins.go
pkg/webhook/plugins/plugins_test.go
pkg/webhook/plugins/prefernodeswithcache/prefer_nodes_with_cache.go
pkg/webhook/plugins/prefernodeswithoutcache/prefer_nodes_without_cache.go

add testcase of utils and plugin

add testcase of utils and plugin

---

Makefile
charts/fluid/fluid/Chart.yaml
charts/fluid/fluid/values.yaml

Add webhook ci enhancement

---

pkg/webhook/mutatingwebhook.go
pkg/webhook/plugins/plugins.go

Split the entry function of the schedule plugins into two parts

change the entry of plugins

---

charts/fluid/fluid/Chart.yaml
charts/fluid/fluid/values.yaml

Support worker nunmber for reconcile runtime controller

---

charts/fluid/fluid/values.yaml

Disable webhook

---

charts/fluid/fluid/values.yaml
hack/sdk/main.go
pkg/ddc/alluxio/transform.go
pkg/ddc/alluxio/ufs.go
pkg/ddc/alluxio/ufs_internal.go
pkg/ddc/alluxio/ufs_path_builder.go
pkg/ddc/alluxio/ufs_path_builder_test.go
pkg/webhook/mutatingwebhook.go
pkg/webhook/plugins/plugins.go

fix ufs mount issue,

---

pkg/controllers/runtime_controller.go
pkg/controllers/v1alpha1/alluxio/implement.go
pkg/controllers/v1alpha1/jindo/implement.go

Fix a spelling problem for function GetOrCreateEngine
no

fix spelling problem for GetOrCreateEngine

---

charts/fluid/fluid/templates/controller/alluxioruntime_controller.yaml
docs/zh/dev/how_to_develop.md
pkg/common/alluxio.go
pkg/common/constants.go
pkg/common/jindo.go
pkg/controllers/v1alpha1/databackup/implement.go
pkg/controllers/v1alpha1/dataload/dataload_jindo.go
pkg/controllers/v1alpha1/dataload/implement.go
pkg/ddc/alluxio/engine.go
pkg/ddc/alluxio/transform.go
pkg/ddc/alluxio/transform_fuse.go
pkg/ddc/alluxio/transform_init_users.go
pkg/ddc/alluxio/transform_init_users_test.go
pkg/ddc/alluxio/utils.go
pkg/ddc/jindo/transform.go
pkg/utils/docker/image.go

unify get image methods
The basic logic is as follows:
1. If the corresponding value is not empty in "runtime.Spec", use it directly.
2. Otherwise, use the environment value.
3. If the environment value is empty as well, use the default value. 
fixes #680

unify get image methods

---

charts/alluxio/templates/fuse/daemonset.yaml
charts/alluxio/templates/master/statefulset.yaml
charts/alluxio/templates/worker/daemonset.yaml
charts/fluid/fluid/values.yaml
charts/jindofs/templates/fuse/daemonset.yaml
charts/jindofs/templates/master/statefulset.yaml
charts/jindofs/templates/worker/daemonset.yaml

Disable service link

---

docs/en/TOC.md
docs/zh/TOC.md

Update doc structure

---

pkg/ddc/jindo/operations/base.go
pkg/ddc/jindo/transform_fuse_test.go
pkg/ddc/jindo/transform_master_test.go
pkg/ddc/jindo/transform_worker_test.go
pkg/ddc/jindo/utils_test.go

Enhance test coverage of jindo runtime

---

GOVERNANCE.md

update Governance Model, this version draft has been reviewed by the initial maintainers and TOC members.

update Governance Model

---

pkg/ddc/jindo/operations/cached.go

Fix Jindoruntime process blocking when clean cache 

---

charts/fluid/fluid/Chart.yaml
charts/fluid/fluid/values.yaml

Build docker image for HA

---

GOVERNANCE.md

Add vote result for the community chair

---

pkg/ddc/alluxio/operations/cached.go

This pr adaptively executes timeout command with proper option according to Alluxio image version.
fixes #765 
Test the code in different Alluxio image versions.

Exec the timeout command adaptively according to the alluxio image version

---

charts/fluid/fluid/values.yaml
charts/jindofs/Chart.yaml
charts/jindofs/values.yaml
pkg/common/jindo.go
pkg/ddc/jindo/transform.go

upgrade JindoFS version to support HA and other feature

---

charts/alluxio/CHANGELOG.md
charts/alluxio/Chart.yaml
charts/alluxio/templates/config/alluxio-conf.yaml
charts/fluid/fluid/Chart.yaml
charts/fluid/fluid/values.yaml
pkg/common/constants.go

Fix issue which cause alluxio worker crash

---

pkg/common/constants.go
pkg/ddc/alluxio/shutdown.go
pkg/ddc/base/label.go
pkg/ddc/base/runtime.go
pkg/utils/dataset/lifecycle/node.go
pkg/utils/dataset/lifecycle/schedule.go

This PR adds the label DatasetNum which indicates the number of the dataset in a specific node.
fixes #782

Add the label of the node

---

charts/fluid/fluid/Chart.yaml
charts/fluid/fluid/values.yaml

Add node label for scheduling

---

docs/en/samples/accelerate_s3_minio.md

add minio demo

---

.github/workflows/go.yml
.travis.yml
pkg/ddc/alluxio/shutdown.go
pkg/utils/kubeclient/pod_test.go
pkg/utils/kubeclient/volume_claim_test.go
pkg/utils/kubeclient/volume_test.go
vendor/k8s.io/apimachinery/pkg/util/rand/rand.go
vendor/k8s.io/client-go/testing/actions.go
vendor/k8s.io/client-go/testing/fake.go
vendor/k8s.io/client-go/testing/fixture.go
vendor/modules.txt
vendor/sigs.k8s.io/controller-runtime/pkg/client/fake/client.go
vendor/sigs.k8s.io/controller-runtime/pkg/client/fake/doc.go
vendor/sigs.k8s.io/controller-runtime/pkg/internal/objectutil/filter.go

Add testcase for persistentVolume

---

api/v1alpha1/alluxioruntime_types.go
api/v1alpha1/openapi_generated.go
pkg/controllers/v1alpha1/alluxio/implement.go
pkg/controllers/v1alpha1/databackup/implement.go
pkg/controllers/v1alpha1/dataload/implement.go
pkg/controllers/v1alpha1/jindo/implement.go
pkg/ddc/alluxio/hcfs.go
pkg/ddc/alluxio/port_parser.go
pkg/ddc/alluxio/shutdown.go
pkg/ddc/alluxio/transform_fuse_test.go
pkg/ddc/alluxio/transform_resources_test.go
pkg/ddc/alluxio/transform_test.go
pkg/ddc/alluxio/transform_ufs_test.go
pkg/ddc/base/runtime_test.go
pkg/ddc/jindo/cache.go
pkg/ddc/jindo/port_parser.go
pkg/ddc/jindo/shutdown.go
pkg/ddc/jindo/transform_fuse_test.go
pkg/ddc/jindo/transform_master_test.go
pkg/ddc/jindo/transform_worker_test.go
pkg/utils/dataset/volume/create.go
pkg/utils/docker/image.go

This pr fixes several small mistakes which are detected by gofmt, ineffassign and misspell.

Fix several mistakes detected by the plugins gofmt, ineffassign and misspell.

---

README-zh_CN.md
README.md

Fix circleci

---

docs/zh/operation/pod_schedule.md
pkg/common/constants.go
pkg/ddc/alluxio/shutdown.go
pkg/ddc/base/label.go
pkg/ddc/base/runtime.go
pkg/ddc/jindo/shutdown.go
pkg/utils/dataset/lifecycle/node.go
pkg/utils/dataset/lifecycle/schedule.go
pkg/utils/dataset/volume/create.go
pkg/utils/webhook.go
pkg/utils/webhook_test.go
pkg/webhook/plugins/plugins_test.go
pkg/webhook/plugins/prefernodeswithcache/prefer_nodes_with_cache.go
pkg/webhook/plugins/prefernodeswithoutcache/prefer_nodes_without_cache.go

when pod mounting no dataset, change the affinity info injected by the plugin from pod AntiPrefer to node Prefer.
The test code is optimized.
change "Labelname" to "LabelName"
doc/zh/operation/pod_schedule.md

when pod mounting no dataset, change the affinity info from pod AntiPrefer to node Prefer.

---

charts/fluid/fluid/Chart.yaml
charts/fluid/fluid/values.yaml
pkg/utils/kubeclient/pod.go
pkg/utils/kubeclient/pod_test.go
pkg/utils/kubeclient/volume_claim_test.go
pkg/utils/kubeclient/volume_test.go

Add test case for volume

---

pkg/utils/kubeclient/pod.go
pkg/utils/kubeclient/pod_test.go
pkg/utils/kubeclient/service_test.go
pkg/utils/kubeclient/volume.go
pkg/utils/kubeclient/volume_test.go

Add testcase for utils

---

api/v1alpha1/groupversion_info.go
go.sum
pkg/utils/dataload_test.go

add ut for dataload

---

pkg/utils/kubeclient/namespace_test.go

Add ut for namespace

---

pkg/utils/dataset_runtime_test.go

add ut for utils GetRuntimeByCategory

add ut for utils GetRuntimeByCategory

---

pkg/ddc/jindo/transform_fuse_test.go
pkg/ddc/jindo/transform_master_test.go
pkg/ddc/jindo/transform_worker_test.go

Add unit test for JindoRuntime

---

pkg/utils/kubeclient/configmap_test.go

Add unit test

---

api/v1alpha1/jindoruntime_types.go
charts/fluid/fluid/crds/data.fluid.io_jindoruntimes.yaml
charts/jindofs/templates/fuse/daemonset.yaml
charts/jindofs/templates/master/statefulset.yaml
charts/jindofs/templates/worker/daemonset.yaml
config/crd/bases/data.fluid.io_alluxioruntimes.yaml
config/crd/bases/data.fluid.io_jindoruntimes.yaml
config/webhook/manifests.yaml
pkg/ddc/jindo/transform.go
pkg/ddc/jindo/transform_test.go
pkg/ddc/jindo/types.go

JindoRuntime support toleration with dataset and runtime spec

---

pkg/ddc/jindo/transform.go
pkg/ddc/jindo/transform_fuse_test.go
pkg/ddc/jindo/transform_test.go

Reactor JindoRuntime engine and add Some UT

---

pkg/ddc/alluxio/metadata.go
pkg/ddc/alluxio/transform.go
pkg/ddc/alluxio/transform_ufs.go
pkg/ddc/alluxio/ufs_internal.go
pkg/utils/common.go
pkg/utils/common_test.go
pkg/utils/dataset.go
pkg/utils/dataset_test.go
pkg/utils/ufs_path_builder.go
pkg/utils/ufs_path_builder_test.go

add ut for utils dataset

---

pkg/utils/kubeclient/configmap.go
pkg/utils/kubeclient/configmap_test.go
pkg/utils/kubeclient/node_test.go

Add ut for node

---

pkg/utils/init_user_test.go

Add ut for utils init_user
NONE
- Added pkg/utils/init_user_test.go

Add ut for utils init_user

---

pkg/utils/dataset/lifecycle/node.go
pkg/utils/dataset/lifecycle/node_test.go

This pr deletes the dead code of the node.go

Delete the dead code

---

charts/fluid/fluid/values.yaml
charts/jindofs/Chart.yaml
charts/jindofs/values.yaml
pkg/common/jindo.go
pkg/ddc/jindo/transform.go
pkg/ddc/jindo/transform_fuse_test.go
pkg/ddc/jindo/transform_test.go

upgrade jindofs version to 3.6.0 

---

charts/fluid/fluid/Chart.yaml
charts/fluid/fluid/values.yaml

Update JindoRuntime image

---

pkg/ddc/jindo/transform.go

transform Toleration with dataset spec

---

docs/en/userguide/faq.md
docs/zh/userguide/faq.md

add faq about alluxio master Pod entering into CrashLoopBackOff state
#857

add faq about alluxio master Pod entering into CrashLoopBackOff state

---

pkg/ddc/alluxio/transform.go
pkg/ddc/jindo/transform.go
pkg/utils/dataset/lifecycle/node_test.go
pkg/utils/docker/image_test.go
pkg/utils/excluisve_test.go
pkg/utils/quantity.go
pkg/utils/quantity_test.go

Add unit tests for exclusive and quantity funcs in utils pkg
NONE
- pkg/utils/exclusive_test.go
- pkg/utils/quantity_test.go

Add unit tests for exclusive and quantity funcs in utils pkg

---

pkg/utils/resources_test.go

ut for utils TransformRequirementsToResources

add ut for utils TransformRequirementsToResources

---

docs/zh/samples/master_high_avaliability.md

Add Master High-Avaliablilty sample doc.

Add Master Ha Sample

---

pkg/ddc/alluxio/shutdown_test.go
pkg/utils/dataset/lifecycle/node_test.go

This pr adds the unit tests for the DestroyWorker and LabelCacheNode.

Add the unit test for the DestroyWorker and LabelCacheNode

---

pkg/utils/byte_size.go
pkg/utils/byte_size_test.go

ut for BytesSize and FromHumanSize

add ut for BytesSize and FromHumanSize

---

pkg/ddc/alluxio/api_gateway_test.go

ut for api_gateway

---

pkg/ddc/alluxio/shutdown_test.go
pkg/utils/kubeclient/volume_test.go

Add ut for GetPvcMountPods

---

pkg/ddc/alluxio/types_test.go

add ut for alluxio types

---

pkg/utils/dataset/volume/delete_test.go
pkg/utils/dataset/volume/deprecated_test.go

This pr adds the ut for delete.go and deprecated.go.

Add ut for delete.go and deprecated.go

---

pkg/utils/kubeclient/volume_claim_test.go
pkg/utils/kubeclient/volume_test.go

Add pvc test

---

pkg/utils/charts.go
pkg/utils/charts_test.go
pkg/utils/crtl_utils.go
pkg/utils/crtl_utils_test.go

add testcases of charts.go and ctrl_utils.go

add testcases of charts.go and ctrl_utils.go

---

pkg/utils/databackup_test.go

add testcase of databackup utils

add testcase of databackup utils

---

pkg/utils/dataset/volume/create_test.go
pkg/utils/dataset/volume/delete_test.go
pkg/utils/dataset/volume/deprecated_test.go
pkg/utils/kubeclient/volume.go

This pr adds the ut for create.go and delete.go.

add the ut for create.go and  delete.go

---

pkg/ddc/alluxio/shutdown_test.go
pkg/ddc/alluxio/worker_test.go
pkg/utils/dataset/volume/create_test.go
pkg/utils/dataset/volume/delete_test.go

Signed-off-by: chrisydxie chrisydxie@tencent.com

Add ut for worker

---

pkg/ddc/alluxio/operations/conf_test.go

Add ut for conf.go

---

pkg/ddc/alluxio/delete_volume_test.go

add ut for delete_volume.go

---

docs/zh/operation/pod_schedule.md
docs/zh/operation/pod_schedule_default.md
docs/zh/operation/pod_schedule_global.md
docs/zh/operation/pod_schedule_glolbal.md

Update doc for scheduling

---

pkg/ddc/jindo/const.go
pkg/ddc/jindo/master.go
pkg/ddc/jindo/worker.go
pkg/ddc/jindo/worker_test.go

Add ut for JindoRuntime with worker

---

pkg/ddc/alluxio/create_volume_test.go
pkg/ddc/alluxio/dataset.go
pkg/ddc/alluxio/dataset_test.go
pkg/ddc/alluxio/shutdown_test.go
pkg/utils/runtimes.go

This pr added the ut for create-volume.go and dataset.go. Meanwhile, this pr fixed several small mistakes I saw.

Add-ut-create-volume

---

pkg/utils/label.go

This pr adds TODO for patch operation.

Add TODO for patch

---

pkg/ddc/alluxio/deprecated_label_test.go

add ut for deprecated_label

---

pkg/ddc/alluxio/engine._test.go
pkg/ddc/alluxio/shutdown_test.go

This pr adds the ut for engine.go.

Add-unit-test-engine

---

pkg/ddc/alluxio/hcfs_test.go

Signed-off-by: LDawn <lsm@smail.nju.edu.cn>
add ut for hcfs

add ut for hcfs

---

pkg/ddc/alluxio/operations/conf_test.go
pkg/ddc/alluxio/transform_api_gateway.go
pkg/ddc/alluxio/transform_api_gateway_test.go

add ut of transform and add a checker of nil pointer

add ut of transform and add a checker of nil pointer

---

pkg/ddc/alluxio/health_check_test.go

This pr adds ut for health_check.go.

Add ut health check

---

pkg/ddc/alluxio/hcfs_test.go
pkg/ddc/alluxio/label_test.go

Signed-off-by: LDawn <lsm@smail.nju.edu.cn>
add ut for label and fix hcfs_test

add ut for label and fix hcfs_test

---

docs/en/dev/dev_with_kind.md

1. add ddc-helm
2. add soft link for charts
3. fix csi and node-driver-register start.sh bug
After @littletiger123 experience, give some suggestions and make some update
fixes #919

update dev with kind

---

pkg/ddc/alluxio/node_test.go

Signed-off-by: LDawn <lsm@smail.nju.edu.cn>
add ut for alluxioEngine-node
fixes #918

add ut for alluxioEngine-node

---

pkg/utils/kubeclient/volume.go
pkg/utils/kubeclient/volume_test.go

Add ut for TestShouldDeleteDataset

---

pkg/ddc/alluxio/port_parser_test.go

Signed-off-by: LDawn <lsm@smail.nju.edu.cn>
add ut for port_parser

add ut for port_parser

---

charts/fluid-databackup/goosefs/values.yaml
charts/fluid/fluid/values.yaml
charts/goosefs/values.yaml
pkg/common/goosefs.go
pkg/ddc/goosefs/port_parser_test.go
pkg/ddc/goosefs/utils_test.go

Fix goosefs image repo

---

pkg/ddc/alluxio/health_check_test.go
pkg/ddc/alluxio/master_internal_test.go
pkg/ddc/alluxio/metadata_test.go
pkg/utils/helm/helm_test.go

This pr adds ut for master-internal.go, metadata.go, health_check.go and helm.go.

Add ut for several functions

---

charts/fluid/fluid/values.yaml
cmd/goosefs/app/goosefs.go

fix goosefs cmd start error
cc @cheyang

Set goosefs default disable and fix goosefs cmd error

---

pkg/utils/helm/utils_test.go

Add ut for utils.go

---

docs/zh/operation/pod_schedule.md
docs/zh/operation/pod_schedule_global.md

Add instructions to enable API Server parameter MutatingAdmissionWebHook

---

pkg/ddc/alluxio/operations/base_test.go

This pr adds the uts for base.go

Add ut for base.go

---

pkg/ddc/jindo/cache.go
pkg/ddc/jindo/cache_test.go
pkg/ddc/jindo/create_volume_test.go
pkg/ddc/jindo/dataset_test.go
pkg/ddc/jindo/delete_volume_test.go
pkg/ddc/jindo/deprecated_label_test.go
pkg/ddc/jindo/label_test.go
pkg/ddc/jindo/load_data.go
pkg/ddc/jindo/load_data_test.go
pkg/ddc/jindo/master_internal_test.go
pkg/ddc/jindo/master_test.go
pkg/ddc/jindo/metadata_test.go
pkg/ddc/jindo/node_test.go
pkg/ddc/jindo/operations/base.go
pkg/ddc/jindo/replicas.go
pkg/ddc/jindo/replicas_test.go
pkg/ddc/jindo/shutdown_test.go
pkg/ddc/jindo/transform_hadoop_config.go
pkg/ddc/jindo/ufs.go

add some ut for jindoruntime

---

pkg/utils/webhook.go
pkg/utils/webhook_test.go

Signed-off-by: ldd91 <lvdongdong30@gmail.com>
fix #938

put nodeSelectotRequirement in first MatchExpressions

---

README-zh_CN.md
README.md

This pr changes README.md due to the modification of the homepage.

Change README

---

pkg/utils/kubeclient/volume.go
pkg/utils/kubeclient/volume_test.go

Add ut for pvc

---

pkg/utils/random_test.go

ut for utils random
fixes #949

add ut for utils random

---

docs/en/dev/api_doc.md
docs/zh/dev/api_doc.md

Add GooseFS API for api doc.
cc @cheyang

Add GooseFS API Doc

---

README-zh_CN.md
README.md

Add CNCF Slack link.
#959 
cc @cheyang @RongGu

Add CNCF Slack link

---

charts/fluid/fluid/CHANGELOG.md
charts/fluid/fluid/Chart.yaml
charts/fluid/fluid/values.yaml

Create 0.6.0 release candidates

---

charts/fluid/fluid/Chart.yaml
charts/fluid/fluid/values.yaml
charts/fluid/v0.6.0/.helmignore
charts/fluid/v0.6.0/CHANGELOG.md
charts/fluid/v0.6.0/Chart.yaml
charts/fluid/v0.6.0/VERSION
charts/fluid/v0.6.0/crds/data.fluid.io_alluxioruntimes.yaml
charts/fluid/v0.6.0/crds/data.fluid.io_databackups.yaml
charts/fluid/v0.6.0/crds/data.fluid.io_dataloads.yaml
charts/fluid/v0.6.0/crds/data.fluid.io_datasets.yaml
charts/fluid/v0.6.0/crds/data.fluid.io_goosefsruntimes.yaml
charts/fluid/v0.6.0/crds/data.fluid.io_jindoruntimes.yaml
charts/fluid/v0.6.0/templates/_helpers.tpl
charts/fluid/v0.6.0/templates/controller/alluxioruntime_controller.yaml
charts/fluid/v0.6.0/templates/controller/dataset_controller.yaml
charts/fluid/v0.6.0/templates/controller/goosefsruntime_controller.yaml
charts/fluid/v0.6.0/templates/controller/jindoruntime_controller.yaml
charts/fluid/v0.6.0/templates/csi/daemonset.yaml
charts/fluid/v0.6.0/templates/csi/driver.yaml
charts/fluid/v0.6.0/templates/role/alluxio/rbac.yaml
charts/fluid/v0.6.0/templates/role/dataset/rbac.yaml
charts/fluid/v0.6.0/templates/role/goosefs/rbac.yaml
charts/fluid/v0.6.0/templates/role/jindo/rabc.yaml
charts/fluid/v0.6.0/templates/role/webhook/rabc.yaml
charts/fluid/v0.6.0/templates/webhook/service.yaml
charts/fluid/v0.6.0/templates/webhook/webhook.yaml
charts/fluid/v0.6.0/templates/webhook/webhookconfiguration.yaml
charts/fluid/v0.6.0/values.yaml
docs/zh/TOC.md

Release 0.6.0

---

charts/fluid/fluid/CHANGELOG.md
charts/fluid/v0.6.0/CHANGELOG.md

Add goosefs to v0.6.0 release

---

CHANGELOG.md

add v0.6 release notes

---

README.md

This pr adds the picture of the wechat official acccount.

Add the picture of the wechat official acccount

---

charts/fluid/fluid/crds/data.fluid.io_datasets.yaml
charts/fluid/fluid/crds/data.fluid.io_goosefsruntimes.yaml
charts/fluid/v0.6.0/crds/data.fluid.io_datasets.yaml
charts/fluid/v0.6.0/crds/data.fluid.io_goosefsruntimes.yaml
config/crd/bases/data.fluid.io_datasets.yaml
config/crd/bases/data.fluid.io_goosefsruntimes.yaml

update crds for v0.6.0

---

.github/workflows/go.yml

Signed-off-by: cheyang <cheyang@163.com>>
fixes #986

Fix CI action,

---

pkg/ddc/alluxio/runtime_info_test.go

add ut for RT

---

GOVERNANCE.md
api/v1alpha1/alluxioruntime_types.go
api/v1alpha1/jindoruntime_types.go
charts/fluid/fluid/crds/data.fluid.io_alluxioruntimes.yaml
charts/fluid/fluid/crds/data.fluid.io_jindoruntimes.yaml
config/crd/bases/data.fluid.io_alluxioruntimes.yaml
config/crd/bases/data.fluid.io_jindoruntimes.yaml
docs/en/dev/api_doc.md
docs/zh/dev/api_doc.md

Fix typo in api

---

pkg/ddc/jindo/engine_test.go
pkg/ddc/jindo/operations/base_test.go
pkg/ddc/jindo/operations/cached_test.go

This pr adds ut for base-test.go, engine_test.go, and cached_test.go.

Add ut for base-test.go, engine_test.go, and cached_test.go.

---

cmd/alluxio/main.go

update License header

---

pkg/ddc/goosefs/runtime_info_test.go

add ut for GooseRT

---

pkg/controllers/v1alpha1/dataload/dataload_controller.go

fix a function name and variable name collide with package name
fixes #1009 
NO，just rename some function name

fix a function name and variable package collide

---

charts/fluid/fluid/values.yaml
pkg/ddc/goosefs/runtime_info_test.go

fix go test and build new  docker image

---

pkg/ddc/jindo/runtime_info_test.go

add ut for jindoRT.

---

charts/fluid/fluid/Chart.yaml
charts/fluid/fluid/values.yaml
pkg/ddc/jindo/runtime_info_test.go

fix jindo runtime test format

---

pkg/ddc/alluxio/cache_test.go

add ut for cache.

---

api/v1alpha1/jindoruntime_types.go
charts/fluid/fluid/crds/data.fluid.io_jindoruntimes.yaml
charts/jindofs/CHANGELOG.md
charts/jindofs/Chart.yaml
charts/jindofs/templates/config/jindofs-conf.yaml
charts/jindofs/templates/worker/daemonset.yaml
config/crd/bases/data.fluid.io_jindoruntimes.yaml
pkg/ddc/jindo/transform.go
pkg/ddc/jindo/transform_worker_test.go
pkg/ddc/jindo/types.go

Enhance jindoruntime with default stderr log and worker resource

---

charts/fluid/fluid/Chart.yaml
charts/fluid/fluid/values.yaml
docs/en/dev/api_doc.md
docs/zh/dev/api_doc.md

Enhance jindoruntime docker image

---

pkg/ddc/jindo/health_check_test.go

add ut for healthcheck.

---

pkg/ddc/base/pv_test.go
pkg/ddc/base/template_engine_test.go
pkg/ddc/jindo/metadata_test.go

This pr adds ut for template_engine.go and metadata.go.
fixes #1044

Add ut for template_engine.go and metadata.go

---

charts/jindofs/templates/fuse/daemonset.yaml
charts/jindofs/templates/master/statefulset.yaml
charts/jindofs/templates/worker/statefulset.yaml
pkg/ddc/base/pv_test.go
pkg/ddc/goosefs/cache_test.go
pkg/ddc/jindo/cache_test.go
pkg/ddc/jindo/transform.go
pkg/ddc/jindo/transform_worker_test.go
pkg/ddc/jindo/types.go

add master and fuse resource option for jindoruntime 

---

pkg/common/webhook.go
pkg/webhook/certificate_builder.go
pkg/webhook/certificate_builder_test.go

add test case of cert builder
fixes #1053

add test case of cert builder

---

pkg/ddc/jindo/const.go
pkg/ddc/jindo/fuse.go
pkg/ddc/jindo/fuse_test.go
pkg/ddc/jindo/shutdown.go
pkg/ddc/jindo/shutdown_test.go

Clean fuse label when deleting dataset

---

charts/fluid/fluid/Chart.yaml
charts/fluid/fluid/values.yaml

Build docker image for jindoruntime update

---

pkg/ctrl/affinity.go
pkg/ctrl/affinity_test.go
pkg/ddc/base/label.go
pkg/ddc/jindo/cache.go
pkg/ddc/jindo/engine.go
pkg/ddc/jindo/master.go
pkg/ddc/jindo/node.go
pkg/ddc/jindo/replicas_test.go
pkg/ddc/jindo/status.go
pkg/ddc/jindo/transform_hadoop_config.go
pkg/ddc/jindo/utils.go
pkg/ddc/jindo/worker.go
pkg/ddc/jindo/worker_test.go
pkg/utils/dataset/lifecycle/node.go
pkg/utils/dataset/lifecycle/node_test.go
pkg/utils/kubeclient/pod_test.go
pkg/utils/kubeclient/statefulset.go
pkg/utils/kubeclient/statefulset_test.go
pkg/utils/slice.go
pkg/utils/slice_test.go

Move GetStatefulSet, BuildWorkAffinity as common function

---

charts/fluid/fluid/Chart.yaml
charts/fluid/fluid/values.yaml

Build docker image for refactoring jindo workers

---

pkg/controllers/v1alpha1/dataload/implement.go

insert licence for implement.go

insert licence for implement.go

---

pkg/common/webhook.go

Signed-off-by: fhkong <fh_kong@nuaa.edu.cn>

This pr is to add "Apache License" for pkg/common/webhook.go

---

pkg/ddc/alluxio/create_volume_test.go

add Apache 2.0 License
fixes #1084 
no tests
see the source file pkg/ddc/alluxio/create_volume_test.go

Add Apache 2.0 License to the beginning of file pkg/ddc/alluxio/create_volume_test.go

---

pkg/controllers/v1alpha1/dataload/implement_test.go

add license on /pkg/controllers/v1alpha1/dataload/implement_test.go
Signed-off-by: bigbanglwb <bigbanglwb@163.com>
fixes #1092

add license on /pkg/controllers/v1alpha1/dataload/implement_test.go

---

pkg/ddc/alluxio/dataset_test.go

Insert licence for pkg/ddc/alluxio/dataset_test.go.
Fixes #1080

Insert licence for dataset_test.go

---

charts/jindofs/CHANGELOG.md
charts/jindofs/Chart.yaml
charts/jindofs/templates/fuse/daemonset.yaml

fix jindofs-fuse mount

---

pkg/ddc/alluxio/api_gateway_test.go

add Apache License announcement statement for pkg/ddc/alluxio/api_gateway_test.go
fixes #1101 

Add Apache License announcement statement for  pkg/ddc/alluxio/api_gateway_test.go

---

pkg/ddc/alluxio/load_data_test.go

This pr is to add a license for the file pkg/ddc/alluxio/load_data_test.go
fixes #1099 
NONE
NONE
NONE

add license for pkg/ddc/alluxio/load_data_test.go

---

pkg/ddc/alluxio/delete_volume_test.go

Signed-off-by: smile_fifteen <1024125320@qq.com>
This is a pr to add Apache License announcement statement for pkg/ddc/alluxio/delete_volume_test.go
fixes #1100 
NONE
NONE
NONE

Add Apache License announcement statement for pkg/ddc/alluxio/delete_volume_test.go

---

pkg/common/storage.go

Signed-off-by: huangxu.chase <huangxu@smail.nju.edu.cn>
add lisence at pkg/common/storage.go 
fixes #1102

This pr is to add Apache License announcement statement for pkg/common/storage.go

---

pkg/ddc/alluxio/master_test.go

This pr is to add the license notice statement information to the head of the file pkg/ddc/alluxio/master_test.go.
fixes #1090 
no tests
the file pkg/ddc/alluxio/master_test.go.

Add Apache 2.0 License to the beginning of file pkg/ddc/alluxio/master_test.go

---

pkg/dataload/value.go

add Apache License announcement statement for pkg/dataload/value.go
fixes #1104 

Add Apache License announcement statement for pkg/dataload/value.go

---

api/v1alpha1/interface.go
api/v1alpha1/jindoruntime_types.go
pkg/ctrl/affinity.go
pkg/ctrl/affinity_test.go
pkg/ctrl/ctrl.go
pkg/ctrl/ctrl_test.go
pkg/ddc/base/interface.go
pkg/ddc/base/runtime_test.go
pkg/ddc/jindo/engine.go
pkg/ddc/jindo/replicas.go
pkg/ddc/jindo/replicas_test.go
pkg/ddc/jindo/worker.go
pkg/ddc/jindo/worker_test.go

make the function setupWorker as common function

---

pkg/ddc/alluxio/node_test.go

This PR is to add an Apache-2.0 license to pkg/ddc/alluxio/node_test.go
fixes #1108 
No tests are needed.

Add Apache 2.0 license to pkg/ddc/alluxio/node_test.go

---

charts/fluid/fluid/Chart.yaml
charts/fluid/fluid/values.yaml

Refactor ctrl for new docker image

---

pkg/ddc/alluxio/health_check_test.go

This pr is to add the license notice statement information to the head of the file pkg/ddc/alluxio/health_check_test.go
fixes #1116 
no tests
check out the head of the file pkg/ddc/alluxio/health_check_test.go

description(向pkg/ddc/alluxio/health_check_test.go添加许可证声明信息)

---

pkg/databackup/value.go

Signed-off-by: tmsxk <1985045185@qq.com>
add Apache 2.0 License
fixes #1113 
none
add missing license
none

add license for pkg/databackup/value.go

---

pkg/common/init.go

Signed-off-by: hongxinweiqi <hongxinweiqi@163.com>
This pr is to add the Apache license for pkg/common/init.go.
fixes #1129

add the Apache license

---

pkg/ddc/alluxio/report_test.go

This pr is to add Apache License at the beginning of file
fixes #1131

add license at the very beginning

---

pkg/common/goosefs.go

add apache license for pkg/common/goosefs.go
fixes #1132

add apache license for pkg/common/goosefs.go

---

pkg/databackup/constants.go

This PR is to add the announcement statement of Apache 2.0 License
fixes #1123

add Apache2.0 license to pkg/databackup/constants.go

---

pkg/ddc/alluxio/label_test.go

This pr is to add a license for the file `pkg/ddc/alluxio/label_test.go`
fixes #1126 
None
None
None

add license for pkg/ddc/alluxio/label_test.go

---

pkg/controllers/runtime_controller.go
pkg/controllers/v1alpha1/dataload/implement.go
pkg/ddc/alluxio/dataset_test.go
pkg/ddc/alluxio/transform_resources.go
pkg/ddc/alluxio/transform_resources_test.go
pkg/ddc/alluxio/types.go
pkg/dump/dump.go

For hang issue, you  can run `kill -3 pid` to analyze the dumped groutings.
```
** goroutine dump...
goroutine 69 [running]:
github.com/fluid-cloudnative/fluid/pkg/dump.StackTrace(0xc000593301, 0x0, 0x0)
/go/src/github.com/fluid-cloudnative/fluid/pkg/dump/dump.go:26 +0x96
github.com/fluid-cloudnative/fluid/pkg/dump.coredump(0xc00011af40, 0x1a)
/go/src/github.com/fluid-cloudnative/fluid/pkg/dump/dump.go:70 +0x145
github.com/fluid-cloudnative/fluid/pkg/dump.InstallCoreDumpGenerator.func1(0xc000052cc0)
/go/src/github.com/fluid-cloudnative/fluid/pkg/dump/dump.go:56 +0x2ad
created by github.com/fluid-cloudnative/fluid/pkg/dump.InstallCoreDumpGenerator
/go/src/github.com/fluid-cloudnative/fluid/pkg/dump/dump.go:47 +0x113
goroutine 1 [select]: …
```

Add grouting dump

---

pkg/ctrl/worker.go
pkg/ctrl/worker_test.go
pkg/ddc/base/log.go
pkg/ddc/base/log_test.go
pkg/ddc/base/setup.go
pkg/ddc/jindo/node.go
pkg/ddc/jindo/node_test.go
pkg/ddc/jindo/replicas.go
pkg/ddc/jindo/replicas_test.go
pkg/ddc/jindo/status.go
pkg/ddc/jindo/status_test.go
pkg/ddc/jindo/worker.go
pkg/ddc/jindo/worker_test.go
pkg/errors/deprecated.go
pkg/errors/errors.go
pkg/errors/errors_test.go
pkg/utils/kubeclient/daemonset.go
pkg/utils/webhook_test.go

Adopt existing jindoruntime with worker daemonset

---

charts/fluid/fluid/Chart.yaml
charts/fluid/fluid/values.yaml

Build docker image with the latest change

---

charts/fluid/fluid/VERSION
charts/fluid/fluid/values.yaml
tools/alluxio/build-image.sh
tools/alluxio/tarball.sh

Verified it could pass all the manual tests.
Not sure if I should update the commit string in fluid charts and in values.yaml

upgrade Alluxio to 2.7.0

---

pkg/ddc/alluxio/operations/cached_test.go

the file: "pkg/ddc/alluxio/operations/cached_test.go" is no notice statement added, so I added the Apache 2.0 license to the header of the file.
fixes #1151
none
file_url: https://github.com/fluid-cloudnative/fluid/blob/master/pkg/ddc/alluxio/operations/cached_test.go
none

add Apache 2.0 license at the head of "pkg/ddc/alluxio/operations/cached_test.go"

---

charts/jindofs/CHANGELOG.md
charts/jindofs/templates/worker/statefulset.yaml
charts/jindofs/values.yaml
pkg/controllers/v1alpha1/jindo/jindoruntime_controller.go
pkg/ddc/base/syncs.go
pkg/ddc/jindo/cache.go
pkg/ddc/jindo/dataset.go
pkg/ddc/jindo/metadata.go
pkg/ddc/jindo/status.go
pkg/utils/time_tracker.go
pkg/utils/time_tracker_test.go

Change worker from order to Parallel

---

charts/fluid/fluid/Chart.yaml
charts/fluid/fluid/values.yaml

Change worker from order to Parallel, build docker image

---

charts/fluid/fluid/Chart.yaml
charts/fluid/fluid/values.yaml
pkg/utils/time_tracker.go

Update long task period

---

pkg/ddc/alluxio/operations/conf_test.go

Signed-off-by: wsl <wangshulin@smail.nju.edu.cn>
add Apache License for pkg/ddc/alluxio/operations/conf_test.go
fixes #1168

This pr is to add Apache License for pkg/ddc/alluxio/operations/conf_test.go

---

charts/fluid/fluid/VERSION
charts/fluid/fluid/values.yaml

Alluxio release-2.7.0 has a bug that makes the build failed. Fixed that and update the commit string here. 
Fix #1146

Update Alluxio commit string

---

charts/fluid/fluid/Chart.yaml
charts/fluid/fluid/values.yaml

Build docker image with alluxio 2.7.0

---

pkg/ddc/alluxio/hcfs_test.go

Signed-off-by: 08mamba24 <864701928@qq.com>
fixes #1178

Add the Announcement statement of Apache 2.0 License

---

charts/fluid/fluid/Chart.yaml
charts/fluid/fluid/values.yaml

Update docker image with alluxio controller changed

---

pkg/common/constants_test.go

This pr is to add license of pkg/common/constants_test.go
fixes #1181

add license of pkg/common/constants_test.go

---

pkg/ddc/jindo/status.go
pkg/ddc/jindo/worker.go

Fix logging

---

charts/fluid/fluid/Chart.yaml
charts/fluid/fluid/values.yaml

Create docker image for logging

---

pkg/ddc/alluxio/shutdown_test.go

Add Apache 2.0 license to pkg/ddc/alluxio/shutdown_test.go.
Fixes #1161 
Check the beginning of pkg/ddc/alluxio/shutdown_test.go.

Add Apache 2.0 license to pkg/ddc/alluxio/shutdown_test.go

---

pkg/ddc/alluxio/port_parser_test.go

This PR is to add the announcement statement of Apache 2.0 License
#1165

add Apache2.0 license to pkg/ddc/alluxio/port_parser_test.go

---

pkg/ddc/alluxio/cache_test.go

add Apache lincense in cache_test.go
Fix #1193

add Apache lincense in cache_test.go

---

docs/en/dev/api_doc.md
docs/zh/dev/api_doc.md

Update jucie api doc

---

pkg/ddc/alluxio/dataset.go
pkg/ddc/alluxio/node.go
pkg/ddc/alluxio/node_test.go
pkg/ddc/alluxio/status.go
pkg/ddc/alluxio/status_test.go
pkg/ddc/alluxio/worker.go

Signed-off-by: 道民 <jiebin.cjb@alibaba-inc.com>
fixes #1198

Adopt Alluxio worker in daemon

---

charts/fluid/fluid/Chart.yaml
charts/fluid/fluid/values.yaml

Update docker images for alluxio change

---

pkg/common/jindo.go

This PR is to add Apache 2.0 license
fixes #1191

add Apache 2.0 license to jindo.go

---

charts/juicefs/README.md
docs/en/samples/juicefs_runtime.md
docs/zh/samples/juicefs_runtime.md

Update `JuiceFSRuntime` docs
NONE
NONE
N/A
N/A

Docs: update JuiceFSRuntime docs

---

charts/fluid/fluid/Chart.yaml
charts/fluid/fluid/values.yaml

Build docker image for juice

---

pkg/ddc/alluxio/replicas_test.go

PR is to add the announcement statement of Apach 2.0 license. I added apache license to head of file named 'pkg/ddc/alluxio/replicas_test.go'.
fixes #1212 
No tests are needed.
check out the head of the file named 'pkg/ddc/alluxio/replicas_test.go'.

add comment at the beginning of the file

---

api/v1alpha1/juicefsruntime_types.go
charts/fluid/fluid/crds/data.fluid.io_juicefsruntimes.yaml
config/crd/bases/data.fluid.io_juicefsruntimes.yaml
pkg/ddc/juicefs/transform_fuse.go

add printcolume "Age" in juicefs & fix when cacheRatio is nil

add printcolume in juicefs & fix cacheRatio is nil

---

charts/fluid/fluid/Chart.yaml
charts/fluid/fluid/values.yaml

Update docker images, To #37688693

---

charts/fluid/fluid/Chart.yaml
charts/fluid/fluid/values.yaml

Update docker image for goosefs

---

charts/fluid/fluid/Chart.yaml
charts/fluid/fluid/values.yaml

Update docker images for dataload

---

docs/en/dev/api_doc.md

Add dataload options api in api doc.
@cheyang

add dataload options api in api doc

---

charts/fluid/fluid/values.yaml
charts/fluid/v0.6.0/values.yaml
charts/jindofs/CHANGELOG.md
charts/jindofs/Chart.yaml
charts/jindofs/values.yaml
pkg/common/jindo.go
pkg/ddc/jindo/transform.go
pkg/ddc/jindo/transform_fuse_test.go
pkg/ddc/jindo/transform_test.go

upgrade jindofs version

---

pkg/ddc/alluxio/transform_api_gateway_test.go

add apache license to `pkg/ddc/alluxio/transform_api_gateway_test.go`
fixes #1253

add apache license to `pkg/ddc/alluxio/transform_api_gateway_test.go`

---

charts/fluid/fluid/Chart.yaml
charts/fluid/fluid/values.yaml

Build docker image for cleanPolicy

---

pkg/ddc/base/pv_test.go

add Apache license to `pkg/ddc/base/pv_test.go`
fixes #1256

add Apache license to `pkg/ddc/base/pv_test.go`

---

pkg/ddc/base/portallocator/port_allocator.go

add license to `pkg/ddc/base/portallocator/port_allocator.go`
fixes #1262

add license to `pkg/ddc/base/portallocator/port_allocator.go`

---

charts/fluid/fluid/Chart.yaml
charts/fluid/fluid/values.yaml
pkg/ddc/alluxio/dataset.go
pkg/ddc/base/runtime_test.go
pkg/ddc/base/template_engine.go
pkg/ddc/jindo/dataset.go
pkg/ddc/jindo/health_check.go

If the healthy is ready, the status of  dataset is turned to bound

---

api/v1alpha1/juicefsruntime_types.go
charts/fluid/fluid/crds/data.fluid.io_juicefsruntimes.yaml
config/crd/bases/data.fluid.io_juicefsruntimes.yaml
pkg/ddc/base/runtime.go
pkg/ddc/base/runtime_test.go

support clean policy for juicefs runtime
fixes #1268

Jfsruntime clean policy

---

pkg/ddc/base/portallocator/port_allocator_test.go

Add Missing Apache 2.0 License to pkg/ddc/base/portallocator/port_allocator_test.go
Fixes #1266

to fix #1266

---

charts/fluid-dataloader/goosefs/templates/configmap.yaml
charts/fluid-dataloader/goosefs/templates/dataloader.yaml

fix goosefs dataload helm template error
cc @cheyang

fix goosefs dataload helm template error

---

pkg/ddc/base/base_suite_test.go

Add Missing Apache 2.0 License to pkg/ddc/base/base_suite_test.go
Fixes to #1273

Fixes #1273

---

pkg/ddc/base/runtime_test.go

add license to `pkg/ddc/base/runtime_test.go`
fixes #1278

add license to `pkg/ddc/base/runtime_test.go`

---

pkg/ddc/base/label_test.go

add apache license to `pkg/ddc/base/label_test.go`
fixes #1280

Fixes #1280

---

pkg/ddc/goosefs/cache_test.go

add license to `pkg/ddc/goosefs/cache_test.go`
fixes #1284

Fixes #1284

---

Makefile

set GO111MODULE="on" in Makefile.
fixes #1282

set GO111MODULE="on" in Makefile

---

pkg/utils/docker/image.go
pkg/utils/docker/image_test.go

Signed-off-by: Wang Ni <wangni@4paradigm.com>
fix bug with 1293
https://github.com/fluid-cloudnative/fluid/issues/1293

fix bug with 1293

---

docker/Dockerfile.csi
docker/Dockerfile.dataset
docker/Dockerfile.goosefsruntime
docker/Dockerfile.jindoruntime
docker/Dockerfile.juicefsruntime
docker/Dockerfile.webhook

Support remote debug

---

charts/fluid/fluid/Chart.yaml
charts/fluid/fluid/values.yaml

Build docker images for network mode

---

pkg/utils/kubeclient/exec.go

fix data race about kubeconfigpath
fixes #1303

fix data race about kubeconfigpath

---

charts/fluid/fluid/Chart.yaml
charts/fluid/fluid/values.yaml

Build cis plugin

---

charts/fluid/fluid/VERSION
charts/fluid/fluid/values.yaml
tools/alluxio/build-image.sh
tools/alluxio/tarball.sh

Alluxio 2.7.2 is published. Upgrade Alluxio version to v2.7.2.
fixes #1312

upgrade Alluxio to v2.7.2

---

charts/fluid/fluid/Chart.yaml
charts/fluid/fluid/VERSION
charts/fluid/fluid/values.yaml

Build alluxio 2.7.2

---

charts/fluid/fluid/Chart.yaml
charts/fluid/fluid/values.yaml

Build docker image for fuse recovery

---

Makefile

add juicefsruntime controller build&push in build-all & push-al
fixes #1341

add juicefsruntime build&push in all

---

charts/fluid/fluid/CHANGELOG.md
charts/fluid/fluid/Chart.yaml
charts/fluid/fluid/templates/csi/daemonset.yaml
charts/fluid/fluid/values.yaml

Fix helm lint

---

charts/fluid/fluid/Chart.yaml
charts/fluid/fluid/values.yaml

Build docker images for juice fuse recovery

---

docs/en/samples/fuse_recover.md
docs/zh/samples/fuse_recover.md

add en/zh doc for FUSE recover demo

add fuse recover doc

---

docs/en/samples/fuse_recover.md
docs/zh/samples/fuse_recover.md

fix typo in fuse recover doc

---

pkg/ddc/alluxio/node.go
pkg/ddc/alluxio/node_test.go

Signed-off-by: 道民 <jiebin.cjb@alibaba-inc.com>
fixes #1314
fixes #1314

fix-issue1314-Node_Not_labeled

---

pkg/webhook/certificate_builder_test.go

fix ci bug
fix the ci bug that 'go test' cannot paas in pkg/webhook
fixes #1369

fix ci bug

---

charts/goosefs/templates/fuse/daemonset.yaml
pkg/ddc/goosefs/transform_fuse.go
pkg/ddc/goosefs/types.go
pkg/ddc/goosefs/utils.go
pkg/ddc/goosefs/utils_test.go

Fix goosefs fuse container restart fail
#1354 
Already tested based https://github.com/fluid-cloudnative/fluid/blob/master/docs/zh/samples/fuse_recover.md.
@cheyang

Fix goosefs fuse container restart fail

---

charts/goosefs/templates/fuse/daemonset.yaml
pkg/ddc/goosefs/transform_fuse.go
pkg/ddc/goosefs/types.go
pkg/ddc/goosefs/utils.go
pkg/ddc/goosefs/utils_test.go

Sorry for this pr #1366， is not necessary, pls revert.
@cheyang

(goosefs): revert

---

charts/fluid/fluid/Chart.yaml
charts/fluid/fluid/values.yaml

Build docker image for reverting goose PR

---

charts/fluid/fluid/Chart.yaml
charts/fluid/fluid/values.yaml

Build docker image for cleaning labels for juicefs fuse

---

.github/workflows/go.yml
charts/jindofs/values.yaml

Add helm lint check in Github workflow
fixes #1372

Add helm lint check in Github workflow

---

docs/en/TOC.md
docs/zh/TOC.md
docs/zh/troubleshooting/debug-fuse.md

Add documents for debuging

---

tools/diagnose-fluid.sh

Fix diagnose script. The previous script does not compare the strings correctly.
fix #1403

fix diagnose

---

charts/alluxio/docker/init-users/Dockerfile

Fix building docker image for init user

---

charts/fluid/fluid/Chart.yaml
charts/fluid/fluid/values.yaml
pkg/ddc/base/runtime_helper.go
pkg/ddc/base/runtime_helper_test.go

Make  AlluxioRuntime support serverless

---

charts/fluid/fluid/Chart.yaml
charts/fluid/fluid/values.yaml

Build docker image for knative

---

pkg/ddc/goosefs/metadata_test.go
pkg/ddc/goosefs/replicas_test.go
pkg/ddc/goosefs/utils_test.go

Fix redundant type from array, slice, or map composite literal

---

pkg/ddc/goosefs/runtime_info_test.go
pkg/ddc/goosefs/shutdown_test.go
pkg/ddc/goosefs/transform_fuse_test.go
pkg/ddc/goosefs/transform_hadoop_config.go
pkg/ddc/goosefs/transform_optimization.go
pkg/ddc/goosefs/transform_optimization_test.go
pkg/ddc/goosefs/transform_resources_test.go
pkg/ddc/goosefs/transform_test.go
pkg/ddc/goosefs/transform_ufs_test.go
pkg/ddc/goosefs/ufs_internal_test.go
pkg/ddc/goosefs/ufs_test.go
pkg/ddc/goosefs/worker_test.go

1. change goosefs fuse default parameters; 
2. fix  redundant type from array, slice, or map composite literal;
3. fix when ha mode journal type
@cheyang

fix goosefs error

---

api/v1alpha1/juicefsruntime_types.go
charts/fluid/fluid/crds/data.fluid.io_juicefsruntimes.yaml
charts/juicefs/templates/fuse/daemonset.yaml
charts/juicefs/values.yaml
config/crd/bases/data.fluid.io_juicefsruntimes.yaml
pkg/ddc/juicefs/transform_fuse.go
pkg/ddc/juicefs/type.go
pkg/scripts/poststart/check_fuse.go
pkg/scripts/poststart/check_fuse_test.go
pkg/utils/kubeclient/volume_mount.go
pkg/utils/kubeclient/volume_mount_test.go

1. delete initContainer in juicefs fuse pod, for serverless
2. update fuse volumeMount name to "juicefs-fuse-mount"
3. name of cm in check_fuse toLower

support juicefs in serverless

---

charts/fluid/fluid/Chart.yaml
charts/fluid/fluid/values.yaml

Build docker image for juicefs on serverless

---

charts/fluid/fluid/Chart.yaml
charts/fluid/fluid/values.yaml

Build docker image for Goosefs bug

---

pkg/ddc/alluxio/port_parser_test.go
pkg/ddc/alluxio/transform_optimization.go
pkg/ddc/goosefs/port_parser_test.go
pkg/ddc/goosefs/shutdown_test.go
pkg/ddc/goosefs/transform_optimization.go

Related to https://github.com/Alluxio/alluxio/issues/14909, disable this optimization

Disable fuse.shared.caching.reader.enabled for alluxio and goosefs

---

charts/fluid/fluid/templates/csi/daemonset.yaml
charts/fluid/fluid/values.yaml
cmd/csi/app/csi.go
docs/en/samples/fuse_recover.md
docs/zh/samples/fuse_recover.md
go.mod
pkg/csi/config/config.go
pkg/csi/features/csi_features.go
pkg/csi/plugins/register.go
pkg/csi/recover/recover.go
pkg/csi/recover/recover_test.go
pkg/csi/recover/register.go
pkg/csi/register.go
pkg/utils/feature/feature_gate.go
vendor/modules.txt

add feature gate to csi & get period from env `RECOVER_FUSE_PERIOD`
fixes #1446

add feature gate to csi

---

charts/fluid/fluid/Chart.yaml
charts/fluid/fluid/values.yaml

Build docker image for v0.7.0

---

charts/fluid/fluid/Chart.yaml
charts/fluid/fluid/values.yaml

Build for optimizing job worker's thread

---

charts/fluid/fluid/templates/csi/daemonset.yaml

Fix csi daemonset template typo
fixes #1453

Fix csi daemonset template typo

---

docs/en/samples/accelerate_data_accessing.md
docs/en/samples/accelerate_data_accessing_by_hdfs.md
docs/en/samples/data_co_locality.md
docs/en/samples/multi_dataset_same_node_accessing.md
docs/zh/operation/dataset_cron_scaling.md
docs/zh/samples/accelerate_data_accessing.md
docs/zh/samples/accelerate_data_accessing_by_hdfs.md
docs/zh/samples/api_proxy.md
docs/zh/samples/backup_and_restore_metadata.md
docs/zh/samples/data_toleration.md
docs/zh/samples/dataset_scaling.md
docs/zh/samples/master_high_avaliability.md
docs/zh/samples/multi_dataset_same_node_accessing.md

Update Fluid documents:
1. Fix documents affected by Fuse lazy start feature.
2. Fix documents affected by migrating runtime worker `Daemonset` to `StatefulSet`
NONE

Update Fluid documents

---

.gitignore
Makefile
api/v1alpha1/openapi_generated.go
api/v1alpha1/swagger.json
hack/sdk/gen-sdk.sh

fix https://github.com/fluid-cloudnative/fluid/issues/1456

fix gen_sdk.sh

---

charts/fluid/fluid/Chart.yaml
charts/fluid/fluid/values.yaml

Build Docker image for fuse without cachedir

---

pkg/ddc/base/runtime_helper.go

Disable timezone hostpath for jindoruntime

---

charts/fluid/fluid/Chart.yaml
charts/fluid/fluid/values.yaml

Build docker image for disabling timezone hostpath 

---

README.md

Add community meeting information

Add community meeting information

---

docs/en/userguide/install.md
docs/zh/userguide/install.md

Update install document

---

charts/fluid-dataloader/jindo/templates/configmap.yaml

enable run jindo dataload synchronously

---

charts/fluid/fluid/Chart.yaml
charts/fluid/fluid/values.yaml

Build docker image for release v0.7.0

---

docs/zh/userguide/install.md

Fix typo in install.md
NONE
no tests added.

Fix typo in install doc

---

charts/fluid/fluid/Chart.yaml
charts/fluid/fluid/values.yaml

Build docker image for 0.7.0 release candidate

---

CHANGELOG.md

Update CHANGELOG.md for 0.7
NONE

Update CHANGELOG.md for 0.7

---

charts/fluid/fluid/values.yaml

Default csi fuse recovery to false. 
Related Issue: #1495 
NONE

Default csi fuse recovery to false

---

charts/fluid/fluid/values.yaml

Cherry-pick "Default csi fuse recovery to fase" to release 0.7

Cherry-pick "Default csi fuse recovery to fase" to release 0.7

---

docs/zh/samples/s3_configuration.md

Add an example using s3 as dataset. 
Solves https://github.com/fluid-cloudnative/fluid/issues/1469

add s3 example

---

charts/fluid/fluid/Chart.yaml
charts/fluid/fluid/values.yaml
pkg/common/critical_fuse_pod.go
pkg/common/critical_fuse_pod_test.go
pkg/common/init.go
pkg/utils/runtimes/options/critical_fuse_pod.go
pkg/utils/runtimes/options/critical_fuse_pod_test.go
pkg/utils/runtimes/options/init.go
pkg/utils/runtimes/options/init_port_check.go
pkg/utils/runtimes/options/init_port_check_test.go

Fix misleading logging in csi plugin

---

ADOPTERS.md

add dmetasoul in adopters documents
NONE

add dmetasoul in adopters documents

---

docs/en/samples/s3_configuration.md
docs/zh/samples/s3_configuration.md

…d the English version of the S3 configuration document
Signed-off-by: Javy <javy@Javys-MBP.lan>
Updated the Chinese version of the S3 configuration document and added the English version of the S3 configuration document
fixes #1508

Updated and Add the Chinese && English version of the S3 configuration document

---

charts/fluid/fluid/Chart.yaml
charts/fluid/fluid/values.yaml

Build docker image for env in csi plugin

---

docs/zh/TOC.md

fix update JindoRuntime doc link

---

charts/fluid/fluid/templates/role/fluidapp/rbac.yaml
charts/fluid/fluid/values.yaml

fix pod/exec rbac in application controller

---

charts/fluid/fluid/values.yaml

fix application controller image 

---

Makefile
cmd/csi/app/csi.go
docker/Dockerfile.alluxioruntime
docker/Dockerfile.application
docker/Dockerfile.csi
docker/Dockerfile.dataset
docker/Dockerfile.goosefsruntime
docker/Dockerfile.jindoruntime
docker/Dockerfile.juicefsruntime
docs/en/userguide/install.md
docs/zh/dev/runtime_dev_guide.md
docs/zh/userguide/install.md

Fix Makefile, Dockerfile and makefile

---

pkg/ddc/alluxio/types_test.go

Signed-off-by: 陈阳 <1977295856@qq.com>
This pr is to normalize the license of pkg/ddc/alluxio/types_test.go.
fixes #1537

normalize the license of pkg/ddc/alluxio/types_test.go

---

charts/fluid/fluid/Chart.yaml
charts/fluid/fluid/values.yaml

Build docker image for csi plugin optimization

---

charts/fluid-dataloader/alluxio/templates/dataloader.yaml
charts/fluid-dataloader/goosefs/templates/dataloader.yaml
charts/fluid-dataloader/jindo/templates/dataloader.yaml
pkg/webhook/scheduler/mutating/schedule_pod_handler.go

fix https://github.com/fluid-cloudnative/fluid/issues/1540

add app label in dataload & skip dataload pod inject

---

docs/en/samples/fuse_affinity.md
docs/zh/samples/fuse_affinity.md

Signed-off-by: wangxu <wangxu199811@163.com>
This PR add docs for how to use fuse node selector.
fixes #1470 Missing doc for how to use fuse node selector

add doc about fuse node selector

---

pkg/ddc/alluxio/load_data.go

Signed-off-by: -Beiming- <191840314@smail.nju.edu.cn>
This pr is to add License for `pkg/ddc/alluxio/load_data.go` in Task 143

This pr is to add License for pkg/ddc/alluxio/load_data.go

---

pkg/ddc/base/interface.go

Signed-off-by: 191220029 <1830970417@qq.com>
This pr is to add License for `pkg/ddc/base/interface.go`

standerlize license `pkg/ddc/base/interface.go`

---

pkg/ddc/jindo/dataset.go

Signed-off-by: Bug-001 <191850169@smail.nju.edu.cn>
This pr is to add copyright header to pkg/ddc/jindo/dataset.go.

add copyright to pkg/ddc/jindo/dataset.go

---

pkg/ddc/jindo/load_data.go

Signed-off-by: lawrshen <191220090@smail.nju.edu.cn>
This pr is to add Copyright to pkg/ddc/jindo/load_data.go

docs: add Copyright to pkg/ddc/jindo/load_data.go

---

docs/en/samples/fuse_affinity.md

Signed-off-by: wangxu <wangxu199811@163.com>
Fix the doc about  fuse node selector.

fix the doc

---

pkg/ddc/alluxio/worker.go

Signed-off-by: Khancancancan <1361398253@qq.com>
This PR is to add Copyright infos of Apache License to file `pkg/ddc/alluxio/worker.go`.

Add Copyright infos of Apache License to file `pkg/ddc/alluxio/worker.go`

---

pkg/ddc/goosefs/transform_permission.go

This pr is to add Copyright to pkg/ddc/goosefs/transform_permission.go

规范License信息

---

charts/fluid/fluid/Chart.yaml
charts/fluid/fluid/values.yaml

Build docker image for controller runtime 0.8.3

---

pkg/ddc/jindo/health_check.go

Signed-off-by: Lattic-zjj <2186283744@qq.com>
This PR is to add Apache License to pkg/ddc/jindo/health_check.go.

add Apache License to pkg/ddc/jindo/health_check.go

---

pkg/ddc/goosefs/transform_hadoop_config.go

Signed-off-by: kevin999wang 191220111@smail.nju.edu.cn
This PR is to add license info to pkg/ddc/goosefs/transform_hadoop_config.go.

add license info to pkg/ddc/goosefs/transform_hadoop_config.go

---

pkg/ddc/alluxio/master_internal_test.go

Signed-off-by: AbeZbm <1287589303@qq.com>
add Apache License to pkg/ddc/alluxio/master_internal_test.g

add Apache License to pkg/ddc/alluxio/master_internal_test.go

---

pkg/ddc/jindo/runtime_info.go

This pr is to add  License information at the head of the file(pkg/ddc/jindo/runtime_info.go)

Add License information

---

pkg/ddc/goosefs/operations/cached.go

Signed-off-by: lollipop <191250190@smail.nju.edu.cn>
normalize Apache License declaration in specific file

normalize Apache License declaration in specific file

---

pkg/ddc/base/template_engine_test.go

This pull request fixes the format of the license in `pkg/ddc/base/template_engine_test.go` by adding a copyright notice.
NONE
No test needed since this PR changes comments only.
NONE
NONE

Fix license format of template_engine_test.go by adding a copyright line

---

pkg/ddc/jindo/ufs.go

Signed-off-by: huyyyyIan <1450971512@qq.com>

This pr is to add apache license & copyright

---

pkg/ddc/jindo/utils_test.go

This PR is to add Apache License to pkg/ddc/jindo/utils_test.go.

add copyright to utils_test.go

---

pkg/ddc/goosefs/transform_resources.go

Signed-off-by: millsll <1606945339@qq.com>
This pr is to standardize the License in pkg/dcc/goosefs/transform_resources.go

standardize License in pkg/ddc/goosefs/transform_resources.go

---

pkg/ddc/goosefs/transform_fuse.go

Signed-off-by: ephemeralove <1684723848@qq.com>
fixes #pkg/ddc/goosefs/transform_fuse.go

This pr is to add copyright to pkg/ddc/goosefs/transform_fuse.go

---

pkg/ddc/goosefs/transform_api_gateway_test.go

Signed-off-by: NJUCS-CC <191220005@smail.nju.edu.cn>
This PR is to add Apache License to pkg/ddc/goosefs/transform_api_gateway_test.go

add Apache License to pkg/ddc/goosefs/transform_api_gateway_test.go

---

charts/fluid/fluid/Chart.yaml
charts/fluid/fluid/values.yaml

Build docker image for csi optimization

---

pkg/ddc/goosefs/operations/base.go

Signed-off-by: xingshangyu 1535845977@qq.com
This pr is to add license information in pkg/ddc/goosefs/operations/base.go.

add license information in pkg/ddc/goosefs/operations/base.go

---

pkg/ddc/goosefs/transform_ufs_test.go

Signed-off-by: WangJunYao-yy <312956331@qq.com>

formalize License in pkg/ddc/goosefs/transform_ufs_test.go file

---

charts/fluid/fluid/Chart.yaml
charts/fluid/fluid/values.yaml

Build docker for fixing node patch with node cache

---

pkg/ddc/goosefs/engine_test.go

Signed-off-by: neverland-lhy <447087673@qq.com>
This pr is to add Apache License to pkg/ddc/goosefs/engine_test.go

add Apache License to pkg/ddc/goosefs/engine_test.go

---

pkg/ddc/jindo/port_parser.go

Signed-off-by: x33333xc <1477194584@qq.com>
This PR adds license to pkg/ddc/jindo/port_parser.go .

Add license to port_parser.go

---

pkg/ddc/goosefs/transform_init_users_test.go

Signed-off-by: djlovewq <1362174908@qq.com>

add the Copyright in pkg/ddc/goosefs/transform_init_users_test.go

---

pkg/ddc/jindo/cache.go

Signed-off-by: 191220128 <850069607@qq.com>

This pr is to add license info to pkg/ddc/jindo/cache.go

---

pkg/ddc/goosefs/load_data_test.go

Signed-off-by: 樊润璞 <1060103520@qq.com>
This pr is to add Apache License of the task 24

description  add configure

---

pkg/ddc/goosefs/label_test.go

Signed-off-by: OverdosedJoker <528784732@qq.com>

This pr is to add Apache License to pkg/ddc/goosefs/label_test.go

---

pkg/ddc/goosefs/operations/local.go

Signed-off-by: Ladbed <2569741105@qq.com>
This pr is to add license to pkg/ddc/goosefs/operations/local.go
NONE
NONE
NONE
NONE

This pr is to add license to pkg/ddc/goosefs/operations/local.go

---

pkg/ddc/goosefs/utils.go

Signed-off-by: ysy <893902275@qq.com>
This pr is to add copyright of task58

first commit

---

pkg/ddc/goosefs/types.go

Signed-off-by: Michael-LiangAnze <1468623593@qq.com>
add copyright to pkg/ddc/goosefs/types.go

add copyright to pkg/ddc/goosefs/types.go

---

pkg/ddc/goosefs/transform_init_users.go

Signed-off-by: chmr7 <1913447694@qq.com>

This pr is to add license to pkg/ddc/goosefs/transform_init_users.go

---

pkg/ddc/base/log_test.go

Signed-off-by: X-March <191220133@smail.nju.edu.cn>

This pr is to add Apache License at pkg/ddc/base/log_test.go

---

pkg/ddc/goosefs/transform_resources_test.go

This PR is to add Copyright to perfect License to pkg/ddc/goosefs/transform_resources_test.go

---

pkg/ddc/goosefs/deprecated_label.go

This pr is to upgrade the apache license of file 'pkg/ddc/goosefs/deprecated_label.go'.

Upgraded the apache license

---

pkg/ddc/jindo/dataset_test.go

Signed-off-by: zhangdingchu <2364872290@qq.com>
This pr is to add the Lincese information in the pkg/ddc/jindo/dataset_test.go

description pkg/ddc/jindo/dataset_test.go add Lincese information

---

pkg/ddc/alluxio/node.go

Signed-off-by: BakaSea <sea@infstudio.net>
This pr is to update Apache License in pkg/ddc/alluxio/node.go

Add license to pkg/ddc/alluxio/node.go

---

pkg/ddc/goosefs/replicas.go

Signed-off-by: tinywisdom <191220176@smail.nju.edu.cn>
The PR is to check and complete pkg/ddc/goosefs/replicas.go's annotation

check replicas.go

---

pkg/ddc/goosefs/ufs_internal.go

This pr is to update the copyright in ufs_internal.go

Update the copyright in ufs_internal.go

---

pkg/ddc/goosefs/shutdown.go

update license in `pkg/ddc/goosefs/shutdown.go`

update license in shutdown.go

---

pkg/ddc/goosefs/transform_optimization_test.go

Signed-off-by: EnxIII <1621875326@qq.com>
update  Apache License in file "pkg/ddc/goosefs/transform_optimization_test.go"

update Apache License

---

pkg/ddc/base/log.go

Signed-off-by: fengling-aat <995474376@qq.com>

License pkg/ddc/base/log.go

---

pkg/ddc/goosefs/replicas_test.go

This pr is to add License to pkg/ddc/goosefs/replicas_test.go

This pr is to add License to pkg/ddc/goosefs/replicas_test.go

---

pkg/ddc/jindo/metadata_test.go

Signed-off-by: polaris0-a <2763917266@qq.com>
This PR adds license infomation to pkg/ddc/jindo/metadata_test.go

Add license infomation to metadata_test.go

---

pkg/ddc/goosefs/report_test.go

Signed-off-by: LLZPP <2380854993@qq.com>
This PR adds license infomation to pkg/ddc/goosefs/report_test.go

add Apache License to pkg/ddc/goosefs/report_test.go

---

pkg/ddc/goosefs/api_gateway.go

Signed-off-by: WwangX <wangfighting02@gmail.com>

This pr is to add Copyright for task-68
