fluid-cloudnative/fluid

Makefile

`controller-gen` is now got by initializing a temporary module. However, with a golang environment variable `GO111MODULE` set to `off`, a temporary module is not allowed: 
```
go mod init: modules disabled by GO111MODULE=off; see 'go help modules'
Makefile:107: recipe for target 'controller-gen' failed
```
This PR commits a modification that adds a `export GO111MODULE=on` to temporarily enable golang module support. 
NONE

Fix bug: can't go get controller-gen when GO111MODULE=off

---

api/v1alpha1/alluxioruntime_types.go
charts/fluid/fluid/crds/data.fluid.io_alluxioruntimes.yaml
config/crd/bases/data.fluid.io_alluxioruntimes.yaml

用户通过`kubectl get alluxioruntime <dataset> -o yaml`获得的信息中冗余信息过多, 可读性差.
该PR通过添加在AlluxioRuntime CRD上`additionalPrinterColumn`属性, 控制`kubectl get alluxioruntime`以及`kubectl get -o wide alluxioruntime`时输出的信息, 将用户最为在意的重要信息通过这种更加简单的方式提供
修改后`kubectl get alluxioruntime`的结果示例:
```
$ kubectl get alluxioruntime.data.fluid.io dataset
NAME      MASTER PHASE   WORKER PHASE   FUSE PHASE     AGE
dataset   Ready          PartialReady   PartialReady   46s 
```
修改后`kubectl get -o wide alluxioruntime`的结果示例:
```
$ kubectl get alluxioruntime.data.fluid.io dataset
NAME      READY MASTERS   DESIRED MASTERS   MASTER PHASE   READY WORKERS   DESIRED WORKERS   WORKER PHASE   READY FUSE   DESIRED FUSE   FUSE PHASE     AGE
dataset   1               1                 Ready          1               2 …
```

Add AdditionalPrinterColumns for AlluxioRuntime CRD

---

cmd/controller/main.go

Make controller-manager's logs more readable:
- Use console encoder instead of json encoder
- Make timestamp more readable by using `zapcore.ISO8601TimeEncoder`
Log snippet:
```
...
2020-09-13T14:48:57.013+0800	INFO	alluxioctl.AlluxioRuntime	base/setup.go:43	Setup the ddc engine	{"alluxioruntime": "default/hbase", "engine": "alluxio", "id": "default-hbase", "runtime": {"apiVersion": "data.fluid.io/v1alpha1", "kind": "AlluxioRuntime", "namespace": "default", "name": "hbase"}}
2020-09-13T14:48:59.144+0800	INFO	alluxioctl.AlluxioRuntime	alluxio/dataset.go:121	the dataset status	{"alluxioruntime": "default/hbase", "status": {"ufsTotal":"443.5MiB","phase":"Bound","conditions":[{"type":"Ready","status":"True","reason":"DatasetReady","message":"The ddc runtime is …
```

Make controller-manager's logs more readable

---

config/samples/data_v1alpha1_alluxioruntime.yaml
docs/en/samples/accelerate_data_accessing.md
docs/en/samples/data_co_locality.md
docs/en/userguide/get_started.md
docs/zh/samples/accelerate_data_accessing.md
docs/zh/samples/data_co_locality.md
docs/zh/userguide/get_started.md
pkg/ddc/alluxio/transform_fuse_test.go
pkg/ddc/alluxio/transform_optimization.go
pkg/ddc/alluxio/transform_test.go
samples/accelerate/runtime.yaml
samples/co-locality/runtime.yaml
samples/ufspath/app.yaml
samples/ufspath/dataset.yaml

The fuse option `max_readahead=0` may have some negative effect in some scenarios due to some currently unknown issue. This PR reverts the change that set the option to default.
We should track this issue in v0.4.0
What does this PR does:
- Revert fuse max_readahead default option
- Fix samples
NONE

Revert fuse max_readahead default option

---

Makefile
cmd/csi/main.go
version.go

Edit the command of fluid-csi
fluid-csi version will print the version info of commit, fluid-csi start will start to run csi on node
Change the name of command
the command name of fluid-csi is fluid in the past, which is not correct
fixes #208 
after build fluid-csi,run fluid-csi version and fluid-csi start
because the start command of csi has changed , the dockerfile of csi need to be changed.

Add version command

---

pkg/utils/kubectl/configmap.go

Remove redundant comment on `kubectl` function. (pkg/utils/kubectl/configmap.go)

remove redundant comment on `kubectl` function

---

Dockerfile.csi
Makefile
cmd/csi/main.go
csi/shell/entrypoint.sh
version.go

when fluid-csi starts，it will print version info by golog. After starting, users can query version info by command "fluid-csi version".
edit the makefile and dockerfile.csi.
fixes #239 
I have verified it with the building command "docker build --no-cache . -f Dockerfile.csi -t xxx".

Fix the failure of starting  fluid-csi 

---

pkg/ddc/alluxio/metadata.go
pkg/ddc/alluxio/operations/local.go

Fix missing syncLocalDir method when loading metadata
Fixes #241

Fix missing syncLocalDir method when loading metadata

---

pkg/utils/kubeclient/pod.go

Task 65: Standardize the comment of `func GetPodByName` godoc
NONE
Just fix comments
NONE

Task 65 Standardize the comment of `func GetPodByName`

---

pkg/ddc/alluxio/shutdown.go
pkg/ddc/alluxio/ufs.go

Optmize alluxio engine's time-consuming shutdown process
When mounting a dataset with millions of files and trying to delete its bounded AlluxioRuntime, it would take a very long time to complete the deletion. This PR tries to optimize the process.
In my case, with this PR, the deletion takes about 3min to 7min according to its cahced size(Fluid have to clean up all the cache before the deletion), while Fluid on master branch may take 30min+ due to the time-consuming `du` operation on Alluxio
Fixes #230 
Mount a dataset with millions of files, and try to delete its AlluxioRuntime.

Optmize Alluxio engine's time-consuming shutdown process

---

pkg/ddc/alluxio/operations/base.go

standardized comment on LoadMetaData function

---

docs/en/samples/accelerate_data_accessing_by_hdfs.md
docs/zh/samples/accelerate_data_accessing_by_hdfs.md
samples/hdfs/fluid/app.yaml
samples/hdfs/src/main/java/io/fluid/demo/HDFSClient.java

测试示例 - HDFS Client文件访问加速 提供的java示例程序，将端口直接写在程序中，测试时较为不便。
如果用户直接使用我们直接提供的镜像进行测试，端口默认写死，无法通过回归测试。
现将其修改为从环境变量获取。
fixes #327

fix the port problems in hdfs test samples

---

pkg/utils/kubectl/configmap.go

standardize the comment on func `SaveConfigMapToFile` in `pkg/utils/kubectl/configmap.go`.
fixes #348 
This is a comment, so test is not necessary.

Normalize SaveConfigMapToFile comment (pkg/utils/kubectl/configmap.go)

---

pkg/utils/kubeclient/configmap.go

In this comment normalization, l change the first word of the comment to the function name. Lowercase the first letter of the word 'Check'. And add a period at the end of the comment.
fixes #375 375

change the first word of the comment to the function name

---

pkg/ddc/alluxio/shutdown.go

Close the MetadataSyncDoneCh when shutting down the Alluxio engine, which can avoid orphan goroutine.

Avoid orphan goroutine by explicitly closing sync metadata channel

---

pkg/ddc/alluxio/create_volume.go

change the default StroageClassName of pv and pvc to ""
propably fixes #409

change the default StroageClassName of pv and pvc

---

pkg/controllers/runtime_controller.go
pkg/controllers/v1alpha1/dataset/dataset_controller.go
pkg/ddc/alluxio/cache.go
pkg/ddc/alluxio/shutdown.go
pkg/utils/crtl_utils.go
pkg/utils/kubeclient/volume.go

This PR edits the deleting logic of dataset and alluxioruntime , so that delete dataset can cascading delete runtime.
The alluxioruntime needs to query the cache through the dataset when it is deleted. Now , it can be deleted without a dataset.
During the deleting logic, I have found a bug : when deleting alluxioruntime, the pvc can be deleted if the pvc name is not same as the volume name defined in pod.Spec.Volumes
So , I changed the calibration condition from "if pvc.Name == pvcName" in function GetPvcMountPods to "pvc.PersistentVolumeClaim.ClaimName == pvcName".
#405
#420
when a pod is using the pvc ,delete the dataset, it cannot be deleted.
When deleting a dataset , the alluxioruntime will be deleted later.
the return values in cache.go are not consistent， I change them to "states". …

add ownerference of alluxioruntime, delete dataset will delete alluxioruntime with the same name

---

api/v1alpha1/dataset_types.go
charts/fluid/fluid/crds/data.fluid.io_datasets.yaml
cmd/dataset/main.go
config/crd/bases/data.fluid.io_datasets.yaml
pkg/ddc/alluxio/ufs_internal.go
pkg/utils/secret.go

Support secrets for dataset.
fix #447 
You can create a dataset and configure its mount options using secret. Here is an example:
```yaml
apiVersion: v1
kind: Secret
metadata:
name: mysecret
stringData:
fs.oss.accessKeyId: <OSS_ACCESS_KEY_ID>
fs.oss.accessKeySecret: <OSS_ACCESS_KEY_SECRET>
---
kind: Dataset
metadata:
name: mypod
spec:
mounts:
- mountPoint: oss://<OSS_BUCKET>/<OSS_DIRECTORY>/
name: myoss
options:
fs.oss.endpoint: <OSS_ENDPOINT>
encryptOptions:
- name: fs.oss.accessKeyId
valueFrom:
secretKeyRef:
name: mysecret
key: fs.oss.accessKeyId
- name: fs.oss.accessKeySecret
valueFrom:
secretKeyRef:
name: mysecret
key: fs.oss.accessKeySecret
```

Support secrets for dataset

---

pkg/controllers/v1alpha1/dataload/dataload_controller.go

in the fluid-cloudnative/fluid/pull/444, deleting the dataset will delete the alluxioruntime.
I add the owner of dataload now, so that deleting the dataset will not only delete alluxioruntime but also delete dataload. 
create a dataset and then create a dataload , the dataset will be the owner of dataload.
create a dataload without a dataset, the dataload will have no owner and finalizer.

add owner of dataload

---

api/v1alpha1/alluxioruntime_types.go
charts/fluid/fluid/crds/data.fluid.io_alluxioruntimes.yaml
charts/fluid/fluid/crds/data.fluid.io_jindoruntimes.yaml
config/crd/bases/data.fluid.io_alluxioruntimes.yaml
config/crd/bases/data.fluid.io_jindoruntimes.yaml
pkg/ddc/alluxio/engine.go
pkg/ddc/alluxio/runtime_info.go
pkg/ddc/alluxio/transform.go
pkg/ddc/alluxio/transform_optimization.go
pkg/ddc/alluxio/transform_resources_test.go
pkg/ddc/alluxio/utils.go
pkg/ddc/base/runtime.go
pkg/ddc/base/runtime_test.go
pkg/ddc/jindo/engine.go
pkg/ddc/jindo/runtime_info.go
pkg/utils/slice.go
pkg/utils/slice_test.go
pkg/utils/tieredstore/tiered_store.go

Currently, Fluid does not support multiple paths for a specific tieredstore like this
```yaml
kind: AlluxioRuntime
metadata:
name: dataset
spec:
...
tieredstore:
levels:
....
path: /path/to/cachestore1,/path/to/cachestore2
....
```
This PR adds support for this feature. Specifically, this PR did the following things:
- Refactor `runtime_info` data structure to better support this feature
- Add mult-path tieredstore support in both root and non-root scenarios
Fixes #531 
For verification, here's some samples:
Sample 1(set multiple paths and set quota with `quota`):
```yaml
kind: Dataset
metadata:
name: hbase
spec:
mounts:
- mountPoint: https://mirror.bit.edu.cn/apache/hbase/stable/
name: hbase
---
apiVersion: …
```

Support multi-dir tierstore

---

pkg/controllers/v1alpha1/dataload/implement.go

fix the bug causing by "nil boundedRuntime"
fixes #549

fix bug when boundedRuntime is nil

---

cmd/dataset/main.go
pkg/common/constants.go
pkg/controllers/v1alpha1/dataset/dataset_controller.go
pkg/utils/kubeclient/volume.go

when I tried to delete dataset, it will hang because the pod which uses pvc is not deleted.
I Enhance log and Event reporting when the dataset cannot being deleted
#535 
create a pod to use the pvc, and the delete the dataset

Enhance log and Event reporting when the dataset cannot being deleted

---

charts/fluid/fluid/templates/controller/alluxioruntime_controller.yaml
charts/fluid/fluid/templates/controller/dataset_controller.yaml
charts/fluid/fluid/templates/controller/jindoruntime_controller.yaml
charts/fluid/fluid/templates/csi/daemonset.yaml

removing the "priorityClassName: system-cluster-critical" in charts. 
fixes #559 
In default, pods with system-cluster-critical priorityClass is not permitted in fluid-system namespace

the bug of priorityClassName fixing

---

api/v1alpha1/alluxioruntime_types.go
charts/alluxio/templates/master/statefulset.yaml
charts/alluxio/templates/worker/daemonset.yaml
charts/alluxio/values.yaml
charts/fluid/fluid/crds/data.fluid.io_alluxioruntimes.yaml
config/crd/bases/data.fluid.io_alluxioruntimes.yaml
docs/zh/samples/hdfs_configuration.md
pkg/ddc/alluxio/const.go
pkg/ddc/alluxio/transform.go
pkg/ddc/alluxio/transform_hadoop_config.go
pkg/ddc/alluxio/types.go

When using HDFS as Alluxio's UFS, Alluxio may need additional HDFS configuraions (e.g. `hdfs-site.xml` and `core-site.xml`) to enable some features. For now, there is no way for Fluid's user to specify their HDFS conf files. 
This PR supports non-default configuration for HDFS with the following workflow:
1. user creates a configmap from HDFS conf file(s). (Only support `hdfs-site.xml` and `core-site.xml` for now)
2. user specifies the configmap name in AlluxioRuntime
3. Fluid mounts the configmap to Alluxio's Pods and enables special features for HDFS.
fixes #502 
1. Create configmap from HDFS conf file
```
kubectl create configmap hdfs-cm --from-file=/path/to/hdfs-site.xml --from-file=/path/to/core-site.xml
```
2. Create Dataset and AlluxioRuntime with `hadoopConfig` set to the name of …

Support non-default configurations for HDFS

---

charts/fluid-databackup/templates/configmap.yaml
pkg/ddc/alluxio/metadata.go
pkg/ddc/alluxio/operations/base.go

This PR decouples the restoring logic from loading metadata.
Only when user creating a DataBackup, the metadatafile info file will be saved.
Only when user restoring metadata from backup, the runtime will go to the restore logic.
I have vertified it in testing environment.
The goal to supple status of DataBackup（such as time and file size）will be submited in another PR.

Decouple the restore logic from load metadata

---

charts/alluxio/templates/fuse/daemonset.yaml
charts/jindofs/templates/fuse/daemonset.yaml

Currently, both Alluxio-fuse and Jindo-fuse mounts `/dev/fuse` from hostPath with a type of `File`. This can lead to error during mount time since k8s 1.19+. `/dev/fuse` is a char device, so this PR changes the HostPath mount type to `CharDevice` to pass the type check.
fixes #603

Fix /dev/fuse type check bug on K8s 1.19+

---

pkg/ddc/alluxio/runtime_info.go
pkg/utils/crtl_utils.go
pkg/utils/dataset/lifecycle/schedule.go
pkg/utils/dataset/lifecycle/schedule_test.go
pkg/utils/kubeclient/volume.go

prefer to chhoose PVC Mount Nodes when scale up if fuse is in global mode
#588
I have vertified it by some indirect means, such as printing logs
To show the effect , it needs plenty of nodes

sort nodes to be scheduled before filter if fuse is in global mode

---

pkg/utils/kubeclient/volume.go

When coding the function of GetPvcMountNodes, a check was forgetten: ignoring Pods which is completed.

ignore pods which is completed when calculate PVCMountNodes

---

api/v1alpha1/alluxioruntime_types.go
api/v1alpha1/status.go
charts/fluid/fluid/crds/data.fluid.io_alluxioruntimes.yaml
config/crd/bases/data.fluid.io_alluxioruntimes.yaml
pkg/common/constants.go
pkg/ddc/alluxio/operations/base.go
pkg/ddc/alluxio/replicas.go
pkg/ddc/alluxio/shutdown.go
pkg/ddc/alluxio/ufs.go
pkg/ddc/alluxio/utils.go
pkg/ddc/alluxio/utils_test.go
pkg/utils/dataset/lifecycle/schedule.go
pkg/utils/dataset/lifecycle/schedule_test.go

Add support for Alluxio runtime scaling in. Generally, this PR does the following changes:
- Alluxio is now able to scale in if user decrease `AlluxioRuntime.spec.replicas`
- Add scale subresources for AlluxioRuntime to enable a convenience way(i.e. by `kubectl scale` cli) for user to scale out or scale in.
fixes #545 
Here are some testcases to verify this PR. 
In a multiple-node k8s env, create Dataset and AlluxioRuntime like this:
```yaml
kind: Dataset
metadata:
name: hbase
spec:
mounts:
- mountPoint: https://mirrors.bit.edu.cn/apache/hbase/stable/
name: hbase
---
kind: AlluxioRuntime
metadata:
name: hbase
spec:
replicas: 2
tieredstore:
levels:
- mediumtype: MEM
path: /dev/shm
quota: 1Gi
high: "0.95"
low: "0.7" …
```

Add support for Alluxio runtime scaling in

---

api/v1alpha1/alluxioruntime_types.go
config/crd/bases/data.fluid.io_alluxioruntimes.yaml

fix quotaList pattern

---

pkg/ddc/base/pv.go
pkg/ddc/base/runtime.go
pkg/ddc/jindo/create_volume.go
pkg/utils/dataset/volume/create.go
pkg/utils/dataset/volume/delete.go
pkg/utils/dataset/volume/deprecated.go

Currently, Fluid take "\<dataset-name\>" as corresponding PersistentVolume(PV)'s name. Since PV is not a namespaced resource in Kubernetes, such a naming style may cause issues when different users create Dataset objects with the same name in different namespaces. 
This PR fixes this by changing PV's name from "\<dataset-name\>" to "\<namspace\>-\<dataset-name\>". Such a naming style ensures there are no conflicts when users in different namespaces create Dataset with the same name. Specifically, this PR
- Checks if there is some dataset using original naming style
- Creates the PV with the new naming style
- Deletes the PV no matter what naming style it is using
fixes #695 
1. Ensure you have a Fluid with an existing version deployed
2. Create a dataset
3. Upgrade Fluid
4. Delete the …

Fix PV multi-tenancy issue

---

pkg/ddc/alluxio/node.go

This PR solves the NPE problem.
fixed #686 
If the log is put before the if-clause, it will cause NPE problem when the dataset get before is nil.

Solve the NPE problem

---

charts/fluid/fluid/Chart.yaml
charts/fluid/fluid/values.yaml

Fix backup for non root, and build docker image

---

pkg/common/alluxio.go
pkg/common/constants.go
pkg/common/fluid_ufs_scheme.go
pkg/common/fluid_ufs_scheme_test.go
pkg/controllers/v1alpha1/databackup/databackup_controller.go
pkg/controllers/v1alpha1/databackup/implement.go
pkg/controllers/v1alpha1/dataload/implement.go
pkg/ddc/alluxio/metadata.go
pkg/ddc/alluxio/transform.go
pkg/ddc/alluxio/transform_optimization.go
pkg/ddc/alluxio/transform_ufs.go
pkg/ddc/alluxio/ufs_internal.go
pkg/ddc/alluxio/ufs_path_builder.go
pkg/ddc/alluxio/ufs_path_builder_test.go
pkg/ddc/alluxio/utils.go
pkg/ddc/alluxio/utils_test.go
pkg/utils/databackup.go

1.  support set alluxio instance configuration  `alluxio.master.mount.table.root.ufs` by dataset count and scheme
2. support if user define `mount.path`, replace mount.name as the mount path 
fixed #643

Support path to overwrite name in Dataset API

---

pkg/ddc/alluxio/cache.go
pkg/ddc/jindo/cache.go

when delete JindoRuntime, if master statefulset deleted early, the delete process will trap in a loop so that the deletion process cannot proceed normally
2021-05-12T15:33:49.437+0800	INFO	jindoctl.JindoRuntime	jindo/cache.go:65	Failed to get master	{"jindoruntime": "default/hadoop", "err": "StatefulSet.apps \"hadoop-jindofs-master\" not found"}
2021-05-12T15:33:49.437+0800	ERROR	jindoctl.JindoRuntime.reconcileRuntimeDeletion	controllers/runtime_controller.go:158	Failed to shutdown the engine	{"jindoruntime": "default/hadoop", "Runtime": {"namespace": "default", "name": "hadoop"}, "error": "StatefulSet.apps \"hadoop-jindofs-master\" not found"}
fixes #775

retry find statefulset when destroyMaster

---

charts/fluid/fluid/templates/controller/alluxioruntime_controller.yaml
charts/fluid/fluid/templates/controller/jindoruntime_controller.yaml
charts/fluid/fluid/values.yaml
cmd/alluxio/main.go
cmd/jindo/main.go
pkg/controllers/v1alpha1/alluxio/alluxio_runtime_controller.go
pkg/controllers/v1alpha1/jindo/jindoruntime_controller.go
pkg/utils/dataset/lifecycle/node.go
pkg/utils/dataset/lifecycle/schedule.go
pkg/utils/map.go
pkg/utils/map_test.go
pkg/utils/time_tracker.go

Currently, Fluid controllers(e.g. AlluxioRuntime Controller) use only one worker for reconciliation. Given that there are many AlluxioRuntime CRs, there is a chance that reconciliation for one CR may be delayed especially when a single reconciliation process takes significant time cost.
This PR allows users to adjust max concurrent reconciles for controllers according to their needs. Default value for max concurrent reconciles is 1, and users can set this when `helm install` Fluid's chart by:
```
helm install --set runtime.alluxio.runtimeWorkers=3 fluid fluid-chart
``` 
To avoid concurrency issue, this PR also add a mutex lock. For now, only scheduling processing is locked because as far as I know, the scheduling process is the only location that can cause concurrency bugs. 
fixes #768

Allow users to adjust max concurrent reconciles

---

pkg/ddc/alluxio/operations/cached.go

Fix timeout unknown option bug when using default alluxio images. (#765 )
This is a workaround fix and we should consider a more adaptive solution in the future.
NONE

Fix timeout unknown option bug

---

pkg/utils/dataset/lifecycle/node.go
pkg/utils/dataset/lifecycle/schedule.go

- Log time cost for func `AssignDatasetToNode`
- Log time cost for func `LabelCacheNode`
These logs are added for easier debugging
NONE

Add time tracker for scheduler

---

charts/alluxio/values.yaml

Now, we not expose the journal interface for user. So we change journal type from "UFS" to ”EMBEDDED“ manually. It's only temporary.
cc @cheyang

fix ha bug

---

pkg/ddc/alluxio/shutdown.go
pkg/ddc/jindo/shutdown.go
pkg/utils/dataset/lifecycle/node.go
pkg/utils/dataset/lifecycle/node_test.go

This PR lets the datasetNum calculates the number of the dataset regardless of the type of the dataset(such as alluxioruntime, jindoruntime)
I test the code in different cases. Continue to create, continue to delete and create and delete at the same time for both two kinds of the dataset.

Update the datasetNum label regardless of the type of the dataset

---

Makefile
charts/fluid/fluid/Chart.yaml
charts/fluid/fluid/values.yaml
pkg/ddc/alluxio/port_parser_test.go

Build docker image

---

pkg/controllers/v1alpha1/databackup/implement.go

fix the bug of unable to backup when Name of Databackup containing "-"

fix the bug of unable to backup when Name of Databackup containing "-"

---

charts/fluid/fluid/templates/csi/daemonset.yaml

node-driver-registrar will mount kubelet-dir on {{ .Values.csi.kubelet.rootDir }}
without 'HostToContainer' or 'Bidirectional'.
If another pod mount a temporary device on their volume directory like
'${kubelet-dir}/lib/kubelet/pods/xxx/volumes/' which create before node-driver-registrar
and delete after node-driver-registrar is created will cause device deconstruction to fail.
Signed-off-by: tuji.yyf <tuji.yyf@alibaba-inc.com>
https://github.com/fluid-cloudnative/fluid/issues/1048

Add mount propagation in node-driver-registrar

---

Makefile
charts/fluid/fluid/CHANGELOG.md
charts/fluid/fluid/Chart.yaml
charts/fluid/fluid/values.yaml
pkg/ddc/jindo/health_check_test.go
pkg/ddc/jindo/worker.go
pkg/ddc/jindo/worker_test.go
pkg/webhook/certificate_builder_test.go

Fix issue for jindo

---

tools/diagnose-fluid.sh

In diagnose scirpt, for Alluxio logs, copy from the logs directory instead of using `kubectl logs`
fixes #1059

Copy Alluxio logs out from containers in diagnose script

---

pkg/ddc/alluxio/transform_optimization_test.go
pkg/ddc/alluxio/transform_resources.go
pkg/ddc/alluxio/transform_resources_test.go
pkg/ddc/alluxio/types.go

When I use a new image to create AlluxioRuntime in namespace with resourceQuota， I created this statefulset 
> apiVersion: apps/v1
kind: StatefulSet
spec:
podManagementPolicy: OrderedReady
replicas: 1
revisionHistoryLimit: 10
selector:
matchLabels:
app: alluxio
name: autocv-det-train-180-eaff-master
role: alluxio-master
serviceName: autocv-det-train-180-eaff-master
template:
metadata:
creationTimestamp: null
labels:
app: alluxio
chart: alluxio-0.7.0
heritage: Helm
name: autocv-det-train-180-eaff-master
release: autocv-det-train-180-eaff
role: alluxio-master
spec:
affinity: {}
containers:
- args:
- master-only
- --no-format
command:
- /entrypoint.sh
env:
- name: ALLUXIO_MASTER_HOSTNAME
valueFrom:
fieldRef:
apiVersion: v1
fieldPath: status.podIP
- name: …

fix setting resources to jobmaster and jobworker

---

charts/fluid/fluid/templates/csi/daemonset.yaml
cmd/csi/main.go

Add support for csi pprof
**Port Forward**
`kubectl port-forward -n fluid-system <csi-plugin-pod> 6060`
**CPU Profile**
`go tool pprof http://localhost:6060/debug/pprof/profile`
**Mem Profile**
`go tool pprof http://localhost:6060/debug/pprof/heap`
#1139

Add support for csi pprof

---

charts/fluid-dataloader/goosefs/templates/configmap.yaml
charts/fluid-dataloader/goosefs/templates/dataloader.yaml
charts/fluid-dataloader/goosefs/values.yaml
pkg/ddc/goosefs/load_data.go
pkg/ddc/goosefs/load_data_test.go

Add goosefs dataload atomic cache.
#1182 
Dataload yaml like this:
```yaml
kind: DataLoad
metadata:
name: tke-cos
namespace: default
spec:
dataset:
name: tke-cos
namespace: default
loadMetadata: true
target:
- path: /new_in_cos
options:
- atomicCache: "true"
- expireTime: 43200000
```
cc @cheyang

Add goosefs dataload atomic cache

---

pkg/ddc/alluxio/transform_api_gateway.go

Provide a link to that doc page:
https://github.com/fluid-cloudnative/fluid/blob/master/pkg/ddc/alluxio/transform_api_gateway.go
What is the defect and your suggestions on improvement:
defect: missing Apache 2.0 License at the begining of file pkg/ddc/alluxio/transform_api_gateway.go
suggestions: add the Apache 2.0 license
Fixes #1241

add license on `pkg/ddc/alluxio/transform_api_gateway.go`

---

charts/fluid/fluid/CHANGELOG.md
charts/fluid/fluid/templates/controller/alluxioruntime_controller.yaml
charts/fluid/fluid/templates/controller/goosefsruntime_controller.yaml
charts/fluid/fluid/templates/controller/jindoruntime_controller.yaml
charts/fluid/fluid/templates/controller/juicefsruntime_controller.yaml
charts/fluid/fluid/values.yaml
pkg/ddc/base/runtime_test.go
pkg/ddc/base/syncs.go
pkg/ddc/base/template_engine.go
pkg/ddc/base/template_engine_test.go

This PR is to avoid high frequently retries. By default, it's 5 seconds. And you can customize it  by setting environment variable `FLUID_SYNC_RETRY_DURATION`.
fixes #1246

Avoid high frequently retries of sync

---

api/v1alpha1/constant.go
api/v1alpha1/jindoruntime_types.go
charts/fluid/fluid/crds/data.fluid.io_jindoruntimes.yaml
config/crd/bases/data.fluid.io_jindoruntimes.yaml
pkg/csi/fuse/nodeserver.go
pkg/ddc/base/runtime.go
pkg/ddc/base/runtime_test.go

Set default fuse clean policy to OnRuntimeDeleted
NONE

Set default fuse clean policy to OnRuntimeDeleted

---

charts/alluxio/templates/master/statefulset.yaml
charts/goosefs/templates/master/statefulset.yaml

This pr fix syntax error in alluxio helm template, missing prefix "{{"
fixes #1302

Fix bug in helm template

---

charts/fluid/fluid/templates/controller/alluxioruntime_controller.yaml
charts/fluid/fluid/templates/controller/dataset_controller.yaml
charts/fluid/fluid/templates/controller/goosefsruntime_controller.yaml
charts/fluid/fluid/templates/controller/jindoruntime_controller.yaml
charts/fluid/fluid/templates/controller/juicefsruntime_controller.yaml
charts/fluid/fluid/templates/webhook/webhook.yaml
cmd/alluxio/main.go
cmd/dataset/main.go
cmd/goosefs/app/goosefs.go
cmd/jindo/main.go
cmd/juicefs/app/juicefs.go
cmd/webhook/app/webhook.go
pkg/utils/kubeclient/exec.go
pkg/utils/pprof.go
pkg/utils/pprof_test.go

add instant live visualization of statistics for performance analysis
fixes #780 
I cannot decide on nodeport number. please give me some advice. thanks.

Add support for dataset,runtime,webhook pprof

---

charts/juicefs/templates/fuse/daemonset.yaml
pkg/ddc/juicefs/transform_fuse.go
pkg/ddc/juicefs/utils.go
pkg/ddc/juicefs/utils_test.go

fix juicefsruntime fuse container restart fail. see issue: https://github.com/fluid-cloudnative/fluid/issues/1345

fix juicefs fuse container restart fail

---

pkg/ddc/juicefs/shutdown.go
pkg/ddc/juicefs/shutdown_test.go

fix fuse label is not deleted after juicefs runtime is deleted 
fixes #1381

add fuse clean in juicefs runtime shutdown

---

charts/fluid/fluid/Chart.yaml
charts/fluid/fluid/values.yaml

Build docker image for csi plugin

---

cmd/alluxio/app/alluxio.go
cmd/alluxio/app/init.go
cmd/alluxio/app/version.go
cmd/alluxio/main.go
cmd/dataset/app/dataset.go
cmd/dataset/app/init.go
cmd/dataset/app/version.go
cmd/jindo/app/init.go
cmd/jindo/app/jindo.go
cmd/jindo/app/version.go
cmd/jindo/main.go

Unify the file format under cmd, three modules alluxio,dataset,jindo
this modification is in this PR https://github.com/fluid-cloudnative/fluid/pull/1287
but a long time leads to conflicts
so submit it independently

unify the file format under cmd, alluxio jindo dataset

---

charts/fluid/fluid/Chart.yaml
charts/fluid/fluid/values.yaml
pkg/webhook/scheduler/mutating/schedule_pod_handler.go
pkg/webhook/scheduler/mutating/schedule_pod_handler_test.go

Support pod's namespace is empty in webhook

---

pkg/controllers/v1alpha1/dataload/dataload_controller.go

To fix the bug, This PR reorders the reconciliation logic to ensure that deletion event of the DataLoad CRD will be processed in the first place.
fixes #1419

Fix dataload cannot be cleaned up bug

---

charts/fluid/fluid/values.yaml
pkg/common/goosefs.go
pkg/ddc/alluxio/operations/cached.go
pkg/ddc/goosefs/operations/cached.go
pkg/ddc/goosefs/operations/cached_test.go
pkg/ddc/goosefs/shutdown_test.go
pkg/ddc/goosefs/utils_test.go

Fix CleanCache function linux version error, if using alpine image, timeout command have no `-k` option.
@cheyang

(GooseFS) [Bug Fix] Fix clean cache linux version error

---

pkg/controllers/v1alpha1/dataload/dataload_controller.go
pkg/controllers/v1alpha1/dataload/implement.go

Dataload controller try to update the `Dataload` status using name/namespace in `ctx` which is the name of `Dataset` but not `Dataload`
Fix this by replacing `ctx` with `targetDataload`
fixes #1436

Fix update dataload status error

---

charts/alluxio/templates/config/alluxio-conf.yaml

The high low water mark has been removed from alluxio from 2.0.
User will be confused by the removed watermark configure keys.

Remove the removed watermark configure key

---

pkg/ddc/alluxio/transform_optimization.go

With the new implementation of distributedLoad in Alluxio, when reading a lot of files, 164 job workers will flood the connection to worker and make the job fail. Thus decrease the thread pool size to 32.

Use less job worker threads to prevent flooding connection to worker

---

pkg/application/inject/fuse/injector.go
pkg/common/constants.go
pkg/ddc/base/runtime.go
pkg/ddc/base/runtime_helper.go
pkg/ddc/base/runtime_helper_test.go
pkg/utils/annotations.go
pkg/utils/annotations_test.go
pkg/utils/volumes.go
pkg/utils/volumes_test.go

We shouldn't inject cache dir volume into App pod by default in serverless scenario.  But the user is able to use it by setting 
label `cachedir.sidecar.fluid.io/inject=true` 
fixes #1463

Remove cache dir from sidecar pod

---

README.md

Added what's new for v0.7 release

Added what's new for v0.7 release

---

pkg/ddc/alluxio/worker_test.go

This pr is to add copyright to standardize the Apache License in file: "pkg/ddc/alluxio/worker_test.go"
fixes #1565

add "copyright" to standardize the Apache License in file: "pkg/ddc/alluxio/worker_test.go"

---

pkg/ddc/goosefs/deprecated_label_test.go

add Apache License to pkg/ddc/goosefs/deprecated_label_test.go

---

pkg/ddc/jindo/label_test.go

This PR is to add Copyright infos of Apache License to file pkg/ddc/jindo/label_test.go.

Add Copyright infos of Apache License to file pkg/ddc/jindo/label_test.go

---

pkg/ddc/jindo/deprecated_label_test.go

This pr is to add Apache License on pkg/ddc/jindo/deprecated_label_test.go

Zjr191220158

---

charts/fluid/fluid/templates/csi/daemonset.yaml
pkg/csi/plugins/nodeserver.go
pkg/ddc/goosefs/transform_permission.go

Optimize CSI Plugin node server logic.
This PR  caches node to avoid frequent requests to api server
NONE

Optimize CSI Plugin node server logic

---

pkg/csi/plugins/nodeserver.go

Fluid CSI Plugin should not check stale cache node info before patch. 
Stale cache node may have stale information so it's not reliable.
fixes #1618

Bug fix: should not check stale cache node info before patch

---

pkg/ddc/base/pv.go

This pr is to add license information in pkg/ddc/base/pv.go

normalize license information in pkg/ddc/base/pv,go

---

pkg/ddc/goosefs/types_selector.go

Signed-off-by: Slepha <1552173217@qq.com>
This pr is to add license to pkg/ddc/goosefs/types_selector.go.

add license to pkg/ddc/goosefs/types_selector.go

---

pkg/ddc/jindo/node.go

The pr is to add the licence in pkg/ddc/jindo/node.go.

add the license in node.go

---

pkg/ddc/goosefs/transform_optimization.go

This pr is to add Apache License on pkg/ddc/goosefs/transform_optimization.go

add Apache License on transform_optimization.go

---

pkg/ddc/goosefs/runtime_info.go

This pr is to add a correct license in pkg/ddc/goosefs/runtime_info.go
fixes #1748

revise license in pkg/ddc/goosefs/runtime_info.go

---

pkg/ddc/alluxio/shutdown.go
pkg/ddc/alluxio/shutdown_test.go
pkg/ddc/base/portallocator/port_allocator.go
pkg/ddc/goosefs/shutdown.go
pkg/ddc/goosefs/shutdown_test.go
pkg/ddc/goosefs/ufs_internal_test.go

- Restart controller and restore port allocator when port allocation leak happens
- Add warning logs to indicate some ports may already be leaked
NONE
no tests are needed
1. Set a tight port range with `helm install --set runtime.alluxio.portRange=20000-20010 fluid fluid`
2. Create a dataset with AlluxioRuntime.
3. Delete the corresponding ConfigMap `<dataset-name>-alluxio-values`. Then delete the dataset, now the allocated port is leaked.
4. Create a new dataset.
5. The alluxioruntime-controller should exit with error code and restart to restore port allocator.

[BUGFIX]Restart controller and restore port allocator when port allocation leak happens

---

pkg/ddc/jindo/delete_volume_test.go

This pr is to add license information to pkg/ddc/jindo/delete_volume_test.go

add License information to pkg/ddc/jindo/delete_volume_test.go

---

api/v1alpha1/juicefsruntime_types.go
api/v1alpha1/openapi_generated.go
api/v1alpha1/zz_generated.deepcopy.go
charts/fluid/fluid/crds/data.fluid.io_alluxioruntimes.yaml
charts/fluid/fluid/crds/data.fluid.io_databackups.yaml
charts/fluid/fluid/crds/data.fluid.io_dataloads.yaml
charts/fluid/fluid/crds/data.fluid.io_datasets.yaml
charts/fluid/fluid/crds/data.fluid.io_goosefsruntimes.yaml
charts/fluid/fluid/crds/data.fluid.io_jindoruntimes.yaml
charts/fluid/fluid/crds/data.fluid.io_juicefsruntimes.yaml
config/crd/bases/data.fluid.io_alluxioruntimes.yaml
config/crd/bases/data.fluid.io_databackups.yaml
config/crd/bases/data.fluid.io_dataloads.yaml
config/crd/bases/data.fluid.io_datasets.yaml
config/crd/bases/data.fluid.io_goosefsruntimes.yaml
config/crd/bases/data.fluid.io_jindoruntimes.yaml
config/crd/bases/data.fluid.io_juicefsruntimes.yaml
config/rbac/role.yaml
config/webhook/manifests.yaml
pkg/ddc/juicefs/transform_fuse.go
pkg/ddc/juicefs/transform_fuse_test.go

fix https://github.com/fluid-cloudnative/fluid/issues/1803

add configs in juicefsruntime

---

pkg/ddc/juicefs/cache.go
pkg/ddc/juicefs/cache_test.go
pkg/ddc/juicefs/const.go
pkg/ddc/juicefs/operations/base.go
pkg/ddc/juicefs/operations/base_test.go
pkg/ddc/juicefs/report.go
pkg/ddc/juicefs/report_test.go
pkg/ddc/juicefs/status.go
pkg/ddc/juicefs/status_test.go
pkg/ddc/juicefs/ufs.go
pkg/ddc/juicefs/ufs_internal.go
pkg/ddc/juicefs/ufs_test.go
pkg/ddc/juicefs/utils.go
pkg/ddc/juicefs/utils_test.go

Signed-off-by: hwanghoward <2281743190@qq.com>
fix https://github.com/fluid-cloudnative/fluid/issues/1827
Both enterprise and community edition use .stats file to get cache size.
Both enterprise and community edition use 'df' to get total used space.

get cache states from runtime pods instead of fuse pods when using juicefs enterprise edition

---

docs/en/samples/gcs_configuration.md
docs/zh/samples/gcs_configuration.md

Signed-off-by: Lize Cai <lize.cai@sap.com>
As Alluxio Runtime support mount volumes now by https://github.com/fluid-cloudnative/fluid/pull/1839. Users are able to mount datasets from GCS.
fixes #1835
This PR only add docs to show users how to configure GCS dataset in Fluid.
can follow the steps to verify it. I have verified it manually.

Add docs to mount dataset from GCS in Alluxio Runtime

---

pkg/ctrl/watch/pod.go

If fluidapp controller restart on handling update event of pod, after fluidapp controller restarted, it will receive only create event. To avoid this situation, check if should pod inqueue in onCreateFunc in app controller.

check if should pod inqueue in onCreateFunc in app controller

---

charts/fluid/fluid/values.yaml

Enable juicefs runtime by default

Enable juicefs runtime by default

---

cmd/alluxio/app/alluxio.go
cmd/dataset/app/dataset.go
cmd/fluidapp/app/fluidapp.go
cmd/goosefs/app/goosefs.go
cmd/jindo/app/jindo.go
cmd/juicefs/app/juicefs.go
cmd/webhook/app/webhook.go

Fix: #1960
For dataset, fluidapp, webhook and all runtimes controller:
- add the `leader-election-namespace` flag to set the namespace leader election resource will be created, the default is `fluid-system`.
- update `LeaderElectionID` by the component name.
PS. The webhook component is ok to add leader election directly because the webhook service is recognized as the **non-leaderelection Runnables** by controller-runtime so that all webhook Pod will start the webhook service in the multi-replica scenario.
PPS. There are still some RBAC issue with the leader election, I'll update the helm chart template in next PR.

Support leader election for controller and webhook

---

pkg/ddc/juicefs/transform_fuse.go
pkg/ddc/juicefs/transform_fuse_test.go
pkg/ddc/juicefs/utils.go
pkg/ddc/juicefs/utils_test.go

fix: juicefs cache-size should be integer in MiB
fix: parse edition in juicefs value none

fix cache-size & parse edition in juicefs

---

pkg/ddc/base/runtime_helper.go
pkg/scripts/poststart/check_fuse_app.go

Fix NPE when running juicefs with unprivileged fuse sidecar. 
- Check if `securityContext` is nil when mutating juicefs unprivileged fuse sidecar 
- Make mountType to lowercase to fix RFC naming error.
fixes #2039

Fix NPE when running juicefs with unprivileged fuse sidecar

---

charts/fluid/fluid/templates/webhook/webhookconfiguration.yaml

Remove redundant admission webhook operation rule. According to #2053, pod update will failed when fluid webhook injection is enabled. 
This is because fluid webhook will be called when any pod update request is issued. For some of the webhook plugins(e.g. `PreferNodesWithoutCache`), they attempt to mutate some immutable information in the pod, causing validation failure.
fixes #2053

Remove redundant admission webhook operation rule

---

charts/fluid/fluid/values.yaml

update image of csi-node-driver-registrar to support arm64 platform.
only the lastest version updated, and the past versions not chanaged.

node driver registrar support arm64

---

api/v1alpha1/alluxioruntime_types.go
charts/alluxio/CHANGELOG.md
charts/alluxio/templates/_helpers.tpl
charts/alluxio/templates/fuse/daemonset.yaml
charts/fluid/fluid/crds/data.fluid.io_alluxioruntimes.yaml
charts/fluid/fluid/crds/data.fluid.io_goosefsruntimes.yaml
charts/fluid/fluid/crds/data.fluid.io_jindoruntimes.yaml
charts/fluid/fluid/crds/data.fluid.io_juicefsruntimes.yaml
config/crd/bases/data.fluid.io_alluxioruntimes.yaml
config/crd/bases/data.fluid.io_goosefsruntimes.yaml
config/crd/bases/data.fluid.io_jindoruntimes.yaml
config/crd/bases/data.fluid.io_juicefsruntimes.yaml
pkg/common/constants.go
pkg/ddc/alluxio/transform.go
pkg/ddc/alluxio/transform_test.go
pkg/ddc/base/runtime.go

Support emptyDir as tieredstore's optional volume type
#2069
Only for AlluxioRuntime now, will fixes it when all the runtime supports it.
1. A naive AlluxioRuntime with modification on `tieredstore.levels[*].volumeType` can be used to verify it. 
```
kind: AlluxioRuntime
metadata:
name: demo-dataset
spec:
replicas: 1
tieredstore:
levels:
- mediumtype: SSD
volumeType: emptyDir
path: /mnt/ssd1,/mnt/ssd2
#quota: 20Gi
quotaList: 5Gi,10Gi
high: "0.99"
low: "0.99"
```
2. Check worker pod and fuse pod's `volumes` and `volumeMounts`
3. See something like this
```
volumes:
- emptyDir:
medium: Memory
sizeLimit: 10Gi
name: mem
```

Support emptyDir as tieredstore's optional volume type for AlluxioRuntime

---

charts/fluid/fluid/templates/csi/daemonset.yaml
charts/fluid/fluid/values.yaml
cmd/csi/app/csi.go
pkg/csi/config/config.go
pkg/csi/register.go
pkg/csi/updatedbconf/register.go
pkg/csi/updatedbconf/updatedbconf.go
pkg/csi/updatedbconf/updatedbconf_test.go

#2058
Add a plugin in CSI to modify `/etc/updatedb.conf` on host node whiling starting the CSI Pod. The changes are only made when `/etc/updatedb.conf` do exist on the node.
The fs to prune in `PRUNEFS` use `runtime.mountRoot` in `values.yaml`.
The paths to prune in `PRUNEPATHS` use `csi.pruneFs` in `values.yaml`.
Which add the flowing flags in CSI plugin container:
```
- --prune-fs=fuse.alluxio-fuse,fuse.jindofs-fuse,JuiceFS,fuse.goosefs-fuse,ossfs
- --prune-path=/runtime-mnt
```

Update node /etc/updatedb.conf in csi plugin

---

charts/alluxio/Chart.yaml
charts/jindofsx/CHANGELOG.md
charts/jindofsx/Chart.yaml
charts/jindofsx/templates/fuse/daemonset.yaml
charts/jindofsx/templates/master/statefulset.yaml
charts/jindofsx/templates/worker/statefulset.yaml
charts/jindofsx/values.yaml
pkg/common/constants.go
pkg/ddc/jindofsx/transform.go
pkg/ddc/jindofsx/transform_master_test.go
pkg/ddc/jindofsx/transform_worker_test.go
pkg/ddc/jindofsx/types.go

Runtime support configurable tieredstore volume type
fixes #2069 
runtime.yaml
```
kind: JindoRuntime
metadata:
name: demo-dataset
spec:
replicas: 1
tieredstore:
levels:
- mediumtype: MEM
volumeType: emptyDir
path: /dev/shm
quota: 20Gi
high: "0.99"
low: "0.99"
```
Setting `spec.tieredstore.levels[*].volumeType=emptyDir` will force JindoRuntime master and worker pods to mount emptyDir volume as their tieredstore. If not set, the `volumeType` defaults to `hostPath` which is the current behavior

JindoRuntime support configurable tieredstore volume type

---

charts/fluid/fluid/templates/csi/daemonset.yaml

When plugin restarted for some reason, `preStop` will be executed and remove reg.sock. It will cause kubelet remove it from csi plugin list and can not serve any more.
reg.sock will be removed by node-driver-registar when it shutdown. refer to https://github.com/kubernetes-csi/node-driver-registrar/pull/61 . `preStop` is not needed any more.

remove prestop in csi plugin

---

charts/juicefs/CHANGELOG.md
charts/juicefs/Chart.yaml
charts/juicefs/templates/fuse/daemonset.yaml
charts/juicefs/templates/worker/statefuleset.yaml
charts/juicefs/values.yaml
pkg/ddc/alluxio/transform.go
pkg/ddc/alluxio/transform_test.go
pkg/ddc/jindofsx/transform_test.go
pkg/ddc/juicefs/transform.go
pkg/ddc/juicefs/transform_test.go
pkg/ddc/juicefs/type.go

Make juicefs runtime pod metadata configurable
Related PR: #2086 
fixes #2089 
- Added unit tests for `transformPodMetadata` function.
JuiceFSRuntime example:
```
kind: JuiceFSRuntime
metadata:
name: jfsdemo
spec:
replicas: 1
podMetadata:
labels:
test1: common-value
common-label: "true"
annotations:
annotation-x: "y"
worker:
podMetadata:
labels:
test1: worker-value
annotations:
annotation-test: "worker"
fuse:
podMetadata:
labels:
test1: fuse-value
annotations:
annotation-test: "fuse"
tieredstore:
levels:
- mediumtype: MEM
path: /dev/shm
quota: 4096
low: "0.1"
```

Make juicefs runtime pod metadata configurable

---

pkg/csi/updatedbconf/register.go
pkg/csi/updatedbconf/updatedbconf.go

#2058 
Backup old `/etc/updatedb.conf` to `/etc/updatedb.conf.backup`

Backup `/etc/updatedb.conf` in CSI if changes were made

---

charts/alluxio/CHANGELOG.md
charts/alluxio/Chart.yaml
charts/alluxio/templates/master/statefulset.yaml
charts/alluxio/templates/worker/statefulset.yaml

Remove host pid and hostPath volume in Alluxio. This PR makes the following changes:
- Remove `hostPid: true` for its only usage when debugging JVM processes
- Remove hostPath volume `backup` in Alluxio helm chart.
The hostPath volume `backup` is used as an intermediate storage for backup metadata and journals of Alluxio. This is a feature supported by Alluxio only for now. To support "Fluid on serverless platforms" which mostly don't allow hostPath volumes in  Pod specs, this PR decides to remove it by default. This may affect the `DataBackup` feature but we can guide users to manually mount the hostPath volume  in [document](https://github.com/fluid-cloudnative/fluid/blob/master/docs/zh/samples/backup_and_restore_metadata.md) to work around this problem.
NONE

Remove host pid and backup hostPath volume in Alluxio

---

charts/alluxio/CHANGELOG.md
charts/alluxio/Chart.yaml
charts/alluxio/templates/_helpers.tpl
charts/jindofsx/CHANGELOG.md
charts/jindofsx/Chart.yaml
charts/jindofsx/templates/worker/statefulset.yaml
pkg/ddc/alluxio/transform.go
pkg/ddc/alluxio/transform_test.go
pkg/ddc/base/runtime.go
pkg/ddc/jindofsx/transform.go
pkg/ddc/jindofsx/transform_worker_test.go

Transform emptyDir volume source. Users can specify `Runtime.Spec.TieredStore.Levels[*].volumeSource` to use platform-dependent emptyDir medium.
For example:
```
tieredstore:
levels:
- mediumtype: SSD
volumeType: emptyDir
volumeSource:
emptyDir:
medium: <storage-medium>
path: /dev/shm
quota: 10Gi
high: "0.99"
low: "0.99"
```
#2122

Transform emptyDir volume source

---

pkg/ddc/alluxio/transform_fuse_test.go
pkg/ddc/alluxio/transform_optimization.go
pkg/ddc/alluxio/transform_optimization_test.go

fix the fuse args bug when the alluxio version is 2.8.0 or greater.
fixes #2134 
alluuxioruntime:
...
fuse:
args:
- "fuse"
- "--fuse-opts=kernel_cache,rw"
...
when set the fuse args in alluxioruntime, the fuse pod is running, mount success, and the pod which use this pvc will running normally.

fix when alluxioruntime fuse args set, add mountPath in args

---

docs/en/userguide/troubleshooting.md
docs/zh/userguide/troubleshooting.md
tools/diagnose-fluid-alluxio.sh
tools/diagnose-fluid-goosefs.sh
tools/diagnose-fluid-juicefs.sh

add juicefs diagnose script and fix alluxio diagnose script

---

pkg/ddc/base/template_engine.go

When scale runtime replicas, it will wait util retry period which is 60s. It's too long to wait and set default runtime reconcile period to 5s.

update default runtime retry period

---

charts/alluxio/CHANGELOG.md
charts/alluxio/Chart.yaml
charts/alluxio/templates/fuse/client-daemonset.yaml
charts/alluxio/templates/fuse/daemonset.yaml
charts/goosefs/CHANGELOG.md
charts/goosefs/Chart.yaml
charts/goosefs/templates/fuse/client-daemonset.yaml
charts/goosefs/templates/fuse/daemonset.yaml
charts/jindofs/CHANGELOG.md
charts/jindofs/Chart.yaml
charts/jindofs/templates/fuse/daemonset.yaml
charts/jindofsx/CHANGELOG.md
charts/jindofsx/Chart.yaml
charts/jindofsx/templates/fuse/daemonset.yaml
charts/juicefs/CHANGELOG.md
charts/juicefs/Chart.yaml
charts/juicefs/templates/fuse/daemonset.yaml
charts/thin/CHANGELOG.md
charts/thin/Chart.yaml
charts/thin/templates/fuse/daemonset.yaml

Add the toleration to fuse. With this feature, FUSE pod has toleration that tolerates everything. So the FUSE pod can be aways shceduled to the same node with the application pod. And i have test the feature with alluxio, juicefs and jindo runtime.
fix #2132

feature:add the toleration to fuse

---

pkg/ddc/thin/status.go

Fix "runtime not ready" bug when setting thin runtime replicas to 0
Related to #2160

Fix zero runtime replicas for thinruntime

---

pkg/ddc/base/runtime.go
pkg/utils/runtimes.go
pkg/utils/runtimes_test.go

Build runtime info for thin runtime type. Fix webhook error: 
```
fail to get runtimeInfo for runtime type: thin
```

Build runtime info for thin runtime type

---

charts/juicefs/templates/worker/statefuleset.yaml
pkg/ddc/juicefs/cache.go
pkg/ddc/juicefs/cache_test.go

1. remove liveness probe of juicefs worker
2. fix cacheHits query of juicefs worker

fix cacheHits query & remove liveness probe of juicefs worker

---

pkg/ddc/thin/transform_config.go
pkg/ddc/thin/type.go

Add persistent volume support for thin runtime.
If the mount point of the bounded dataset is specified as `pvc://`, we consider it as an existing bounded persistent volume claim. For thin runtime, any CSI related persistent volume information will be marshalled and passed into ThinRuntime's fuse pods in order to let users handle it.
fixes #2210

Add persistent volume support for thin runtime

---

pkg/ddc/thin/transform_config.go
pkg/ddc/thin/transform_fuse.go
pkg/ddc/thin/transform_volumes.go
pkg/utils/volumes.go
pkg/utils/volumes_test.go

For mount points with `pvc://` scheme, Fluid can support auto-mounting secrets specified in the related PV for better experience. This is designed for those who want to integrate their storage system(already with csi provisioner which can provision PVs) with Fluid's ThinRuntime.
For example, user can specify Dataset like this:
```
kind: Dataset
metadata:
name: demo
spec:
mounts:
- mountPoint: pvc://my-pvc
name: my-pvc
---
kind: ThinRuntime
metadata:
name: demo
spec:
profileName: myfs-profile
fileSystemType: myfs
```
Given the persistent volume is like:
```
apiVersion: v1
kind: PersistentVolume
metadata:
name: my-pv
spec:
capacity:
storage: 5Gi
accessModes:
- …
```

Auto mount node publish secret for pvc mount points

---

pkg/ddc/thin/transform.go

Remove related code that checks if worker image is set.
For cases when users only need Fuse, they do not have to specify worker's image info, so an empty image for worker is acceptable in such case.
NONE

Skip checking worker image when worker is disabled

---

charts/fluid/fluid/templates/webhook/webhook.yaml
cmd/webhook/app/webhook.go

Disable leaderelection in webhook by default
It's ok for mutliple webhook instance to watch and patch webhook. Because for each webhook instance it will compare the CA cert with Secert `fluid-webhook-certs`, then skip if no changes.

Disable leaderelection in webhook

---

docs/en/samples/data_accessmodes.md
docs/zh/samples/data_accessmodes.md

After test, i find the dataset only support the ReadOnlyMany and ReadWriteMany mode. If it was set with ReadWriteOnce mode, it still can be read/writed by other pods which are in another node. If it was set  with ReadWriteOncePod mode, fluid can`t create the pv/pvc. I am sorry for the pre PR whitout test.

update:update the accessmode

---

pkg/common/constants.go
pkg/controllers/runtime_controller.go
pkg/controllers/v1alpha1/dataset/dataset_controller.go

Signed-off-by: Yanghaihai1020 <Yanghaihai690@163.com>
When the name field of dataset and runtime resources'name starts with a number, a DNS-1035 error is reported to events.
fixes #2213 
`kubectl describe dataset 300-khbase`
Type     Reason              Age                From     Message
----     ------              ----               ----     -------
Warning  ErrorCreateDataset  4s (x12 over 21s)  Dataset  Failed to create dataset because err: metadata.name: Invalid value: "300-khbase": a DNS-1035 label must consist of lower case alphanumeric characters or '-', start with an alphabetic character, and end with an alphanumeric character (e.g. 'my-name',  or 'abc-123', regex used for validation is '[a-z]([-a-z0-9]*[a-z0-9])?')
`kubectl describe alluxio 300-khbase`
Type     Reason …

Fixed the failure to create statefulset when dataset and runtime resources'name starts with a number.

---

api/v1alpha1/juicefsruntime_types.go

Signed-off-by: Wang Qian <1498953301@qq.com>
This pr is to fix the wrong year of Copyright in juicefsruntime_types.go.

fix copyright's year error in juicefsruntime_types.go

---

charts/fluid/fluid/templates/webhook/webhookconfiguration.yaml
docs-new/zh/runtime_alluxio/task/serverless/application_controller.md
docs-new/zh/runtime_alluxio/task/serverless/knative.md
docs/en/samples/application_controller.md
docs/zh/samples/application_controller.md
docs/zh/samples/knative.md
pkg/common/constants.go
pkg/utils/annotations.go
pkg/webhook/scheduler/mutating/schedule_pod_handler.go

Disaggregate fluid webhook injections with pod-level object selector. 
This PR modifies existing `mutatingWebhookConfiguration` by:
- deleted `namespaceSelector` to avoid unnecessary webhook calls
- disaggregate two mutations (i.e. dataset affinity mutations and fuse sidecar injections) to two different webhooks with corresponding `objectSelector`
fixes #2266

Disaggregate fluid webhook injections with pod-level object selector

---

pkg/application/inject/fuse/container_test.go

Ⅰ. this PR change Copyright2021 to Copyright 2022 in pkg/application/inject/fuse/container_test.go
None.
No tests are needed as it is just a change of copyright text in one file.
The Copyright in file container_test.go should be 2022 after this changing.
None.

This Pr is to change Copyright2021 to Copyright 2022 in pkg/application/inject/fuse/container_test.go

---

charts/fluid/fluid/templates/webhook/webhookconfiguration.yaml
docs-new/zh/runtime_alluxio/task/dataset_schedule/pod_schedule_global.md
docs-new/zh/runtime_alluxio/task/high_avaliable/fuse_recover.md
docs/en/samples/fuse_recover.md
docs/en/samples/knative.md
docs/zh/operation/pod_schedule_global.md
docs/zh/samples/fuse_recover.md
pkg/common/constants.go
pkg/utils/annotations.go
pkg/webhook/scheduler/mutating/schedule_pod_handler.go

For now, Fluid webhook mutates pod create requests if the namespace of the pod is labeled with `fluid.io/enable-injection=true`. Such label may affect other pods running in the same namespace and lead to efficiency issues.
This PR replace the namespace selector with an object label selector that only mutates pod labeled with `fuse.serverfull.fluid.io/inject=true`.
NONE

Support webhook object selector for serverfull fuse

---

charts/fluid-dataloader/alluxio/templates/configmap.yaml
pkg/controllers/v1alpha1/dataload/implement.go

Signed-off-by: Yanghaihai1020 <Yanghaihai690@163.com>
It repeated to call the runtime engine in the controller which introduced a lot of latency, move the logic of checking path existence after helm chart install can speed up the whole dataLoad process.
fixes #2339

Check dataLoad path existence after chart install

---

Makefile
cmd/eac/app/eac.go
cmd/eac/app/init.go
cmd/eac/app/version.go
cmd/eac/main.go
docker/Dockerfile.eacruntime
pkg/common/eac.go
pkg/controllers/v1alpha1/eac/eacruntime_controller.go
pkg/controllers/v1alpha1/eac/implement.go
pkg/ddc/eac/engine.go
pkg/ddc/eac/engine_test.go
pkg/ddc/eac/port_parser.go
pkg/ddc/eac/port_parser_test.go
pkg/ddc/eac/runtime_info.go
pkg/ddc/eac/runtime_info_test.go
pkg/ddc/eac/utils.go
pkg/ddc/factory.go

Add EACRuntime Controller cmd.
fixes #2352 
unit test

Add EACRuntime Controller cmd

---

api/v1alpha1/constant.go
api/v1alpha1/dataset_types.go
pkg/controllers/runtime_controller.go
pkg/ddc/base/runtime.go
pkg/webhook/scheduler/mutating/schedule_pod_handler_test.go
pkg/webhook/scheduler/mutating/utils.go

The PR reports detailed message to user if a webhook mutation failed because dataset is in an unhealthy state(e.g. notBound).
Firstly, the PR records the reason why the dataset is in unhealthy state into `Dataset.Status.Conditions` with a `conditionType=DatasetNotReady`. Then, at any time when the reason is needed, Fluid controllers or webhook can extract the reason from the Dataset's conditions.
NONE

Report dataset not ready message when failed to mutate pod specs

---

pkg/ddc/thin/referencedataset/volume.go
pkg/ddc/thin/referencedataset/volume_test.go

AccessModes of PVC should be set by dataset's accessModes. But the accessModes of virtual dataset should be less than physical dataset. 
fixes #2448

Control accessModes for virtual dataset

---

charts/thin/templates/config/runtime.yaml
pkg/ddc/thin/transform_config.go
pkg/ddc/thin/type.go

Extract volume mount options for ThinRuntime fuse container.
See https://kubernetes.io/docs/concepts/storage/persistent-volumes/#mount-options
NONE

Extract volume mount options for ThinRuntime fuse container

---

docs/zh/samples/thinruntime.md

Minor fix for ThinRuntime.md demo. Run `mkdir $tagetPath` before `exec mount` to make sure the `$targetPath` exists
NONE

DOCFIX: mkdir before mount goofys in ThinRuntime demo

---

pkg/csi/recover/recover_test.go
pkg/ddc/alluxio/utils_test.go
pkg/ddc/base/runtime_test.go
pkg/ddc/eac/utils_test.go
pkg/ddc/goosefs/utils_test.go
pkg/ddc/jindo/utils_test.go
pkg/ddc/jindofsx/utils_test.go
pkg/ddc/juicefs/utils_test.go
pkg/ddc/thin/util_test.go
pkg/utils/charts_test.go
pkg/utils/common_test.go
pkg/utils/docker/image_test.go
pkg/utils/env_test.go
pkg/utils/kubeclient/exec_test.go
pkg/utils/mount_test.go
pkg/utils/mountinfo/mountpoint_test.go
pkg/utils/runtimes/options/critical_fuse_pod_test.go
pkg/utils/runtimes/options/init_port_check_test.go
pkg/webhook/certificate_builder_test.go

This PR replaces `os.Setenv` with `t.Setenv`. Starting from Go 1.17, we can use `t.Setenv` to set environment variable in test. The environment variable is automatically restored to its original value when the test and all its subtests complete. This ensures that each test does not start with leftover environment variables from previous completed tests.
This saves us at least 2 lines (error check, and cleanup) on every instance, or in some cases adds cleanup that we forgot.
Reference: https://pkg.go.dev/testing#T.Setenv
```go
func TestFoo(t *testing.T) {
// before
os.Setenv(key, "new value")
defer os.Unsetenv(key)
// after
t.Setenv(key, "new value")
}
```
NONE
Test improvements only. No new test cases required.
The CI covers the changes.

test: use `T.Setenv` to set env vars in tests

---

charts/fluid-dataloader/alluxio/templates/configmap.yaml
charts/fluid-dataloader/alluxio/templates/dataloader.yaml
charts/fluid-dataloader/goosefs/templates/configmap.yaml
charts/fluid-dataloader/goosefs/templates/dataloader.yaml
charts/fluid-dataloader/jindo/templates/configmap.yaml
charts/fluid-dataloader/jindo/templates/dataloader.yaml
charts/fluid-dataloader/jindofsx/templates/configmap.yaml
charts/fluid-dataloader/juicefs/templates/configmap.yaml
charts/fluid-dataloader/juicefs/templates/dataloader.yaml
pkg/controllers/v1alpha1/dataload/implement.go
pkg/utils/kubeclient/pod.go

Signed-off-by: yn <915093340@qq.com>
use the pod's logs of the dataload job to check whether the path exist and the data load is complete.
fixes #2339 
Now, we check the existence of the DataLoad's TargetPath based on the pod's logs of the dataload job's .
DataLoad e.g:
```
kind: DataLoad
metadata:
name: spark-dataload
spec:
dataset:
name: spark
target:
- path: /spark/spark-3.1.3
- path: /spark/spark-3.2.2
- path: /spark/spark-unexistenceTest
- path: /spark/spark-3.3.1
```
when `kubectl describe dataload spark-dataload`, it shows this:
```
Events:
Type     Reason              Age                    From      Message
----     ------              ----                   ----      -------
Normal   DataLoadJobStarted  3m7s                   DataLoad  The …
```

Check dataLoad's targetPath existence by dataload job's log.

---

pkg/controllers/v1alpha1/databackup/implement.go
pkg/csi/recover/recover.go
pkg/csi/recover/recover_test.go
pkg/ddc/alluxio/load_data.go
pkg/ddc/alluxio/master_internal.go
pkg/ddc/eac/master_internal.go
pkg/ddc/goosefs/load_data.go
pkg/ddc/goosefs/master_internal.go
pkg/ddc/jindo/load_data.go
pkg/ddc/jindo/master_internal.go
pkg/ddc/juicefs/data_load.go
pkg/ddc/juicefs/master_internal.go
pkg/ddc/thin/master_internal.go
pkg/dump/dump.go
pkg/utils/charts_test.go
pkg/utils/helm/helm.go
pkg/utils/kubectl/configmap.go
pkg/utils/mount.go
pkg/utils/mount_test.go
pkg/utils/webhook/writer/fs.go
pkg/utils/yaml_test.go
pkg/webhook/certificate_builder_test.go
test/e2etest/patch_node_label_test.go

Fix Deprecated  io/utils

---

pkg/controllers/v1alpha1/fluidapp/fluidapp_controller.go
pkg/controllers/v1alpha1/fluidapp/implement.go
pkg/controllers/v1alpha1/fluidapp/implement_test.go
pkg/ctrl/watch/pod.go
pkg/ctrl/watch/pod_test.go
pkg/ddc/juicefs/shutdown.go
test/prow/juicefs_access_data.py

add e2e test for juicefs

---

charts/fluid/fluid/templates/webhook/webhookconfiguration.yaml
charts/fluid/fluid/values.yaml

Signed-off-by: Lize Cai <lize.cai@sap.com>
Make `timeoutSeconds` configurable in the helm chart and reduce the default value to 15s.
fixes #2515 
NA
Manually deploy it and it is working fine.
Based on a discussion with @cheyang the average response for the webhook is about `2 ms` during their internal benchmark, so this adjustment should be fine.

make webhook timeoutSeconds configurable and set default value to 15s

---

api/v1alpha1/common.go
charts/fluid/fluid/Chart.yaml
charts/fluid/fluid/crds/data.fluid.io_alluxioruntimes.yaml
charts/fluid/fluid/crds/data.fluid.io_eacruntimes.yaml
charts/fluid/fluid/crds/data.fluid.io_goosefsruntimes.yaml
charts/fluid/fluid/crds/data.fluid.io_jindoruntimes.yaml
charts/fluid/fluid/crds/data.fluid.io_juicefsruntimes.yaml
charts/fluid/fluid/values.yaml
config/crd/bases/data.fluid.io_alluxioruntimes.yaml
config/crd/bases/data.fluid.io_eacruntimes.yaml
config/crd/bases/data.fluid.io_goosefsruntimes.yaml
config/crd/bases/data.fluid.io_jindoruntimes.yaml
config/crd/bases/data.fluid.io_juicefsruntimes.yaml
pkg/ddc/alluxio/cache_test.go
pkg/ddc/alluxio/const.go
pkg/ddc/alluxio/shutdown.go
samples/accelerate/dataset.yaml

Set default value for clean cache

---

charts/fluid/fluid/values.yaml

Add EAC Fuse to pruneFS to avoid mlocate scan
fixes #2493
NONE

Add EAC Fuse to pruneFS to avoid mlocate scan

---

pkg/ddc/alluxio/cache_test.go
pkg/ddc/alluxio/engine.go
pkg/ddc/alluxio/metadata.go
pkg/ddc/alluxio/metadata_test.go
pkg/ddc/alluxio/shutdown.go
pkg/ddc/alluxio/transform_optimization_test.go
pkg/ddc/alluxio/transform_test.go
pkg/ddc/alluxio/ufs_test.go
pkg/ddc/base/metadata_sync.go
pkg/ddc/base/metadata_sync_test.go
pkg/ddc/goosefs/engine.go
pkg/ddc/goosefs/metadata.go
pkg/ddc/goosefs/transform_optimization_test.go
pkg/ddc/goosefs/ufs_test.go
pkg/ddc/jindo/engine.go
pkg/ddc/jindo/metadata.go
pkg/ddc/jindo/metadata_test.go
pkg/ddc/jindofsx/engine.go
pkg/ddc/jindofsx/metadata.go
pkg/ddc/jindofsx/metadata_test.go
pkg/ddc/juicefs/engine.go
pkg/ddc/juicefs/metadata.go
pkg/ddc/juicefs/metadata_test.go
pkg/ddc/thin/engine.go
pkg/ddc/thin/metadata.go
pkg/ddc/thin/metadata_test.go

This PR supports recovery from metadata sync channel panics for all runtime engines (e.g. Alluxio、Jindo/JindoFSx、GooseFS、JuiceFS、Thin). In addition, the PR refactors `SyncMetadata` related code logic by unifying `type MetadataSyncResult struct` to a commonly-used struct defined in `pkg/ddc/base`.
To support recovery, this PR defines two functions: `SafeClose()` and `SafeSend()` to manipulate `chan base.MetadataSyncResult`. Each engine must call either of the functions to avoid panic when manipulating on a closed channel.
fixes #2530 
When recovery happens, the runtime controller should log something like:
```
2023-01-30T16:13:48.986+0800	INFO	alluxioctl.AlluxioRuntime	runtime/asm_amd64.s:1581	Recover from sending result to a closed channel	{"alluxioruntime": "default/hbase", "result": …
```

[BUGFIX] Support recovery from metadata sync channel panics

---

charts/alluxio/CHANGELOG.md
charts/alluxio/Chart.yaml
charts/alluxio/templates/config/alluxio-conf.yaml
charts/alluxio/templates/fuse/daemonset.yaml
charts/alluxio/templates/master/service.yaml
charts/alluxio/templates/master/statefulset.yaml
charts/alluxio/templates/worker/statefulset.yaml
charts/alluxio/values.yaml
charts/eac/CHANGELOG.md
charts/eac/Chart.yaml
charts/eac/templates/fuse/daemonset.yaml
charts/eac/templates/master/statefulset.yaml
charts/eac/templates/worker/configmap.yaml
charts/eac/templates/worker/statefulset.yaml
charts/eac/values.yaml
charts/jindofsx/templates/config/jindofs-client-conf.yaml
charts/jindofsx/templates/config/jindofs-conf.yaml
pkg/ctrl/watch/daemonset.go
pkg/ctrl/watch/runtime.go
pkg/ctrl/watch/statefulset.go
pkg/ddc/alluxio/transform.go
pkg/ddc/alluxio/types.go
pkg/ddc/eac/transform.go
pkg/ddc/eac/types.go

Runtime Controller now watches resources like StatefulSet and DaemonSet for event-driven reconcilation. However, some statefulsets and daemonsets will be skipped by runtime controller due to lack of ownerReferences.
This PR enables event-driven reconcilation for all cache runtimes by adding ownerReferences when installing them.
NONE

Support event driven reconcilation for cache runtimes 

---

pkg/utils/dataset/volume/create.go

Signed-off-by: yn <915093340@qq.com>
PV.spec.capacity and PVC.spec.resources are required values that have no meaning but cannot be empty,which means these values cannot avoid setting. We can set a large value such as 100Pi as an initial value to ensure these two fields have a valid value while not affecting actual usage.
fixes #2520

Setting pv.spec.capacity capacity value to a large initial value.

---

charts/juicefs/CHANGELOG.md
charts/juicefs/Chart.yaml
charts/juicefs/templates/fuse/daemonset.yaml
charts/juicefs/templates/worker/statefuleset.yaml
pkg/ddc/juicefs/transform.go
pkg/ddc/juicefs/transform_fuse.go
pkg/ddc/juicefs/transform_volume.go
pkg/ddc/juicefs/transform_volume_test.go

When set `cache-dir` in worker options, juicefs worker will use different caches with fuse pod, and mount cache-dir in hostPath.
fixes #2564

[juicefs] fix worker cache when set option

---

pkg/ddc/eac/dataset.go
pkg/ddc/eac/status.go

Return early when syncing EAC to speed up scaling
fixes #2570

Return early when syncing EAC to speed up scaling

---

cmd/dataset/app/dataset.go
pkg/controllers/v1alpha1/databackup/databackup_controller.go
pkg/controllers/v1alpha1/dataload/dataload_controller.go
pkg/controllers/v1alpha1/dataset/dataset_controller.go

Currently, dataset controller reconciles objects with only 1 goroutine which may be not enough for frequent operations on related objects like Dataset, DataLoad and DataBackup. This PR sets default reconcile worker num of dataset controller to 3 and make it configurable.
NONE

Increase default reconcile worker num of dataset controller to 3

---

cmd/dataset/app/dataset.go
pkg/controllers/v1alpha1/databackup/databackup_controller.go
pkg/controllers/v1alpha1/dataload/dataload_controller.go
pkg/controllers/v1alpha1/dataset/dataset_controller.go
pkg/ctrl/affinity.go
pkg/ctrl/affinity_test.go

Avoid spread-first scheduling policy for EACRuntime's workers. Currently EAC prefers binpack-first scheduling policy to spread-first scheduling policy. Set PreferredDuringSchedulingIgnoredDuringExecution to empty to avoid using spread-first scheduling policy.
Note：This is a temporary fix and should be removed when EAC is ready for spread-first scheduling policy
fixes #2581

Avoid spread-first scheduling policy for EACRuntime's workers

---

charts/fluid/fluid/templates/controller/goosefsruntime_controller.yaml
charts/fluid/fluid/templates/controller/jindoruntime_controller.yaml
charts/fluid/fluid/values.yaml
cmd/alluxio/app/alluxio.go
cmd/dataset/app/dataset.go
cmd/goosefs/app/goosefs.go
cmd/jindo/app/jindo.go
pkg/controllers/v1alpha1/databackup/databackup_controller.go
pkg/controllers/v1alpha1/dataload/dataload_controller.go
pkg/controllers/v1alpha1/dataset/dataset_controller.go
pkg/ddc/alluxio/master_internal_test.go
pkg/ddc/alluxio/shutdown_engine_test.go
pkg/ddc/alluxio/shutdown_test.go
pkg/ddc/alluxio/transform_test.go
pkg/ddc/base/portallocator/port_allocator.go
pkg/ddc/base/portallocator/port_allocator_test.go
pkg/ddc/eac/master_internal_test.go
pkg/ddc/eac/shutdown_test.go
pkg/ddc/eac/transform_port_test.go
pkg/ddc/eac/transform_test.go
pkg/ddc/goosefs/master_internal_test.go
pkg/ddc/goosefs/shutdown_test.go
pkg/ddc/jindo/master_internal_test.go
pkg/ddc/jindofsx/master_internal_test.go
pkg/ddc/jindofsx/transform_test.go

- Default to using random port allocator for runtime controllers. 
- Bitmap-based port allocator is still an option that can be set in runtime controllers' command argument (e.g. `--port-allocate-policy=bitmap`) 
NONE

Default use random port allocator for runtime controllers

---

pkg/ddc/eac/transform_option.go
pkg/ddc/eac/transform_option_test.go

when eac-worker is disabled, eac-fuse mount options "g_tier_EnableClusterCache=true" and "g_tier_EnableClusterCachePrefetch=true" are not set.
fixes #2589 
no
no

fix eac-fuse mount options

---

charts/fluid/fluid/templates/controller/goosefsruntime_controller.yaml
charts/fluid/fluid/templates/controller/jindoruntime_controller.yaml
charts/fluid/fluid/values.yaml
cmd/alluxio/app/alluxio.go
cmd/goosefs/app/goosefs.go
cmd/jindo/app/jindo.go
pkg/ddc/alluxio/master_internal_test.go
pkg/ddc/alluxio/shutdown_engine_test.go
pkg/ddc/alluxio/shutdown_test.go
pkg/ddc/alluxio/transform_test.go
pkg/ddc/base/portallocator/port_allocator.go
pkg/ddc/base/portallocator/port_allocator_test.go
pkg/ddc/goosefs/master_internal_test.go
pkg/ddc/goosefs/shutdown_test.go
pkg/ddc/jindo/master_internal_test.go
pkg/ddc/jindofsx/master_internal_test.go
pkg/ddc/jindofsx/transform_test.go

* Validate port allocating policy before setting up
* Expose configurable option for port allocating policy
* Fix unit tests
* Fix static check
* Fix static check
* Fix comments for `SetupRuntimePortAllocator()`
* Support configurable port allocate policy
---------
fixes #XXXX

Cherry-pick Random port allocation

---

addons/cubefs/v2.4/dev-guide/cubefs-v2.4-zh_CN.md
addons/cubefs/v2.4/dev-guide/cubefs-v2.4.md
addons/cubefs/v2.4/docker/fluid_config_init.py
addons/cubefs/v2.4/readme-zh_CN.md
addons/cubefs/v2.4/readme.md

update addons for cubefs 2.4 to not use cubefs csi
fixes #XXXX

update addons for cubefs 2.4 to not use cubefs csi

---

csi/shell/check_mount.sh
pkg/csi/plugins/nodeserver.go

FUSE may be not a reliable filesystem due to its limitation on its user-space implementation. It is quite usual that FUSE process is killed but left a broken mount point on the node. This may incurs further crashes when restarting FUSE pods which attempt to mount the FUSE system onto an already broken mount point.
Currently, Fluid CSI plugin fails to detect such broken mount point. The CSI plugin may consider it  as an healthy one and mistakenly binds it to the VolumeMount path in the application Pod.
This PR enhances CSI plugin to check mount point aliveness before binding mount points. Specifically, this PR does:
- Clean up an existing broken mount point when calling `NodeStageVolume()` function.
- Stats the mount point path in the `check_mount.sh` script which will be called in …

[Enhancement]CSI plugin checks mount point liveness before binding mount points

---

charts/fluid/fluid/templates/webhook/webhookconfiguration.yaml
charts/fluid/fluid/values.yaml

allow setting [reinvocationPolicy](https://kubernetes.io/docs/reference/access-authn-authz/extensible-admission-controllers/#reinvocation-policy) in the webhook configuration.
I faced an issue in testing that webhook is not injecting the fuse-sidecar even the annotation is added. This is probably due to the ordering of mutating webhook (we have 2-3 webhooks mutating the pod). After setting the `reinvocationPolicy` to `IfNeeded`, the webhook is working as expected.
This PR adds the option in the helm chart to overwrite the default value.

Support setting webhook reinvocationPolicy in chart

---

pkg/csi/plugins/nodeserver.go
pkg/utils/helm/utils.go
pkg/utils/mount.go

Fluid relies on `exec.Command` to execute some operations and interacts with K8s API-Server(e.g. The `helm` for install/check/delete engine-related resources). `exec.Command` will always returns a meaningless `err` that would confuses users about the cause of their problems.
For example, when Fluid CSI Plugin fails to bind mount a FUSE mount point onto a pod, an event is issued on the pod showing messages like:
```
MountVolume.Setup failed for volume "default-jfsdemo": rpc error: code = InvalidArgument desc = exit status 1
```
This PR prettifies such error messages with a clearer explanation about the cause. For example, the event message mentioned above would be changed to:
```
MountVolume.Setup failed for volume "default-jfsdemo": rpc error: code = Internal desc = timeout waiting for …
```

Prettify error messages for exec.Commands in Fluid

---

pkg/controllers/runtime_controller.go
pkg/ddc/alluxio/metadata.go
pkg/ddc/base/metadata_sync.go
pkg/ddc/base/setup.go
pkg/ddc/base/syncs.go
pkg/ddc/base/template_engine.go
pkg/ddc/jindofsx/metadata.go
pkg/ddc/juicefs/metadata.go
pkg/ddc/thin/metadata.go
pkg/metrics/dataset_metrics.go
pkg/metrics/labels_key_func.go
pkg/metrics/runtime_metrics.go

1. Forget runtime and dataset metrics after shutting down engines
2. Add dataset metrics (e.g. UfsTotal and FileNum) as a prometheus metric
fixes #2725

Forget prometheus metrics after shutting down engines

---

charts/eac/templates/fuse/daemonset.yaml
charts/fluid/fluid/templates/role/eac/rbac.yaml
cmd/eac/app/eac.go
pkg/common/eac.go
pkg/csi/plugins/nodeserver.go
pkg/ddc/eac/create_volume.go
pkg/ddc/eac/create_volume_test.go
pkg/ddc/eac/sessmgr.go

Refactor EAC SessMgr
- Decouple the `init-fuse` initContainer and the `sessmgr` container from FUSE pod. 
- Add a new `eac-sessmgr` daemonset in `eac-system` namespace to handle EAC FUSE pods.
- Add extra volume attributes to instruct CSI Plugin to prepare SessMgr before EAC FUSE starts
- Redesign Fluid CSI Plugin to trigger creation of SessMgr pods if needed
fixes #2745

Refactor EAC SessMgr

---

pkg/csi/recover/recover.go
pkg/csi/recover/recover_test.go

Fix CSI FUSE Recovery. More details pls see #2719 .
This PR skip checking FUSE containers' restart and keep check /proc/self/mountinfo to find broken mount points in a loop mannner. This ensures any broken FUSE mount points will be eventually found and recoverd after a short period.
fixes #2719

Fix CSI FUSE Recovery

---

pkg/utils/helm/utils.go

Fix unexpected dataset phase after helm install failure. Specifically, this PR:
- Additionally checks status of the `helm status` command and considered it as success only when `STATUS: deployed`
- If `STATUS` does not equal to `deployed`, it deletes the helm release, and retries `helm install`
fixes #2748 
Follow the steps described in #2748

[BUGFIX] Fix unexpected dataset phase after helm install failure

---

pkg/ddc/alluxio/types_selector.go

Use json tag instaed of yaml tag since we use k8s yaml to unmarshal, which only use json tag
fixes https://github.com/fluid-cloudnative/fluid/issues/2772
See the related issue

fix(alluxio): should use json tag instead of yaml tag

---

pkg/ddc/alluxio/runtime_info.go

Added the missing copyright in the head of file `pkg/ddc/alluxio/runtime_info.go`
fixes #2787

add copyright

---

pkg/ddc/alluxio/operations/conf.go

Modified fluid\pkg\ddc\alluxio\operations\conf.go with adding License description "Copyright 2021 The Fluid Authors." on the first line.

added License description

---

pkg/ddc/base/metadata_sync_test.go

This pr is to add Apache License to pkg/ddc/base/metadata_sync_test.go.
(task100)
fixes #XXXX

add Apache License to pkg/ddc/base/metadata_sync_test.go

---

pkg/utils/unix.go

This PR added the copyright to file 'fluid/pkg/util/unix.go'.

add copyright to file 'fluid/pkg/util/unix.go'

---

pkg/ddc/goosefs/dataset_test.go

This pr is to add Apache Lisence to `pkg/ddc/goosefs/dataset_test.go`.

add apache license to `pkg/ddc/goosefs/dataset_test.go`

---

pkg/ddc/juicefs/data_load_test.go

This pr is to add Apache Lisence to pkg/ddc/juicefs/data_load_test.go

add Apache License

---

pkg/ddc/eac/sessmgr.go

Fix sessmgr init-fuse container's privilege bug introduced by #2744 
NONE

BUGFIX: fix init-fuse container privilege mode for EAC SessMgr

---

pkg/ddc/jindofsx/deprecated_label.go

This PR is to add CopyRight to pkg/ddc/jindofsx/deprecated_label.go
fixes #XXXX

This PR is to Add CopyRight to pkg/ddc/jindofsx/deprecated_label.go

---

pkg/ddc/jindo/port_parser_test.go

The file pkg/ddc/jindo/port_parser_test.go lacks a legal license. This PR is to add a correct license to that file.
fixes #68
Take a look at file pkg/ddc/jindo/port_parser_test.go, and you can check the corrrect license I added.

add license to file pkg/ddc/jindo/port_parser_test.go

---

pkg/utils/resources.go

This pr is to add Copyright to the Apache License of pkg/utils/resources.go.

add Copyright to pkg/utils/resources.go

---

pkg/ddc/alluxio/health_check_test.go

This pr is to change copyright's year in pkg/ddc/alluxio/health_check_test.go

change copyright's year in health_check_test.go

---

pkg/ddc/jindofsx/port_parser_test.go

This pr is to add license to the file "pkg/ddc/jindofsx/port_parser_test.go".
fixes #XXXX

add license to the file "pkg/ddc/jindofsx/port_parser_test.go"

---

pkg/ddc/jindofsx/hcfs.go

This pr is to add a Copyright in the head of pkg/ddc/jindofsx/hcfs.go

add Copyright in pkg/ddc/jindofsx/hcfs.go

---

pkg/utils/runtimes_test.go

This pr is to add a Apache License license to pkg/utils/runtimes_test.go.
fixes #XXXX

Add Apache License license

---

pkg/ddc/alluxio/hcfs.go

This pr is to add normalized License content to the header of 'pkg/ddc/alluxio/hcfs.go'

normalize the License content in the file header of 'hcfs.go'

---

pkg/ddc/jindo/cache_test.go

This pr is to add Apache License to pkg/ddc/jindo/cache_test.go
fixes #XXXX

add Apache License to pkg/ddc/jindo/cache_test.go

---

pkg/ddc/jindo/deprecated_label.go

This pr is to add copyright info in file pkg/ddc/jindo/deprecated_label.go
fixes #XXXX

standardize License

---

pkg/ctrl/watch/runtime.go

This pr is to add Apache License to pkg/ctrl/watch/runtime.go.

Add Apache License to pkg/ctrl/watch/runtime.go

---

pkg/utils/testutil/envvars.go

this pr is to add license to the head of "pkg/utils/testutil/envvars.go"
fixes #XXXX

assignment208

---

charts/jindofsx/CHANGELOG.md
charts/jindofsx/Chart.yaml
charts/jindofsx/templates/fuse/daemonset.yaml
charts/jindofsx/templates/master/statefulset.yaml
charts/jindofsx/templates/worker/statefulset.yaml
charts/jindofsx/values.yaml
pkg/ddc/jindofsx/transform.go
pkg/ddc/jindofsx/transform_test.go
pkg/ddc/jindofsx/types.go

This PR passes user-set env variables in JindoRuntime to JindoFSx's components.
fixes #3154

bugfix: support configurable env variables for JindoRuntime

---

charts/alluxio/CHANGELOG.md
charts/alluxio/Chart.yaml
charts/alluxio/templates/worker/statefulset.yaml

* Fix worker volumes in alluxio chart
* Update Alluxio helm chart changelog
Cherry-pick fix worker volumes in alluxio chart (#2330)
fixes #XXXX

Cherry-pick fix worker volumes in alluxio chart (#2330)

---

pkg/utils/kubeclient/statefulset.go

This pr is to add Apache License to pkg/utils/kubeclient/statefulset.go.
No.
No. Just a license update.

add Apache License to pkg/utils/kubeclient/statefulset.go

---

charts/efc/templates/fuse/daemonset.yaml
charts/efc/values.yaml
pkg/ddc/efc/transform.go
pkg/ddc/efc/types.go

- Add runtime identity info to EFCRuntime
- fix readiness probe for general usage
NONE

fix(efcruntime): Add runtime identity info and fix readiness probe for EFCRuntime

---

charts/fluid/fluid/values.yaml

Follow up PR of [this](https://github.com/fluid-cloudnative/fluid/pull/2702#discussion_r1127739207) to set default webhook reinvocationPolicy to `IfNeeded`.

Set default webhook reinvocationPolicy to IfNeeded

---

pkg/ddc/efc/sessmgr.go

efcruntime: set Privileged=true when start init-fuse
fixes #3220

fix(efcruntime): set Privileged=true when init-fuse start

---

pkg/ddc/alluxio/transform_fuse_test.go
pkg/ddc/alluxio/transform_optimization.go
pkg/ddc/alluxio/transform_optimization_test.go
pkg/ddc/alluxio/transform_test.go

In Fluid 0.9.0 will use Alluxio 2.9.0 as default. But in Alluxio 2.9.0, the default libfuse version is 2, which may leads to performance decreasing. In this PR, I make Fluid default use libfuse 3 and do some parameter adaption.
fixes #3209

Adapt to libfuse 3

---

Makefile
charts/fluid/fluid/Chart.yaml
charts/fluid/fluid/values.yaml

Build docker images: libfuse3 for alluxio 2.9

---

api/v1alpha1/dataset_types.go
api/v1alpha1/openapi_generated.go
charts/fluid/fluid/crds/data.fluid.io_datasets.yaml
config/crd/bases/data.fluid.io_datasets.yaml

Currently, `Dataset.Spec.Mounts` is an optional property, allowing users to create a Dataset without `mounts`. This PR changes it as a required property to make CRD validation works.
For example, the following will be illegal after this PR:
```
kind: Dataset
metadata:
name: hbase
spec:
```
NONE

bugfix: Set Dataset.Spec.Mounts as a required property

---

.github/workflows/go.yml
Makefile
docker/Dockerfile.application
docker/Dockerfile.csi
docker/Dockerfile.efcruntime
docker/Dockerfile.jindoruntime
docker/Dockerfile.juicefsruntime
docker/Dockerfile.thinruntime
docker/Dockerfile.webhook
test/prow/testcases/common/fuse_recovery.py

Optimize makefile targets and speed up docker build. The PR removes redundant `generate fmt vet gen-openapi` actions away from the original Makefile targets and do once before targets like `make build`, `make docker-push-all`.
Targets for building one single component will no longer check these actions `generate fmt vet gen-openapi`.
NONE

optimize: optimize makefile targets and speed up docker build

---

api/v1alpha1/dataset_types.go
api/v1alpha1/dataset_types_test.go

fix when OperationRef[operationType] is nil, `SetDataOperationInProgress ` failed.
fixes #3258

fix dataoperation when nil

---

pkg/ddc/alluxio/transform_optimization.go

Now Fluid set the default writetype configuration in Alluxio to MUST_CACHE, which makes Alluxio doesn't persist new file to backend storage. I change the default writetype to ASYNC_THROUGH, which is the defalut configuration in Alluxio. Here is [the writetype document](https://docs.alluxio.io/os/user/stable/en/overview/Architecture.html#data-flow-write).
fixes #3260

Fix default Alluxio writetype config

---

pkg/ddc/alluxio/dataset.go
pkg/ddc/alluxio/dataset_test.go
pkg/ddc/efc/dataset.go
pkg/ddc/efc/dataset_test.go
pkg/ddc/jindofsx/dataset.go
pkg/ddc/jindofsx/dataset_test.go
pkg/ddc/juicefs/dataset.go
pkg/ddc/juicefs/dataset_test.go
pkg/ddc/thin/dataset.go
pkg/ddc/thin/dataset_test.go

Dataset's status stores runtime information(i.e. `Dataset.Status.Runtimes[]`) to indicate which kind of Runtime is binding to the Dataset. However, now the code updates `Dataset.Status.Runtimes[]` in the sync loop, which is not appropriate for such information.
This PR fixes this by moving the related code logic from the sync loop to the point when Fluid updates the Dataset's phase to bound. 
ReferenceDataset doesn't need code changes because Fluid now copies physical dataset's status into the reference dataset. 
NONE

Update runtime info in dataset's status during binding

---

pkg/ddc/alluxio/transform_optimization.go

In default setting, the `alluxio.master.journal.type` will set to `UFS`, causing the HA mode fail. Now we change the default setting according to the master replicas.
Deploy a HA alluxio dataset,  delete the leading master pod, you will see: 
* Without this commit, the leading master will always be master-0 if it exists, and the workers will lost when the old leading master restart.
* With the commit, everything works well.

fix default master journal type setting

---

Makefile
charts/fluid-datamigrate/juicefs/templates/cronjob.yaml
cmd/dataset/app/dataset.go
pkg/controllers/v1alpha1/datamigrate/status_handler.go
pkg/utils/compatibility/batch.go
pkg/utils/datamigrate.go
pkg/utils/kubeclient/cronjob.go
pkg/utils/kubeclient/cronjob_test.go
pkg/utils/kubeclient/pod_test.go
pkg/utils/testutil/unit_test_env.go

- installs cronjob resources according to kubernetes version (batch/v1beta1 cronjobs for K8s < 1.22, batch/v1 cronjobs for K8s >= 1.22)
- Refactor cron DataMigrate logic to support backward compatibility
fixes #3279 
A follow-up PR of #3280

bugfix: fix cron DataMigrate for Kubernetes 1.20

---

charts/fluid/fluid/CHANGELOG.md
charts/fluid/fluid/templates/csi/daemonset.yaml

This PR fixes #3286, which is caused by looping bind-mounts when Fluid's CSI plugin attempts to mount both `/var/lib/kubelet`(with `mountPropagation=Bidirectional`) and `/var/lib/kubelet/pki` into the container. 
This PR fixes this bug by checking if `kubelet-root-dir` is a parent directory of `kubelet-cert-dir` and determine whether to mount `kubelet-cert-dir`.  This is to avoid looping bind mounts and mount info leak when restarting the Pod.
fixes #3286

bugfix: fix csi plugin loop mount bug

---

charts/fluid/fluid/CHANGELOG.md
charts/fluid/fluid/templates/csi/daemonset.yaml

* Fix CSI node plugin loop mount error
---------
fixes #XXXX

bugfix: fix csi plugin loop mount bug (#3287)

---

pkg/csi/plugins/driver.go
pkg/csi/plugins/nodeserver.go
pkg/utils/volume_lock.go

check path existence and lock in NodeUnpublishVolume
fixes #3269

check path existence and lock in NodeUnpublishVolume

---

pkg/controllers/runtime_controller.go
pkg/ddc/base/dataset.go
pkg/ddc/base/dataset_test.go
pkg/ddc/thin/engine.go
pkg/ddc/thin/engine_test.go
pkg/ddc/thin/referencedataset/cm.go
pkg/ddc/thin/referencedataset/engine.go
pkg/ddc/thin/referencedataset/engine_test.go
pkg/ddc/thin/referencedataset/runtime.go
pkg/ddc/thin/referencedataset/runtime_test.go
pkg/ddc/thin/referencedataset/sync.go
pkg/ddc/thin/referencedataset/volume.go

bugfix: reconcile thinruntime failed when dataset is deleted
fixes #3295

bugfix: reconcile thinruntime failed when dataset is deleted

---

pkg/ddc/alluxio/transform_fuse.go
pkg/ddc/goosefs/transform_fuse.go

When setting .Spec.Fuse.ImagePullPolicy, the setting will not pass to the fuse daemonset.
fixes #XXXX

fix fuse ImagePullPolicy

---

csi/shell/entrypoint.sh

fail fast with wrong kubelet rootdir
fixes #3327

fail fast with wrong kubelet rootdir

---

pkg/ddc/thin/engine.go
pkg/ddc/thin/engine_test.go

In this PR, we change `CheckReferenceDatasetRuntime`'s implementation from checking dataset's mount point to simply check `runtime.spec.profileName == 0`. If users attempts to create a ThinRuntime used to integrate third-party storage, it must have a non-empty `runtime.spec.profileName` value, otherwise, ThinRuntime represents a Reference engine.
fixes #3334

bugfix: fix thinruntime stuck bug when deleting it

---

pkg/utils/helm/utils.go

* Fix helm install failure
---------
fixes #XXXX

[BUGFIX] Fix unexpected dataset phase after helm install failure (#2751)

---

api/v1alpha1/juicefsruntime_types.go
api/v1alpha1/openapi_generated.go
api/v1alpha1/zz_generated.deepcopy.go
charts/fluid/fluid/crds/data.fluid.io_juicefsruntimes.yaml
config/crd/bases/data.fluid.io_juicefsruntimes.yaml
pkg/ddc/juicefs/cache.go
pkg/ddc/juicefs/cache_test.go
pkg/ddc/juicefs/engine.go
pkg/ddc/juicefs/transform.go
pkg/ddc/juicefs/transform_fuse.go
pkg/ddc/juicefs/transform_fuse_test.go
pkg/ddc/juicefs/transform_test.go

1. add options in JuiceFSRuntime.spec.fuse and get mount options of fuse pod from it instead of dataset.mount.option
2. get worker cache from tiredstore
3. cache-size&cache-dir in worker.options is deprecated, send event in runtime
4. fix cache capacity in dataset when cache-size is set in worker.options.

fix worker&fuse options & worker tiredstore

---

pkg/controllers/v1alpha1/databackup/status_handler.go
pkg/controllers/v1alpha1/dataload/status_handler.go
pkg/controllers/v1alpha1/datamigrate/status_handler.go
pkg/controllers/v1alpha1/dataprocess/status_handler.go

calculate data operation duration by calculating the time between `job.CreationTimestamp` and job finish time.
fixes #3373

enhancement: accurately calculate data operation's duration

---

charts/thin/templates/config/runtime.yaml
charts/thin/templates/fuseconfig/fuseconfig.yaml
pkg/ddc/thin/shutdown.go
pkg/ddc/thin/shutdown_test.go

Since #3272 , Fluid now uses `configmaps` as the default `HELM_DRIVER` in Fluid controllers. However, this may lead to several upgrading issues like orphaned resources. 
This PR checks and deletes these orphaned resources in a best-effort way.
fixes #XXXX

bugfix: clean up orphaned thinruntime resources

---

charts/juicefs/templates/fuse/daemonset.yaml
charts/juicefs/templates/worker/statefuleset.yaml
pkg/ddc/juicefs/transform.go
pkg/ddc/juicefs/transform_fuse.go
pkg/ddc/juicefs/transform_fuse_test.go
pkg/ddc/juicefs/transform_test.go

1. do not auth if `/root/.juicefs/xxx.conf` exist
2. `mount --no-update` to avoid downloading config again when mount
fixes #XXXX

support auth config for juicefs & add no-update for juicefs mount

---

docs/zh/samples/thinruntime.md

When mounting Fluid dataset with sidecar mode, it requires that the fuse container has `bash` command to execute post start script. This PR fixes this by adding bash into goofys' Dockerfile.
NONE

docfix: fix thinruntime example for sidecar mode

---

docker/Dockerfile.crds

Upgrade kubectl version to support `--server-side` apply to fix CRD auto-upgrade failure.
fixes #3408

bugfix: fix failure when auto-upgrading Fluid CRDs

---

charts/alluxio/templates/config/alluxio-mount-conf.yaml
charts/alluxio/templates/master/statefulset.yaml
charts/alluxio/values.yaml
charts/fluid/fluid/templates/controller/alluxioruntime_controller.yaml
charts/fluid/fluid/templates/role/alluxio/rbac.yaml
charts/fluid/fluid/values.yaml
pkg/common/constants.go
pkg/ddc/alluxio/const.go
pkg/ddc/alluxio/master_internal.go
pkg/ddc/alluxio/operations/base.go
pkg/ddc/alluxio/operations/base_test.go
pkg/ddc/alluxio/transform.go
pkg/ddc/alluxio/transform_test.go
pkg/ddc/alluxio/transform_volumes.go
pkg/ddc/alluxio/types.go
pkg/ddc/alluxio/ufs.go
pkg/ddc/alluxio/ufs_internal.go
pkg/ddc/alluxio/ufs_test.go
pkg/ddc/goosefs/ufs_internal.go
pkg/utils/dataset.go
pkg/utils/kubeclient/configmap.go
pkg/utils/ufs_path_builder.go
pkg/utils/ufs_path_builder_test.go

1. support alluxio runtime controller rbac with no secret resource.
2. support alluxio runtime controller to generate idempotent mount scripts instead of directly executing multiple mount command.
The above abilities are supported with **single configuration**.
fixes #2771
1. existing alluxio prow test `alluxio_dynamic_mountpoint.py`.
2. manul test for secret logic.

support alluxioruntime with no secret and generate idempotent mount scripts

---

pkg/application/inject/fuse/injector.go
pkg/common/constants.go
pkg/common/types.go
pkg/ddc/base/runtime_helper.go
pkg/utils/annotations.go
pkg/utils/annotations_test.go

This PR makes some modification to the code logic about Fuse sidecar injection:
- Add a new label `fuse.sidecar.poststart.fluid.io/inject=false` that allows users to launch their FUSE sidecar in a non-blocking way. (**IMPORTANT: The non-blocking way does not ensure fuse mount point ready when app container starts**)
- Refactor constants to improve code readability
- Reorgnize codebase about fuse sidecar injection to improve code readability
fixes #3424

feat: allow users to skip inject post start hook when using Fuse Sidecar

---

pkg/dataprocess/generate_values.go
pkg/dataprocess/generate_values_test.go

Support dataprocess without mounting dataset. This PR allows users to set `spec.dataset.mountPath` to empty value to skip mounting Dataset's PV on DataProcess if it's not necessary. For example, DataProcess submits a job and wait for its completion, so there is no need for DataProcess to access data.
example:
```
kind: DataProcess
metadata:
name: flow-test-step1
spec:
dataset:
name: oss-data
namespace: default
```
#3391

feat: support dataprocess without mounting dataset

---

pkg/ddc/juicefs/transform_fuse.go
pkg/ddc/juicefs/transform_fuse_test.go

Keep mount options in dataset still effective, but it can be overwrited by fuse specified options
fixes #XXXX

Make dataset options still effective for juicefsRuntime

---

api/v1alpha1/common.go
api/v1alpha1/openapi_generated.go
charts/fluid/fluid/crds/data.fluid.io_databackups.yaml
charts/fluid/fluid/crds/data.fluid.io_dataloads.yaml
charts/fluid/fluid/crds/data.fluid.io_datamigrates.yaml
charts/fluid/fluid/crds/data.fluid.io_dataprocesses.yaml
config/crd/bases/data.fluid.io_databackups.yaml
config/crd/bases/data.fluid.io_dataloads.yaml
config/crd/bases/data.fluid.io_datamigrates.yaml
config/crd/bases/data.fluid.io_dataprocesses.yaml
pkg/controllers/v1alpha1/dataflow/operations.go
pkg/utils/dataoperation.go

- This PR rename data operation's `spec.runAfter.operationKind` to `spec.runAfter.kind` for extensibility. 
- Also, the PR adds `spec.runAfter.apiVersion` to work with non-builtin kinds.
- Additionally, the PR makes `spec.runAfter.namespace` an optional value when it's in the same namespace. 
#3391

enhancement: rename data operation's `spec.runAfter.operationKind` for extensibility

---

charts/fluid-dataloader/alluxio/templates/configmap.yaml

When using alluxio runtime, users cannot load new added files after first dataload operation. This PR fix this bug.
NONE
Actually, this is a bug with Alluxio ([Alluxio issue #17827](https://github.com/Alluxio/alluxio/issues/17827)). After alluxio fix this bug, maybe we need to change to the previous version.

[BUGFIX] Fix alluxio dataload bug

---

charts/juicefs/templates/fuse/daemonset.yaml

Remove juicefs fuse readiness probe.
NONE

enhancement: remove juicefs fuse readiness probe

---

charts/juicefs/templates/fuse/daemonset.yaml

* Remove useless readiness probe on JuiceFS fuse
* Remove useless readiness probe on JuiceFS fuse
---------
fixes #XXXX

enhancement for 0.9: remove juicefs fuse readiness probe (#3435)

---

pkg/scripts/poststart/check_fuse_app.go

Check fsType for a more strict check in check mount ready script.
For example, the script checks fsType (9th item in the `/proc/self/mountinfo` entry) instead of just `grep mountType`.
The script returns success with the following message:
```
$ bash check-mount-ready.sh /data/data0 juicefs
fuse.juicefs
succeed in checking mount point /data/data0 with runtimeType juicefs
```
The script returns failure with the following message:
```
bash check-mount-ready.sh /data/data0 alluxio 
fail to check mount point /data/data0 with runtimeType alluxio: timed out for 10 seconds
```
NONE

enhancement: check fsType for a more strict check in check mount ready script

---

pkg/ddc/juicefs/transform.go

`readonly` only matters in fuse pod and dataload will fail when worker readonly. So, do not set worker readonly any more.

[JuiceFS] do not set worker readonly

---

pkg/csi/plugins/nodeserver.go

ignore not connected error at the beginning of NodeUnpublishVolume
fixes #3444

Bugfix: ignore not connected error in NodeUnpublishVolume

---

cmd/csi/app/csi.go
pkg/csi/config/config.go
pkg/csi/plugins/driver.go
pkg/csi/plugins/nodeserver.go
pkg/csi/plugins/register.go
pkg/csi/recover/recover.go
pkg/csi/recover/recover_test.go
pkg/csi/recover/register.go
pkg/csi/register.go
pkg/csi/updatedbconf/register.go

Fix potential concurrency issue when FuseRecovery and NodeUnpublishVolume process on a same target path.
fixes #3449

bugfix: fix csi plugin concurrency issue on FuseRecovery and NodeUnpublishVolume

---

pkg/csi/plugins/driver.go
pkg/csi/plugins/nodeserver.go
pkg/utils/volume_lock.go

Cherry-pick for PR #3284 
fixes #XXXX

Cherry-pick to 0.9: check path existence and lock in NodeUnpublishVolume (#3284)

---

cmd/csi/app/csi.go
pkg/csi/config/config.go
pkg/csi/plugins/driver.go
pkg/csi/plugins/nodeserver.go
pkg/csi/plugins/register.go
pkg/csi/recover/recover.go
pkg/csi/recover/recover_test.go
pkg/csi/recover/register.go
pkg/csi/register.go
pkg/csi/updatedbconf/register.go

Cherry-pick #3445 and #3448 to 0.9
fixes #XXXX

Cherry-pick to 0.9: fix csi plugin concurrency issue on FuseRecovery and NodeUnpublishVolume (#3448)

---

pkg/ddc/alluxio/ufs_internal.go
pkg/ddc/alluxio/ufs_test.go

Fix error when using sharedOptions to mount multiple mounts

Fix the problem of using option to append Dataset public option

---

pkg/ddc/alluxio/ufs_internal.go
pkg/ddc/alluxio/ufs_test.go

* Fix the problem of using option to append Dataset public option
* Add Unit Test for alluxio engine genUFSMountOptions
---------
fixes #XXXX

Fix the problem of using option to append Dataset public option (#3454)

---

pkg/ddc/juicefs/sync_runtime.go

When update env of worker in JuiceFSRuntime, envFrom is synced none.
fixes #3465

fix env sync in juicefs worker

---

charts/jindocache/templates/fuse/daemonset.yaml
charts/jindofsx/templates/fuse/daemonset.yaml

The `CLIENT_STORAGE_RPC_HOST` env is not used in jindofsx engine and jindocache engine. This PR removes it.
NONE

Remove unused CLIENT_STORAGE_RPC_HOST env from jindo engines

---

charts/jindocache/CHANGELOG.md
charts/jindocache/Chart.yaml
charts/jindocache/templates/fuse/daemonset.yaml
charts/jindocache/templates/master/statefulset.yaml
charts/jindocache/templates/worker/statefulset.yaml
charts/jindofsx/CHANGELOG.md
charts/jindofsx/Chart.yaml
charts/jindofsx/templates/fuse/daemonset.yaml
charts/jindofsx/templates/master/statefulset.yaml
charts/jindofsx/templates/worker/statefulset.yaml

JindoFSx or JindoCache engine should either use sts token or ak/sk to access underlying data storage. However, the code now mounts both of them when setting `secret` to a non-nil name and setting useStsToken=true. This PR fixes the bug.
NONE

bugfix: fix secret volume mounts for jindofsx and jindocache engine

---

docs/en/userguide/install.md
docs/zh/userguide/install.md

When user install k8s clusters using [Sealer](http://sealer.cool), the CSI Plugin may cannot find the IP address of API server. In that case, users need to make the CSI Plugin use host network. This PR enhanced the install user guide to show how to make the CSI Plugin use host network.
fixes #3417

Enhanced the install user guide document

---

pkg/application/inject/fuse/injector.go
pkg/application/inject/fuse/mount_point_script.go
pkg/application/inject/fuse/mutator/mutator.go
pkg/application/inject/fuse/mutator/mutator_default.go
pkg/application/inject/fuse/mutator/mutator_unprivileged.go

The PR refactors fuse sidecar mutator with pod-level info. It replaces `injector.injectObject()` func with `mutator.MutateWithRuntimeInfo()` func which mutates pod according to different serverless platforms. Also, this PR adds a `PostMutate()` func in the `Mutator` interface to allow some global mutations on the pod.
NONE

refactor: refactor fuse sidecar mutator with pod-level info

---

charts/fluid/fluid/templates/csi/daemonset.yaml
pkg/utils/map.go
pkg/utils/map_test.go
pkg/utils/mountinfo/mountinfo.go
pkg/utils/mountinfo/mountinfo_test.go
pkg/utils/mountinfo/mountpoint.go
pkg/utils/mountinfo/mountpoint_test.go

This PR does the following changes to Fluid:
1. Set `fluid-src-dir` volume in Fluid's CSI daemonset to `HostToContainer` instead of `Bidirectional`
There is no need for `fluid-src-dir` volume to be mounted with `Bidirectional` mount propagation. `HostToContainer` is enough to make FUSE mountpoint propagate from FUSE pod to CSI pod.
2. Detect mount points' multiple peer groups (if exist) instead of checking only the first peer group
When mounting `fluid-src-dir` with mountPropagation=HostToContainer, there may be several peer groups in a mount info line. For example:
```
1764 1620 0:388 / /runtime-mnt/juicefs/default/jfsdemo/juicefs-fuse ro,relatime shared:475 master:478 - fuse.juicefs JuiceFS:minio ro,user_id=0,group_id=0,default_permissions,allow_other
```
Both peer group 475 and 478 …

enhancement: recover fuse according to multiple peer group options

---

charts/fluid/fluid/templates/upgrade/crd-upgrade.yaml
charts/fluid/fluid/values.yaml

add ttl for crd-upgrade job to clean up old crd-upgrade pods. 
fixes #3499
upgrade fluid and wait for the crd-upgrade pod to be cleaned.

auto clean up crd-upgrade pod 

---

pkg/ddc/goosefs/shutdown.go

Ⅰ. This pr is to add a modification to pkg/ddc/goosefs/shut_down.go

Modify the License of shutdown.go

---

pkg/dataoperation/context.go

this PR is to update the YEAR of the license text of pkg/dataoperation/context.go, from "2022" to "2023".
NONE

update YEAR of the license text of pkg/dataoperation/context.go

---

pkg/ddc/goosefs/engine.go

This PR updates the year information in copyright section of file `pkg/ddc/goosefs/engine.go`, task 15.
Please note that task 15 is originally to modify the copyright section of file `pkg/ddc/goosefs/worker.go`, which has already been modified in Apr. 2023. Since the original task is complete, this PR modifies the copyright section for a different file.

modify: change copyright year 2022 -> 2023

---

pkg/application/inject/fuse/mutator/mutator_unprivileged.go

Complete Task 64: add license to /pkg/application/inject/fuse/mutator/mutator_unprivileged.go
NONE
NONE
NONE
NONE

task64, add license

---

pkg/utils/runtimes/options/init.go

This PR is to update the license of pkg/utils/runtimes/options/init.go modifying the year from 2021 to 2023.

【task58】：update the license of pkg/utils/runtimes/options/init.go

---

pkg/ddc/juicefs/transform_volume.go

This pr is to update the license of pkg/ddc/juicefs/transform_volume.go (for the second time...)
fix:
the year in the copyright is based on the file creation time, see commit de8206c, thus keep 2022.
use `-s` when commit.

update the license of pkg/ddc/juicefs/transform_volume.go

---

pkg/ddc/jindofsx/load_data.go

change pkg/ddc/jindofsx/load_data.go license to 2023 version
none
no, change only license

change pkg/ddc/jindofsx/load_data.go license

---

pkg/ddc/jindofsx/operate.go

modify `pkg/ddc/jindofsx/operate.go` "Copyright 2022 The Fluid Authors." to "Copyright 2023 The Fluid Authors."

modify pkg/ddc/jindofsx/operate.go

---

charts/jindocache/CHANGELOG.md
charts/jindocache/templates/fuse/daemonset.yaml
charts/jindocache/templates/master/statefulset.yaml
charts/jindocache/templates/worker/statefulset.yaml
charts/jindocache/values.yaml
charts/jindofsx/CHANGELOG.md
charts/jindofsx/templates/fuse/daemonset.yaml
charts/jindofsx/templates/master/statefulset.yaml
charts/jindofsx/templates/worker/statefulset.yaml
charts/jindofsx/values.yaml
pkg/ddc/jindocache/transform.go
pkg/ddc/jindocache/types.go
pkg/ddc/jindofsx/transform.go
pkg/ddc/jindofsx/types.go

1. Remove any `fsGroup` related transformation in Jindofsx and JindoCache engine. `fsGroup` has no critical effect on JindoRuntime's functionality but it will chown mounted persistent volumes which may cause unexpected changes on file ownership and permissions. See [Configure volume permission and ownership change policy for Pods](https://kubernetes.io/docs/tasks/configure-pod-container/security-context/#configure-volume-permission-and-ownership-change-policy-for-pods) for more information: 
> By default, Kubernetes recursively changes ownership and permissions for the contents of each volume to match the fsGroup specified in a Pod's securityContext when that volume is mounted. For large volumes, checking and changing ownership and permissions can take a lot of time, slowing Pod startup. …

enhance: remove jindoruntime's fsGroup

---

addons/glusterfs/dev-guide/glusterfs-zh_CN.md
addons/glusterfs/dev-guide/glusterfs.md
addons/glusterfs/docker/Dockerfile
addons/glusterfs/docker/build.sh
addons/glusterfs/docker/entrypoint.py
addons/glusterfs/readme-zh_CN.md
addons/glusterfs/readme.md
addons/glusterfs/runtime-profile.yaml

Add new feature: support glusterfs addon  
Including the following files
- glusterfs ThinRuntime profile
- glusterfs-fuse image dockerfile
- glusterfs develop guide
fixes #3620

Feature: add GlusterFS addons

---

charts/jindofsx/CHANGELOG.md
charts/jindofsx/templates/fuse/daemonset.yaml
charts/jindofsx/templates/master/statefulset.yaml
charts/jindofsx/templates/worker/statefulset.yaml
charts/jindofsx/values.yaml
pkg/ddc/jindofsx/transform.go
pkg/ddc/jindofsx/types.go

* Remove jindofsx's securityContext.fsGroup
---------
fixes #XXXX

enhance: remove jindoruntime's fsGroup (#3632)

---

charts/alluxio/CHANGELOG.md
charts/alluxio/Chart.yaml
charts/alluxio/templates/fuse/daemonset.yaml
charts/alluxio/templates/master/statefulset.yaml
charts/alluxio/templates/worker/statefulset.yaml
charts/alluxio/values.yaml
charts/fluid-databackup/alluxio/templates/databackup.yaml
charts/fluid-databackup/alluxio/values.yaml
charts/fluid-databackup/goosefs/templates/databackup.yaml
pkg/ddc/alluxio/backup_data.go
pkg/ddc/alluxio/port_parser_test.go
pkg/ddc/alluxio/transform.go

Remove fsgroup from alluxio runtime

---

pkg/csi/recover/recover_test.go

update recover_test.go copyright year information to 2022
Update pkg/csi/recover/recover_test.go Copyright Year to 2022
fixes #XXXX

Update recover_test.go Copyright Year to 2022

---

charts/alluxio/CHANGELOG.md
charts/alluxio/Chart.yaml
charts/alluxio/templates/fuse/daemonset.yaml
charts/alluxio/templates/master/statefulset.yaml
charts/alluxio/templates/worker/statefulset.yaml
charts/alluxio/values.yaml
charts/fluid-databackup/alluxio/templates/databackup.yaml
charts/fluid-databackup/alluxio/values.yaml
charts/fluid-databackup/goosefs/templates/databackup.yaml
pkg/ddc/alluxio/backup_data.go
pkg/ddc/alluxio/port_parser_test.go
pkg/ddc/alluxio/transform.go

* Remove fsgroup from alluxio runtime, To #53506158
* Remove fsgroup from alluxio runtime, To #53506158
* Remove fsgroup from alluxio runtime, To #53506158
---------
fixes #XXXX

Remove fsgroup from alluxio runtime (#3635)

---

api/v1alpha1/openapi_generated.go
api/v1alpha1/swagger.json
api/v1alpha1/vineyardruntime_types.go
charts/alluxio/values.yaml
charts/fluid/fluid/crds/data.fluid.io_vineyardruntimes.yaml
charts/vineyard/Chart.yaml
charts/vineyard/templates/_helpers.tpl
charts/vineyard/templates/config/vineyard-rpc-conf.yaml
charts/vineyard/templates/fuse/daemonset.yaml
charts/vineyard/templates/master/service.yaml
charts/vineyard/templates/master/statefulset.yaml
charts/vineyard/templates/worker/service.yaml
charts/vineyard/templates/worker/statefulset.yaml
charts/vineyard/values.yaml
config/crd/bases/data.fluid.io_vineyardruntimes.yaml

Add the helm chart for vineyard runtime including the master, worker and fuse.
A follow-up of https://github.com/fluid-cloudnative/fluid/pull/3555 and fix parts of https://github.com/fluid-cloudnative/fluid/issues/3528

Add the helm chart for vineyard runtime.

---

pkg/ddc/jindocache/engine_test.go

This PR addresses the issue in `pkg/ddc/jindocache/engine_test.go` where the License information had an incorrect year (2021) and lacked proper spacing from the package declaration. The year has been updated to 2023, and a blank line has been added for compliance and improved readability.

Normalize license format in pkg/ddc/jindocache/engine_test.go

---

api/v1alpha1/common.go
api/v1alpha1/dataset_types.go
api/v1alpha1/openapi_generated.go
charts/fluid/fluid/crds/data.fluid.io_alluxioruntimes.yaml
charts/fluid/fluid/crds/data.fluid.io_datamigrates.yaml
charts/fluid/fluid/crds/data.fluid.io_datasets.yaml
charts/fluid/fluid/crds/data.fluid.io_efcruntimes.yaml
charts/fluid/fluid/crds/data.fluid.io_goosefsruntimes.yaml
charts/fluid/fluid/crds/data.fluid.io_jindoruntimes.yaml
charts/fluid/fluid/crds/data.fluid.io_juicefsruntimes.yaml
charts/fluid/fluid/crds/data.fluid.io_thinruntimes.yaml
charts/fluid/fluid/crds/data.fluid.io_vineyardruntimes.yaml
config/crd/bases/data.fluid.io_alluxioruntimes.yaml
config/crd/bases/data.fluid.io_datamigrates.yaml
config/crd/bases/data.fluid.io_datasets.yaml
config/crd/bases/data.fluid.io_efcruntimes.yaml
config/crd/bases/data.fluid.io_goosefsruntimes.yaml
config/crd/bases/data.fluid.io_jindoruntimes.yaml
config/crd/bases/data.fluid.io_juicefsruntimes.yaml
config/crd/bases/data.fluid.io_thinruntimes.yaml
config/crd/bases/data.fluid.io_vineyardruntimes.yaml

Now some fields in Fluid's data types are marked as required, but in the generated CRD, these field is still optional (e.g. the `mountPoint` field). This is because kubebuilder will not make these fields required as these fields is marked with `omitempty`.
This PR removes these required field's `omitempty` and make them required in CRD.
fixes #3683

change some fields from optional to required in CRD YAML

---

charts/fluid/fluid/values.yaml
pkg/webhook/plugins/nodeaffinitywithcache/node_affinity_with_cache.go
pkg/webhook/plugins/nodeaffinitywithcache/node_affinity_with_cache_test.go

Add  `fluid.io/fuse` plugin parameter to schedule app pod to node with existed fuse pod.
fixes #XXXX

add fluid.io/fuse plugin parameter to schedule app pod to node with existed fuse pod

---

pkg/ddc/thin/ufs_internal.go

This pr is to update the Copyright year from 2022 to 2023 in the file pkg/ddc/thin/ufs_internal.go.
NONE

Update the Copyright year in pkg/ddc/thin/ufs_internal.go

---

pkg/ddc/thin/metadata.go

Update Apache license in `pkg/ddc/thin/metadata.go`

---

pkg/ddc/juicefs/master_internal_test.go

This pr is to update the pkg/ddc/juicefs/master_internal_test.go license copyright 2021 to 2023.
fixes #XXXX

update the pkg/ddc/juicefs/master_internal_test.go license copyright

---

pkg/ddc/thin/transform_config.go
pkg/ddc/thin/transform_fuse_test.go
pkg/ddc/thin/type.go

pass AccessModes to thinruntime fuse container
fixes #3636

pass AccessModes to thinruntime fuse container

---

pkg/ddc/alluxio/operations/base.go
pkg/ddc/goosefs/hcfs_test.go
pkg/ddc/goosefs/operations/base.go
pkg/ddc/jindo/operations/base.go
pkg/ddc/jindofsx/operations/base.go
pkg/ddc/juicefs/data_load_test.go
pkg/ddc/juicefs/operations/base.go
pkg/ddc/thin/operations/base.go
pkg/utils/helm/helm.go
pkg/utils/helm/helm_test.go
pkg/utils/shell_pipes.go
pkg/utils/shell_pipes_test.go

Support pipe command

---

charts/fluid/fluid/values.yaml
pkg/utils/jindo/jindo.go

Change the default engine implementation of JindoRuntime to `jindocache`.
NONE
Related: #3672

enhancement: upgrade to jindo cache engine

---

charts/vineyard/templates/fuse/daemonset.yaml

- Change the terminationGracePeriodSeconds of vineyard fuse from 30s to 60s to make sure the configmap can be unmounted successfully.
- Remove the hard link of vineyard socket and do not unmount the vineyard fuse directory.
A fixup of https://github.com/fluid-cloudnative/fluid/pull/3713

Change the terminationGracePeriodSeconds of vineyard fuse to 60s and update the prestop command

---

pkg/ddc/jindofsx/shutdown.go
pkg/ddc/vineyard/runtime_info.go
pkg/ddc/vineyard/runtime_info_test.go

A followup of https://github.com/fluid-cloudnative/fluid/pull/3713

Set the node-puhlish-method as symlink mode for vineyard runtime.

---

charts/fluid-datamigrate/juicefs/templates/job.yaml
charts/fluid-datamigrate/juicefs/templates/statefulset.yaml
pkg/dataoperation/constants.go
pkg/ddc/juicefs/data_migrate.go
pkg/ddc/juicefs/data_migrate_test.go

The launcher (job pod) is used as a worker, so it should add **PodAntiAffinity** to prefer to not on the same node as worker pods.
fixes #XXXX

fix parallel datamigrate pod anti affinity for the launcher(job) pod

---

cmd/alluxio/app/alluxio.go
cmd/dataset/app/dataset.go
cmd/efc/app/efc.go
cmd/jindo/app/jindo.go
cmd/juicefs/app/juicefs.go
cmd/thin/app/thin.go
cmd/vineyard/app/vineyard.go
pkg/controllers/manager.go

Allow Fluid users to set rest config QPS and Burst to controler client-side throttling for large-scale Kubernetes cluster.
The following command args are supported in Fluid dataset controller and runtime controllers.
```
--rest-config-burst int              Burst of rest config. (default 30)
--rest-config-qps int                QPS of rest config. (default 20)
```
QPS is default to 20 and burst is default to 30 because it's the default value for controller-runtime.
fixes #3737

feat: allow setting kube client QPS and Burst

---

api/v1alpha1/dataset_types.go
api/v1alpha1/openapi_generated.go
charts/fluid/fluid/crds/data.fluid.io_datasets.yaml
config/crd/bases/data.fluid.io_datasets.yaml

In VineyardRuntime, users dont't need to mount some external storage. This PR changes the `Mounts` field to optional. 
NONE

Fix mount validation for vineyard runtime

---

charts/fluid/fluid/templates/role/alluxio/rbac.yaml
charts/fluid/fluid/templates/role/dataset/rbac.yaml
charts/fluid/fluid/templates/role/efc/rbac.yaml
charts/fluid/fluid/templates/role/fluidapp/rbac.yaml
charts/fluid/fluid/templates/role/goosefs/rbac.yaml
charts/fluid/fluid/templates/role/jindo/rbac.yaml
charts/fluid/fluid/templates/role/juicefs/rbac.yaml
charts/fluid/fluid/templates/role/thin/rbac.yaml

Fix rbac role issue.
fixes #XXXX
None.

fix rbac role issue

---

pkg/ddc/jindocache/node.go
pkg/ddc/jindocache/node_test.go
pkg/ddc/jindofsx/node.go
pkg/ddc/jindofsx/node_test.go

1. Improve efficiency and avoid memory issue in `func SyncScheduleInfoToCacheNodes` by skipping pod listing when possible.
2. bugfix for cases where there are some pending worker pods without nodenames.
`JindoCacheEngine` and `JindoFSxEngine` syncs schedule cache locality information to nodes for Fluid's affinity scheduling policy. `SyncScheduleInfoToCacheNodes` implement this by listing the `nodeName` of all the pods controlled by the worker statefulset. This is a very heavy operation especially when there is a large amount of pods in the namespace.
To improve efficiency and avoid memory issue, it would be a great idea to skip the listing if the worker statefulset has no replicas. 
Maybe related to #3772

enhancement: Avoid heavy pod listing when worker statefulset has no replicas

---

api/v1alpha1/dataprocess_types.go

Fixed #3787
This pr is to corrected 'requried' to 'required' of file api\v1alpha1\dataprocess_types.go:99:5
fixes #3787

Fixes #3787 about typo in dataprocess_types.go

---

charts/fluid/fluid/templates/role/dataset/rbac.yaml

Revert #3860, cause for now `daemonset` rbac is required for Data Operation Reconcilers
NONE

Readd daemonsets rbac permission

---

docs/zh/operation/dataset_auto_scaling.md

Fixed #3804 
The pr is to fix some typo below:
docs\zh\operation\dataset_auto_scaling.md:139:56: corrected "Prometheous" to
"Prometheus"
docs\zh\operation\dataset_auto_scaling.md:139:96: corrected "Prometheous" to "Prometheus"
docs\zh\operation\dataset_auto_scaling.md:139:134: corrected "Prometheous" to "Prometheus"
docs\zh\operation\dataset_auto_scaling.md:423:21: corrected "Prometheous" to "Prometheus"
fixes #3804

fix typo in dataset_auto_scaling.md

---

docs/en/samples/dataset_sharedOptions.md

Fixed #3835
This pr is to correct 'accroding' to 'according' of file docs\en\samples\dataset_sharedOptions.md:113:190:

fix typo in dataset_sharedOptions.md

---

pkg/controllers/v1alpha1/datamigrate/datamigrate_controller.go

Fixed #3841
This pr is to correct "cannnot" to "cannot" of file pkg\controllers\v1alpha1\datamigrate\datamigrate_controller.go

fixed typo in datamigrate_controller.go

---

pkg/controllers/v1alpha1/dataload/dataload_controller.go

This pr is to fix Copyright time from 2022 to  2020 in file "pkg/controllers/v1alpha1/dataload/dataload_controller.go" line 2.
fixes #XXXX

fix Copyright time from 2022 to 2020  in file "pkg/controllers/v1alpha1/dataload/dataload_controller.go" line 2

---

pkg/ctrl/watch/fake_runtime_reconciler.go

changed CopyRight year from 2023 to 2021 of pkg/ctrl/watch/fake_runtime_reconciler.go
NONE
NONE
Just follow the guide

changed CopyRight year from 2023 to 2021 of pkg/ctrl/watch/fake_runtime_reconciler.go

---

pkg/controllers/v1alpha1/databackup/databackup_controller_test.go

this PR is to add Apache License to  databackup_controller_test.go

Add the missing Apache License

---

cmd/csi/app/csi.go

This pr is to normalize License information of ./cmd/csi/app/csi.go, the time of Copyright is wrong, change it from 2021 to 2022.

normalize License information of ./cmd/csi/app/csi.go

---

api/v1alpha1/status.go

This pr is to modify an year error in the license in api/v1aplha1/status.go. I changed 2022 to 2020.

modify the License in api/v1alpha1/status.go, change 2022 to 2020

---

pkg/ddc/alluxio/transform_volumes_test.go

This PR corrects copyright year ( 2023 -> 2022 ) in `transform_volumes_test.go`.
The first commit for it is f8991a19af2940310bd91ea91bfe799c68253099, which was created in 2022-05-14 00:30:47 UTC.
NONE

Correct copyright year in transform_volumes_test.go

---

hack/sdk/main.go

The copyright year of the code `/hack/sdk/main.go` should be 2021 instead of 2022.
NONE
NO TESTS ARE NEEDED as no codings were changed.
N/A

fix the copyright year of the file 'hack/sdk/main.go'

---

pkg/ddc/alluxio/runtime_info_test.go

This pr is to modify the date of CopyRight in the license of ./pkg/ddc/alluxio/runtime_info_test.go.

Modify the license of  ./pkg/ddc/alluxio/runtime_info_test.go

---

api/v1alpha1/groupversion_info.go

This pr is to corrected "2022" to "2020" of file api/v1alpha1/status.go:2:10:

Fix a copyright date error

---

pkg/ddc/base/operation_lock_test.go

This pr is to add or normalize license information in the file ./pkg/ddc/base/operation_lock_test.go.The time of Copyright is wrong.(2022->2023)
NONE

fix copyright date error

---

pkg/ddc/alluxio/operations/base.go

Ⅰ.Describe what this pr does
This pr is to change the wrong year of copyright in task 136 from 2023 to 2020 in pkg/ddc/alluxio/operations/base.go.

change the wrong year of copyright

---

pkg/controllers/v1alpha1/efc/implement.go

Fixed #3921 
This pr is to corrected '2022' to '2023' of file fluid/pkg/controllers/v1alpha1/efc/implement.go:2:14:

fix copyright

---

cmd/webhook/app/init.go

This pr is to add the missing **Copyright info** the Apache License in cmd/webhook/app/init.go

Add missing Copyright info in cmd/webhook/app/init.go

---

pkg/ddc/alluxio/cache.go

Modify the year of the Copyright of the Apache License in ./pkg/ddc/alluxio/cache.go. "2023" -> "2020"
NONE

Modify the year of the Copyright of the Apache License in ./pkg/ddc/alluxio/cache.go

---

pkg/controllers/v1alpha1/juicefs/suite_test.go

Solve Lab1Task2Task98 by changing  the apach liscense date of file './pkg/controllers/v1alpha1/juicefs/suite_test.go' from 2023 to 2021.
fixes #XXXX

changing the apach liscense year of file './pkg/controllers/v1alpha1/juicefs/suite_test.go'

---

pkg/ddc/alluxio/ufs_internal.go

The pr is to fix the copyright year of Apache License in pkg/ddc/alluxio/ufs_ internal.go
NONE

Fix the copyright year of Apache License in pkg/ddc/alluxio/ufs_ internal.go

---

pkg/ddc/alluxio/deprecated_label.go

This pr is to modify copyright year of pkg/ddc/alluxio/deprecated_label.go
fixes #XXXX

modify copyright year

---

pkg/application/inject/fuse/poststart/check_fuse_unprivileged.go

This pr is to add License for ./pkg/application/inject/fuse/poststart/check_fuse_unprivileged.go
fixes #XXXX

add and modify infomation for check_fuse_unprivileged.go

---

pkg/ddc/alluxio/runtime_info.go

This pr is to correct the license year of ./pkg/ddc/alluxio/runtime_info.go from 2023 to 2020.

correct the license year of ./pkg/ddc/alluxio/runtime_info.go

---

pkg/ddc/alluxio/transform_volumes.go

The year of the Copyright should be 2022, change it to 2022.

Change the time of the Copyright in pkg/ddc/alluxio/transform_volumes.go

---

pkg/controllers/v1alpha1/juicefs/implement.go

correct the year of License at pkg\controllers\v1alpha1\juicefs\implement.go

correct Apache License year at implement.go

---

pkg/common/label.go
pkg/common/label_test.go

fix code scaning https://github.com/fluid-cloudnative/fluid/security/code-scanning/945
fixes #XXXX

fix code scaning alerts —— Incomplete regular expression for hostnames

---

pkg/ddc/alluxio/transform_optimization_test.go
pkg/ddc/alluxio/transform_resources.go

The year of the Copyright should be 2020, change it from 2023 to 2020.

Change the time of the Copyright in pkg/ddc/alluxio/transform_resources.go

---

pkg/common/efc.go

This pr is to standardize the License of /pkg/common/efc.go, change the wrong year 2022 to 2022

Standardize the License of /pkg/common/efc.go

---

pkg/ddc/base/volume.go

This pr is to fix copyright year from 2022 to 2020 of pkg/ddc/base/volume.go

fix copyright year from 2022 to 2020

---

charts/vineyard/templates/worker/statefulset.yaml

During tests, we find the vineyard worker always restarts as the liveness probe doesn't succeed in the host network mode.
It's caused by the vineyard worker using the default port 9600 instead of the assigned one from the host.

Fix the inconsistent rpc socket port with assigned port in vineyard worker.

---

pkg/ddc/alluxio/types.go

this pr is to fix a wrong time of Copyright from 2023 to 2020 in the file"pkg/ddc/alluxio/types.go",so the Task 166 is finished.
fixes #XXXX

this pr is to fix a wrong time of Copyright

---

pkg/common/constants.go

This pr is to add license to ./pkg/common/constants.go

---

pkg/ddc/jindocache/transform.go

fix default value

---

pkg/ddc/base/mock/mock_engine.go

The purpose of this pull request is to add or standardize the license information in the header of the mock_engine.go file located at ./pkg/ddc/base/mock/mock_engine.go. I have already made the necessary modifications.
NONE
NONE
Clone the repository in your local environment.
Navigate to the ./pkg/ddc/base/mock/ directory.
Open the mock_engine.go file.
Ensure that the license information has been added or standardized in the header of the file.
Please pay attention to whether the added license information complies with the standard requirements and is correctly placed in the header of the file.
Please modify your pull request description according to the provided template, ensuring that the information accurately and clearly reflects your changes. If you have any further questions, feel …

Standardize License Information in mock_engine.go

---

pkg/ddc/efc/cache.go

This PR is to modify the incorrect license information in file 'pkg/ddc/efc/cache.go', where there is something wrong with the copyright time.

Correcting License Information in 'pkg/ddc/efc/cache.go' due to Copyright Time Error

---

addons/dynamic-mount/base/Dockerfile
addons/dynamic-mount/base/build.sh
addons/dynamic-mount/base/entrypoint.sh
addons/dynamic-mount/base/inotify-fluid-config.ini
addons/dynamic-mount/base/inotify.sh
addons/dynamic-mount/base/mount-helper.sh
addons/dynamic-mount/base/mount-passthrough-fuse.sh
addons/dynamic-mount/base/prestop.sh
addons/dynamic-mount/base/reconcile_mount_program_settings.py
addons/dynamic-mount/juicefs/docker/Dockerfile.juicefs
addons/dynamic-mount/juicefs/docker/mount.sh

Changes:
- Add a base image Dockerfile supporting common logic for dynamic mount feature
- A JuiceFS example that leverages the dynamic mount feature
NONE

addons: add dynamic mount examples

---

pkg/ddc/base/label.go

Correct the copyright year from 2022 to 2020 in ./pkg/ddc/base/label.go

Correct Copyright year in ./pkg/ddc/base/label.go

---

pkg/webhook/handler/mutating/mutating_handler.go
pkg/webhook/handler/mutating/mutating_handler_test.go

- Override `pod.Namespace` with req.Namespace. This is only effective before K8s 1.24, see discussion and the bugfix in https://github.com/kubernetes/kubernetes/issues/113952#issuecomment-1317042694
- By overriding `pod.Namespace`, we avoid passing `namespace` into deeper mutation functions and make code clearer.
None

refactor: avoid passing namespace to mutation functions

---

pkg/webhook/handler/mutating/mutating_handler.go

Follow-up of #4171 
#4171 overrides `pod.Namespace` with `req.Namespace` no matter what `pod.Namespace` is. The may have some side effect when mutating a Pod, for example, changing pod.metadata.namespace after mutation. This PR fixes this by checking if `pod.Namespace` is valid and try to revert it before the handler responds.
None

minorfix: carefully handle pod.namespace to avoid side effect

---

charts/fluid/fluid/Chart.yaml
charts/fluid/fluid/values.yaml

Build docker images for refactoring dataflow controller

---

pkg/webhook/handler/mutating/mutating_handler.go

Fluid webhook skips mutation for runtime pods by checking if it has a label `app: <runtimeType>`. This is not what we want in some cases. For example, an AlluxioRuntime accelerating a PVC that backed by another Runtime. In such case, AlluxioRuntime's master and worker pods should mount the PVC so they should be mutated. 
NONE

minorfix: do not skip mutation for fluid pods

---

pkg/ctrl/watch/pod.go
pkg/utils/annotations.go
pkg/webhook/plugins/fusesidecar/fuse_sidecar.go

bugfix of #4138 
#4138 removed labelSelector on cache, making fluidapp-controller fail to watch mutated pods and umount fuse sidecar appropriately. 
NONE

bugfix: fix application controller manage pod lifecycle

---

pkg/ddc/efc/create_volume.go
pkg/utils/dataset.go
pkg/utils/dataset/volume/create.go
pkg/utils/dataset_test.go

The generated PVC and PV have a fixed size of 100 Pi and cannot be changed. In a namespace with a Resourcequota set for storage, it is not possible to create such large PV and PVC. Therefore, the size needs to be configurable.
fixes #4177
“pvc.fluid.io/resources.requests.storage” as the annotation key on Dataset to specify the desired storage size for the generated PVC. If not set, or if the storage size format is incorrect, it will be set to the default value of 100Pi.

dataset support pvc storageSize

---

pkg/ddc/efc/create_volume.go
pkg/ddc/juicefs/transform_fuse.go
pkg/utils/annotations.go
pkg/utils/map.go

bugfix: allow users to override juicefs attr-cache and entry-cache options

---

.circleci/config.yml
.github/workflows/go.yml
.travis.yml
go.mod

This PR updates the `go.mod` file to specify the Go version as `1.21.10`, adhering to the required 1.N.P syntax. This change ensures compatibility with Go 1.21 and prevents potential issues with `go` commands.
fixes #4195

Update go.mod to comply with Go 1.21 toolchain syntax

---

pkg/csi/plugins/nodeserver.go

bugfix for #4189 
- Add a new `func isLikelyNeedUnmount` to check if a path is likely a mount point that needs to be unmount.
- Unmount mount points on the path until cleaned up.
fixes #4189

bugfix: fix early break when cleaning mount point in NodeUnpublishVolume

---

cmd/thin/app/thin.go

This pr is to add the translation of the Apache License notice

---

charts/fluid/fluid/templates/role/vineyard/rbac.yaml

Delete the unused rbac roles for vineyard runtime.

---

charts/jindocache/CHANGELOG.md
charts/jindocache/Chart.yaml
charts/jindocache/templates/_helpers.tpl
charts/jindocache/templates/fuse/daemonset.yaml
charts/jindocache/templates/master/statefulset.yaml
charts/jindocache/templates/worker/statefulset.yaml
charts/jindofsx/CHANGELOG.md
charts/jindofsx/Chart.yaml
charts/jindofsx/templates/_helpers.tpl
charts/jindofsx/templates/fuse/daemonset.yaml
charts/jindofsx/templates/master/statefulset.yaml
charts/jindofsx/templates/worker/statefulset.yaml

Bugfix for #4213 
- Using projected secret keys instead of `subPath` in secret volume mounts because `subPath` mounting does not receive automated Secret updates.
- Refactor helm chart template with a common function defined in `.tpl`
fixes #4213

bugfix: support sync ak/sk secret key-values in JindoRuntime

---

charts/fluid/fluid/templates/_helpers.tpl
charts/fluid/fluid/templates/controller/alluxioruntime_controller.yaml
charts/fluid/fluid/templates/controller/dataset_controller.yaml
charts/fluid/fluid/templates/controller/efcruntime_controller.yaml
charts/fluid/fluid/templates/controller/fluidapp_controller.yaml
charts/fluid/fluid/templates/controller/goosefsruntime_controller.yaml
charts/fluid/fluid/templates/controller/jindoruntime_controller.yaml
charts/fluid/fluid/templates/controller/juicefsruntime_controller.yaml
charts/fluid/fluid/templates/controller/thinruntime_controller.yaml
charts/fluid/fluid/templates/controller/vineyardruntime_controller.yaml
charts/fluid/fluid/templates/csi/daemonset.yaml
charts/fluid/fluid/templates/upgrade/crd-upgrade.yaml
charts/fluid/fluid/templates/webhook/webhook.yaml
charts/fluid/fluid/values.yaml

refactor: separate image and tag in helm values

---

pkg/application/inject/fuse/injector.go
pkg/application/inject/fuse/mutator/mutator.go
pkg/application/inject/fuse/mutator/mutator_default.go
pkg/application/inject/fuse/mutator/mutator_test.go
pkg/application/inject/fuse/mutator/mutator_unprivileged.go
pkg/common/types.go

Provide a way to pass any key-value pairs when building fuse sidecar mutators. The key-value pair can be defined in pod.metadata.annotations in the format of `{platform}.fluid.io/{key}={value}` where `{platform}` is related to fuse sidecar mutators.
For example:
```
metadata:
annotations:
myplatform.fluid.io/foo=bar
```
meaning a mutator registered with name `myplatform` will be created with extra arguments `foo=bar`.
NONE

feat: pass extra args when building fuse sidecar mutators

---

.github/scripts/deploy-fluid-to-kind.sh
tools/diagnose-fluid-alluxio.sh
tools/diagnose-fluid-jindo.sh
tools/diagnose-fluid-juicefs.sh

Adapt kind e2e test to follow the new format of `charts/fluid/fluid/values.yaml` introduced in #4216 
NONE

bugfix: fix kind e2e test images

---

pkg/ddc/jindo/const.go

We need to update the naming convention of the constant variable CSI_DRIVER to follow camelCase format as CsiDriver. This change is to maintain consistency with our project's coding standards and improve readability.
fixes #4228

Change Constant Variable Naming Convention for CSI_DRIVER in camelCase format

---

charts/fluid/fluid/Chart.yaml
charts/fluid/fluid/values.yaml
pkg/ddc/jindo/const.go
pkg/ddc/jindo/transform.go

Update docker images for refactoring sidecar mutator

---

addons/dynamic-mount/juicefs/docker/mount.sh

Previously, dynamic-mount is supported in Version 1.0.9, users can configure the juicefs mount-point in dataset dynamically, however only the root dir can be configured. This pull request optimizes the parameter parsing logic in the juicefs mount script to support the subpath configuration of juicefs mount-points.
NONE
No tests was added.
Specify the following mount point configuration in dynamic-mount dataset, the subpath of juicefs volume can be dynamic mounted.
```shell
- mountPoint: juicefs://$volume-name/$volume-subpath-1/.../
name: juicefs-volume
path: /subpath
```

Feat:support dynamic mount of subpath format JuiceFS mount-points

---

pkg/common/constants.go
pkg/controllers/runtime_controller.go
pkg/ddc/alluxio/validate.go
pkg/ddc/base/engine.go
pkg/ddc/base/mock/mock_engine.go
pkg/ddc/base/template_engine.go
pkg/ddc/efc/validate.go
pkg/ddc/goosefs/validate.go
pkg/ddc/jindo/validate.go
pkg/ddc/jindocache/validate.go
pkg/ddc/jindofsx/validate.go
pkg/ddc/juicefs/validate.go
pkg/ddc/thin/referencedataset/validate.go
pkg/ddc/thin/transform_config.go
pkg/ddc/thin/transform_fuse.go
pkg/ddc/thin/type.go
pkg/ddc/thin/validate.go
pkg/ddc/vineyard/validate.go

- Added  `func Validate()` for all engines. Only `ThineEngine.Validate()` is implemented in this PR and others are left future TODOs.
- Allowed launchingThinRuntime when there is no mount point defined in the Dataset.
- Validate `spec.mounts[*].name` and `spec.mounts[*].path` in ThineEngine.Validate() to avoid duplicated fields.
NONE

enhance: validate dataset mounts before reconiling thinruntimes

---

pkg/ddc/jindocache/transform.go
pkg/ddc/jindofsx/transform.go

fix the issue: when jindocache/jindofsx runtime use container network, it can't use default DEFAULT_MASTER_RPC_PORT=8101 and DEFAULT_WORKER_RPC_PORT=6101.
NONE
when use JindoRuntime with `networkmode: ContainerNetwork` like:
```
kind: JindoRuntime
metadata:
name: liuxiang-fluid-jindocache-demo1
namespace: fluid-system
spec:
networkmode: ContainerNetwork
replicas: 1
tieredstore:
levels:
- mediumtype: SSD
path: /mnt/liuxiang-fluid-jindocache-demo1
quota: 10Gi
high: "0.9"
low: "0.7"
```
check the master/worker rpc port at configmap liuxiang-fluid-jindocache-demo1-jindocache-values is not default DEFAULT_MASTER_RPC_PORT=8101 and DEFAULT_WORKER_RPC_PORT=6101, otherwise is like:
```
master:
ports:
rpc: 18364
worker:
ports:
rpc: 19971
```

jindo: fix master and worker ports of jindo runtime

---

pkg/ddc/thin/ufs_internal.go
pkg/utils/map.go
pkg/utils/map_test.go

bugfix: fix options affecting sharedOptions in other mounts

---

pkg/ddc/jindocache/operate.go
pkg/ddc/jindocache/process_data.go

Support `DataProcess` operation type for JindoCache engine.
NONE

bugfix: Support data process operation type for JindoCache engine

---

pkg/ddc/jindocache/operations/base.go
pkg/ddc/jindofsx/operations/base.go
pkg/utils/kubeclient/exec.go

The default 2min may be not enough in some circumstances, especially when there are large amount of files in the underlying file system. This PR expand the timeout to 1500s(25min), which should be enough for most cases.
NONE

Make JindoRuntime sync Ufs total size with a longer timeout

---

cmd/csi/app/csi.go
pkg/common/alluxio.go
pkg/common/constants.go
pkg/common/ufs_path.go
pkg/ddc/alluxio/transform.go
pkg/ddc/alluxio/ufs_internal.go
pkg/ddc/goosefs/ufs_internal.go
pkg/ddc/jindocache/operations/base.go
pkg/ddc/jindocache/transform.go
pkg/ddc/jindocache/ufs_internal.go
pkg/ddc/jindocache/utils.go
pkg/ddc/jindofsx/operations/base.go
pkg/ddc/jindofsx/ufs_internal.go
pkg/ddc/jindofsx/utils.go
pkg/utils/dataset.go
pkg/utils/pprof.go
pkg/utils/ufs_path_builder.go
pkg/utils/ufs_path_builder_test.go

- refactor `UFSPathBuilder` to make it reused by all the cache systems with a Unified Namespace. (i.e. Alluxio, GooseFS and JindoFS)
- bugfix for #4273 
- optimize code logic for functions of JindoFsxEngine and JindoCacheEngine.
fixes #4273 
There is a corner case that backward incompatibility may happen in this PR. Please have a loot at my comment below for more information.

optimize mount logic && fix calculating ufs total size for JindoRuntime

---

api/v1alpha1/common.go
charts/fluid/fluid/crds/data.fluid.io_alluxioruntimes.yaml
charts/fluid/fluid/crds/data.fluid.io_thinruntimes.yaml
config/crd/bases/data.fluid.io_alluxioruntimes.yaml
config/crd/bases/data.fluid.io_thinruntimes.yaml
pkg/ddc/jindocache/cache_test.go
pkg/ddc/thin/metadata.go
pkg/ddc/thin/metadata_test.go

- disable metadata auto-sync for ThinRuntime by default
- update crd to remove `// +kubebuilder:default=true` for `spec.management.metadataSyncPolicy.autoSync`.
- NOTE: The removal is backward compatible because we take an empty `metadataSyncPolicy.autoSync` as `true`w before.
```
func (msb *MetadataSyncPolicy) AutoSyncEnabled() bool {
return msb.AutoSync == nil || *msb.AutoSync
}
```
fixes #4282 
Related to #4091 where we allow users to disable metadata auto-sync, while this PR make it a default behavior.

disable metadata auto-sync for ThinRuntime by default

---

test/gha-e2e/alluxio/test.sh
test/gha-e2e/jindo/test.sh
test/gha-e2e/juicefs/test.sh

Add a timeout (default: 180s) to each e2e test case in Github Actions.
NONE

enhance: add timeout for kind-e2e github actions tests

---

docs/en/samples/dataflow_affinity.md
docs/zh/samples/dataflow_affinity.md
pkg/common/label.go
pkg/controllers/v1alpha1/fluidapp/dataflowaffinity/dataflowaffinity_controller.go
pkg/controllers/v1alpha1/fluidapp/dataflowaffinity/dataflowaffinity_controller_test.go
pkg/dataflow/affinity.go
pkg/dataflow/affinity_test.go
pkg/dataflow/helper.go
pkg/dataflow/helper_test.go
pkg/dataprocess/generate_values.go
pkg/ddc/alluxio/load_data.go
pkg/ddc/goosefs/load_data.go
pkg/ddc/jindocache/load_data.go
pkg/ddc/jindofsx/load_data.go
pkg/ddc/juicefs/data_load.go
pkg/ddc/juicefs/data_migrate.go
pkg/utils/affinity.go

user should define annotation for exposed dataflow affinity. see the usage in the doc.
fixes #XXXX

use annotation for exposed affinity for dataflow

---

pkg/ctrl/affinity.go
pkg/ctrl/affinity_test.go

remove redundant update to avoid upper replicas update must has conflict error, although it's in retry.RetryOnConflict()
remove redundant statefulset update to avoid upper replicas update must has conflict error, although it's in retry.RetryOnConflict(), result to it have to update twice unneedly.
NONE

remove redundant update for performance

---

.github/scripts/build-all-images.sh
.github/scripts/deploy-fluid-to-kind.sh
Makefile

1. Variable reorganization: Grouped related variables together for better clarity and easier maintenance.
2. Enhanced architecture support.
3. Standardized Docker build options.
4. Consolidated build targets: Streamlined the definition of build targets for various controllers, reducing repetition in the Makefile.
5. Improved multi-architecture support: Added Docker buildx targets to facilitate building for multiple architectures in a single command.
6. Standardized naming conventions: Adopted more consistent naming for targets and variables throughout the Makefile.
8. Enhanced modularity: Separated some functionalities into distinct targets, making the Makefile more modular and easier to extend.
Part of  #4297

Use Variables for simplify edits and enhance readability.

---

pkg/controllers/operation_controller.go
pkg/controllers/v1alpha1/databackup/implement.go
pkg/controllers/v1alpha1/dataload/implement.go
pkg/controllers/v1alpha1/datamigrate/implement.go
pkg/controllers/v1alpha1/dataprocess/implement.go
pkg/dataoperation/interface.go
pkg/dataoperation/mock.go
pkg/ddc/base/operation_lock.go
pkg/utils/datamigrate.go

- Add a new function `GetPossibleTargetDatasetNamespacedNames()` for all data operations. It's currently only used when cleaning data operations. The function returns a list of possible datasets' `types.NamespacedName`, after then the operation reconciler can correctly remove engines with the namespace and name.
- Refactor `func GetTargetDatasetOfMigrate` to make it easier to read.
fixes #4328

bugfix: fix data operation failure when upgrading cache engine implementation with same Dataset name

---

pkg/webhook/plugins/mountpropagationinjector/mount_propagation_injector.go

The intention here should be to initialize a slice with a capacity of   `len(runtimeInfos)`  rather than initializing the length of this slice. 
The online demo: https://go.dev/play/p/q1BcVCmvidW
fixes #XXXX

fix: fix slice init length

---

api/v1alpha1/openapi_generated.go
api/v1alpha1/thinruntime_types.go
api/v1alpha1/thinruntimeprofile_types.go
charts/fluid/fluid/crds/data.fluid.io_thinruntimeprofiles.yaml
charts/fluid/fluid/crds/data.fluid.io_thinruntimes.yaml
charts/thin/templates/fuse/daemonset.yaml
charts/thin/templates/worker/statefuleset.yaml
config/crd/bases/data.fluid.io_thinruntimeprofiles.yaml
config/crd/bases/data.fluid.io_thinruntimes.yaml
pkg/ddc/thin/transform.go
pkg/ddc/thin/transform_fuse.go
pkg/ddc/thin/type.go

ThinRuntime, as provided by Fluid, allows users to customize the storage system definition. In many scenarios, users build their own ThinRuntime images, so the configuration of imagePullSecrets is essential. This is because private images need to be pulled when the Fuse mountPod is started. 
In this PR, we have added a multi-level definition of `imagePullSecrets` to the `ThinRuntime` and `ThinRuntimeProfile` custom resource definitions (CRDs).  
Global level, under spec
Component level
a. Worker level, under spec.worker
b. Fuser level, under spec.fuse
When `imagePullSecrets` are defined in both the ThinRuntime and ThinRuntimeProfile CRs, the priority is as follows:
```
thinRuntime.spec.fuse.imagePullSecrets > thinRuntime.spec.imagePullSecrets > …
```

feat: support imagePullSecrets in thinRuntime & thinRuntimeProfile

---

pkg/common/label.go
pkg/csi/plugins/nodeserver.go
pkg/ddc/alluxio/runtime_info.go
pkg/ddc/base/runtime.go
pkg/ddc/efc/runtime_info.go
pkg/ddc/goosefs/runtime_info.go
pkg/ddc/jindo/runtime_info.go
pkg/ddc/jindocache/runtime_info.go
pkg/ddc/jindofsx/runtime_info.go
pkg/ddc/juicefs/runtime_info.go
pkg/ddc/thin/referencedataset/runtime.go
pkg/ddc/thin/runtime_info.go
pkg/ddc/vineyard/runtime_info.go
pkg/utils/dataset/volume/create.go

As a premise, this PR clarifies a concept that has always existed in Fluid: 
"**MountMode**". Historically, the processes responsible for executing the fuse mount actions have existed in two patterns: mountPod and sidecar.
The mountPod is initiated before the pod starts, performing the corresponding mount actions. Meanwhile, the NodePublishVolume interface of the Fluid CSI plugin implements a check_mount script to verify whether the mountPod has completed its mounting. However, in certain runtime scenarios where `dataset.spec.mounts` may initially be empty (such as thinRuntime or vineyard), there are no initial mount points, causing the check_mount validation of the NodePublishVolume interface to fail. This results in the inability to start pods using mountPod as the mountMode.
To address …

feat: support mountMode configuration to skip checking mount ready

---

charts/fluid-dataloader/jindocache/templates/cronjob.yaml

In the upgrade of historical versions of jindocache fuse, the referenced configuration file path changed. Therefore, in [PR#3662](https://github.com/fluid-cloudnative/fluid/pull/3662) the contributor modified the configuration path for jindocache in the dataload job helm template. However, this modification did not take into account the cronJob. As a result, when using jindoCache as a runtime in Fluid versions v1.0.0 to v1.0.3, the dataload cronJob ends up referencing an incorrect configuration file path, leading to failure. 
fixes #4357

[WIP] fix: fix the dataload with cronJob failure in jindoCacheRuntime

---

charts/fluid-dataloader/juicefs/templates/cronjob.yaml
charts/fluid/fluid/templates/_helpers.tpl
charts/fluid/fluid/templates/controller/alluxioruntime_controller.yaml
charts/fluid/fluid/templates/controller/dataset_controller.yaml
charts/fluid/fluid/templates/controller/efcruntime_controller.yaml
charts/fluid/fluid/templates/controller/fluidapp_controller.yaml
charts/fluid/fluid/templates/controller/goosefsruntime_controller.yaml
charts/fluid/fluid/templates/controller/jindoruntime_controller.yaml
charts/fluid/fluid/templates/controller/juicefsruntime_controller.yaml
charts/fluid/fluid/templates/controller/thinruntime_controller.yaml
charts/fluid/fluid/templates/controller/vineyardruntime_controller.yaml
charts/fluid/fluid/templates/upgrade/crd-upgrade.yaml

fix some issues of helm chart
1. imagePullSecret is supported in deploying thinRuntimeController & crd-Uprader
2. unify the interface of resource declaration
3. fix duplicated imagePullSecret configuration in juicefs-dataloader-conJob

fix some issues of helm chart

---

pkg/csi/plugins/nodeserver.go
pkg/utils/mount.go

`NodeUnpublishVolume` stops and reports error when checking target paths with corrupted mount points on it. This is not an intended behavior because it stucks NodeUnpublishVolume and may causes Pod stucking at terminating phase. This PR fixes this issue.
This is a regression bug brought by #4318 
NONE

bugfix: fix NodeUnpublishVolume when checking corrupted mount points

---

GOVERNANCE.md

`Nominated by one of the maintainers or TOC members by open a community issue` -> `Nominated by one of the maintainers or TOC members by opening a community issue`
Copy of #4368

Fix spelling

---

pkg/csi/plugins/nodeserver.go

We support a configuration to skip checking mount ready in #4346, to handle the case that user define a nil mountPoints dataset in thinruntime. the verification of the existence of the mountPath was also skipped in the nodePublishVolume function with this configuration. The mountPath was linked to the targetPath using a symlink, which caused the targetPath to be linked to a non-existent directory before the mountPod created it. As a result, the application pod's creation would fail until the fusePod was started and running, which then created the mountPath linked to the targetPath.
In this PR, a pre-check for the existence of the mountPath will be added in the nodePublishVolume method of the CSI plugin.

Fix: add check mountPath in nodePublishVolume

---

charts/fluid/fluid/templates/webhook/webhook.yaml

The following configuration in Fluid Chart Values.yaml can be apply to Fluid Webhook Pod.Spec.Container[0].Resource
```
webhook:
replicas: 3
resources:
requests:
cpu: 1000m
memory: 2048Mi
limits:
cpu: 2000m
memory: 4086Mi
```

Support to set the resource configuration for Fluid webhook pod

---

charts/thin/templates/fuse/daemonset.yaml
charts/thin/templates/worker/statefuleset.yaml

>  Annotation "sidecar.istio.io/inject" has been deprecated in favor of the "sidecar.istio.io/inject" label and may not work in future Istio versions.

refactor: Optimize thin usage of istio

---

charts/jindocache/templates/master/statefulset.yaml
charts/jindofsx/templates/master/statefulset.yaml
pkg/ddc/jindocache/transform.go
pkg/ddc/jindofsx/transform.go

bugfix: add pod anti affinity to master sts to make HA available

---

pkg/application/inject/fuse/injector.go

This is a bugfix for Fluid webhooks running in development mode which might panic when using the `FuseSidecar` webhook plugin.
To reproduce the issue:
1. create any dataset & runtime
2. create pod using `FuseSidecar` plugin
3. found webhook panics with the following message
```
2025/01/13 14:57:45 http: panic serving 192.168.4.149:37462: odd number of arguments passed as key-value pairs for logging
goroutine 104 [running]:
net/http.(*conn).serve.func1()
/usr/local/go/src/net/http/server.go:1868 +0x13d
panic({0x21fce40?, 0xc00018b390?})
/usr/local/go/src/runtime/panic.go:920 +0x290
github.com/fluid-cloudnative/fluid/vendor/go.uber.org/zap/zapcore.CheckWriteAction.OnWrite(0x2, 0xc0006f6000, {0x0, 0xc0005ed800, 0xbda})
/go/src/github.com/fluid-cloudnative/fluid/vendor/go.uber.org/zap/zapcore/ …
```

bugfix: fix log panic when webhook running in development mode

---

api/v1alpha1/swagger.json
pkg/ddc/jindocache/transform.go

- Set JindoCache engine's default readahead prefetcher version to "legacy".
- Update `swagger.json` and python sdk submodule to the latest version and
NONE

Set JindoCache's defaut readahead prefetcher version to "legacy"

---

pkg/ddc/juicefs/utils.go

len() for nil slices is defined as zero, omit nil check

fix code static check

---

charts/fluid/fluid/templates/csi/daemonset.yaml
charts/fluid/fluid/templates/role/csi/rbac.yaml
charts/fluid/fluid/values.yaml
pkg/csi/plugins/nodeserver.go
pkg/csi/plugins/register.go

- Add an option to `values.yaml` to enable node authorized client for CSI. (default value: true)
Background:
Fluid borrows kubelet's kube config to use [node authorization](https://kubernetes.io/docs/reference/access-authn-authz/node/) to restrict Fluid CSI Plugin's permission. However, in some Kubernetes environment (e.g. AWS EKS), it may need extra effort to correctly configure node authorization.
This PR adds an option in Fluid's chart to allow users to deploy Fluid without using node authorization. This enforces Fluid CSI Plugin to fall back to use standard kubernetes client (based on service account and RBAC).
**WARNING:** It should be well noted that deploying Fluid without using node authorization promotes Fluid CSI Plugin's permission, and this may lead to potential security …

Support `useNodeAuthorization` option to enable node authorized client for CSI

---

pkg/common/dataset.go
pkg/ddc/thin/transform_fuse.go
pkg/ddc/thin/transform_fuse_test.go

Currently, many storage products have not been adapted to cloud-native environments and only provide mounting clients suitable for traditional VM environments. In such scenarios, users can only manually mount on Kubernetes nodes and then mount to the Pod using HostPathVolume. For these users, to enable management of this type of mount through dataset orchestration, this PR introduces a `fluid.fuse.hostvolume` option in the dataset. This configuration will be converted into a hostVolume and related volumeMount of fuse pod in thinruntime, enabling the management of such mountPoints on HostPath through thinruntime. This approach allows users to leverage Fluid's features, such as fluid dataProcess and referenceDataset capabilities. 
```
kind: Dataset …
```

support mountPoint on host for thinruntime

---

pkg/ctrl/fuse.go
pkg/ctrl/fuse_test.go

The implementations of CheckFuseHealthy lack updates for the `FuseReason`, `CurrentFuseNumberScheduled`, and `DesiredFuseNumberScheduled` fields in the Runtime Fuse Status. In this PR, this information is completed.

Completion runtime schedule info of runtime fuse status

---

pkg/controllers/runtime_controller.go
pkg/ctrl/ctrl.go
pkg/ctrl/fuse.go
pkg/ddc/base/syncs.go
pkg/ddc/thin/dataset.go
pkg/ddc/thin/status.go
pkg/ddc/thin/ufs.go
pkg/utils/crtl_utils.go
pkg/utils/crtl_utils_test.go

As Fluid is increasingly being adopted by more users in production environments, the number of datasets within clusters has reached the order of thousands. This places higher demands on the overall performance of the RuntimeController. The most critical factor here is the time taken for a dataset to become bounded after its creation, as this directly affects the readiness time of business operations. Through extensive testing, it has been observed that the time for a dataset to become bound increases exponentially with the number of datasets. In a cluster environment with thousands of datasets, the average time for a single dataset to become bound has reached 40 seconds. Therefore, this PR aims to optimize the performance of the RuntimeController in large-scale dataset clusters.
Testing …

improve the runtimeController performance in large-scale scenarios

---

pkg/ddc/juicefs/data_migrate_test.go

TestJuiceFSEngine_setParallelMigrateOptions in pkg/ddc/juicefs/data_migrate_test.go.
fixes #4573

This PR is to add comments toTestJuiceFSEngine_setParallelMigrateOptions in pkg/ddc/juicefs/data_migrate_test.go.

---

pkg/ddc/jindo/dataset_test.go

Add comments to TestUpdateCacheOfDataset() in pkg/ddc/jindo/dataset_test.go
fixes #4538

This PR is to add comments to TestUpdateCacheOfDataset() in pkg/ddc/jindo/dataset_test.go

---

pkg/ddc/juicefs/datasetinfo_parser_test.go

This PR adds documentation comments to the unit test function Test_parseFSInfoFromConfigMap 
in pkg/ddc/juicefs/datasetinfo_parser_test.go. These comments improve the readability of 
the function by describing its purpose and the steps involved in the test cases.
fixes #1
Please check if the comments clearly describe the function's purpose and test process.
Any suggestions for better clarity are welcome.

This PR is to add comments to Test_parseFSInfoFromConfigMap in pkg/ddc/juicefs/datasetinfo_parser_test.go.

---

pkg/ddc/alluxio/transform_test.go

add comments to TestTransformMasterProperties in  pkg\ddc\alluxio\transform_test.go.
fixes #4548, fixes #4541
the issue#4541 is Chinese and the issue #4548 is English，and the comment in this request is English，so you can accpet it to close two issues

This PR is to add comments to TestTransformMasterProperties in  pkg\ddc\alluxio\transform_test.go.

---

pkg/ddc/alluxio/ufs_test.go

This PR is to add comments to TestUpdateMountTime in pkg/ddc/alluxio/ufs_test.go
fixes #4543

This PR is to add comments to TestUpdateMountTime in pkg/ddc/alluxio/ufs_test.go

---

pkg/ddc/alluxio/load_data.go

Add notation to CheckRuntimeReady in pkg/ddc/alluxio/load_data.go
fixes #4551

This PR is to add comments to CheckRuntimeReady in pkg/ddc/alluxio/load_data.go.

---

pkg/ddc/jindo/dataset_test.go

Add comments to TestBindToDataset in pkg\ddc\jindo\dataset_test.go.
fixes #4549

This PR is to add comments to TestBindToDataset in pkg\ddc\jindo\dataset_test.go.

---

pkg/ddc/alluxio/delete_volume_test.go

…ete_volume_test.go
add comments to TestAlluxioEngine_DeleteVolume in pkg/ddc/alluxio/delete_volume_test.go
```
// TestAlluxioEngine_DeleteVolume tests the DeleteVolume function of the AlluxioEngine.
// It sets up test cases with different PersistentVolume (PV) and PersistentVolumeClaim (PVC) inputs,
// including scenarios with and without errors. The function uses a fake Kubernetes client to simulate
// the behavior of the AlluxioEngine when deleting volumes. The test cases include:
// 1. A common scenario where the volume should be deleted without errors.
// 2. A scenario where an error is expected due to specific annotations on the PVC.
// 3. A scenario where an error is expected because the AlluxioEngine is not running.
// The function then runs these test cases using the doTestCases …
```

This PR is to add comments to TestAlluxioEngine_DeleteVolume in pkg/ddc/alluxio/delete_volume_test.go

---

pkg/ddc/juicefs/delete_volume_test.go

add commentsto dotestcases in pkg\ddc\juicefs\delete_volume_test.go
fixes #4567
None

This PR is to add comments to DoTestCases in pkg\ddc\juicefs\delete_volume_test.go

---

pkg/ddc/juicefs/delete_volume_test.go

This PR is to add comments to newTestJuiceEngine in pkg\ddc\juicefs\delete_volume_test.go
Yes. It fixes #4529
None.

This PR is to add comments to newTestJuiceEngine in pkg\ddc\juicefs\delete_volume_test.go

---

pkg/ddc/alluxio/transform_volumes_test.go

add Comments to TestTransformWorkerValumes in pkg/ddc/alluxio/transform_volumes_test.go.
fixes #4555

This PR is to add Comments to TestTransformWorkerValumes in pkg/ddc/alluxio/transform_volumes_test.go

---

pkg/ddc/alluxio/transform_resources.go

Ⅰ.Describe what this PR does
Add comments to transformTolerations in pkg/ddc/alluxio/transform_resources.go.
fixes #4522
```
// transformTolerations updates the Alluxio configuration with tolerations specified in the dataset.
// It iterates over each toleration in dataset.Spec.Tolerations, clears the TolerationSeconds field,
// and appends the modified toleration to value.Tolerations. This ensures that only the necessary toleration
// settings (without expiration) are transferred to the Alluxio value.
```

This PR is to add comments to transformTolerations in pkg/ddc/alluxio/transform_resources.go.

---

pkg/ddc/jindo/delete_volume_test.go

Add notation to TestJindoEngine_DeleteVolume in pkg\ddc\jindo\delete_volume_test.go.
fixes #4569

This PR is to add comments to TestJindoEngine_DeleteVolume in pkg\ddc\jindo\delete_volume_test.go.

---

pkg/ddc/juicefs/datasetinfo_parser.go

This PR is to add comments to parseFSInfoFromConfigMap in pkg\ddc\juicefs\datasetinfo_parser.go.
fixes #4575 

This PR is to add comments to parseFSInfoFromConfigMap in pkg\ddc\juicefs\datasetinfo_parser.go.

---

pkg/ddc/alluxio/cache.go

Add comments to patchDatasetStatus in pkg\ddc\alluxio\cache.go.
fixes #4577

This PR is to add comments to patchDatasetStatus in pkg\ddc\alluxio\cache.go.

---

pkg/ddc/alluxio/utils_test.go

This PR is to add comments to TestGetMasterStatefulset in pkg/ddc/alluxio/utils_test.go.
fixes #4583

This PR is to add comments to TestGetMasterStatefulset in pkg/ddc/alluxio/utils_test.go.

---

pkg/ddc/alluxio/cache_test.go

Add Notation to TestGetCacheHitStates in pkg/ddc/alluxio/cache_test.go.
fixes https://github.com/fluid-cloudnative/fluid/issues/4534

This PR is to add comments to TestGetCacheHitStates in pkg\ddc\alluxio\cache_test.go.

---

pkg/ddc/alluxio/transform_test.go

This PR is to add comments to TestAlluxioEngine_allocateSinglePort in pkg\ddc\alluxio\transform_test.go.
fixes #4587

This PR is to add comments to TestAlluxioEngine_allocateSinglePort in pkg\ddc\alluxio\transform_test.go.

---

pkg/ddc/alluxio/cache.go

This PR is to add comments to add comments to getCleanCacheGracePeriodSeconds in pkg\ddc\alluxio\cache.go
fixes #4591

This PR is to add comments to add comments to getCleanCacheGracePeriodSeconds in pkg\ddc\alluxio\cache.go

---

pkg/ddc/juicefs/data_process_test.go

This PR is to add comments to TestJuiceFSEngine_generateDataProcessValueFile in pkg/ddc/juicefs/data_process_test.go.
fixes #4594
Check if the comments have explained the function clearly.

This PR is to add comments to TestJuiceFSEngine_generateDataProcessValueFile in pkg/ddc/juicefs/data_process_test.go.

---

pkg/ddc/alluxio/transform_resources_test.go

Add comments to mockAlluxioRuntimeForMaster in pkg/ddc/alluxio/transform_resources_test.go.
fixes #4598 
No need.
No need.

This PR is to add comments to mockAlluxioRuntimeForMaster in pkg/ddc/alluxio/transform_resources_test.go.

---

pkg/ddc/juicefs/delete_volume_test.go

This PR is to add comments to TestJuiceFSEngine_deleteFusePersistentVolume in pkg\ddc\juicefs\delete_volume_test.go.
fixes #4603
Please check if the comments clearly describe the function's purpose and test process.
Any suggestions for better clarity are welcome.

This PR is to add comments to TestJuiceFSEngine_deleteFusePersistentVolume in pkg\ddc\juicefs\delete_volume_test.go.

---

pkg/ddc/jindo/runtime_info_test.go

add comments to TestGetRuntimeInfo in pkg/ddc/jindo/runtime_info_test.go
fixes #4605 

This PR is to add comments to TestGetRuntimeInfo in pkg/ddc/jindo/runtime_info_test.go.

---

pkg/ddc/alluxio/transform_ufs_test.go

This PR is to add comments to TestTransformDatasetToVolume in pkg/ddc/alluxio/transform_ufs_test.go, which could improve the readability of the function by describing its purpose and the steps involved in the test cases
fixes #4611
Ⅲ.Special notes for reviews
Please check if the comments clearly describe the function's purpose. Any suggestions for better clarity is welcome.

This PR is to add comments to TestTransformDatasetToVolume in pkg/ddc/alluxio/transform_ufs_test.go

---

pkg/ddc/alluxio/cache_test.go

Add comments to TestQueryCacheStatus in pkg\ddc\alluxio\cache_test.go.
fixes #4609 

This PR is to add comments to TestQueryCacheStatus in pkg\ddc\alluxio\cache_test.go.

---

pkg/ddc/alluxio/utils_test.go

Add notation to Test_lookUpUsedCapacity in pkg\ddc\alluxio\utils_test.
fixes #4621

This PR is to add comments to Test_lookUpUsedCapacity in pkg\ddc\alluxio\utils_test.

---

pkg/ddc/jindo/runtime_info_test.go

Add comments to newJindoEngineRT in pkg/ddc/jindo/runtime_info_test.go
fixes #4613

This PR is to add comments to newJindoEngineRT in pkg/ddc/jindo/runtime_info_test.go

---

pkg/ddc/jindo/master_internal_test.go

Add comments to TestGenerateJindoValueFile in /pkg/ddc/jindo/master_internal_test.go.
fixes #4629

This PR is to add comments to TestGenerateJindoValueFile in /pkg/ddc/jindo/master_internal_test.go.

---

pkg/ddc/jindo/delete_volume_test.go

This PR is to add commentsto TestJindoEngine_DeleteFusePersistentVolumeClaim in pkg\ddc\jindo\delete_volume_test.go
fixes #4631
nothing more

This PR is to add commentsto TestJindoEngine_DeleteFusePersistentVolumeClaim in pkg\ddc\jindo\delete_volume_test.go

---

pkg/ddc/alluxio/utils_test.go

Ⅰ. Describe what this PR does？
Add notation to TestGetFuseDaemonsetName in pkg\ddc\alluxio\utils_test.go
fixes #4645

This PR is to add comments to TestGetFuseDaemonsetName in pkg\ddc\alluxio\utils_test.go.

---

pkg/ddc/alluxio/metadata_test.go

Add comments to TestShouldSyncMetadata in pkg\ddc\alluxio\metadata_test.go.
fixes #4649

Add comments to TestShouldSyncMetadata in pkg\ddc\alluxio\metadata_test.go

---

pkg/ddc/alluxio/metadata_test.go

Add comments to the function TestShouldRestoreMetadata.
fixes #4658
No tests are needed, as I just added a comment.
None.
None.

Add comments to TestShouldRestoreMetadata in pkg\ddc\alluxio\metadata_test.go

---

pkg/ddc/alluxio/utils_test.go

Add comments to Test_isPortInUsed in pkg\ddc\alluxio\utils_test.go.
fixes #4687

This PR is to add comments to Test_isPortInUsed  in pkg\ddc\alluxio\utils_test.go.

---

pkg/ddc/alluxio/load_data_test.go

this PR add comments to TestCheckRuntimeReady in pkg/ddc/alluxio/load_data_test.go
fixes #4696 

This PR is to add comments to TestCheckRuntimeReady in pkg/ddc/alluxio/load_data_test.go

---

pkg/ddc/alluxio/ufs_test.go

This PR is to add comments to TestPrepareUFS in pkg/ddc/alluxio/ufs_test.go.
fixes #4698

This PR is to add comments to TestPrepareUFS in pkg/ddc/alluxio/ufs_test.go.

---

pkg/ddc/alluxio/transform_optimization_test.go

Add comments to TestOptimizeDefaultForWorkerNoValue in pkg\ddc\alluxio\transform_optimization_test.go
fixes #4712

This PR is to add comments to TestOptimizeDefaultForWorkerNoValue in pkg\ddc\alluxio\transform_optimization_test.go

---

pkg/ddc/alluxio/transform_test.go

….go.
Add comments to TestTransformMaster in pkg\ddc\alluxio\transform_test.go.
fixes #4714

This PR is to add comments to TestTransformMaster in pkg\ddc\alluxio\transform_test.go.

---

pkg/ddc/alluxio/cache.go

Add comments to getGracefulShutdownLimits in pkg/ddc/alluxio/cache.go.
fixes #4651 
None

This PR is to add comments to getGracefulShutdownLimits in pkg/ddc/alluxio/cache.go

---

pkg/ddc/juicefs/master_internal_test.go

Annotated the TestSetupMasterInternal function with AI.
fixes #4768 
NONE
Just some annotation so no need to verify.
It's just a PR for homework of course NJU BigData (NJU 大数据综合处理实验).

Annotated the TestSetupMasterInternal function with AI.

---

pkg/ddc/juicefs/datasetinfo_parser.go

Ⅰ. Describe what this PR does  
This PR adds a function `GetFSInfoFromConfigMap` to retrieve file system information from a specified ConfigMap. It fetches the ConfigMap based on the given name and namespace, then parses and returns the relevant file system details.  
Ⅱ. Does this pull request fix one issue?  
Fixes #4736 
Ⅲ. Special notes for reviews  
- Ensure that the ConfigMap naming convention aligns with existing standards.  
- Verify error handling when the ConfigMap is missing or contains unexpected data.  
- Check if additional validation is needed for the parsed information.

This PR is to add comments to GetFSInfoFromConfigMap in pkg\ddc\juicefs\datasetinfo_parser.go.

---

pkg/ddc/alluxio/utils_test.go

Add Notation to TestGetRuntime in pkg/ddc/alluxio/utils_test.go
fixes #4744

This PR is to add comments to TestGetRuntime in pkg/ddc/alluxio/utils_test.go.

---

pkg/ddc/jindo/node_test.go

This PR is to add comments to getTestJindoEngineNode in pkg/ddc/jindo/node_test.go.

---

pkg/ddc/alluxio/utils_test.go

Add comments to TestGetMountPoint in pkg/ddc/alluxio/utils_test.go.
fixes #4690

This PR is to add comments to TestGetMountPoint in pkg/ddc/alluxio/utils_test.go.

---

.circleci/config.yml
.github/workflows/kind-e2e.yml
.github/workflows/project-check.yml
.travis.yml
docker/Dockerfile.alluxioruntime
docker/Dockerfile.application
docker/Dockerfile.csi
docker/Dockerfile.dataset
docker/Dockerfile.efcruntime
docker/Dockerfile.goosefsruntime
docker/Dockerfile.jindoruntime
docker/Dockerfile.juicefsruntime
docker/Dockerfile.thinruntime
docker/Dockerfile.vineyardruntime
docker/Dockerfile.webhook

Upgrade golang 1.23.7

---

pkg/application/inject/fuse/injector.go
pkg/application/inject/fuse/mutator/mutator.go
pkg/common/constants.go
pkg/common/label.go
pkg/common/types.go
pkg/ctrl/watch/pod.go
pkg/utils/annotations.go
pkg/utils/annotations_test.go
pkg/utils/map.go
pkg/utils/map_test.go
pkg/utils/utils_suite_test.go

Currently, Fluid webhook gets serverless platform from a specific label in Pod's metadata. The label's key is set by a env variable called `KEY_SERVERLESS_PLATFORM`. This is not a great design because each time when we add a new serverless platform, we also need to change the Webhook's `MutatingWebhookConfiguration` to register the webhook with a matched `objectSelector`. This makes `MutatingWebhookConfiguration` longer.
This PR refactors the logic about getting serverless platform. Fluid webhook now looks at the Pod's annotation to see if there's an special annotation called `serverless.fluid.io/platform`. 
Other changes this PR made:
- clean and refactor some unused code
- deprecate `ServerlessPlatformKey` which is defined from a env variable. 
NONE

refactor: fuse sidecar serverless platform

---

pkg/ddc/thin/transform_fuse.go
pkg/ddc/thin/transform_fuse_test.go
pkg/ddc/thin/type.go

During testing, it was discovered that even though `thinruntime.spec.fuse.networkMode` and `thinruntimeprofile.spec.fuse.networkMode` were configured with containerNetwork, the created Fuse Daemonset Pod still used HostNetwork. Upon investigation, two issues were identified:
1. hostNetwork is a boolean value and was set with omitempty, which results in hostNetwork being ignored as an empty value even when set to false after transformation. In this PR, the omitempty attribute of hostNetwork has been removed.
2. The transformation process first checks the network mode of fuse from the profile and then from thinruntime, with the configuration in thinruntime having a higher priority. The current implementation defaults hostNetwork to false if not set in thinruntime, which directly overwrites …

Fix that containerNetwork config is not effected in Thinruntime

---

pkg/ddc/alluxio/create_volume_test.go

This PR is to add comments to TestCreateVolume in pkg\ddc\alluxio\create_volume_test.go.
fixes https://github.com/fluid-cloudnative/fluid/issues/4678

 This PR is to add comments to TestCreateVolume in pkg\ddc\alluxio\create_volume_test.go. 

---

pkg/ddc/juicefs/datasetinfo_parser_test.go

This PR is to add comments to TestGetFSInfoFromConfigMap in pkg/ddc/juicefs/datasetinfo_parser_test.go
fixes #4633 

This PR is to add comments to TestGetFSInfoFromConfigMap in pkg/ddc/juicefs/datasetinfo_parser_test.go

---

pkg/ddc/juicefs/datasetinfo_parser_test.go
samples/hdfs/pom.xml

Update alluxio jar version to 2.9.4

---

pkg/ddc/alluxio/transform_test.go

This PR is to add comments to TestGetMediumTypeFromVolumeSource in pkg/ddc/alluxio/transform_test.go 
fixes #4527
Ⅲ Special notes for reviews
nothing.

This PR is to add comments to TestGetMediumTypeFromVolumeSource in pkg/ddc/alluxio/transform_test.go 

---

Makefile
docker/Dockerfile.alluxioruntime
docker/Dockerfile.application
docker/Dockerfile.crds
docker/Dockerfile.csi
docker/Dockerfile.dataset
docker/Dockerfile.efcruntime
docker/Dockerfile.goosefsruntime
docker/Dockerfile.jindoruntime
docker/Dockerfile.juicefsruntime
docker/Dockerfile.thinruntime
docker/Dockerfile.vineyardruntime
docker/Dockerfile.webhook

Update dependency version:
1. helm 3.11.3 -> 3.17.3: https://github.com/helm/helm/releases/tag/v3.17.3
" Helm v3.17.3 is a security (patch) release. Users are strongly recommended to update to this release. "
2. alpine base image: 3.18 -> 3.19.1: https://github.com/alpinelinux/docker-alpine/issues/384

fix security issue in current helm and alpine version

---

pkg/ddc/alluxio/transform_test.go

This PR is to add comments to TestTransformShortCircuit in pkg\ddc\alluxio\transform_test.go.
fixes Add comments/notation to TestTransformShortCircuit in pkg\ddc\alluxio\transform_test.go.#4585
update to English

This PR is to add comments to TestTransformShortCircuit in pkg\ddc\alluxio\transform_test.go.

---

pkg/ddc/alluxio/delete_volume_test.go

Add Notation to TestAlluxioEngine_DeleteFusePersistentVolumeClaim in pkg/ddc/alluxio/delete_volume_test.go.
fixes #4872

This PR is to add comments to TestAlluxioEngine_DeleteFusePersistentVolumeClaim in pkg/ddc/alluxio/delete_volume_test.go.

---

pkg/ddc/alluxio/ufs_test.go

This PR is to add comments to TestGenUFSMountOptionsMultiTimes in pkg/ddc/alluxio/ufs_test.go.
fixes #4866

This PR is to add comments to TestGenUFSMountOptionsMultiTimes in pkg/ddc/alluxio/ufs_test.go.

---

pkg/ddc/juicefs/data_migrate_test.go

This PR is to add comments to Test_addWorkerPodAntiAffinity in pkg/ddc/juicefs/data_migrate_test.go
fixes #4862 

This PR is to add comments to Test_addWorkerPodAntiAffinity in pkg/ddc/juicefs/data_migrate_test.go

---

pkg/ddc/alluxio/transform_resources_test.go

…pkg/ddc/alluxio/transform_resources_test.go.
This PR is to add comments to TestTransformResourcesForWorkerWithValue in pkg/ddc/alluxio/transform_resources_test.go.
fixes #4867

This PR is to add comments to TestTransformResourcesForWorkerWithValue in pkg/ddc/alluxio/transform_resources_test.go.

---

pkg/ddc/goosefs/master.go

1. Describe what this PR does
Add comments to SetupMaster in pkg\ddc\goosefs\master.go.
2. Does this pull request fix one issue?
fixes #4879 
3. Special notes for reviews

This PR is to add comments to SetupMaster in pkg\ddc\goosefs\master.go.

---

pkg/ddc/alluxio/utils_test.go

…tils_test.go.
This PR is to add comments to TestAlluxioEngine_getInitUserDir in pkg\ddc\alluxio\utils_test.go
fixes #4885

This PR is to add comments to TestAlluxioEngine_getInitUserDir in pkg\ddc\alluxio\utils_test.go

---

pkg/ddc/goosefs/health_check.go

This PR is to add comments to checkMasterHealthy in pkg/ddc/goosefs/health_check.go
fixes #4881

This PR is to add comments to checkMasterHealthy in pkg/ddc/goosefs/health_check.go

---

pkg/ddc/thin/shutdown.go

Ensure resources exit before performing deletion

---

pkg/ddc/juicefs/sync_runtime.go
pkg/ddc/juicefs/sync_runtime_test.go
pkg/ddc/juicefs/utils.go

Fix unexpected update in juiceruntime

---

pkg/ddc/alluxio/ufs_test.go

add comments to TestCheckIfRemountRequired(t *testing.T) in pkg\ddc\alluxio\ufs_test.go.
fixes #4894
Bigdata

This PR is to add comments to TestCheckIfRemountRequired(t *testing.T) in pkg\ddc\alluxio\ufs_test.go.

---

pkg/ddc/alluxio/ufs_test.go

add comments to TestGenUFSMountOptions in pkg/ddc/alluxio/ufs_test.go
fixes #4850

This PR is to add comments to TestGenUFSMountOptions in pkg/ddc/alluxio/ufs_test.go

---

pkg/ddc/alluxio/ufs_test.go

Add comments to TestGenUFSMountOptionsWithDuplicatedKey in pkg\ddc\alluxio\ufs_test.go
fixes #4653

This PR is to add comments to TestGenUFSMountOptionsWithDuplicatedKey in pkg\ddc\alluxio\ufs_test.go

---

pkg/ddc/alluxio/ufs_test.go

Add Notation to TestUsedStorageBytes in pkg/ddc/alluxio/ufs_test.go
fixes #4943

This PR is to add comments to TestUsedStorageBytes in pkg/ddc/alluxio/ufs_test.go.

---

pkg/ddc/alluxio/metadata_test.go

add comments to TestSyncMetadataInternal in pkg\ddc\alluxio\metadata_test.g
fixes #4836

This PR is to add comments to TestSyncMetadataInternal in pkg\ddc\alluxio\metadata_test.go

---

pkg/ddc/juicefs/dataset_test.go

This PR is to add notation to TestUpdateDatasetStatus in pkg\ddc\juicefs\dataset_test.go
fixes #4791

This PR is to add notation to TestUpdateDatasetStatus in pkg\ddc\juicefs\dataset_test.go

---

pkg/ddc/jindo/create_volume_test.go

to add comments to TestCreateFusePersistentVolume in pkg/ddc/jindo/create_volume_test.go
fixes #4957

This PR is to add comments to TestCreateFusePersistentVolume in pkg/ddc/jindo/create_volume_test.go

---

pkg/ddc/alluxio/utils_test.go

Add Notation to TestIsFluidNativeScheme in pkg/ddc/alluxio/utils_test.go
// TestIsFluidNativeScheme tests whether the IsFluidNativeScheme function correctly identifies Fluid native schemes.
//
// Parameters:
// - t (*testing.T): Testing context object from Go test framework
//
// Returns:
// - No return value; reports test failures through t.Errorf
fixes #5007

This PR is to Add Notation to TestIsFluidNativeScheme in pkg/ddc/alluxio/utils_test.go

---

pkg/ddc/alluxio/transform_optimization_test.go

This PR adds detailed comments to the function TestOptimizeDefaultForFuseWithArgs(t *testing.T) located in pkg/ddc/alluxio/transform_optimization_test.go. The comments clarify the purpose of the test, key logic steps, and expected outcomes to improve code readability and maintainability.
fixes #4703
PR submitted by molihh.
Focus review on:
1.Clarity and accuracy of the added comments.
2.Whether the comments align with the test logic and cover critical aspects.
3.Suggestions for further improvements to the comments or test logic.

This PR is to add comments to TestOptimizeDefaultForFuseWithArgs(t *testing.T) in pkg\ddc\alluxio\transform_optimization_test.go.

---

pkg/ddc/alluxio/master_test.go

Add comments to the `TestCheckMasterReady` function in `pkg/ddc/alluxio/master_test.go`.
fixes #1
No new test cases added. This PR only adds code comments.
Check the comments above the `TestCheckMasterReady` function to ensure they are clear, accurate, and correctly placed before the function.
None.

This PR is to add comments to TestCheckMasterReady in pkg/ddc/alluxio/master_test.go

---

pkg/ddc/alluxio/health_check_test.go

Add comments to TestCheckRuntimeHealthy in pkg/ddc/alluxio/health_check_test.go
fixes #4927

This PR is to add comments to TestCheckRuntimeHealthy in pkg/ddc/alluxio/health_check_test.go.

---

.github/workflows/codeql-analysis.yml
.github/workflows/kind-e2e.yml
.github/workflows/project-check.yml
.github/workflows/sonarcloud.yaml

Add pinned GithubAction

---

.github/workflows/kind-e2e.yml
.github/workflows/project-check.yml
addons/cubefs/v2.4/docker/Dockerfile
addons/cubefs/v3.2/docker/Dockerfile
addons/dynamic-mount/base/Dockerfile
addons/dynamic-mount/juicefs/docker/Dockerfile.juicefs
addons/nfs/docker/Dockerfile
charts/alluxio/docker/init-users/Dockerfile
charts/goosefs/docker/init-users/Dockerfile
samples/knative/docker/Dockerfile
samples/vineyard/Dockerfile
tools/file-prefetcher/Dockerfile

Support pinned dependencies

---

pkg/ddc/alluxio/hcfs_test.go

add notation to this function.
fixes #4920

This PR is to add comments to newAlluxioEngineHCFS in pkg\ddc\alluxio\hcfs_test.go

---

pkg/ddc/goosefs/health_check.go

This PR is to add notation to checkWorkersHealthy in pkg\ddc\goosefs\health_check.go
fixes #5087

This PR is to add notation to checkWorkersHealthy in pkg\ddc\goosefs\health_check.go

---

pkg/ddc/alluxio/cache_test.go

…pkg\ddc\alluxio\cache_test.go.
This PR is to add comments to TestAlluxioEngine_getCleanCacheGracePeriodSeconds in pkg\ddc\alluxio\cache_test.go.
fixes #5145

This PR is to add comments to TestAlluxioEngine_getCleanCacheGracePeriodSeconds in pkg\ddc\alluxio\cache_test.go.

---

pkg/utils/validation/validation_test.go

Add fuzz test

---

pkg/ddc/alluxio/utils_test.go

add comments to TestGetDaemonset in pkg\ddc\alluxio\utils_test.go.
fixes #4955

This PR is to add comments to TestGetDaemonset in pkg\ddc\alluxio\utils_test.go.

---

pkg/ddc/goosefs/deprecated_label.go

I. Describe what this PR does
```
// HasDeprecatedCommonLabelname checks whether the deprecated common label name exists.
// This method retrieves the DaemonSet's NodeSelector and determines if it contains the deprecated label name.
//
// Returns:
//
//	deprecated: true if the deprecated common label name exists, otherwise false.
//	err: error information if any error occurs during execution.
```
II. Does this pull request fix one issue?
fixes #5092
III. Special notes for reviews

This PR is to add comments to HasDeprecatedCommonLabelname in pkg/ddc/goosefs/deprecated_label.go.

---

Makefile
docker/Dockerfile.alluxioruntime
docker/Dockerfile.application
docker/Dockerfile.dataset
docker/Dockerfile.efcruntime
docker/Dockerfile.goosefsruntime
docker/Dockerfile.jindoruntime
docker/Dockerfile.juicefsruntime
docker/Dockerfile.thinruntime
docker/Dockerfile.vineyardruntime

In Fluid, there is only a unique version of runtime when deploying through Helm. Therefore, this PR import self-maintainerd ddc-helm and optimize the logic for confirming the version by listing release configmaps during helm install/uninstall to use the get method to retrieve version 1. This reduces the pressure of list operations on the apiserver.

import self-maintainerd ddc-helm in dockerfile

---

pkg/utils/helm/utils.go

A follow-up optimization of #5164 
NONE

enhance: optimize helm status efficiency

---

api/v1alpha1/openapi_generated.go
api/v1alpha1/thinruntime_types.go
charts/fluid/fluid/crds/data.fluid.io_thinruntimeprofiles.yaml
charts/fluid/fluid/crds/data.fluid.io_thinruntimes.yaml
charts/thin/templates/fuse/daemonset.yaml
config/crd/bases/data.fluid.io_thinruntimeprofiles.yaml
config/crd/bases/data.fluid.io_thinruntimes.yaml
pkg/ddc/thin/transform_fuse.go
pkg/ddc/thin/transform_fuse_test.go
pkg/ddc/thin/type.go

```
kind: ThinRuntimeProfile
metadata:
name: demo-profile
spec:
fileSystemType: ossfs
fuse:
image: demo-image
imageTag: demo-tag
lifecycle:
preStop:
exec:
command: [ "sh", "-c", "/script/unmount.sh" ]
imagePullPolicy: IfNotPresent
command:
- tini
- -g
- --
- /usr/local/bin/entrypoint.sh
```

Feature: support custom lifecycle configuration in thinruntimeprofile

---

pkg/ddc/alluxio/cache_test.go

Adds descriptive comments to the TestPatchDatasetStatus function in pkg/ddc/alluxio/cache_test.go.
The comment explains the purpose and logic of the unit test, which validates the calculation of cached data percentage in a dataset.
fixes #5057 
No new test cases are added.
This PR only adds comments to an existing unit test function. The logic and behavior of the code remain unchanged.
Since this PR only adds comments, no additional verification is required.
This is a documentation-only change.

This PR is to add comments to TestPatchDatasetStatus in pkg\ddc\alluxio\cache_test.go.

---

pkg/ddc/juicefs/cache_test.go

…/cache_test.go
Add Notation to TestJuiceFSEngine_queryCacheStatus in pkg/ddc/juicefs/cache_test.go.
fixes #5084

This PR is to add comments to TestJuiceFSEngine_queryCacheStatus in pkg/ddc/juicefs/cache_test.go.

---

cmd/webhook/app/webhook.go
pkg/application/inject/fuse/injector_runtime_test.go
pkg/application/inject/fuse/injector_test.go
pkg/common/webhook.go
pkg/ddc/alluxio/cache_test.go
pkg/ddc/alluxio/shutdown_test.go
pkg/ddc/alluxio/status_test.go
pkg/ddc/base/runtime.go
pkg/ddc/base/runtime_helper.go
pkg/ddc/base/runtime_helper_test.go
pkg/ddc/base/runtime_test.go
pkg/ddc/goosefs/cache_test.go
pkg/ddc/goosefs/shutdown_test.go
pkg/ddc/goosefs/status_test.go
pkg/ddc/jindo/cache_test.go
pkg/ddc/jindocache/cache_test.go
pkg/ddc/jindofsx/cache_test.go
pkg/utils/dataset.go
pkg/utils/kubeclient/daemonset.go
pkg/utils/runtimes.go
pkg/webhook/handler/mutating/mutating_handler.go
pkg/webhook/handler/mutating/mutating_handler_test.go
pkg/webhook/handler/register.go
pkg/webhook/plugins/fusesidecar/fuse_sidecar.go
pkg/webhook/utils/errors.go
pkg/webhook/utils/runtime_info.go

In the current webhook design, to avoid generating excessive API requests to the apiserver, a `cacheClient` implementation is used in the webhook. However, under heavy load on the apiserver or communication link issues, this can lead to delays in resource status updates within the webhook, causing problems such as state verification failures or resource retrieval failures. This PR introduces new error types for errors returned during the mutation process. For errors of this type, the webhook will use a direct client connection to the apiserver for retries.

Enhancement: support to retry by apireader client in webhook

---

pkg/ctrl/fuse.go
pkg/ctrl/master.go
pkg/ctrl/worker.go
pkg/utils/kubeclient/daemonset.go
pkg/utils/kubeclient/statefulset.go
pkg/utils/kubeclient/statefulset_test.go

Even with a label selector, pod listing can be a very heavy operation when there are a lot of pods in the Kubernetes cluster. 
The PR removes some unnecessary pod listing in the following functions:
- `func CheckMasterHealthy` in `pkg/ctrl/master.go`
- `func CheckWorkerHealthy` in `pkg/ctrl/worker.go`
-  `func CheckFuseHealthy` in `pkg/ctrl/fuse.go`
fixes #XXXX

refactor: remove "getting unavailable pods" code logic to avoid heavy pod listing

---

pkg/ddc/juicefs/sync_runtime_test.go

fix flaky unit tests in JuiceFSEngine.checkAndSetFuseChanges. Iterating `map` is flaky, so this PR removes EXPECT assertions using specific index (e.g. VolumeMounts[2], Env[2]) to avoid flaky unit tests. 
fixes #XXXX

minorfix: fix flaky unit tests in JuiceFSEngine.checkAndSetFuseChanges

---

dashboard/fluid-ks-extension/extensions/fluid/src/pages/datasets/components/CreateDatasetModal/components/BasicInfoStep.tsx
dashboard/fluid-ks-extension/extensions/fluid/src/pages/datasets/components/CreateDatasetModal/components/DataLoadStep.tsx
dashboard/fluid-ks-extension/extensions/fluid/src/pages/datasets/components/CreateDatasetModal/components/DataSourceStep/DataSourceStep.tsx
dashboard/fluid-ks-extension/extensions/fluid/src/pages/datasets/components/CreateDatasetModal/components/DataSourceStep/components/AddMountButton.tsx
dashboard/fluid-ks-extension/extensions/fluid/src/pages/datasets/components/CreateDatasetModal/components/DataSourceStep/components/EncryptOptionsInput.tsx
dashboard/fluid-ks-extension/extensions/fluid/src/pages/datasets/components/CreateDatasetModal/components/DataSourceStep/components/MountItem.tsx
dashboard/fluid-ks-extension/extensions/fluid/src/pages/datasets/components/CreateDatasetModal/components/DataSourceStep/styles.ts
dashboard/fluid-ks-extension/extensions/fluid/src/pages/datasets/components/CreateDatasetModal/components/DataSourceStep/types.ts
dashboard/fluid-ks-extension/extensions/fluid/src/pages/datasets/components/CreateDatasetModal/components/DataSourceStep/utils.ts
dashboard/fluid-ks-extension/extensions/fluid/src/pages/datasets/components/CreateDatasetModal/components/RuntimeStep.tsx
dashboard/fluid-ks-extension/extensions/fluid/src/pages/datasets/components/CreateDatasetModal/components/StepIndicator.tsx
dashboard/fluid-ks-extension/extensions/fluid/src/pages/datasets/components/CreateDatasetModal/components/YamlEditor.tsx
dashboard/fluid-ks-extension/extensions/fluid/src/pages/datasets/components/CreateDatasetModal/index.tsx
dashboard/fluid-ks-extension/extensions/fluid/src/pages/datasets/components/CreateDatasetModal/types.ts
dashboard/fluid-ks-extension/extensions/fluid/src/pages/datasets/detail/Events/index.tsx
dashboard/fluid-ks-extension/extensions/fluid/src/pages/datasets/detail/Metadata/index.tsx
dashboard/fluid-ks-extension/extensions/fluid/src/pages/datasets/detail/ResourceStatus/index.tsx
dashboard/fluid-ks-extension/extensions/fluid/src/pages/datasets/detail/index.tsx
dashboard/fluid-ks-extension/extensions/fluid/src/pages/datasets/detail/routes.tsx
dashboard/fluid-ks-extension/extensions/fluid/src/pages/datasets/list/index.tsx
dashboard/fluid-ks-extension/extensions/fluid/src/pages/shared/components/ResourceStatusStyles.tsx

Prerequisite: Please merge the PR #5250  first.
This PR migrates dataset-related pages and logic, including:
- Migrating all contents under the pages/datasets/ directory (including components/, detail/, list/, etc.)
- Migrating shared directory that is the common style of the data set, data loading, and runtime for their detail page resource status TAB page
The change only affects dataset-related pages and functionalities.
NONE
No new test cases are added in this PR. The verification will focus on the normal rendering of dataset-related pages and the availability of core functionalities (create, view, delete), which can be validated through manual testing as described in the verification steps.
1. Ensure this PR has been merged successfully
2. Make sure you have KubeSphere version 4 …

feat(dashboard-ks-extension): migrate dataset-related pages and logic

---

dashboard/fluid-ks-extension/extensions/fluid/src/pages/runtimes/detail/Events/index.tsx
dashboard/fluid-ks-extension/extensions/fluid/src/pages/runtimes/detail/Metadata/index.tsx
dashboard/fluid-ks-extension/extensions/fluid/src/pages/runtimes/detail/ResourceStatus/index.tsx
dashboard/fluid-ks-extension/extensions/fluid/src/pages/runtimes/detail/index.tsx
dashboard/fluid-ks-extension/extensions/fluid/src/pages/runtimes/detail/routes.tsx
dashboard/fluid-ks-extension/extensions/fluid/src/pages/runtimes/list/index.tsx
dashboard/fluid-ks-extension/extensions/fluid/src/pages/runtimes/runtimeMap.ts

Prerequisite: Please merge the PR #5252  first.
This PR migrates runtime-related pages and logic, specifically:
- Migrating all contents under the pages/runtimes/ directory
The change only affects runtime-related pages and functionalities.
NONE
No new test cases are added in this PR. The verification will focus on the normal rendering of runtime-related pages and the availability of core functionalities (view details, navigate to Workload interface, scale operations), which can be validated through manual testing as described in the verification steps.
1. Add the necessary labels to all runtime CRDS
```bash
kubectl patch crd alluxioruntimes.data.fluid.io --patch '{"metadata":{"labels":{"kubesphere.io/resource-served": "true"}}}'
```
2. Run `yarn dev` to start the application
3. Since …

feat(dashboard-ks-extension): migrate runtime-related pages and logic
