fluid-cloudnative/fluid

pkg/ddc/goosefs/operations/base_test.go

add license to pkg/ddc/goosefs/operations/base_test.go

---

pkg/ddc/jindo/transform_test.go

Signed-off-by: changanyyy <1263522794@qq.com>
This pr is to add copyright information at pkg/ddc/jindo/transform_test.go

description 在transform_test.go添加了copyright信息

---

pkg/ddc/goosefs/create_volume_test.go

Signed-off-by: salty-Frankenstein <1328955419@qq.com>
This pr is to add license to `pkg/ddc/goosefs/create_volume_test.go`.

add license

---

pkg/ddc/jindo/transform_fuse_test.go

This pr is to add license to pkg/ddc/jindo/transform_fuse_test.go

This pr is to add license to pkg/ddc/jindo/transform_fuse_test.go

---

pkg/ddc/base/engine.go

Signed-off-by: haibara4869 <haibara1110@qq.com>
This pr is to update license in engine.go

update license in engine.go

---

pkg/ddc/goosefs/master_internal.go

Signed-off-by: Curat-D <ds.curat@gmail.com>

modified master_internal.go

---

pkg/ddc/goosefs/ufs_test.go

Signed-off-by: Cindyxin228 <1364195528@qq.com>
This pr is to add normalized license information.

normalize_license_info

---

pkg/ddc/base/load_data.go

Signed-off-by: PPYSC <ppysc1115204116@gmail.com>
This pr is to add Copyright information to pkg/ddc/base/load_data.go

Add Copyright infomation

---

docs/zh/samples/knative.md
samples/knative/docker/entrypoint.sh

Fix knative sample doc when using volatile web ufs

Fix knative sample doc when using volatile web ufs

---

pkg/ddc/goosefs/operations/cached_test.go

This PR is to nomalized License

---

pkg/ddc/goosefs/delete_volume_test.go

Signed-off-by: RainTreeCrow <1683762615@qq.com>

add copyright and apache license declaration to delete volume test

---

pkg/ddc/goosefs/engine.go

This pr is to add normalized license information.

Normalize this file LICENSE information

---

pkg/ddc/jindo/worker_test.go

Signed-off-by: 不知吟 <2659428453@qq.com>
Ⅰ. This pr is to Normalize the license information in the header of file pkg/ddc/jindo/worker_test.go

add Apache License to pkg/ddc/jindo/worker_test.go

---

.circleci/config.yml
docker/Dockerfile.alluxioruntime
docker/Dockerfile.application
docker/Dockerfile.csi
docker/Dockerfile.dataset
docker/Dockerfile.goosefsruntime
docker/Dockerfile.jindoruntime
docker/Dockerfile.juicefsruntime
docker/Dockerfile.webhook

Upgrade golang to 1.17

---

charts/fluid/fluid/Chart.yaml
charts/fluid/fluid/values.yaml

Build docker image for juice enterprise

---

pkg/ddc/goosefs/health_check_test.go

This pr is to add copyright in file pkg/ddc/goosefs/health_check_test.go

添加License信息

---

pkg/ddc/goosefs/node_test.go

Signed-off-by: Richard Wang <ricky9wang@gmail.com>
Added License information for pkg/ddc/goosefs/node_test.go

Add License Info

---

pkg/ddc/base/syncs.go

Signed-off-by: RX580ZZZ <RX580ZZZ@outlook.com>

This pr is to Add Apache License to pkg/ddc/base/syncs.go

---

pkg/ddc/jindo/engine.go

Signed-off-by: zzx-c <1691190912@qq.com>
add copyright to pkg/ddc/jindo/engine.go

add copyright to pkg/ddc/jindo/engine.go

---

pkg/ddc/base/label.go

I.This pr is to add copyright in file pkg/ddc/base/label.go

---

pkg/ddc/jindo/label.go

This pr is to add Apache License to pkg/ddc/jindo/label.go

add Apache License to pkg/ddc/jindo/label.go

---

pkg/ddc/goosefs/transform.go

Signed-off-by: 0030gz <80144861+0030gz@users.noreply.github.com>
Add Apache License at pkg/ddc/goosefs/transform.go

Add Apache License

---

pkg/ddc/jindo/operations/base.go

Signed-off-by: kiaye <1361994617@qq.com>
Add Apache License notice statement at pkg/ddc/jindo/operations/base.go
NONE
Didn't add any test cases.
Just take a look. 
None

Add Apache License notice statement

---

pkg/ddc/goosefs/master_internal_test.go

Signed-off-by: wwz0504 <1370211850@qq.com>

This pr is to modify master_internal_test.go with adding Copyright

---

pkg/ddc/goosefs/transform_api_gateway.go

Signed-off-by: SilenceXjh <1816036457@qq.com>
This pr is to add license for pkg/ddc/goosefs/transform_api_gateway.go.

add license for transform_api_gateway.go

---

pkg/ddc/goosefs/master_internal.go

Signed-off-by: Curat-D <ds.curat@gmail.com>

This pr is to add Copyright in master_internal.go

---

pkg/ddc/base/template_engine.go

Signed-off-by: Crowyah <1442638392@qq.com>
This pr is to add Copyright

This pr is to add Copyright

---

pkg/ddc/goosefs/transform_test.go

Signed-off-by: Zmzm <191220163@smail.nju.edu.cn>

Standardize the notice statement and add Copyright

---

pkg/ddc/jindo/shutdown.go

Signed-off-by: chenyuan <784740115@qq.com>
This PR is to add Apache License to pkg/ddc/jindo/shutdown.go

add_shutdown

---

pkg/ddc/goosefs/metadata.go

Signed-off-by: KW-NJU <191220109@smail.nju.edu.cn>
Add license to metadata.go.

add_license_to_metadata.go

---

pkg/ddc/goosefs/hcfs_test.go

Signed-off-by: gravity-hole <1446234602@qq.com>
This PR is to add copyright license

add copyright license

---

docs/en/samples/juicefs_runtime.md
docs/zh/samples/juicefs_runtime.md

fix https://github.com/fluid-cloudnative/fluid/issues/1723

add doc for juicefs cloud service edition

---

pkg/ddc/jindo/node_test.go

Signed-off-by: 梁天润 <905641425@qq.com>
This pr is to add License info to pkg/ddc/jindo/node_test.go

This pr is to add License info to pkg/ddc/jindo/node_test.go

---

pkg/ddc/jindo/utils.go

Signed-off-by: neo <840364310@qq.com>
This pr is to add Apache License information in pkg/ddc/jindo/utils.go

Add Apache License in pkg/ddc/jindo/utils.go

---

pkg/ddc/jindo/status.go

Signed-off-by: Xutangzhi <1293815069@qq.com>
This pr is to add a comment to pkg/ddc/jindo/status.go

add a comment

---

pkg/ddc/goosefs/master.go

this pr is to modify the Apache License in pkg/ddc/goosefs/master.go

a little modification

---

pkg/ddc/base/runtime.go

add Copyright to pkg/ddc/base/runtime.go

task-82:add Copyright

---

pkg/ddc/goosefs/master_test.go

Signed-off-by: tianzhe <181240051@smail.nju.edu.cn>
This pr is to add Apache License in pkg/ddc/goosefs/master_test.go

add apache in task3

---

pkg/ddc/goosefs/create_volume.go

Signed-off-by: AvAOfficial <1823552982@qq.com>

This pr is to add task33

---

pkg/ddc/jindo/transform_master_test.go

Signed-off-by:  姜泓林 <72690456+KCCOAK12@users.noreply.github.com>
Standardized the license of pkg/ddc/jindo/transform_master_test.go
"NONE"

Standardized the license of pkg/ddc/jindo/transform_master_test.go

---

pkg/ddc/alluxio/status.go

Signed-off-by: Night-Hunters <2501087332@qq.com>

This pr is to add the Copyright line to status.go

---

pkg/ddc/jindo/transform.go

This pr is to add apache license on pkg/ddc/jindo/transform.go

add license on pkg/ddc/jindo/transform.go

---

pkg/ddc/jindo/delete_volume.go

Signed-off-by: stfklav <stfklav@163.com>
This pr is to add Apache License to file 'pkg/ddc/jindo/delete_volume.go'

Modify pkg/ddc/jindo/delete_volume.go

---

pkg/ddc/goosefs/operations/local_test.go

Signed-off-by: Nagisa <1243512162@qq.com>

191220123 PR

---

pkg/ddc/jindo/master_internal.go

Signed-off-by: gequanyu <2322337235@qq.com>
This PR is to add license information

This PR is to add license information

---

pkg/ddc/goosefs/operations/conf.go

Signed-off-by: WangYuqiao-JOJO <943737352@qq.com>
fixes #1746

This pr is to add year information

---

pkg/ddc/goosefs/label.go

Signed-off-by: Laurel-Canyon <2847262244@qq.com>
fixes #1747

Add Copyright to pkg/ddc/goosefs/label.go

---

charts/fluid/fluid/Chart.yaml
charts/fluid/fluid/values.yaml
docker/Dockerfile.application
docker/Dockerfile.csi
docker/Dockerfile.dataset
docker/Dockerfile.goosefsruntime
docker/Dockerfile.jindoruntime
docker/Dockerfile.juicefsruntime
docker/Dockerfile.webhook
pkg/ddc/jindo/const.go

Fix dlv issue

---

pkg/ddc/goosefs/port_parser.go

Signed-off-by: lszxb <lszxbgeek@outlook.com>
This pr is to add copyright information to file `pkg/ddc/goosefs/port_parser.go`.

add copyright information to file pkg/ddc/goosefs/port_parser.go

---

pkg/ddc/jindo/transform_hadoop_config.go

Signed-off-by: Oltremarer <1090546584@qq.com>
This pr is to add liscence information to pkg/ddc/jindo/transform_hadoop_config.go

add Liscence information

---

pkg/ddc/jindo/create_volume_test.go

Signed-off-by: ztz <1711556082@qq.com>
This pr is to add apache license for one file

add_apache_license

---

pkg/ddc/jindo/health_check_test.go

Signed-off-by: alien <charon42oy@163.com>
This PR is to add Apache License to pkg/ddc/jindo/health_check_test.go.

add Apache License to pkg/ddc/jindo/health_check_test.go

---

pkg/ddc/alluxio/deprecated_label_test.go

Signed-off-by: Wang-Zhijian <928937364@qq.com>

This PR is to add Apache License to pkg/ddc/alluxio/deprecated_label_test.go

---

pkg/ddc/goosefs/ufs_internal_test.go

Signed-off-by: LyraC42 <597975901@qq.com>
This pr is to add "Copyright 2022 The Fluid Authors." to pkg/ddc/goosefs/ufs_internal_test.go

This pr is to add "Copyright 2022 The Fluid Authors." to pkg/ddc/goosefs/ufs_internal_test.go 

---

pkg/ddc/goosefs/const.go

Signed-off-by: dchenhe [762137071@qq.com](mailto:762137071@qq.com)
The pr is to add copyright of /pkg/ddc/goosefs/const.go

add copyright of /pkg/ddc/goosefs/const.go

---

pkg/ddc/jindo/replicas_test.go

…ment
Signed-off-by: Perfume-QwQ <1272892522@qq.com>

This pr is to add the statement to pkg/ddc/jindo/replicas_test.go.

---

pkg/ddc/jindo/transform_worker_test.go

Signed-off-by: zyilier <1136980583@qq.com>
fixes #1768

This pr is to add Copyright for Apache License

---

pkg/ddc/goosefs/transform_fuse_test.go

This pr is to add license information to pkg/ddc/goosefs/transform_fuse_test.go

Task29:finished

---

ADOPTERS.md

Just add adopter for Gaussian Robotics

add-adopters for Gaussian Robotics

---

pkg/ddc/jindo/master_internal_test.go

Signed-off-by: maruNo1 <1527632889@qq.com>
fixes #1780

add license to pkg/ddc/jindo/master_internal_test.go

---

pkg/ddc/goosefs/report.go

Signed-off-by: ComputerEscape <2352614287@qq.com>

add a license to pkg/ddc/goosefs/report.go

---

pkg/ddc/goosefs/types_test.go

Signed-off-by: dingsj <dsj296631741@163.com>
This pr is to add license to pkg/ddc/goosefs/types_test.go

add license information to pkg/ddc/goosefs/types_test.go

---

pkg/ddc/goosefs/hcfs.go

Signed-off-by: guyin <1051909824@qq.com>
This pr is to add Apache License to hcfs.go.

This pr is to add Apache License to hcfs.go.

---

pkg/ddc/jindo/create_volume.go

Add License to pkg/ddc/jindo/create_volume.go

Add License to pkg/ddc/jindo/create_volume.go

---

pkg/ddc/base/volume.go

Signed-off-by: ZhangYi-ZHY <yhz613609@qq.com>

add license to volume.go

---

charts/fluid/fluid/Chart.yaml
charts/fluid/fluid/values.yaml

Build docker image for port allocation fixing

---

cmd/fluidapp/app/fluidapp.go
pkg/controllers/v1alpha1/fluidapp/fluidapp_controller.go
pkg/ctrl/watch/pod.go

fix https://github.com/fluid-cloudnative/fluid/issues/1784

add label selector in controller cache

---

pkg/ddc/juicefs/transform_fuse.go

fix https://github.com/fluid-cloudnative/fluid/issues/1791

fix cachedir is memory

---

.github/workflows/go.yml
pkg/controllers/v1alpha1/databackup/databackup_controller.go
pkg/controllers/v1alpha1/dataload/implement.go
pkg/controllers/v1alpha1/jindo/jindoruntime_controller.go
pkg/csi/plugins/nodeserver.go
pkg/ctrl/fuse_test.go
pkg/ddc/alluxio/transform_hadoop_config.go
pkg/ddc/alluxio/ufs.go
pkg/ddc/alluxio/worker_test.go
pkg/ddc/base/runtime_test.go
pkg/ddc/juicefs/replicas_test.go
pkg/ddc/juicefs/shutdown_test.go
pkg/ddc/juicefs/ufs_test.go
pkg/ddc/juicefs/utils_test.go
pkg/utils/helm/helm_test.go

Add static check

---

charts/fluid/fluid/Chart.yaml
charts/fluid/fluid/values.yaml

Fix juicefs fuse memory issue

---

.github/workflows/go.yml
Makefile
api/v1alpha1/openapi_generated.go
api/v1alpha1/swagger.json
hack/gen-openapi.sh
pkg/ddc/alluxio/worker_test.go

fix https://github.com/fluid-cloudnative/fluid/issues/1795

add code-gen in makefile

---

charts/fluid/fluid/templates/csi/daemonset.yaml

fix https://github.com/fluid-cloudnative/fluid/issues/1798

fix prestop in csi

---

charts/fluid/fluid/Chart.yaml
charts/fluid/fluid/values.yaml

Build docker image for fixing csi prestop script

---

pkg/ddc/jindo/const.go
pkg/ddc/jindofsx/const.go
pkg/ddc/jindofsx/load_data.go
pkg/ddc/jindofsx/utils.go

Fix JindoFSx Dataloader

---

pkg/controllers/v1alpha1/jindo/implement.go
pkg/controllers/v1alpha1/jindo/jindoruntime_controller.go
pkg/ddc/jindo/load_data.go
pkg/utils/jindo/jindo.go

Refactor jindoruntime

---

charts/fluid/fluid/Chart.yaml
charts/fluid/fluid/values.yaml

Build docker image for refactoring jindoruntime

---

api/v1alpha1/juicefsruntime_types.go
api/v1alpha1/openapi_generated.go
api/v1alpha1/zz_generated.deepcopy.go
charts/fluid/fluid/crds/data.fluid.io_juicefsruntimes.yaml
charts/juicefs/templates/fuse/daemonset.yaml
charts/juicefs/templates/worker/statefuleset.yaml
charts/juicefs/values.yaml
config/crd/bases/data.fluid.io_juicefsruntimes.yaml
pkg/ddc/juicefs/transform_fuse.go
pkg/ddc/juicefs/transform_fuse_test.go
pkg/ddc/juicefs/type.go

fix https://github.com/fluid-cloudnative/fluid/issues/1802

separate worker option and fuse option

---

charts/fluid/fluid/Chart.yaml
charts/fluid/fluid/values.yaml

Update API for Juicefs

---

docs/en/samples/application_controller.md
docs/zh/samples/application_controller.md

add application controller doc

---

charts/fluid/fluid/Chart.yaml
charts/fluid/fluid/values.yaml
docs/en/TOC.md
docs/zh/TOC.md

Update docker image for jindofsx

---

charts/fluid/fluid/VERSION
charts/fluid/fluid/values.yaml
tools/alluxio/build-image.sh
tools/alluxio/tarball.sh

Support alluxio 2.7.3

---

charts/fluid/fluid/Chart.yaml
charts/fluid/fluid/values.yaml
pkg/ddc/juicefs/transform_fuse_test.go

Fix genOption and support docker image for alluxio 2.7.3

---

go.mod
pkg/ddc/alluxio/transform_fuse.go
pkg/ddc/alluxio/transform_fuse_test.go
pkg/ddc/alluxio/transform_optimization.go
pkg/ddc/alluxio/transform_optimization_test.go
pkg/ddc/alluxio/transform_test.go
pkg/utils/version/version.go
pkg/utils/version/version_test.go
vendor/k8s.io/apimachinery/pkg/util/version/doc.go
vendor/k8s.io/apimachinery/pkg/util/version/version.go
vendor/modules.txt

Support alluxio 2.8.0

---

pkg/ddc/jindo/master_test.go

Signed-off-by: ComaX <71576355+ComaX21@users.noreply.github.com>
This PR is to add lisence information to pkg/ddc/jindo/master_test.go

add lisence information to pkg/ddc/jindo/master_test.go

---

charts/fluid/fluid/Chart.yaml
charts/fluid/fluid/values.yaml
pkg/ddc/alluxio/transform_fuse.go
pkg/ddc/alluxio/transform_fuse_test.go
pkg/utils/version/version.go

Build for alluxio 2.8.0

---

docs/en/samples/juicefs_for_s3.md
docs/en/samples/juicefs_runtime.md
docs/zh/samples/juicefs_for_s3.md
docs/zh/samples/juicefs_runtime.md

add doc of juicefs for s3 doc

---

charts/fluid/fluid/VERSION
charts/fluid/fluid/values.yaml
pkg/ddc/alluxio/transform_fuse_test.go
tools/alluxio/build-image.sh
tools/alluxio/tarball.sh

Build for alluxio 2.8.1

---

pkg/ddc/alluxio/operations/base.go
pkg/ddc/alluxio/ufs_internal.go
pkg/ddc/jindo/transform.go
pkg/utils/security/filter.go
pkg/utils/security/filter_test.go

Add logging filter for sensitive info

---

pkg/controllers/v1alpha1/fluidapp/implement.go
pkg/ctrl/watch/pod.go
pkg/ctrl/watch/pod_test.go

If serverless app has multi container, app controller should check all app container exist or not.

fix requeue check

---

pkg/ddc/juicefs/metadata.go
pkg/ddc/juicefs/ufs_internal.go
pkg/ddc/juicefs/ufs_test.go

Take fileNum & usedSpace from worker pod instead of fuse

JuiceFS Runtime: fix fileNum & usedSpace in dataset status

---

charts/fluid/fluid/Chart.yaml
charts/fluid/fluid/values.yaml

Build docker image for volumeMounts and volumes in alluxio runtime

---

api/v1alpha1/juicefsruntime_types.go
charts/juicefs/CHANGELOG.md
charts/juicefs/Chart.yaml
charts/juicefs/templates/fuse/daemonset.yaml
charts/juicefs/templates/worker/statefuleset.yaml
charts/juicefs/values.yaml
cmd/juicefs/app/juicefs.go
pkg/common/constants.go
pkg/controllers/v1alpha1/juicefs/juicefsruntime_controller.go
pkg/ddc/juicefs/transform.go
pkg/ddc/juicefs/type.go

add eventDriven & cache selector in JuiceFSRuntime Controller

add eventDriven & cache selector in JuiceFSRuntime Controller

---

charts/fluid/fluid/Chart.yaml
charts/fluid/fluid/values.yaml

Build docker image for juiceRuntime controller

---

charts/fluid/fluid/templates/controller/jindoruntime_controller.yaml
charts/fluid/fluid/values.yaml
charts/jindofsx/Chart.yaml
charts/jindofsx/templates/config/jindofs-conf.yaml
charts/jindofsx/values.yaml
pkg/ddc/jindofsx/const.go
pkg/ddc/jindofsx/transform.go
pkg/ddc/jindofsx/transform_fuse_test.go
pkg/ddc/jindofsx/transform_test.go
pkg/utils/jindo/jindo.go

upgrade jindofsx version and set to default

---

charts/fluid/fluid/Chart.yaml
charts/fluid/fluid/values.yaml
pkg/application/inject/fuse/container_injector.go
pkg/application/inject/fuse/container_injector_test.go
pkg/application/inject/fuse/injector.go
pkg/application/inject/fuse/injector_test.go
pkg/common/types.go
pkg/common/volume.go
pkg/utils/applications/pod/pod.go

Support init container injection(Phase 1)

---

pkg/ddc/jindofsx/transform.go

Refine some default parameter and fuse arg for jindofsx

---

charts/fluid/fluid/templates/controller/jindoruntime_controller.yaml
charts/fluid/fluid/values.yaml

Change engine name

---

charts/fluid/fluid/values.yaml
docker/Dockerfile.jindoruntime

Fix jindofsx not found issue

---

charts/fluid/fluid/Chart.yaml
charts/fluid/fluid/values.yaml

Docker build for fixing jindofsx 

---

charts/fluid/fluid/Chart.yaml
charts/fluid/fluid/values.yaml
pkg/ddc/alluxio/cache.go
pkg/ddc/alluxio/const.go
pkg/ddc/alluxio/metadata.go
pkg/ddc/alluxio/report.go
pkg/ddc/alluxio/transform.go
pkg/ddc/alluxio/transform_hadoop_config.go
pkg/ddc/alluxio/ufs_internal.go
pkg/ddc/alluxio/worker.go
samples/container_network/deploy.yaml

Fix sample

---

charts/fluid/fluid/Chart.yaml
charts/fluid/fluid/values.yaml

Build docker image for  alluxio runtime 

---

charts/fluid/fluid/values.yaml
charts/jindofsx/Chart.yaml
charts/jindofsx/values.yaml
pkg/controllers/v1alpha1/dataload/dataload_controller.go
pkg/ddc/jindofsx/const.go
pkg/ddc/jindofsx/load_data.go
pkg/ddc/jindofsx/transform.go
pkg/ddc/jindofsx/transform_fuse_test.go
pkg/ddc/jindofsx/transform_test.go
pkg/utils/jindo/jindo.go

Fix jindofsx dataload issue and upgrade to 4.4.0

---

api/v1alpha1/openapi_generated.go
charts/fluid/fluid/Chart.yaml
charts/fluid/fluid/values.yaml

Build docker image for jindofsx

---

charts/fluid/fluid/Chart.yaml
charts/fluid/fluid/values.yaml

Build docker image for fixing yaml security issue

---

charts/fluid/fluid/values.yaml

update jindofsx to 4.4.0 version

---

charts/fluid-dataloader/alluxio/templates/dataloader.yaml
charts/fluid-dataloader/goosefs/templates/dataloader.yaml
charts/fluid-dataloader/jindo/templates/dataloader.yaml
charts/fluid-dataloader/jindofsx/templates/dataloader.yaml
charts/fluid-dataloader/juicefs/templates/dataloader.yaml

add sidecar.istio.io/inject annotations for dataloader

---

charts/fluid/fluid/Chart.yaml
charts/fluid/fluid/values.yaml
pkg/webhook/scheduler/mutating/schedule_pod_handler.go

Optimize webhook performance

---

charts/fluid/fluid/Chart.yaml
charts/fluid/fluid/values.yaml

Build docker image for istio annotations

---

charts/fluid/fluid/Chart.yaml
charts/fluid/fluid/values.yaml
pkg/utils/json.go
pkg/webhook/plugins/fusesidecar/fuse_sidecar.go
pkg/webhook/scheduler/mutating/schedule_pod_handler.go

Update time track

---

charts/fluid/fluid/Chart.yaml
charts/fluid/fluid/values.yaml

Build docker image for time tracker

---

pkg/ddc/jindofsx/dataset.go
pkg/ddc/jindofsx/dataset_test.go
pkg/ddc/jindofsx/hcfs.go

refine jindofsx dataset with HCFS URL

---

charts/fluid/fluid/templates/webhook/webhook.yaml
pkg/common/env_names.go
pkg/utils/env.go
pkg/utils/env_test.go
pkg/utils/time_tracker.go

Enhance Time tracker

---

pkg/common/env_names.go
pkg/utils/time_tracker.go
pkg/utils/time_tracker_test.go
pkg/webhook/plugins/fusesidecar/fuse_sidecar.go
pkg/webhook/scheduler/mutating/schedule_pod_handler.go

Refact checkIfDatasetPVCs

---

charts/fluid/fluid/Chart.yaml
charts/fluid/fluid/values.yaml

Build docker image for refactoring pod injection

---

ADOPTERS.md

Signed-off-by: 道民 <jiebin.cjb@alibaba-inc.com>
update ADB adopter to production

update ADB adopter to production

---

charts/jindofs/CHANGELOG.md
charts/jindofs/templates/fuse/daemonset.yaml
charts/jindofs/values.yaml
charts/jindofsx/CHANGELOG.md
charts/jindofsx/templates/fuse/daemonset.yaml
charts/jindofsx/values.yaml
pkg/application/inject/fuse/injector.go
pkg/common/constants.go
pkg/common/types.go
pkg/ddc/base/runtime.go
pkg/ddc/base/runtime_helper.go
pkg/ddc/base/runtime_helper_test.go
pkg/ddc/jindo/transform.go
pkg/ddc/jindo/types.go
pkg/ddc/jindofsx/transform.go
pkg/ddc/jindofsx/types.go
pkg/scripts/poststart/check_fuse.go
pkg/utils/annotations.go
pkg/utils/annotations_test.go
pkg/utils/capabilities.go
pkg/utils/capabilities_test.go

Support virtual fuse device solution
fixes #1881

Support virtual fuse device solution(Phase 1)

---

pkg/application/inject/fuse/injector.go
pkg/common/types.go
pkg/ddc/base/runtime.go
pkg/ddc/base/runtime_helper.go
pkg/ddc/base/runtime_helper_test.go
pkg/scripts/poststart/check_fuse.go
pkg/webhook/cache/fuse_template_cache.go
pkg/webhook/cache/runtime_info_cache.go

Advance cache fuse template

---

charts/fluid/fluid/Chart.yaml
charts/fluid/fluid/values.yaml

Build image for fuse template cache

---

charts/fluid/fluid/Chart.yaml
charts/fluid/fluid/values.yaml

Build docker image for ASK

---

cmd/webhook/app/webhook.go

Fix time style  in development mode

---

pkg/ddc/goosefs/worker_test.go

Signed-off-by: Petrova0 <1563233799@qq.com>
add license to pkg/ddc/goosefs/worker_test.go

add license to pkg/ddc/goosefs/worker_test.go

---

charts/fluid-dataloader/jindo/templates/dataloader.yaml
pkg/ddc/jindofsx/transform.go

refine dataload targetPath volume issue

---

charts/fluid-dataloader/alluxio/CHANGELOG.md
charts/fluid-dataloader/alluxio/Chart.yaml
charts/fluid-dataloader/alluxio/templates/dataloader.yaml
charts/fluid-dataloader/jindo/CHANGELOG.md
charts/fluid-dataloader/jindofsx/CHANGELOG.md
charts/fluid/fluid/Chart.yaml
charts/fluid/fluid/values.yaml

Docker build for data load optimization

---

pkg/ddc/base/runtime_helper.go
pkg/scripts/poststart/check_fuse.go
pkg/scripts/poststart/check_fuse_test.go
pkg/utils/crtl_utils.go
pkg/utils/crtl_utils_test.go

Fix unprivileged post start script configmap bug
fixes #1912

Fix unprivileged post start script configmap bug

---

charts/fluid/fluid/Chart.yaml
charts/fluid/fluid/values.yaml

Build docker images for webhook

---

.circleci/config.yml
charts/fluid/fluid/Chart.yaml
charts/fluid/fluid/values.yaml

Fix ci issue

---

pkg/ddc/jindofsx/const.go
pkg/ddc/jindofsx/transform.go
pkg/ddc/jindofsx/transform_test.go
pkg/ddc/jindofsx/transform_worker_test.go

Improve JindoFSx MEM type with master and worker request memory

---

charts/fluid/fluid/templates/controller/alluxioruntime_controller.yaml
charts/fluid/fluid/templates/controller/goosefsruntime_controller.yaml
charts/fluid/fluid/templates/controller/jindoruntime_controller.yaml
charts/fluid/fluid/templates/controller/juicefsruntime_controller.yaml

fix https://github.com/fluid-cloudnative/fluid/issues/1573

Determine CRITICAL_FUSE_POD according to k8s version in the chart

---

charts/fluid/fluid/templates/controller/alluxioruntime_controller.yaml
charts/fluid/fluid/templates/controller/goosefsruntime_controller.yaml
charts/fluid/fluid/templates/controller/jindoruntime_controller.yaml
charts/fluid/fluid/templates/controller/juicefsruntime_controller.yaml

Fix helm install

---

pkg/ddc/jindofsx/transform.go
pkg/ddc/jindofsx/transform_test.go
pkg/ddc/jindofsx/transform_worker_test.go

Refactoring the transformResources for jindofsx

---

charts/fluid/fluid/Chart.yaml
charts/fluid/fluid/values.yaml

Refactor jindofsx resource allocation

---

charts/fluid/fluid/templates/webhook/webhook.yaml
pkg/common/constants.go
pkg/utils/annotations.go
pkg/utils/annotations_test.go

Make serverless platform label for fuse sidecar injection configurable
fixes #1930

Make serverless platform label for fuse sidecar injection configurable

---

charts/fluid/fluid/Chart.yaml
charts/fluid/fluid/values.yaml

Support key

---

charts/fluid/fluid/Chart.yaml
charts/fluid/fluid/values.yaml

Support jindofsx default memory

---

charts/jindofsx/templates/config/jindofs-conf.yaml
charts/jindofsx/templates/fuse/daemonset.yaml
pkg/ddc/jindofsx/transform.go

Fix Support JindoFSx HDFS HA and Raft

---

pkg/ddc/jindo/shutdown.go
pkg/ddc/jindofsx/shutdown.go

Fix clean cache retry time

---

charts/fluid/fluid/Chart.yaml
charts/fluid/fluid/values.yaml

Support JindoFSx HA

---

charts/jindofsx/templates/config/jindofs-conf.yaml

Fix jindofsx sdk conf set

---

charts/fluid/fluid/Chart.yaml
charts/fluid/fluid/values.yaml

Fix jindofsx HA issue

---

pkg/controllers/v1alpha1/fluidapp/fluidapp_controller.go
pkg/ctrl/watch/pod.go
pkg/ctrl/watch/pod_test.go

fix https://github.com/fluid-cloudnative/fluid/issues/1948

fix container exit

---

charts/fluid/fluid/Chart.yaml
charts/fluid/fluid/values.yaml

Fixing application controller not handle failed pod

---

pkg/controllers/v1alpha1/fluidapp/implement.go

ignore exec 137 in app controller

---

charts/fluid/fluid/values.yaml
charts/jindofsx/CHANGELOG.md
charts/jindofsx/Chart.yaml
charts/jindofsx/values.yaml
pkg/ddc/jindofsx/const.go
pkg/ddc/jindofsx/transform.go
pkg/ddc/jindofsx/transform_fuse_test.go
pkg/ddc/jindofsx/transform_test.go
pkg/utils/jindo/jindo.go

upgrade jindofsx version to 4.4.1

---

charts/fluid/fluid/Chart.yaml
charts/fluid/fluid/values.yaml

Build dockder image for jindofsx changes

---

charts/fluid/fluid/templates/controller/jindoruntime_controller.yaml
charts/fluid/fluid/values.yaml
pkg/ddc/jindofsx/const.go
pkg/ddc/jindofsx/metadata.go

Fix queryUFSTotal issue

---

charts/fluid/fluid/Chart.yaml
charts/fluid/fluid/values.yaml

Build docker image for querying dataset status for jindofsx

---

MAINTAINERS_COMMITTERS.md

Signed-off-by: RongGu <gurongwalker@gmail.com>
Update committer name list
NONE.
NA.
NA.
add Weiwei Zhu to committer list according to the vote result here: https://github.com/fluid-cloudnative/community/issues/44

Update committer name list

---

pkg/ctrl/watch/runtime.go
pkg/ctrl/watch/runtime_test.go

Fix: runtime deletion issue

---

charts/fluid/fluid/Chart.yaml
charts/fluid/fluid/values.yaml

Build docker images for jindofsx

---

charts/jindofsx/templates/worker/statefulset.yaml
pkg/ddc/jindofsx/transform.go
pkg/ddc/jindofsx/types.go

Fix support JindoFSx container network with multi worker one node

---

charts/fluid/fluid/Chart.yaml
charts/fluid/fluid/values.yaml

Build docker image for fixing updateStrategy

---

charts/fluid-dataloader/jindofsx/CHANGELOG.md
charts/fluid-dataloader/jindofsx/Chart.yaml
charts/fluid-dataloader/jindofsx/templates/dataloader.yaml
charts/fluid-dataloader/jindofsx/values.yaml

Set restart policy for dataload

---

docs-new/README.md
docs-new/README_zh.md
docs-new/zh/README.md
docs-new/zh/alluxio_runtime/TOC.md
docs-new/zh/alluxio_runtime/examples/machinelearning.md
docs-new/zh/alluxio_runtime/samples/accelerate_data_accessing.md
docs-new/zh/alluxio_runtime/samples/accelerate_data_accessing_by_hdfs.md
docs-new/zh/alluxio_runtime/samples/accelerate_pvc.md
docs-new/zh/alluxio_runtime/samples/api_proxy.md
docs-new/zh/alluxio_runtime/samples/data_co_locality.md
docs-new/zh/alluxio_runtime/samples/data_toleration.md
docs-new/zh/alluxio_runtime/samples/hostpath.md
docs-new/zh/alluxio_runtime/samples/pod_schedule_global.md
docs-new/zh/alluxio_runtime/userguide/get_started.md
docs-new/zh/install.md
docs-new/zh/overview.md

添加docs-new目录，重新组织TOC：AlluxioRuntime的‘概述’、‘入门’、‘数据集’的‘使用’和‘调度’、‘场景示例’的‘机器学习’的文档迁移。

docs: 添加docs-new目录，重新组织TOC和部分AlluxioRuntime的文档迁移

---

charts/jindofsx/templates/master/service.yaml
pkg/ddc/jindofsx/transform.go
pkg/ddc/jindofsx/types.go

Fix JindoFSx master service issue

---

pkg/ddc/jindofsx/transform.go
pkg/ddc/jindofsx/transform_test.go

Optimize setting service count 

---

charts/fluid/fluid/Chart.yaml
charts/fluid/fluid/values.yaml

Build docker images for optimizing the service count

---

pkg/ddc/jindofsx/metadata.go
pkg/ddc/jindofsx/metadata_test.go

Avoid syncing metadata when fuse only

---

charts/fluid/fluid/Chart.yaml
charts/fluid/fluid/values.yaml

Build docker image for avoid syncing metadata when fuse only

---

pkg/ddc/jindofsx/dataset.go
pkg/ddc/jindofsx/dataset_test.go
pkg/ddc/jindofsx/hcfs.go
pkg/ddc/jindofsx/port_parser.go
pkg/ddc/jindofsx/port_parser_test.go

Fix jindofsx engine's port leak issue

---

charts/fluid/fluid/Chart.yaml
charts/fluid/fluid/values.yaml

Build docker images for jindofsx latest change

---

charts/fluid/fluid/Chart.yaml
charts/fluid/fluid/values.yaml

Build docker image for configurable resource name

---

pkg/common/constants.go
pkg/ctrl/watch/pod.go
pkg/utils/annotations.go
pkg/utils/annotations_test.go

Disable Application controller for specific cloud platform

---

charts/fluid/fluid/Chart.yaml
charts/fluid/fluid/values.yaml

Build docker images for  disabling application controller

---

pkg/application/inject/fuse/container_injector.go
pkg/application/inject/fuse/injector.go
pkg/common/constants.go
pkg/scripts/poststart/check_fuse_app.go
pkg/utils/annotations.go

Signed-off-by: TzZtzt <trafalgarz@outlook.com>
fixes #2005

Inject check mount configmap into app container

---

charts/fluid/fluid/Chart.yaml
charts/fluid/fluid/values.yaml

Build docker images for serverless support

---

api/v1alpha1/dataset_types.go
charts/fluid/fluid/crds/data.fluid.io_datasets.yaml
config/crd/bases/data.fluid.io_datasets.yaml

Update dataset mountPoint min-length to 5

---

charts/fluid/fluid/Chart.yaml
charts/fluid/fluid/values.yaml

Build docker image for webhook's HA solution 

---

charts/fluid/fluid/templates/controller/alluxioruntime_controller.yaml
charts/fluid/fluid/templates/controller/dataset_controller.yaml
charts/fluid/fluid/templates/controller/fluidapp_controller.yaml
charts/fluid/fluid/templates/controller/goosefsruntime_controller.yaml
charts/fluid/fluid/templates/controller/jindoruntime_controller.yaml
charts/fluid/fluid/templates/controller/juicefsruntime_controller.yaml
charts/fluid/fluid/templates/role/alluxio/rbac.yaml
charts/fluid/fluid/templates/role/dataset/rbac.yaml
charts/fluid/fluid/templates/role/fluidapp/rbac.yaml
charts/fluid/fluid/templates/role/goosefs/rbac.yaml
charts/fluid/fluid/templates/role/jindo/rbac.yaml
charts/fluid/fluid/templates/role/juicefs/rbac.yaml
charts/fluid/fluid/templates/role/webhook/rabc.yaml
charts/fluid/fluid/templates/webhook/webhook.yaml
charts/fluid/fluid/values.yaml

For #1960 
1. add replicas setting in helm chart values, default to 1 for each component
2. enable leader election for all components by default
3. fix RBAC issue for leader election

Update HA settings in helm chart

---

charts/alluxio/CHANGELOG.md
charts/alluxio/Chart.yaml
charts/alluxio/templates/fuse/daemonset.yaml
charts/alluxio/values.yaml
charts/jindofs/Chart.yaml
charts/juicefs/CHANGELOG.md
charts/juicefs/Chart.yaml
charts/juicefs/templates/fuse/daemonset.yaml
charts/juicefs/values.yaml
pkg/common/runtime_identity.go
pkg/ddc/alluxio/transform.go
pkg/ddc/alluxio/types.go
pkg/ddc/jindo/transform.go
pkg/ddc/jindo/types.go
pkg/ddc/jindofsx/transform.go
pkg/ddc/jindofsx/types.go
pkg/ddc/juicefs/transform.go
pkg/ddc/juicefs/type.go

Add env variable to indicate runtime identity info for AlluxioRuntime and JuiceFSRuntime. The variables are useful for unprivileged sidecar injection and probably more features.
fixes #2018

Add env variable to indicate runtime identity info

---

charts/fluid/fluid/values.yaml
charts/jindofsx/Chart.yaml
charts/jindofsx/values.yaml
pkg/ddc/jindofsx/const.go
pkg/ddc/jindofsx/transform.go
pkg/ddc/jindofsx/transform_fuse_test.go
pkg/ddc/jindofsx/transform_test.go
pkg/utils/jindo/jindo.go

upgrade jindofsx version to 4.5.0

---

charts/fluid/fluid/Chart.yaml
charts/fluid/fluid/values.yaml

Build docker images for mk

---

pkg/common/runtime_identity.go

Fix runtime identity yaml marshal bug.
This is a fast fix for the bug. We should consider changing all the Runtime's yaml value to `json` or `yaml`.
fixes #2023

Fix runtime identity yaml marshal bug

---

charts/fluid/fluid/Chart.yaml
charts/fluid/fluid/values.yaml

Build docker images with latest changes

---

charts/fluid/fluid/Chart.yaml
charts/fluid/fluid/values.yaml

Build docker images for fixing juiceRuntime bug

---

charts/fluid-dataloader/jindofsx/templates/configmap.yaml
charts/fluid-dataloader/jindofsx/templates/dataloader.yaml
charts/fluid/fluid/values.yaml
charts/jindofsx/Chart.yaml
charts/jindofsx/values.yaml
pkg/ddc/jindofsx/const.go
pkg/ddc/jindofsx/transform.go
pkg/ddc/jindofsx/transform_fuse_test.go
pkg/ddc/jindofsx/transform_test.go
pkg/utils/jindo/jindo.go

fix some jindofsx config value

---

charts/fluid/fluid/Chart.yaml
charts/fluid/fluid/values.yaml

Build docker image for jindofs

---

charts/fluid-dataloader/juicefs/templates/configmap.yaml
charts/fluid-dataloader/juicefs/templates/dataloader.yaml
pkg/ddc/juicefs/cache.go
pkg/ddc/juicefs/const.go
pkg/ddc/juicefs/data_load.go
pkg/ddc/juicefs/report.go
pkg/ddc/juicefs/shutdown.go
pkg/ddc/juicefs/transform_fuse.go

fix when path in dataload contains ":", dataload fails.

fix dataload path contain :

---

charts/fluid/fluid/Chart.yaml
charts/fluid/fluid/values.yaml

Build docker image for fixing data load

---

charts/juicefs/templates/fuse/daemonset.yaml
charts/juicefs/templates/worker/statefuleset.yaml
charts/juicefs/values.yaml
pkg/ddc/juicefs/sync_runtime.go
pkg/ddc/juicefs/transform.go
pkg/ddc/juicefs/transform_fuse.go
pkg/ddc/juicefs/transform_resource_test.go
pkg/ddc/juicefs/transform_resources.go
pkg/ddc/juicefs/transform_test.go
pkg/ddc/juicefs/utils.go

fix nodeSelector and resource in juicefs runtime

fix nodeSelector & resource in juicefs worker

---

charts/fluid/fluid/Chart.yaml
charts/fluid/fluid/values.yaml

Build docker image for fixing juiceRuntime  for mk

---

charts/fluid/fluid/Chart.yaml
charts/fluid/fluid/values.yaml

Build docker image for pod scheduling strategy

---

pkg/webhook/plugins/mountpropagationinjector/mount_propagation_injector.go
pkg/webhook/plugins/mountpropagationinjector/mount_propagation_injector_test.go
pkg/webhook/plugins/prefernodeswithoutcache/prefer_nodes_without_cache.go
pkg/webhook/plugins/prefernodeswithoutcache/prefer_nodes_without_cache_test.go
pkg/webhook/plugins/requirenodewithfuse/require_node_with_fuse.go
pkg/webhook/plugins/requirenodewithfuse/require_node_with_fuse_test.go

Signed-off-by: xliuqq <xlzq1992@gmail.com>
change files in webhook plugins to use camel-case naming style
fixes #2046 
using existed tests.

webhook plugins use camel-case naming style

---

charts/fluid-dataloader/juicefs/templates/dataloader.yaml
pkg/ddc/juicefs/cache.go
pkg/ddc/juicefs/transform.go
pkg/ddc/juicefs/transform_fuse.go

fix juicefs dataload and fix cacheCapacity in dataset
fixes #2048

fix juicefs dataload & dataset cacheCapacity

---

ADOPTERS.md

Add Baidu AI Cloud to ADOPTERS

---

charts/fluid/fluid/CHANGELOG.md
charts/fluid/fluid/templates/controller/alluxioruntime_controller.yaml
charts/fluid/fluid/templates/controller/dataset_controller.yaml
charts/fluid/fluid/templates/controller/fluidapp_controller.yaml
charts/fluid/fluid/templates/controller/goosefsruntime_controller.yaml
charts/fluid/fluid/templates/controller/jindoruntime_controller.yaml
charts/fluid/fluid/templates/controller/juicefsruntime_controller.yaml
charts/fluid/fluid/templates/csi/daemonset.yaml
charts/fluid/fluid/templates/webhook/webhook.yaml
charts/fluid/fluid/values.yaml

support image pull secrets
#2037

support image pull secrets

---

ADOPTERS.md

Add Envision to ADOPTERS

---

charts/fluid/fluid/Chart.yaml
charts/fluid/fluid/values.yaml

Build docker images for juicefs

---

pkg/csi/plugins/nodeserver.go

add nodestage logs

---

charts/fluid/fluid/values.yaml
charts/juicefs/values.yaml
pkg/common/juicefs.go

set juicefs fuse default image to v1.0.0

update juicefs fuse default image

---

charts/fluid/fluid/CHANGELOG.md

Update mutating webhook configuration rules
Related PR: #2054

Update mutating webhook configuration rules

---

charts/fluid/fluid/Chart.yaml
charts/fluid/fluid/values.yaml

Build both amd64 and arm64 docker image

---

charts/fluid/fluid/templates/controller/alluxioruntime_controller.yaml
charts/fluid/fluid/values.yaml
cmd/alluxio/app/alluxio.go
pkg/ddc/base/portallocator/bitmap_allocator.go
pkg/ddc/base/portallocator/port_allocator.go
pkg/ddc/base/portallocator/port_allocator_test.go
pkg/ddc/base/portallocator/random_allocator.go

Signed-off-by: xliuqq <xlzq1992@gmail.com>
add random port allocator and do not check port is allocated or not
fixes #2055 
port_allocator_test.go

Add random port allocator

---

charts/fluid/fluid/Chart.yaml
charts/fluid/fluid/values.yaml

Build docker for upgrader

---

charts/fluid/fluid/templates/upgrade/crd-upgrade.yaml

Fix fluid upgrader namspace
fixes #2071

Fix fluid upgrader namspace

---

api/v1alpha1/openapi_generated.go
charts/fluid/fluid/templates/role/juicefs/rbac.yaml
charts/juicefs/templates/role/rbac.yaml

fix https://github.com/fluid-cloudnative/fluid/issues/2073

fix clusterrole in rbac

---

charts/fluid/fluid/Chart.yaml
charts/fluid/fluid/values.yaml

Build docker image for tiered store with emptydir

---

charts/fluid/fluid/Chart.yaml
charts/fluid/fluid/values.yaml

Fix JuiceRuntime toleration issue

---

charts/fluid/fluid/Chart.yaml
charts/fluid/fluid/values.yaml

Build docker images for labels

---

charts/fluid/fluid/templates/controller/fluidapp_controller.yaml
charts/fluid/fluid/values.yaml

Create runtime controller on demand

---

charts/fluid/fluid/Chart.yaml
charts/fluid/fluid/values.yaml

Build docker image for mk, To #41316467

---

api/v1alpha1/alluxioruntime_types.go
charts/fluid/fluid/crds/data.fluid.io_alluxioruntimes.yaml
charts/fluid/fluid/crds/data.fluid.io_goosefsruntimes.yaml
charts/fluid/fluid/crds/data.fluid.io_jindoruntimes.yaml
charts/fluid/fluid/crds/data.fluid.io_juicefsruntimes.yaml
config/crd/bases/data.fluid.io_alluxioruntimes.yaml
config/crd/bases/data.fluid.io_goosefsruntimes.yaml
config/crd/bases/data.fluid.io_jindoruntimes.yaml
config/crd/bases/data.fluid.io_juicefsruntimes.yaml

Add VolumeSource field in runtime CRDs
fixes #2103

Add VolumeSource field in runtime CRDs

---

charts/fluid/fluid/Chart.yaml
charts/fluid/fluid/values.yaml

Build docker image for mk

---

.github/workflows/go.yml
api/v1alpha1/alluxioruntime_types.go

Github actions support crd validation. This is to avoid forgetting CRD upgrade after modifying golang API structs, which may cause CR conversion bugs when using Fluid.
fixes #1554

Github actions support crd validation

---

docs-new/zh/installation/upgrade.md
docs-new/zh/operation/faq.md
docs/en/userguide/faq.md
docs/en/userguide/install.md
docs/zh/userguide/faq.md
docs/zh/userguide/install.md

Update docs for v0.8.0

---

api/v1alpha1/juicefsruntime_types.go
api/v1alpha1/openapi_generated.go
api/v1alpha1/zz_generated.deepcopy.go
charts/fluid/fluid/crds/data.fluid.io_juicefsruntimes.yaml
charts/juicefs/CHANGELOG.md
charts/juicefs/Chart.yaml
charts/juicefs/templates/fuse/daemonset.yaml
charts/juicefs/templates/worker/statefuleset.yaml
config/crd/bases/data.fluid.io_juicefsruntimes.yaml
pkg/ddc/juicefs/cacheinfo_parser.go
pkg/ddc/juicefs/cacheinfo_parser_test.go
pkg/ddc/juicefs/transform.go
pkg/ddc/juicefs/transform_fuse.go
pkg/ddc/juicefs/transform_fuse_test.go
pkg/ddc/juicefs/transform_volume.go
pkg/ddc/juicefs/transform_volume_test.go
pkg/ddc/juicefs/type.go

support emtpyDir for juicefs tiredstore volumeType

support emtpyDir for juicefs tiredstore volumeType

---

charts/fluid/fluid/Chart.yaml
charts/fluid/fluid/values.yaml

Build docker image for mk, To #44553926

---

docs/en/TOC.md
docs/en/samples/arm64.md

Translate the doc of arm into English.

update: translate the doc of arm into english

---

docs/en/userguide/install.md
docs/zh/userguide/install.md

Update v0.8.0 release docs

---

charts/fluid/fluid/Chart.yaml
charts/fluid/fluid/values.yaml

Build docker images for release v0.8.0

---

README-zh_CN.md
README.md

Signed-off-by: RongGu <gurongwalker@gmail.com>

update what's new for 0.8 release

---

charts/fluid/fluid/values.yaml

update juicefs fuse default image

update fuse default image

---

docs/en/samples/juicefs_runtime.md
docs/zh/samples/arm64.md
docs/zh/samples/juicefs_runtime.md

Update juicefs sample doc in release 0.8

update juicefs doc

---

charts/fluid/fluid/Chart.yaml
charts/fluid/fluid/values.yaml

Build docker images for empty dir

---

charts/fluid/fluid/Chart.yaml
charts/fluid/fluid/values.yaml

Build docker images for jindofsx refacgtor

---

charts/fluid/fluid/Chart.yaml
charts/fluid/fluid/values.yaml

Build docker image for JuiceFS on ECI

---

charts/juicefs/values.yaml
pkg/ddc/juicefs/type.go

fix privileged configurable

---

charts/fluid/fluid/Chart.yaml
charts/fluid/fluid/values.yaml

Build docker image for thinruntime

---

docs/en/samples/arm64.md
docs/zh/samples/arm64.md

fix: fix the arm doc. Correct the path to charts.yaml and add the step of creating fluid-system ns before installing fluid.
fixes #2145

fix: fix the arm doc

---

charts/fluid/fluid/values.yaml
charts/fluid/v0.8.0/values.yaml
charts/jindofsx/CHANGELOG.md
charts/jindofsx/Chart.yaml
charts/jindofsx/values.yaml
pkg/common/jindo.go
pkg/ddc/jindo/transform.go
pkg/ddc/jindofsx/const.go
pkg/ddc/jindofsx/transform.go
pkg/ddc/jindofsx/transform_fuse_test.go
pkg/ddc/jindofsx/transform_test.go
pkg/utils/jindo/jindo.go

Upgrade JindoFSx to 4.5.2 version

---

charts/fluid/fluid/Chart.yaml
charts/fluid/fluid/values.yaml

Update jindofsx image

---

charts/fluid-dataloader/juicefs/templates/dataloader.yaml

delete juicefs dataload privileged

---

charts/fluid/fluid/Chart.yaml
charts/fluid/fluid/values.yaml

Build docker images for multiple dataset mount

---

docs/en/samples/arm64.md
docs/en/samples/juicefs_setup.md
docs/zh/samples/arm64.md

update: translate the juicefs-setup.md to en & indicate we have supply the offical mul-platforms images

update: translate the juicefs-setup.md to en & indicate we have supply the offical mul-platforms images

---

charts/fluid/fluid/Chart.yaml
charts/fluid/fluid/values.yaml

Build docker images for multiple dataset

---

pkg/ddc/alluxio/status.go
pkg/ddc/goosefs/status.go
pkg/ddc/jindo/status.go
pkg/ddc/jindofsx/status.go
pkg/ddc/juicefs/status.go
pkg/utils/kubeclient/statefulset.go

If runtime replicas is 0, worker should be ready

fix runtime replicas is 0

---

pkg/controllers/v1alpha1/dataset/dataset_controller.go

If the dataset is created without runtime, it can't be deleted due to the following error
```
2022-09-27T16:14:58.390+0800 ERROR datasetctl.Dataset controller/controller.go:114 Failed to scale out the runtime controller on demand {"dataset": "wen-fluid /demo", "RuntimeController": "wen-fluid/demo", "error": "no matched controller"}
github.com/fluid-cloudnative/fluid/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Reconcile
/go/src/github.com/fluid-cloudnative/fluid/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:114
github.com/fluid-cloudnative/fluid/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler …
```

Fix no matched controller blocking dataset deletion

---

pkg/controllers/v1alpha1/dataset/dataset_controller.go

* Fix no matched controller blocking dataset deletion

Fix no matched controller blocking dataset deletion (#2161)

---

cmd/dataset/app/dataset.go
pkg/controllers/v1alpha1/dataset/dataset_controller.go

Fix no interval resync if the dataset is created without runtime

---

cmd/dataset/app/dataset.go
pkg/controllers/v1alpha1/dataset/dataset_controller.go

* Fix no interval resync if the dataset is created without runtime, cherry pick from https://github.com/fluid-cloudnative/fluid/pull/2166

Fix no interval resync if the dataset is created without runtime 

---

charts/alluxio/CHANGELOG.md
charts/alluxio/Chart.yaml
charts/alluxio/templates/fuse/client-daemonset.yaml
charts/alluxio/templates/fuse/daemonset.yaml
charts/goosefs/CHANGELOG.md
charts/goosefs/Chart.yaml
charts/goosefs/templates/fuse/client-daemonset.yaml
charts/goosefs/templates/fuse/daemonset.yaml
charts/jindofs/CHANGELOG.md
charts/jindofs/Chart.yaml
charts/jindofs/templates/fuse/daemonset.yaml
charts/jindofsx/CHANGELOG.md
charts/jindofsx/Chart.yaml
charts/jindofsx/templates/fuse/daemonset.yaml
charts/juicefs/CHANGELOG.md
charts/juicefs/Chart.yaml
charts/juicefs/templates/fuse/daemonset.yaml

* feature:add the toleration to fuse

feature:add the toleration to fuse (#2158)

---

Makefile

Update fluid version to 0.8.1, To #43759509

---

Makefile
charts/fluid/fluid/Chart.yaml
charts/fluid/fluid/values.yaml

Docker build release 0.8.1 

---

charts/fluid/fluid/Chart.yaml
charts/fluid/fluid/values.yaml

Build docker image for fuse toleration

---

charts/fluid/fluid/Chart.yaml
charts/fluid/fluid/values.yaml

Build docker images for thin runtime

---

pkg/ddc/thin/master_internal.go
pkg/ddc/thin/type.go

Fix yaml marshalling for thin runtime

Fix yaml marshalling for thin runtime

---

pkg/ddc/juicefs/transform_fuse.go
pkg/ddc/thin/transform_fuse.go

fix ro accessMode

---

charts/fluid/fluid/Chart.yaml
charts/fluid/fluid/values.yaml

Build docker images for alluxio runtime image secrets

---

pkg/ddc/juicefs/cache.go
pkg/ddc/juicefs/status.go
pkg/ddc/juicefs/sync_runtime.go
pkg/ddc/juicefs/sync_runtime_test.go

fix https://github.com/fluid-cloudnative/fluid/issues/2176

fix juicefs cache capacity

---

charts/fluid/fluid/Chart.yaml
charts/fluid/fluid/values.yaml

Build docker images for juicefs runtime

---

Makefile

Update fluid version to 0.8.2

---

README-zh_CN.md
README.md

Signed-off-by: RongGu <gurongwalker@gmail.com>

Add Fluid paper information

---

charts/fluid/fluid/Chart.yaml
charts/fluid/fluid/values.yaml

Build docker images for data accessing from different namespace

---

charts/thin/CHANGELOG.md
charts/thin/Chart.yaml
charts/thin/templates/fuse/daemonset.yaml
charts/thin/values.yaml
pkg/ddc/base/runtime_helper.go
pkg/ddc/thin/transform.go
pkg/ddc/thin/type.go

Fix fuse injection for thin runtime
NONE

Fix fuse injection for thin runtime

---

docs/en/TOC.md
docs/en/samples/image_pull_secrets.md

image pull secrets doc

---

docs/en/TOC.md
docs/en/samples/data_accessmodes.md
docs/zh/TOC.md
docs/zh/samples/data_accessmodes.md

add doc: Set Dataset Access Mode

doc: Set Dataset Access Mode

---

ADOPTERS.md

add metabit-trading into adopters

---

charts/fluid/fluid/Chart.yaml
charts/fluid/fluid/values.yaml

Build docker image for fixing webhook crashed in high pressure

---

charts/juicefs/CHANGELOG.md
charts/juicefs/Chart.yaml
charts/juicefs/templates/worker/statefuleset.yaml
charts/juicefs/values.yaml

make worker manage policy parallel

---

pkg/controllers/v1alpha1/alluxio/alluxio_runtime_controller.go

Signed-off-by: cqm <whqscqm@outlook.com>
add copyright info

update: add copyright info

---

charts/alluxio/templates/worker/statefulset.yaml
charts/alluxio/values.yaml

Signed-off-by: Yanghaihai1020 <Yanghaihai690@163.com>
Change alluxio podManagementPolicy from OrderedReady to Parallel

Change alluxio podManagementPolicy from OrderedReady to Parallel

---

charts/fluid/fluid/Chart.yaml
charts/fluid/fluid/values.yaml

Build docker images for alluxio runtime scaleout

---

api/v1alpha1/thinruntime_types.go

Signed-off-by: Gzy1112 <gongziyu1112@foxmail.com>
This pr is to add copyright to license in task13.

normalize license in task13

---

api/v1alpha1/openapi_generated.go
api/v1alpha1/thinruntime_types.go
api/v1alpha1/thinruntimeprofile_types.go
charts/fluid/fluid/crds/data.fluid.io_thinruntimeprofiles.yaml
charts/fluid/fluid/crds/data.fluid.io_thinruntimes.yaml
config/crd/bases/data.fluid.io_thinruntimeprofiles.yaml
config/crd/bases/data.fluid.io_thinruntimes.yaml
pkg/ddc/thin/create_volume.go
pkg/ddc/thin/create_volume_test.go
pkg/ddc/thin/engine.go
pkg/ddc/thin/engine_test.go
pkg/ddc/thin/transform_fuse_test.go
pkg/ddc/thin/transform_test.go
pkg/utils/runtimes.go
pkg/utils/runtimes_test.go

Move fstype from ThinRuntime spec to ThinRuntime profile spec, because it is a more fundamental property commonly used by multiple file system instance.
NONE

Move fstype from ThinRuntime spec to ThinRuntime profile spec

---

pkg/controllers/v1alpha1/databackup/databackup_controller.go

Signed-off-by: baowj <baowj@smail.nju.edu.cn>
Add Copyright to `pkg/controllers/v1alpha1/databackup/databackup_controller.go`

add Copyright to pkg/controllers/v1alpha1/databackup/databackup_controller.go

---

api/v1alpha1/dataset_types.go

Signed-off-by: naariah <1305289754@qq.com>
this pr adds Copyright for dataset_types.go

add Copyright for dataset_types.go

---

api/v1alpha1/alluxioruntime_types.go

Signed-off-by: CappuccinoNyy <1026564887@qq.com>
This pr is to fix copyright of alluxioruntime_types.go

Fix copyright of alluxioruntime_types.go

---

pkg/controllers/v1alpha1/goosefs/implement.go

…ment.go
Signed-off-by: jiamei-SHEN <shenjiamei@smail.nju.edu.cn>
This pr is to add Copyright of "pkg/controllers/v1alpha1/goosefs/implement.go".

add Copyright of pkg/controllers/v1alpha1/goosefs/implement.go

---

api/v1alpha1/container_network.go

Signed-off-by: WangFengyi0228 <285180762@qq.com>
This pr is is to nomalize license information in container_network.go by adding copyright.
It 's task4.

This pr is to normalize license information in task4

---

pkg/application/inject/injector.go

Signed-off-by: carabnuu <jsnjpengpeng@126.com>
modify the year 2021 in task 21

Fixed the copyright in pkg/application/inject/injector.go

---

api/v1alpha1/jindoruntime_types.go

Signed-off-by: Xingpei.Wang <wxpfelix0825@163.com>
This pr is to fix the copyright of api/v1alpha1/jindoruntime_types.go .

This pr is to fix the copyright of api/v1alpha1/jindoruntime_types.go .

---

docs/en/TOC.md
docs/en/samples/knative.md

doc: Add English document of Serverless Demo and fix its Chinese document
Signed-off-by: Xiaozheng Zhang <zhang__xiaozheng@outlook.com>
Add the English document of Serverless Demo and fix the display error in its Chinese document.
fixed [#1321](https://github.com/fluid-cloudnative/fluid/issues/1321)

doc: Add English document of Serverless Demo and fix its Chinese document

---

docs/en/TOC.md
docs/en/samples/accelerate_different_storage.md
docs/zh/TOC.md
docs/zh/samples/accelerate_different_storage.md
docs/zh/samples/accelerate_s3_minio.md

Signed-off-by: baowj <bwj_678@qq.com>
Add doc on how to support different storage.
fixes #797

doc: Samples for different storages （AlluxioRuntime）

---

charts/fluid/fluid/Chart.yaml
charts/fluid/fluid/values.yaml

Build docker image for fixing alluxio pod crash

---

pkg/ddc/thin/status.go

Fix repeated mounts status in ThinRuntime
fixes #2272

Fix repeated mounts status in ThinRuntime

---

pkg/ddc/alluxio/transform.go
pkg/ddc/alluxio/transform_test.go

Fix go format for alluxio engine

---

docs/en/TOC.md
docs/en/samples/accelerate_data_by_mem_or_ssd.md
docs/zh/TOC.md
docs/zh/samples/accelerate_data_by_mem_or_ssd.md

Signed-off-by: wangshulin <wangshulin@smail.nju.edu.cn>
add doc for Accelerate Data Access by MEM or SSD
[DOC]提供文档样例区分使用内存加速和SSD加速配置 
fixes #211

doc:Example for Accelerate Data Access by MEM or SSD

---

docs/zh/samples/accelerate_data_accessing.md

Signed-off-by: wangxu <351727801@qq.com>
When the web site in the doc is not available, the demo doc provides some backup plans to users.
fixes #1560.

modify a doc

---

charts/fluid/fluid/Chart.yaml
charts/fluid/fluid/values.yaml

Build docker images for pod label selection

---

charts/alluxio/templates/worker/statefulset.yaml
charts/alluxio/values.yaml

Automated cherry pick of #2236: Change alluxio podManagementPolicy from OrderedReady Parallel (#2236)

---

pkg/common/constants.go
pkg/controllers/runtime_controller.go
pkg/controllers/v1alpha1/dataset/dataset_controller.go

Signed-off-by: Yanghaihai1020 <Yanghaihai690@163.com>
Signed-off-by: Yanghaihai1020 <Yanghaihai690@163.com>

Automated cherry pick of #2233:  Validate name of dataset and runtime. (#2233)

---

charts/fluid/fluid/Chart.yaml
charts/fluid/fluid/values.yaml

Build docker image for v0.8.2

---

charts/fluid/fluid/Chart.yaml

Update chart for v0.8.2, To #43759509

---

pkg/controllers/v1alpha1/databackup/implement.go

Signed-off-by: Qonqn <1169670230@qq.com>

description (add cpoyright to implement)

---

pkg/ddc/alluxio/transform.go
pkg/ddc/alluxio/transform_test.go

fix issue #2198 , when set alluxio runtime master port, do not take effect
fix issue: #2198

fix issue: 2198, when set alluxio runtime master port, do not take effect

---

charts/fluid/fluid/Chart.yaml
charts/fluid/fluid/values.yaml

Build docker images for prot setting

---

docs/en/TOC.md
docs/en/dev/pprof.md
docs/zh/TOC.md
docs/zh/dev/pprof.md

doc: add the pprof use

---

api/v1alpha1/thinruntimeprofile_types.go

Signed-off-by: aibn <45821186+Eternity-AIBN@users.noreply.github.com>

This pr is to add Apache License

---

pkg/controllers/v1alpha1/dataload/implement_test.go

Signed-off-by: Jason <1774399559@qq.com>
replace copyright 2021 with copyright 2022

replace copyright 2021 with copyright 2022

---

api/v1alpha1/groupversion_info.go

Signed-off-by: JeffLee1874 <910477365@qq.com>
Normalize the license information of the file "api/v1alpha1/groupversion_info.go"

Normalize the license information

---

api/v1alpha1/constant.go

Signed-off-by: JakChen797 <1213238171@qq.com>

License add Copyright

---

ADOPTERS.md

Add Soul as adopter

---

pkg/ddc/thin/transform_fuse.go
pkg/ddc/thin/transform_fuse_test.go
pkg/ddc/thin/transform_pvc_mounts.go
pkg/ddc/thin/transform_pvc_mounts_test.go
pkg/utils/kubeclient/secret.go
pkg/utils/volumes.go
pkg/utils/volumes_test.go

Copy PV's node publish secret if not exists
NONE

Copy PV's node publish secret if not exists

---

pkg/application/inject/fuse/injector_test.go

Signed-off-by: Xiaozheng Zhang <zhang__xiaozheng@outlook.com>
Correct the Copyright year in `pkg/application/inject/fuse/injector_test.go`
NONE

fix: Correct the Copyright year.

---

pkg/ddc/alluxio/transform.go
pkg/ddc/alluxio/transform_resources.go
pkg/ddc/alluxio/transform_resources_test.go
pkg/ddc/alluxio/transform_test.go

Please make sure you have read and understood the contributing guidelines;
https://github.com/fluid-cloudnative/fluid/blob/master/CONTRIBUTING.md-->
fix issue: #2294 , set tieredstore in AlluxioRuntime do not affect memory
fix issue: #2294

fix issue: 2294, set tieredstore in AlluxioRuntime do not affect memory

---

charts/fluid/fluid/Chart.yaml
charts/fluid/fluid/values.yaml

Build for fixing memory request with alluxio runtime

---

api/v1alpha1/goosefsruntime_types.go

Signed-off-by: cyang <71760601+vooidzero@users.noreply.github.com>

add copyright to license header

---

api/v1alpha1/container_network_test.go

This PR is to change the license in api/v1alpha1/container_network_test.go
None

change the License

---

pkg/ddc/alluxio/transform_resources.go
pkg/ddc/alluxio/transform_resources_test.go
pkg/utils/kubeclient/volume_claim.go

Wrap pv check error for more human-readable log print
NONE

Wrap pv check error for more human-readable log print

---

pkg/ddc/goosefs/transform_ufs.go

Signed-off-by: fyseus <fyseus@163.com>
this pr adds license information to the file "pkg/ddc/goosefs/transform_ufs.go"
no
only license information of "pkg/ddc/goosefs/transform_ufs.go" is updated, so no tests are needed

add license information to pkg/ddc/goosefs/transform_ufs.go

---

charts/fluid/fluid/Chart.yaml
charts/fluid/fluid/values.yaml

Build docker images for jindoruntime

---

pkg/controllers/v1alpha1/dataload/implement.go

Signed-off-by: zhgit35 <3512358903@qq.com>
This PR is to modify license year in pkg/controllers/v1alpha1/dataload/implement.go.
None.

fix: Modify License year

---

pkg/application/inject/fuse/injector.go

Signed-off-by: wanghanxiang <1575799316@qq.com>
This PR is to change the incorrect year "Copyright 2021" to "Copyright 2022" in pkg/application/inject/fuse/injector.go

Change Incorrect License Year

---

pkg/application/inject/fuse/container.go

Signed-off-by: lkj <893685821@qq.com>
modify License year in pkg/application/inject/fuse/container.go

modify License year in pkg/application/inject/fuse/container.go

---

charts/fluid/fluid/values.yaml

Update docker images for thin runtime

---

api/v1alpha1/status.go

Standardize License information on api/v1alpha1/status.go

Standardize license

---

ADOPTERS.md

Add HUYA to adopters.

---

charts/alluxio/CHANGELOG.md
charts/alluxio/Chart.yaml
charts/alluxio/templates/worker/statefulset.yaml

Fix worker volumes in alluxio chart
fixes #2327

Fix worker volumes in alluxio chart

---

.github/PULL_REQUEST_TEMPLATE.md

Update template to guide contributors to auto-close issues
Currently, contributors may forget to add "fixes #xxxx" or mistakenly use another description (e.g. using "#xxxx" only) that Github cannot recognizes. This PR is to update pull request template to guide contributors to use "fixes #xxxx" in their PR description so that the related issue will be closed when the PR is merged.
Some example Issues that have already been fixed by a PR but not closed:
#2205 
#2058 
NONE

Update pull request template's guidance to link PR and related Issues

---

pkg/webhook/scheduler/mutating/schedule_pod_handler_test.go

Fix failed unit test due to variable name changed

---

charts/fluid/fluid/Chart.yaml
charts/fluid/fluid/values.yaml

Build docker iages for jindo cluster domain

---

charts/fluid/fluid/Chart.yaml
charts/fluid/fluid/values.yaml

Build docker images for juicefs's networkMode

---

pkg/ddc/thin/create_volume.go
pkg/ddc/thin/wrap_pvc.go

Add ownerReference to Dataset with mounted PVC as its owner
NONE

Add ownerReference to Dataset with mounted PVC as its owner

---

docs/zh/samples/dataset_across_namespace_with_csi.md
pkg/controllers/runtime_controller.go
pkg/ddc/base/dataset.go
pkg/ddc/base/dataset_test.go
pkg/ddc/thin/engine.go
pkg/ddc/thin/engine_test.go
pkg/ddc/thin/referencedataset/engine.go
pkg/ddc/thin/referencedataset/engine_test.go
pkg/ddc/thin/referencedataset/runtime.go

Signed-off-by: xliuqq <xlzq1992@gmail.com>
use dataset mountpoint to judge thinruntime engine build logic

use dataset mountpoint to judge thinruntime engine build logic

---

charts/fluid/fluid/Chart.yaml
charts/fluid/fluid/values.yaml

Build docker images for crossing namespace

---

ADOPTERS.md

add OPPO to adopters

---

pkg/ddc/alluxio/transform.go
pkg/ddc/goosefs/transform.go
pkg/ddc/jindo/transform.go
pkg/ddc/jindofsx/transform.go
pkg/ddc/juicefs/transform.go
pkg/ddc/thin/transform.go
pkg/utils/helm/utils.go

Add log time cost for runtime value transformation and helm installation.
fixes #2182

Issue 2182

---

charts/juicefs/CHANGELOG.md
charts/juicefs/Chart.yaml
charts/juicefs/templates/fuse/daemonset.yaml
charts/juicefs/templates/worker/statefuleset.yaml
charts/juicefs/values.yaml
pkg/ddc/juicefs/cacheinfo_parser.go
pkg/ddc/juicefs/const.go
pkg/ddc/juicefs/data_load.go
pkg/ddc/juicefs/master_internal.go
pkg/ddc/juicefs/shutdown.go
pkg/ddc/juicefs/type.go
pkg/ddc/juicefs/utils.go

fix juicefs yaml marshal & fix volume mount
fixes #XXXX

fix juicefs yaml marshal & fix volume mount

---

docs/en/userguide/troubleshooting.md
docs/zh/userguide/troubleshooting.md
tools/diagnose-fluid-jindo.sh

fix jindo diagnose

---

charts/fluid/fluid/Chart.yaml
charts/fluid/fluid/values.yaml

Build docker images for dataload

---

cmd/eac/app/eac.go
docker/Dockerfile.eacruntime

Update eac runtime controller with alpine image

---

charts/fluid/fluid/Chart.yaml
charts/fluid/fluid/values.yaml

Docker build for eac runtime controller

---

pkg/application/inject/fuse/injector.go
pkg/application/inject/fuse/mount_point_script.go
pkg/ddc/base/runtime.go
pkg/ddc/base/runtime_helper.go
pkg/ddc/base/runtime_helper_test.go
pkg/ddc/thin/referencedataset/cm.go
pkg/ddc/thin/referencedataset/engine.go
pkg/ddc/thin/referencedataset/engine_test.go
pkg/utils/kubeclient/configmap.go
pkg/utils/kubeclient/configmap_test.go

Support Access dataset from pods in different namespace（Sidecar）
fixes #2061 
manual test.
currently only verify the AlluxioRuntime.

dataset across namespace with sidecar

---

docs/zh/samples/dataset_across_namespace_with_sidecar.md

Signed-off-by: xliuqq <xlzq1992@gmail.com>
add sample docs for referenced dataset with sidecar.

add reference dataset sidecar sample docs

---

docs/zh/TOC.md

Update toc docs

---

charts/juicefs/CHANGELOG.md
charts/juicefs/Chart.yaml
charts/juicefs/templates/fuse/daemonset.yaml
charts/juicefs/values.yaml

close https://github.com/fluid-cloudnative/fluid/issues/2369
fixes #XXXX

add updateStrategy for juicefs fuse

---

docs/en/TOC.md
docs/en/troubleshooting/debug-fuse.md

Add the troubleshooting document.
fixes #2376

DOC: Add troubleshooting doc

---

charts/alluxio/CHANGELOG.md
charts/alluxio/Chart.yaml
charts/alluxio/templates/config/alluxio-conf.yaml

Use short DNS name for alluxio runtime

---

pkg/ddc/jindofsx/replicas.go
pkg/ddc/jindofsx/replicas_test.go

Avoid sync replicas when jindofsx worker is disabled

---

charts/jindofsx/CHANGELOG.md
charts/jindofsx/templates/config/jindofs-client-conf.yaml
charts/jindofsx/templates/config/jindofs-conf.yaml
charts/jindofsx/templates/fuse/daemonset.yaml
charts/jindofsx/templates/master/statefulset.yaml
charts/jindofsx/templates/worker/statefulset.yaml
pkg/ddc/jindofsx/transform.go

fix domain name

---

charts/fluid/fluid/Chart.yaml
charts/fluid/fluid/values.yaml

Build docker images for optimizing service discovery

---

docs/zh/samples/dataset_across_namespace_with_csi.md
docs/zh/samples/dataset_across_namespace_with_sidecar.md
pkg/controllers/v1alpha1/dataset/dataset_controller.go
pkg/ddc/base/dataset.go
pkg/ddc/base/dataset_test.go
pkg/ddc/thin/engine.go
pkg/ddc/thin/engine_test.go
pkg/utils/dataset_runtime.go
pkg/utils/dataset_runtime_test.go
pkg/utils/volumes_test.go

Create Reference Dataset automatically

---

OWNERS

Update approvers for prow integration.
For more information, please check [here](https://docs.prow.k8s.io/docs/components/plugins/approve/approvers/#overview)
NONE

Update approvers for prow integration

---

charts/fluid/fluid/Chart.yaml
charts/fluid/fluid/values.yaml

Docker build for fixing alluxio runtime's health check

---

pkg/controllers/deploy/runtime_controllers.go
pkg/ddc/alluxio/health_check.go
pkg/ddc/alluxio/metadata_test.go
pkg/ddc/alluxio/replicas_test.go
pkg/ddc/alluxio/ufs_test.go
pkg/ddc/eac/engine.go
pkg/utils/crtl_utils.go
pkg/utils/crtl_utils_test.go
pkg/utils/runtime_checkers.go

Handle no match kind error when on-demand scaling runtime controllers
fixes #2398

Handle no match kind error when on-demand scaling runtime controllers

---

pkg/controllers/v1alpha1/dataset/dataset_controller.go
pkg/ddc/thin/referencedataset/engine.go
pkg/utils/dataset_runtime.go
pkg/utils/dataset_runtime_test.go

Fix owner reference for thin runtime

---

test/prow/access_web_ufs.py

Add prow test case: alluxio access web ufs
fixes #2396

Add prow test case: alluxio access web ufs

---

api/v1alpha1/openapi_generated.go
api/v1alpha1/thinruntimeprofile_types.go
charts/fluid/fluid/crds/data.fluid.io_thinruntimeprofiles.yaml
config/crd/bases/data.fluid.io_thinruntimeprofiles.yaml
pkg/ddc/thin/transform_fuse.go
pkg/ddc/thin/transform_pvc_mounts.go
pkg/ddc/thin/transform_pvc_mounts_test.go
pkg/utils/kubeclient/secret.go

Implement node publish secret mount policy
NONE

Implement node publish secret mount policy

---

docker/Dockerfile.alluxioruntime
docker/Dockerfile.application
docker/Dockerfile.crds
docker/Dockerfile.csi
docker/Dockerfile.dataset
docker/Dockerfile.goosefsruntime
docker/Dockerfile.jindoruntime
docker/Dockerfile.juicefsruntime
docker/Dockerfile.thinruntime
docker/Dockerfile.webhook

This PR upgrade alpine base image version from 3.10 to 3.16, fixing image CVEs.
NONE

Fix CVE by upgrading alpine base image version

---

docs/en/TOC.md
docs/en/samples/dataset_across_namespace_with_csi.md

Add english document 'Share data across namespace (CSI mode)' and fix a typo in corresponding zh document.
NONE

DOC: add english doc 'Share data across namespace (CSI mode)'

---

docker/Dockerfile.dataset

Revert dataset dockerfile base image
NONE

Revert dataset dockerfile base image

---

charts/fluid/fluid/Chart.yaml
charts/fluid/fluid/values.yaml

Build docker image for supporting subpath

---

pkg/ddc/jindofsx/load_data.go
pkg/ddc/jindofsx/master_internal.go

replace deprecated package ioutil
fixes #2379

Issue 2379

---

config/crd/kustomization.yaml
config/fluid/bases/role/dataset/rbac.yaml

this pr fix fluid install failure because dataset controller can't successfully started  when deploy fluid by apply

Fix fluid install error

---

api/v1alpha1/dataset_types.go
docs/zh/samples/dataset_across_namespace_with_csi.md
docs/zh/samples/dataset_across_namespace_with_sidecar.md
pkg/ddc/goosefs/transform_ufs_test.go
pkg/utils/ufs_path_builder.go

Mount name optional

---

charts/fluid/fluid/Chart.yaml
charts/fluid/fluid/values.yaml

Build docker images for subDataset

---

test/prow/alluxioruntime_resources_setting.py

Signed-off-by: wangshulin <wangshulin@smail.nju.edu.cn>
add e2e test 8-设置AlluxioRuntime各组件Pod的资源需求 in https://github.com/fluid-cloudnative/community/blob/master/testcase/fluid-testcase.md
fixes #XXXX

add e2e test: alluxioruntime resource setting

---

charts/fluid/fluid/Chart.yaml
charts/fluid/fluid/values.yaml

Build docker images for reporting event of runtime

---

docs/zh/samples/thinruntime.md

Add doc for how to use ThinRuntime
fixes #2437

Add doc for how to use ThinRuntime

---

charts/fluid/fluid/templates/role/csi/rbac.yaml

Signed-off-by: mayingchun <mayingchun321@gmail.com>
fixes #2443

Add eacruntimes in csi rbac

---

test/prow/access_oss_via_jindorumtime.py

Add end-to-end prow test case: [access oss via jindoruntime](https://github.com/fluid-cloudnative/community/blob/master/testcase/fluid-testcase.md#11-%E4%BD%BF%E7%94%A8jindoruntime%E8%AE%BF%E9%97%AEoss%E5%AF%B9%E8%B1%A1%E5%AD%98%E5%82%A8%E6%95%B0%E6%8D%AE).
NONE

Add prow test case: access oss via jindoruntime

---

test/prow/patch_node_label_parallel.py

Signed-off-by: cqm <whqscqm@outlook.com>
testcase: 5 - 同一runtime类型条件下不同并发场景使用Patch进行更新节点标签
fixes #XXXX
add testcase-5 in https://github.com/fluid-cloudnative/community/blob/master/testcase/fluid-testcase.md

test: e2e testcase 5

---

charts/fluid/fluid/Chart.yaml
charts/fluid/fluid/values.yaml

Build docker images for accessModes for virtual dataset

---

test/prow/csi_stable_patch.py

testcase: 12 - CSI Plugin Stale Node Patch
add testcase-12 in https://github.com/fluid-cloudnative/community/blob/master/testcase/fluid-testcase.md

testcase: add testcase 12

---

charts/eac/templates/fuse/daemonset.yaml
charts/eac/templates/master/statefulset.yaml

Signed-off-by: mayingchun <mayingchun321@gmail.com>
fixes #2452

Fix EAC probe

---

docs/en/TOC.md
docs/en/operation/monitoring.md

Add english document 'runtime monitoring'.
NONE

DOC: add english doc 'runtime monitoring'

---

pkg/common/label.go
pkg/ddc/thin/wrap_pvc.go
pkg/ddc/thin/wrap_pvc_test.go
pkg/utils/kubeclient/volume.go
pkg/webhook/scheduler/mutating/utils.go

Rename managed-by label on pvcs
NONE

Rename managed-by label on pvcs

---

charts/fluid/fluid/Chart.yaml
charts/fluid/fluid/values.yaml

Build docker images for volume options

---

pkg/ddc/thin/transform_config_test.go

Add unit test for transform_config.go
NONE
- Add unit tests for `transform_config.go`

Add unit test for transform_config.go

---

charts/fluid/fluid/Chart.yaml
charts/fluid/fluid/values.yaml

Build docker images for pvc support

---

pkg/common/thin.go
pkg/utils/kubeclient/volume_mount.go
pkg/utils/kubeclient/volume_mount_test.go

fix: issue-2367

---

ADOPTERS.md

just add cloudview to ADOPTERS.md
fixes #XXXX

add cloudview to ADOPTERS.md

---

test/prow/alluxio_dynamic_mountpoint.py

add e2e test 9-Alluxio动态变更挂载点 in https://github.com/fluid-cloudnative/community/blob/master/testcase/fluid-testcase.md
fixes #XXXX

add e2e test 9-Alluxio动态变更挂载点

---

charts/eac/CHANGELOG.md
charts/eac/README.md
docs/zh/samples/eac_runtime.md

DOC: Add EAC doc

---

docs/zh/samples/eac_runtime.md

Update docs of  eac runtime

---

charts/fluid/fluid/Chart.yaml
charts/fluid/fluid/values.yaml

Build docker images for thin runtime mount

---

charts/fluid/fluid/templates/role/webhook/rabc.yaml
pkg/ddc/base/runtime_helper.go
pkg/utils/kubeclient/volume.go
pkg/utils/volumes.go
pkg/utils/volumes_test.go

Fix fuse sidecar mutation for EACRuntime. Specifically, this PR:
- Fix webhook rbac for EACRuntime
- Fix Fuse daemonset's container length check since EACruntime's fuse daemonset has more than one container
- Trim `eac-fuse-mount` volume
- Only add volumes needed by the fuse container to be injected
fixes #2471

Fix fuse sidecar mutation for EACRuntime

---

charts/fluid/fluid/Chart.yaml
charts/fluid/fluid/values.yaml

Build docker images for data load

---

docs/en/TOC.md
docs/en/samples/dataset_scaling.md
docs/zh/TOC.md
docs/zh/samples/dataset_scaling.md

Add the "Scaling Dataset Manualy" document.
NONE

DOC: Add scaling Dataset manualy doc

---

docs/en/TOC.md
docs/en/operation/dataset_auto_scaling.md
docs/zh/operation/dataset_auto_scaling.md

Add English document 'Auto Elastic Scaling'.
NONE

DOC: add english doc 'Auto Elastic Scaling'

---

docs/en/TOC.md
docs/en/samples/dataset_across_namespace_with_sidecar.md

Add english document 'Share data across namespace (Sidecar mode)' and fix a typo in corresponding zh document.
NONE

DOC: add english doc 'Share data across namespace (Sidecar mode)'

---

Makefile

Update fluid version to 0.8.3

---

charts/fluid/fluid/values.yaml

Cherry-pick update fuse default image (#2118)

---

charts/juicefs/templates/fuse/daemonset.yaml
charts/juicefs/templates/worker/statefuleset.yaml
charts/juicefs/values.yaml
pkg/ddc/juicefs/transform.go
pkg/ddc/juicefs/transform_resources.go
pkg/ddc/juicefs/type.go

* update resource/privileged of juicefs
* fix resource
* update changelog of chart & update privileged
fixes #XXXX

update resource/privileged of juicefs (#2130)

---

charts/fluid/fluid/Chart.yaml
charts/fluid/fluid/values.yaml

Build docker images for alluxio runtime

---

pkg/ddc/alluxio/ufs_internal.go
pkg/ddc/goosefs/ufs_internal.go
pkg/ddc/jindofsx/ufs_internal.go

Fix NPE error when log dataset info. Specifically, this PR:
- log dataset info after checking if error is nil
fixes #2488

Fix NPE error when log dataset info

---

charts/fluid/fluid/Chart.yaml
charts/fluid/fluid/values.yaml

Build docker images for fixing NPE

---

docs/en/TOC.md
docs/en/samples/api_proxy.md
docs/zh/samples/api_proxy.md

Add english doc 'access via rest api' and fix typo in corresponding zh doc.
NONE

DOC: add english doc 'access via rest api'

---

addons/nfs/docker/Dockerfile
charts/fluid/fluid/Chart.yaml
charts/fluid/fluid/values.yaml

Update base image of NFS thin runtime to 3.16

---

charts/fluid/fluid/Chart.yaml
charts/fluid/fluid/values.yaml

Build docker image for v0.8.3

---

charts/fluid/fluid/Chart.yaml
charts/fluid/fluid/values.yaml

Build docker images for deprecating ioutils

---

docs/en/TOC.md
docs/en/dev/use_go_create_resource.md

Add English doc 'How to create and delete fluid resource using Go client'
NONE

DOC: add english doc about using go client

---

charts/juicefs/CHANGELOG.md
charts/juicefs/Chart.yaml
charts/juicefs/templates/fuse/daemonset.yaml
charts/juicefs/templates/worker/statefuleset.yaml

fix https://github.com/fluid-cloudnative/fluid/issues/2500
fixes #XXXX

update fuse container as root user in sidecar mode

---

ADOPTERS.md

Signed-off-by: wangshulin <wangshulin@smail.nju.edu.cn>
add adopters of autelrobotics
fixes #XXXX

add adopters of autelrobotics

---

Makefile
charts/fluid/fluid/Chart.yaml
charts/fluid/fluid/values.yaml

Docker build for eacruntime controller

---

pkg/controllers/v1alpha1/alluxio/alluxio_runtime_controller.go
pkg/controllers/v1alpha1/databackup/databackup_controller.go
pkg/controllers/v1alpha1/dataload/dataload_controller.go
pkg/controllers/v1alpha1/dataset/dataset_controller.go
pkg/controllers/v1alpha1/goosefs/goosefs_runtime_controller.go

Unify Fluid controller names
NONE

Unify Fluid controller names

---

charts/fluid/fluid/Chart.yaml
charts/fluid/fluid/values.yaml

Docker build for unifying controller name 

---

docs/zh/samples/thinruntime.md

Enhance ThinRuntime example to follow commonly-seen Dataset specification style in Fluid
fixes #2517

Enhance ThinRuntime example to follow Dataset specification style in Fluid

---

docs/zh/TOC.md

Fix typo in docs

---

charts/fluid/fluid/Chart.yaml
charts/fluid/fluid/values.yaml

Build docker images for cleanCachePolicy

---

ADOPTERS.md

docs: add coScene adopter

---

charts/fluid/fluid/Chart.yaml
charts/fluid/fluid/values.yaml

Build docker images for fixing panic

---

charts/alluxio/CHANGELOG.md
charts/alluxio/Chart.yaml
charts/alluxio/templates/fuse/daemonset.yaml
charts/alluxio/templates/master/statefulset.yaml
charts/alluxio/templates/worker/statefulset.yaml

Signed-off-by: Wang Ni <wangni@4paradigm.com>

add sidecar.istio.io/inject annotations for alluxio runtime

---

charts/fluid/fluid/Chart.yaml
charts/fluid/fluid/values.yaml

Build docker images for supporting event driven reconciliation

---

docs/zh/samples/thinruntime.md

Polish thinruntime usage doc
NONE

Polish thinruntime usage doc

---

charts/goosefs/CHANGELOG.md
charts/goosefs/Chart.yaml
charts/goosefs/templates/fuse/daemonset.yaml
charts/goosefs/templates/master/statefulset.yaml
charts/goosefs/templates/worker/statefulset.yaml

Signed-off-by: Wang Ni <wangni@4paradigm.com>

add sidecar.istio.io/inject annotations for goosefs runtime

---

pkg/ddc/base/syncs.go

`TemplateEngine.permitSync` is one kind of protection provided to avoid frequent retries. Such retries may lay overheads on  cache engines and affect its efficiency. 
Currently, the protection protects the whole `TemplateEngine.Sync()` function but there is no need for some operations of the func to be protected. That is, only operations that have interactions(e.g. `queryCacheStatus` in `CheckAndUpdateRuntimeStatus`) with cache engines should be rate-limited by `TemplateEngine.permitSync`. 
This PR fixes it by permitting the operations that should be permitted.
NONE

Optimize permit sync logic

---

docs/zh/dev/how_to_develop.md

Update how-to-develop doc
fixes #XXXX

Update how-to-develop doc

---

charts/fluid/fluid/Chart.yaml
charts/fluid/fluid/values.yaml

Build docker images for optimizing sync logic

---

charts/fluid/fluid/templates/role/thin/rbac.yaml
cmd/dataset/app/dataset.go
pkg/controllers/v1alpha1/databackup/databackup_controller.go
pkg/controllers/v1alpha1/dataload/dataload_controller.go
pkg/controllers/v1alpha1/dataset/dataset_controller.go
pkg/ddc/base/runtime.go
pkg/ddc/base/runtime_test.go
pkg/ddc/eac/shutdown.go
pkg/ddc/thin/referencedataset/cm.go
pkg/ddc/thin/referencedataset/engine.go

Fix reference dataset for eacruntime & Fix NPE bug for eacruntime
fixes #2575

Fix reference dataset & Fix NPE bug for eacruntime 

---

pkg/ddc/alluxio/transform.go
pkg/ddc/alluxio/transform_fuse.go
pkg/ddc/alluxio/transform_optimization.go
pkg/ddc/alluxio/transform_test.go

Fix bug 2521

---

charts/jindofs/CHANGELOG.md
charts/jindofs/Chart.yaml
charts/jindofs/templates/fuse/daemonset.yaml
charts/jindofs/templates/master/statefulset.yaml
charts/jindofs/templates/worker/statefulset.yaml
charts/jindofs/values.yaml

Fearure for #2531 - for jindofs runtime

---

charts/eac/CHANGELOG.md
charts/eac/templates/fuse/daemonset.yaml
charts/eac/templates/master/statefulset.yaml
charts/eac/templates/worker/statefulset.yaml
charts/eac/values.yaml

Fearure for #2531 - for eac runtime

---

charts/thin/CHANGELOG.md
charts/thin/Chart.yaml
charts/thin/templates/fuse/daemonset.yaml
charts/thin/templates/worker/statefuleset.yaml
charts/thin/values.yaml

Fearure for #2531 - for thin runtime

---

charts/fluid/fluid/Chart.yaml
charts/fluid/fluid/values.yaml

Build docker images for shared option

---

charts/fluid/fluid/Chart.yaml
charts/fluid/fluid/values.yaml

Build docker images for random port allocation

---

docs/zh/troubleshooting/debug-fuse.md
docs/zh/userguide/faq.md

Update fuse trouble shooting document
NONE

Update fuse trouble shooting document

---

charts/eac/CHANGELOG.md
charts/eac/Chart.yaml
charts/fluid/fluid/values.yaml

add eac-master image, which separate from eac-fuse image.
fixes #2603 
no
no

add fuse-master image, and update eacruntime version

---

pkg/csi/plugins/nodeserver.go

Ignore not found error when unstage volume
fixes #2596

Ignore not found error when unstage volume

---

codecov.yml
pkg/ddc/thin/transform_fuse_test.go
pkg/utils/testutil/envvars.go

Fix ut for thinRuntime

---

docs/zh/TOC.md
docs/zh/samples/metadata_sync.md

Add guide doc about configuring metadata sync policy
fixes #2599

Add guide doc about configuring metadata sync policy

---

ADOPTERS.md

Add adopters
fixes ADOPTERS.md

Add PVmed to ADOPTERS

---

charts/fluid/fluid/Chart.yaml
charts/fluid/fluid/values.yaml

Build docker images for optimizing dataload

---

charts/fluid/fluid/Chart.yaml
charts/fluid/fluid/values.yaml

Build docker images for refactoring data operation status

---

docs/zh/core-concepts/concepts.md
docs/zh/core-concepts/introduction.md

Update concept docs

---

Makefile
charts/fluid/fluid/Chart.yaml

Origin/init release 0.8.4

---

charts/juicefs/CHANGELOG.md
charts/juicefs/Chart.yaml
charts/juicefs/templates/fuse/daemonset.yaml
charts/juicefs/templates/worker/statefuleset.yaml

* update fuse container as root user in sidecar mode
* update changelog
fixes #XXXX

Cherry-pick update fuse container as root user in sidecar mode (#2501)

---

charts/juicefs/CHANGELOG.md
charts/juicefs/Chart.yaml
charts/juicefs/templates/fuse/daemonset.yaml
charts/juicefs/templates/worker/statefuleset.yaml
charts/juicefs/values.yaml
pkg/ddc/juicefs/transform_fuse.go
pkg/ddc/juicefs/type.go

* fix key of secret
* fix secretkey & update changelog
fixes #XXXX

Cherry-pick Juicefs/fix secret key (#2509)

---

charts/fluid/fluid/Chart.yaml
charts/fluid/fluid/values.yaml

Update fluid version to 0.8.4

---

Makefile
charts/fluid/fluid/Chart.yaml

Update fluid version to 0.8.5

---

charts/jindofsx/CHANGELOG.md
charts/jindofsx/Chart.yaml
charts/jindofsx/templates/fuse/daemonset.yaml
charts/jindofsx/templates/master/statefulset.yaml
charts/jindofsx/templates/worker/statefulset.yaml

Fearure for #2531 - for jindofsx runtime

---

charts/fluid-dataloader/goosefs/templates/dataloader.yaml
charts/fluid-dataloader/goosefs/values.yaml
charts/fluid-dataloader/jindo/templates/dataloader.yaml
charts/fluid-dataloader/jindo/values.yaml
charts/fluid-dataloader/jindofsx/templates/dataloader.yaml
charts/fluid-dataloader/jindofsx/values.yaml
charts/fluid-dataloader/juicefs/templates/dataloader.yaml
charts/fluid-dataloader/juicefs/values.yaml
pkg/ddc/goosefs/load_data.go
pkg/ddc/jindo/load_data.go
pkg/ddc/jindofsx/load_data.go
pkg/ddc/juicefs/data_load.go

support image pull secrets for goosefs,jindo,jindofsx,juicefs dataload

support image pull secrets for goosefs,jindo,jindofsx,juicefs

---

charts/fluid/fluid/Chart.yaml
charts/fluid/fluid/values.yaml

Build docker images for secrets in dataload

---

charts/fluid/fluid/templates/controller/alluxioruntime_controller.yaml
charts/fluid/fluid/templates/controller/eacruntime_controller.yaml
charts/fluid/fluid/templates/controller/goosefsruntime_controller.yaml
charts/fluid/fluid/templates/controller/jindoruntime_controller.yaml
charts/fluid/fluid/templates/controller/juicefsruntime_controller.yaml
charts/fluid/fluid/templates/controller/thinruntime_controller.yaml
pkg/controllers/deploy/runtime_controllers.go
pkg/ddc/eac/engine.go
pkg/ddc/factory.go

Fix EACRuntime controller scaling out bug
fixes #2629

Fix EACRuntime controller scaling out bug

---

api/v1alpha1/openapi_generated.go
api/v1alpha1/status.go
charts/fluid/fluid/crds/data.fluid.io_databackups.yaml
charts/fluid/fluid/crds/data.fluid.io_dataloads.yaml
config/crd/bases/data.fluid.io_databackups.yaml
config/crd/bases/data.fluid.io_dataloads.yaml

Set dataload.status.info as omitEmpty
fixes #2624

Set dataload.status.info as omitEmpty

---

charts/fluid/fluid/Chart.yaml
charts/fluid/fluid/values.yaml

Build docker images for optimzing dataload status

---

charts/fluid/fluid/templates/role/dataset/rbac.yaml

Fix rbac for scaling out eacruntime controller
NONE

Fix rbac for scaling out eacruntime controller

---

charts/fluid-databackup/alluxio/templates/databackup.yaml
charts/fluid-databackup/alluxio/values.yaml
charts/fluid-databackup/goosefs/templates/databackup.yaml
charts/fluid-databackup/goosefs/values.yaml
pkg/controllers/v1alpha1/databackup/implement.go
pkg/databackup/value.go

image pull secrets for databackup

support image pull secrets for databackup

---

docs/en/core-concepts/architecture.md
docs/en/core-concepts/concepts.md
docs/en/core-concepts/introduction.md

Init english version of  core concepts

---

charts/fluid/fluid/templates/role/eac/rbac.yaml
pkg/controllers/v1alpha1/databackup/implement.go
pkg/ddc/eac/data_load.go
pkg/ddc/eac/node.go
pkg/ddc/eac/node_test.go
pkg/ddc/eac/shutdown.go
pkg/ddc/eac/utils.go
pkg/ddc/eac/utils_test.go
pkg/ddc/eac/worker.go

Fix eac runtime controller rbac & fix eac.runtime getWorkerPod logic
NONE

Fix eac runtime controller rbac & fix eac.runtime getWorkerPod logic

---

addons/cubefs/v2.4/readme-zh_CN.md
addons/cubefs/v2.4/readme.md
addons/nfs/readme-zh_CN.md
addons/nfs/readme.md

Update docs for cubefs

---

.github/workflows/codeql-analysis.yml
.github/workflows/go.yml

update ci version

---

charts/fluid/fluid/Chart.yaml
charts/fluid/fluid/values.yaml

Build docker images for fixing juicefs cache dir

---

README-zh_CN.md
README.md

Add contribution leaderboard badge to README.
No.
No need.
Click URL.

docs: add leaderboard badge to readme

---

.github/dependabot.yml

see https://docs.github.com/en/code-security/dependabot/dependabot-security-updates/configuring-dependabot-security-updates
fixes #XXXX

add dependabot ci

---

addons/nfs/docker/Dockerfile
docker/Dockerfile.alluxioruntime
docker/Dockerfile.application
docker/Dockerfile.crds
docker/Dockerfile.csi
docker/Dockerfile.dataset
docker/Dockerfile.eacruntime
docker/Dockerfile.goosefsruntime
docker/Dockerfile.jindoruntime
docker/Dockerfile.juicefsruntime
docker/Dockerfile.thinruntime
docker/Dockerfile.webhook

Update alpine from 3.16 to 3.17

---

pkg/controllers/v1alpha1/dataload/dataload_controller.go
pkg/controllers/v1alpha1/dataload/implement.go
pkg/dataload/constants.go
pkg/ddc/alluxio/load_data.go
pkg/ddc/eac/data_load.go
pkg/ddc/goosefs/load_data.go
pkg/ddc/jindo/load_data.go
pkg/ddc/jindofsx/load_data.go
pkg/ddc/juicefs/data_load.go

rename dataload constants

---

charts/fluid/fluid/Chart.yaml
charts/fluid/fluid/values.yaml

Build docker images for updating go vendor

---

charts/fluid/fluid/Chart.yaml
charts/fluid/fluid/values.yaml

Build docker images for data migrating

---

api/v1alpha1/datamigrate_types.go
charts/fluid/fluid/crds/data.fluid.io_datamigrates.yaml
config/crd/bases/data.fluid.io_datamigrates.yaml
pkg/ddc/juicefs/data_load.go

enhance datamigrate crd shortname

---

go.mod
go.sum
pkg/ddc/alluxio/shutdown_engine_test.go
vendor/github.com/agiledragon/gomonkey/v2/README.md
vendor/github.com/agiledragon/gomonkey/v2/creflect/ae1.17.go
vendor/github.com/agiledragon/gomonkey/v2/creflect/be1.16.go
vendor/github.com/agiledragon/gomonkey/v2/creflect/type.go
vendor/github.com/agiledragon/gomonkey/v2/jmp_386.go
vendor/github.com/agiledragon/gomonkey/v2/jmp_arm64.go
vendor/github.com/agiledragon/gomonkey/v2/modify_binary_darwin.go
vendor/github.com/agiledragon/gomonkey/v2/modify_binary_linux.go
vendor/github.com/agiledragon/gomonkey/v2/patch.go
vendor/modules.txt

Fix alluxio shutdown unit test
fixes #2673

Fix alluxio shutdown unit test

---

api/v1alpha1/dataset_types.go
api/v1alpha1/openapi_generated.go
charts/fluid/fluid/crds/data.fluid.io_datasets.yaml
config/crd/bases/data.fluid.io_datasets.yaml
pkg/controllers/v1alpha1/datamigrate/implement.go
pkg/datamigrate/constants.go

update migrateRef to operateRef

---

charts/fluid/fluid/Chart.yaml
charts/fluid/fluid/values.yaml

Build docker images for operateRef

---

docs/en/userguide/get_started.md
docs/zh/userguide/get_started.md

Update get started doc

---

charts/fluid/fluid/templates/role/alluxio/rbac.yaml
charts/fluid/fluid/templates/role/dataset/rbac.yaml
charts/fluid/fluid/templates/role/eac/rbac.yaml
charts/fluid/fluid/templates/role/goosefs/rbac.yaml
charts/fluid/fluid/templates/role/jindo/rbac.yaml
charts/fluid/fluid/templates/role/juicefs/rbac.yaml
charts/fluid/fluid/templates/role/thin/rbac.yaml

Regulate RBAC of Fluid controllers
#2696

Regulate RBAC of Fluid controllers

---

.github/workflows/sonarcloud.yaml
sonar-project.properties

Add Sonarcloud Scan ci

---

charts/fluid/fluid/templates/csi/daemonset.yaml
csi/deploy/csi-fluid-provisioner.yaml
integration/cronhpa/deploy.yaml
integration/prometheus/prometheus-goosefs.yaml
integration/prometheus/prometheus-jindofs.yaml
integration/prometheus/prometheus.yaml

Remove deprecated serviceAccount

---

.circleci/config.yml

Update circleci image circleci/golang:1.17 to cimg/go:1.18

---

.circleci/config.yml

Fix permission issue which is introduced by circleci

---

charts/fluid/fluid/templates/_helpers.tpl
charts/fluid/fluid/templates/controller/alluxioruntime_controller.yaml
charts/fluid/fluid/templates/controller/dataset_controller.yaml
charts/fluid/fluid/templates/controller/eacruntime_controller.yaml
charts/fluid/fluid/templates/controller/fluidapp_controller.yaml
charts/fluid/fluid/templates/controller/goosefsruntime_controller.yaml
charts/fluid/fluid/templates/controller/jindoruntime_controller.yaml
charts/fluid/fluid/templates/controller/juicefsruntime_controller.yaml
charts/fluid/fluid/templates/controller/thinruntime_controller.yaml
charts/fluid/fluid/templates/csi/daemonset.yaml
charts/fluid/fluid/templates/role/alluxio/rbac.yaml
charts/fluid/fluid/templates/role/csi/rbac.yaml
charts/fluid/fluid/templates/role/dataset/rbac.yaml
charts/fluid/fluid/templates/role/eac/rbac.yaml
charts/fluid/fluid/templates/role/fluidapp/rbac.yaml
charts/fluid/fluid/templates/role/goosefs/rbac.yaml
charts/fluid/fluid/templates/role/jindo/rbac.yaml
charts/fluid/fluid/templates/role/juicefs/rbac.yaml
charts/fluid/fluid/templates/role/thin/rbac.yaml
charts/fluid/fluid/templates/role/webhook/rabc.yaml
charts/fluid/fluid/templates/upgrade/crd-upgrade.yaml
charts/fluid/fluid/templates/webhook/service.yaml
charts/fluid/fluid/templates/webhook/webhook.yaml
charts/fluid/fluid/templates/webhook/webhookconfiguration.yaml
charts/fluid/fluid/values.yaml
pkg/controllers/deploy/runtime_controllers.go

fixes https://github.com/fluid-cloudnative/fluid/issues/2679

Add specify namespace installation

---

charts/fluid-dataloader/goosefs/CHANGELOG.md
charts/fluid-dataloader/goosefs/templates/dataloader.yaml
charts/fluid-dataloader/goosefs/values.yaml
pkg/ddc/goosefs/load_data.go
pkg/ddc/goosefs/load_data_test.go

GooseFS Dataload support setting affinity 
fixes #2730

support setting affinity when using GooseFS Dataload

---

charts/fluid/fluid/Chart.yaml
charts/fluid/fluid/values.yaml

Build docker images for customizing management namespace

---

docker/Dockerfile.alluxioruntime
docker/Dockerfile.application
docker/Dockerfile.csi
docker/Dockerfile.dataset
docker/Dockerfile.eacruntime
docker/Dockerfile.goosefsruntime
docker/Dockerfile.jindoruntime
docker/Dockerfile.juicefsruntime
docker/Dockerfile.thinruntime
docker/Dockerfile.webhook

Update golang:1.17.8 to golang:1.18

---

docker/Dockerfile.alluxioruntime
docker/Dockerfile.application
docker/Dockerfile.csi
docker/Dockerfile.dataset
docker/Dockerfile.eacruntime
docker/Dockerfile.goosefsruntime
docker/Dockerfile.jindoruntime
docker/Dockerfile.juicefsruntime
docker/Dockerfile.thinruntime
docker/Dockerfile.webhook

Remove the from platform parameter to support docker build

---

csi/shell/check_bind_mounts.sh
csi/shell/check_mount.sh
pkg/scripts/poststart/check_fuse.go
pkg/scripts/poststart/check_fuse_app.go

fixes https://github.com/fluid-cloudnative/fluid/issues/2613

update mount to check mountinfo

---

charts/eac/templates/fuse/daemonset.yaml
charts/eac/templates/master/statefulset.yaml

Lower termination grace period seconds of EACRuntime
NONE

Lower termination grace period seconds of EACRuntime

---

charts/fluid-dataloader/jindo/CHANGELOG.md
charts/fluid-dataloader/jindo/templates/dataloader.yaml
charts/fluid-dataloader/jindo/values.yaml
pkg/ddc/jindo/load_data.go
pkg/ddc/jindo/load_data_test.go

Jindo Dataload support setting affinity. #2731

support setting affinity when using Jindo Dataload

---

README-zh_CN.md
README.md

Add Report Vulnerability info
fixes #2746 
NA.
NA.

Add Report Vulnerability info

---

OWNERS

Add weiwei to approver list

---

sonar-project.properties

Skip sonar analysis for test.go file

---

charts/fluid/fluid/templates/role/alluxio/rbac.yaml
charts/fluid/fluid/templates/role/dataset/rbac.yaml
charts/fluid/fluid/templates/role/eac/rbac.yaml
charts/fluid/fluid/templates/role/goosefs/rbac.yaml
charts/fluid/fluid/templates/role/jindo/rbac.yaml
charts/fluid/fluid/templates/role/juicefs/rbac.yaml
charts/fluid/fluid/templates/role/thin/rbac.yaml

`helm install` requires permissions to update secret to successfully install helm releases. This PR grants permissions to Fluid controlllers to update secret.
fixes #2764

Grant secret update permission to Fluid controllers

---

pkg/ddc/juicefs/transform.go

fixes https://github.com/fluid-cloudnative/fluid/issues/2763

fix port allocate

---

charts/fluid-dataloader/juicefs/CHANGELOG.md
charts/fluid-dataloader/juicefs/templates/dataloader.yaml
charts/fluid-dataloader/juicefs/values.yaml
pkg/ddc/juicefs/data_load.go
pkg/ddc/juicefs/data_load_test.go

support setting affinity when using JuiceFS Dataload
fixes #2760

support setting affinity when using JuiceFS Dataload

---

charts/fluid/fluid/values.yaml

Update docker image of csi-node-driver-registrar

---

docker/Dockerfile.alluxioruntime
docker/Dockerfile.application
docker/Dockerfile.csi
docker/Dockerfile.dataset
docker/Dockerfile.eacruntime
docker/Dockerfile.goosefsruntime
docker/Dockerfile.jindoruntime
docker/Dockerfile.juicefsruntime
docker/Dockerfile.thinruntime
docker/Dockerfile.webhook
sonar-project.properties

Fix code smells of dockerfile

---

test/prow/fuse_recovery.py

Signed-off-by: baowj-678 <bwj_678@qq.com>
add e2e testcase fuse-recovery([6-Fuse挂载点自动恢复](https://github.com/fluid-cloudnative/community/blob/master/testcase/fluid-testcase.md#6-fuse%E6%8C%82%E8%BD%BD%E7%82%B9%E8%87%AA%E5%8A%A8%E6%81%A2%E5%A4%8D))
NONE

add e2e testcase fuse-recovery

---

charts/fluid-dataloader/jindofsx/CHANGELOG.md
charts/fluid-dataloader/jindofsx/templates/dataloader.yaml
charts/fluid-dataloader/jindofsx/values.yaml
pkg/ddc/jindofsx/load_data.go
pkg/ddc/jindofsx/load_data_test.go

support setting affinity when using JindoFSX Dataload
fixes #2758

support setting affinity when using JindoFSX Dataload

---

pkg/csi/updatedbconf/updatedbconf.go

This pr is to add copyright in pkg/csi/updatedbconf/updatedbconf.go

Fix license in file pkg/csi/updatedbconf/updatedbconf.go

---

charts/fluid/fluid/Chart.yaml
charts/fluid/fluid/values.yaml

Build docker images for refactoring operations

---

pkg/ddc/jindo/operations/cached.go

Fix license issue in pkg/ddc/jindo/operations/cached.go

---

addons/cubefs/v2.4/dev-guide/cubefs-v2.4-zh_CN.md
addons/cubefs/v2.4/dev-guide/cubefs-v2.4.md
addons/cubefs/v2.4/docker/fluid_config_init.py
addons/cubefs/v2.4/readme-zh_CN.md
addons/cubefs/v2.4/readme.md
addons/cubefs/v2.4/runtime-profile.yaml
addons/cubefs/v3.2/dev-guide/cubefs-v3.2-zh_CN.md
addons/cubefs/v3.2/dev-guide/cubefs-v3.2.md
addons/cubefs/v3.2/docker/Dockerfile
addons/cubefs/v3.2/docker/build.sh
addons/cubefs/v3.2/docker/entrypoint.sh
addons/cubefs/v3.2/docker/fluid_config_init.py
addons/cubefs/v3.2/readme-zh_CN.md
addons/cubefs/v3.2/readme.md
addons/cubefs/v3.2/runtime-profile.yaml

add addons cubefs_v3.2
fixes #XXXX

add addons cubefs_v3.2

---

pkg/ddc/thin/wrap_pvc_test.go

This pr is to modify fluid/pkg/ddc/thin/wrap_pvc_test.go with adding License description.

add License description

---

pkg/ddc/jindo/worker.go

This PR is to add license for the file pkg/ddc/jindo/worker.go
fixes #XXXX

add the license of pkg/ddc/jindo/worker.go

---

pkg/utils/net.go

This pr adds license for pkg/utils/net.go

complete net.go

---

.github/workflows/codeql-analysis.yml
.github/workflows/go.yml
.github/workflows/sonarcloud.yaml
pkg/ddc/jindo/const.go
pkg/ddc/jindo/transform.go
pkg/ddc/jindofsx/const.go
pkg/ddc/jindofsx/load_data.go
pkg/ddc/jindofsx/transform.go

Limit github action permissions

---

pkg/ddc/alluxio/operations/local.go

This pr is to add copyright to pkg/ddc/alluxio/operations/local.go
NONE

add copyright to pkg/ddc/alluxio/operations/local.go

---

pkg/ddc/alluxio/master_internal.go

This pr fixes missing copyright line in `pkg/ddc/alluxio/master_internal.go`. 
NONE

fix missing copyright line in pkg/ddc/alluxio/master_internal.go

---

pkg/utils/pprof.go

modify pkg/utils/pprof.go

---

pkg/ddc/alluxio/transform_init_users_test.go

This pr is to add license in pkg/ddc/alluxio/transform_init_users_test.go.
fixes #XXXX

License is added in pkg/ddc/alluxio/transform_init_users_test.go by 201220131-hzj

---

pkg/utils/mount_test.go

This pr is to add license to file pkg/utils/mount_test.go

add license to file pkg/utils/mount_test.go

---

pkg/ddc/alluxio/transform_init_users.go

This pr is to add "Copyright 2023 The Fluid Authors." in pkg/ddc/alluxio/transform_init_users.go for task32.
fixes #XXXX

task32 in pkg/ddc/alluxio/transform_init_users.go

---

.github/workflows/sonarcloud.yaml

Ignore vendor/* when scorecard  scanning

---

pkg/ddc/alluxio/ufs.go

The PR is to add the Copyright of the License in the file:pkg/ddc/alluxio/ufs.go.
fixes #XXXX

finish the task28:ufs.go

---

.github/workflows/sonarcloud.yaml

Fix issue that  A sequence was not expected

---

OWNERS

Add approvers for release 0.8

---

README-zh_CN.md
README.md

Add OpenSSF Scorecard for README.md

---

pkg/ddc/thin/transform_pvc_mounts_test.go

This pr is to add Apache License to transform_pvc_mounts_test.go
fixes #XXXX

This pr is to add Apache License to transform_pvc_mounts_test.go

---

.gitignore
hack/sdk/gen-sdk.sh

Download swagger-codegen-cli.jar in gen-sdk.sh
fixes #2837

Download swagger-codegen-cli.jar in gen-sdk.sh

---

pkg/ddc/alluxio/label.go

This pr is to add license to pkg/ddc/alluxio/label.go

task 44: add license to pkg/ddc/alluxio/label.go

---

pkg/utils/runtime_checkers.go

This pr is to add pkg/utils/runtime_checkers.go

This pr is to add pkg/utils/runtime_checkers.go

---

addons/cephfs/dev-guide/cephfs-zh_CN.md
addons/cephfs/dev-guide/cephfs.md
addons/cephfs/docker/Dockerfile

pin the Docker image by updating alpine to `alpine@sha256:124c7d2707904eea7431fffe91522a01e5a861a624ee31d03372cc1d138a3126`
fixes #2827

Update base image alpine of ceph thinruntime dockerfile

---

pkg/ddc/alluxio/shutdown_engine_test.go

add CopyRight in pkg/ddc/alluxio/shutdown_engine_test.go

add CopyRight in pkg/ddc/alluxio/shutdown_engine_test.go

---

pkg/ddc/alluxio/dataset.go

This pr is to add pkg/ddc/alluxio/dataset.go
fixes #XXXX

change pkg/ddc/alluxio/dataset.go

---

pkg/ddc/eac/ufs.go
pkg/ddc/eac/ufs_test.go

This pr is to add copyright to pkg/ddc/eac/ufs_test.go
fixes #XXXX

Add copyright to pkg/ddc/eac/ufs_test.go

---

pkg/ddc/jindo/master.go

This pr is to add Apache License to pkg/ddc/jindo/master.go
fixes #XXXX

-smodified: pkg/ddc/jindo/master.go --task72

---

pkg/ddc/goosefs/worker.go

Copyright 2023 The Fluid Author

---

pkg/ddc/alluxio/types.go

add copyright to pkg/ddc/alluxio/types.go
fixes #2881

add copyright to pkg/ddc/alluxio/types.go

---

pkg/ddc/alluxio/ufs_test.go

add "Copyright" to pkg/ddc/alluxio/ufs_test.go
fixes #2889

add 'Copyright' to pkg/ddc/alluxio/ufs_test.go

---

charts/fluid/fluid/Chart.yaml
charts/fluid/fluid/values.yaml

Build docker images for eac fixing

---

pkg/ddc/eac/transform_port_test.go

This pr is to add some notes
fixes #XXXX
yes

Modify copyright

---

pkg/ddc/alluxio/shutdown.go

This PR is to add Copyright  of pkg/ddc/alluxio/shutdown.go
fixes #XXXX

add copyright to pkg/ddc/alluxio/shutdown.go

---

pkg/ddc/goosefs/cache.go

description modify_cache.go

---

docs/en/operation/pod_schedule_optimization.md
docs/zh/operation/pod_schedule_optimization.md

Add some exmaples to https://github.com/fluid-cloudnative/fluid/blob/master/docs/zh/operation/pod_schedule_optimization.md.
This doc https://github.com/fluid-cloudnative/fluid/blob/master/docs/zh/operation/pod_schedule_optimization.md is missing some examples compared to https://github.com/fluid-cloudnative/fluid/blob/master/docs-new/zh/runtime_alluxio/task/dataset_schedule/pod_schedule_global.md.
NONE

Update pod_schedule_optimization doc

---

pkg/ddc/alluxio/replicas.go

add a line of copyright in relicas.go

---

pkg/ddc/alluxio/transform_optimization.go

This pr is to add copyright to pkg/ddc/alluxio/transform_optimization.go
fixes #XXXX

task 52 add copyright

---

pkg/utils/dataset_condition.go

add the copyright to to pkg/utils/dataset_condition.go.
NONE

add copyright to to pkg/utils/dataset_condition.go

---

pkg/utils/testutil/deepequal.go

This PR is to add Apache License to pkg/utils/testutil/deepequal.go.
fixes #XXXX

Add Apache License to pkg/utils/testutil/deepequal.go.

---

pkg/utils/map_test.go

This pr is to add license of pkg/utils/map_test.go  (task150)

add license of pkg/utils/map_test.go

---

pkg/ddc/alluxio/engine_test.go

This pr is to add License content to the file header.

---

pkg/utils/dataset_test.go

This pr is to normalize license for pkg/utils/dataset_test.go.

finish task 154: normalize pkg/utils/dataset_test.go

---

pkg/csi/plugins/nodeserver.go

This pr is to add Copyright in pkg/csi/plugins/nodeserver.go
fixes #XXXX

This pr is to add Copyright in pkg/csi/plugins/nodeserver.go

---

pkg/ddc/alluxio/engine.go

finish task 50

---

pkg/ddc/jindo/port_parser_test.go

add license for pkg/ddc/jindo/port_parser_test.go

add license for pkg/ddc/jindo/port_parser_test.go

---

pkg/ddc/alluxio/create_volume.go

This pr is to add Copyright for the file: /pkg/ddc/alluxio/create_volume.go : )
fixes #XXXX

add Copyright for a file

---

pkg/ddc/alluxio/transform_hadoop_config.go

add_license

---

pkg/utils/random_test.go

This  pr is to add apache license for task 122
fixes #XXXX

add apache license for task 122

---

pkg/ddc/alluxio/transform_ufs_test.go

The pr is to add Copyright to “pkg/ddc/alluxio/transform_ufs_test.go”.
fixes #XXXX

increase Copyright

---

pkg/utils/charts.go

Add Apache License to pkg/utils/charts.go

---

pkg/ddc/alluxio/master.go

This pr is to add copyright to pkg/ddc/alluxio/master.go
fixes #XXXX

 add Copyright to pkg/ddc/alluxio/master.go

---

pkg/ddc/jindo/load_data_test.go

add license to pkg/ddc/jindo/load_data_test.go

---

pkg/ddc/alluxio/transform_ufs.go
pkg/ddc/alluxio/transform_ufs_test.go
pkg/ddc/alluxio/types.go
pkg/ddc/goosefs/transform_ufs.go
pkg/ddc/goosefs/transform_ufs_test.go
pkg/ddc/goosefs/types.go

support dataset with PVC subpath
fixes #2752

support dataset with PVC subpath

---

pkg/ddc/alluxio/utils_test.go

This pr is to add the copyright that was originally missing.
fixes #XXXX

add the missing Copyright

---

pkg/common/volume.go

pkg/common/volume.go has no license, this PR adds license for it.
NONE

Add license for pkg/common/volume.go

---

pkg/ddc/alluxio/metadata.go

This pr is to add Copyright.
fixes #XXXX

addCopyright

---

pkg/utils/dataset/volume/delete.go

This pr is to add with editing pkg/utils/dataset/volume/delete.go

---

pkg/ddc/alluxio/runtime_info_test.go

Add license at pkg/ddc/alluxio/runtime_info_test.go

Add license at pkg/ddc/alluxio/runtime_info_test.go

---

pkg/utils/quantity.go

Standardized file: pkg/utils/quantity.go, add Copyright.
fixes #XXXX

Standardized file:pkg/utils/quantity.go .

---

pkg/utils/map.go

add license to map.go

---

pkg/ddc/alluxio/health_check.go

This pr is to add Apache Liscence to pkg/ddc/alluxio/health_check.go
fixes #XXXX

Add Apache Liscence to pkg/ddc/alluxio/health_check.go

---

pkg/ddc/alluxio/shutdown_engine_test.go

Update License for shutdown_engine_test.go

---

pkg/ddc/alluxio/transform_test.go

This pr is to add copyright to pkg/ddc/alluxio/transform_test.go
fixes #XXXX

add copyright 201220049

---

pkg/ddc/jindofsx/worker.go

This pr is to add Apache License in the form of comments at the top of the pkg/ddc/jindofsx/worker.go.
fixes #XXXX

201220171 Task 94

---

pkg/ddc/juicefs/data_load.go

增加Copyright

---

pkg/csi/plugins/driver.go

add copyright in pkg/csi/plugins/driver.go
fixes #2973

add copyright2

---

pkg/controllers/v1alpha1/juicefs/juicefsruntime_controller.go

Add Copyright Information to pkg/controllers/v1alpha1/juicefs/juicefsruntime_controller.go
NONE

Add Copyright Information to pkg/controllers/v1alpha1/juicefs/juicefsruntime_controller.go

---

pkg/utils/crtl_utils.go

This pr is to normalize the content of License by adding Copyright.

This pr is to normalize the content of License by adding Copyright.

---

pkg/utils/dataset/lifecycle/schedule_utils.go

Add apache liscence to pkg/utils/dataset/lifecycle/schedule_utils.go

---

pkg/ddc/goosefs/port_parser_test.go

Fluid new branch

---

pkg/utils/ufs_path_builder_test.go

This pr is to add lciense for pkg/utils/ufs_path_builder_test.go.
fixes #XXXX

this pr is to add lciense

---

pkg/dump/dump.go

This pr is to add license at pkg/dump/dump.go
fixes #XXXX

Add license at pkg/dump/dump.go

---

pkg/ddc/jindofsx/cache_test.go

this pr is to add a statement to the file header

---

pkg/utils/common.go

add copyright to pkg/utils/common.go
fixes #XXXX

add copyright to pkg/utils/common.go

---

pkg/ddc/alluxio/operations/cached.go

This pr is to add copyright to pkg/ddc/alluxio/operations/cached.go

Add copyright to pkg/ddc/alluxio/operations/cached.go

---

pkg/ddc/base/metadata_sync.go

This pr is to add Apache License to metadata_sync.go
fixes #XXXX

change metadata_sync.go first

---

pkg/utils/dataset/volume/create.go

…t/volume/create.go"
This pr is to add copyright to Apache License on file "pkg/utils/dataset/volume/create.go".

add copyright on file "pkg/utils/dataset/volume/create.go"

---

pkg/ddc/alluxio/transform_permission.go

The pr is to add Copyright to pkg/ddc/alluxio/transform_permission.go
fixes #XXXX

add Copyright to the first line

---

pkg/ddc/alluxio/shutdown_engine_test.go
pkg/ddc/alluxio/transform_test.go
pkg/ddc/jindofsx/transform.go
pkg/ddc/jindofsx/transform_test.go
pkg/ddc/juicefs/data_load.go

bugfix: fix jindoruntime set image info with fallthrough switch cases

---

pkg/ddc/alluxio/delete_volume.go

this pr is to add a correct Copyright at the top of text
fixes #XXXX

add a correct Copyright at the top of text

---

api/v1alpha1/dataset_types.go
pkg/controllers/operation_controller.go
pkg/controllers/v1alpha1/databackup/implement.go
pkg/controllers/v1alpha1/dataload/implement.go
pkg/controllers/v1alpha1/datamigrate/datamigrate_controller.go
pkg/controllers/v1alpha1/datamigrate/implement.go
pkg/dataoperation/context.go
pkg/dataoperation/interface.go
pkg/ddc/base/operation.go
pkg/ddc/base/operation_lock.go
pkg/ddc/juicefs/operate.go
pkg/utils/datamigrate.go
pkg/utils/datamigrate_test.go
test/prow/fluid/fluidapi.py
test/prow/testcases/juicefs/juicefs_minio.py

refactor DataMigrateReconcile to use DataOperationReconcile.
fixes #2815 
existed data migration e2e tests

refactor DataMigrateReconcile to use DataOperationReconcile

---

pkg/utils/byte_size.go

change file

---

charts/fluid-datamigrate/juicefs/templates/datamigrate.yaml
charts/fluid-datamigrate/juicefs/values.yaml
pkg/datamigrate/value.go
pkg/ddc/juicefs/const.go
pkg/ddc/juicefs/data_migrate.go
pkg/ddc/juicefs/data_migrate_test.go

JuiceFS DataMigrate supports `pvc://` volume scheme
fixes #XXXX

JuiceFS DataMigrate supports PVC

---

pkg/utils/databackup.go

add Apache license for pkg/utils/databackup.go
NONE
only comments are added.

add license for pkg/utils/databackup.go

---

pkg/utils/annotations_test.go

This pr is to add Copyright at the beginning of the Apache License statement.
fixes #XXXX

Add Copyright at the beginning of the Apache License statement

---

pkg/ddc/jindofsx/master.go

This pr is to add lisence information to pkg/ddc/jindofsx/master.go.
NONE

add lisence information

---

pkg/utils/security/filter_test.go

This pr is to add Apache License to pkg/utils/security/filter_test.go
fixes #XXXX

Add apache license to pkg/utils/security/filter_test.go

---

pkg/controllers/v1alpha1/dataset/suite_test.go

add a sentence

---

pkg/utils/runtimes.go

This pr is to add Copyright to pkg/utils/runtimes.go
fixes #XXXX

This pr is to add Copyright to pkg/utils/runtimes.go

---

pkg/ddc/alluxio/operations/base_test.go

对其中pkg/ddc/alluxio/operations/base_test.go文件添加Apache License许可证
fixes #63
无需添加测试用例
根据说明文件中的情况2进行修改

add copyright at the beginning

---

pkg/utils/kubeclient/configmap.go

This pr is to add license at pkg/utils/kubeclient/configmap.go
fixes #XXXX

Add license at pkg/utils/kubeclient/configmap.go

---

pkg/utils/dataset/lifecycle/schedule_test.go

This pr is to add Copyright at "pkg/utils/dataset/lifecycle/schedule_test.go".

Adding Copyright at pkg/utils/dataset/lifecycle/schedule_test.go

---

charts/fluid/fluid/Chart.yaml
charts/fluid/fluid/values.yaml

Update docker images for efcruntime

---

pkg/utils/excluisve_test.go

excluisve_test.go
