- docs/zh/samples/juicefs/juicefs_data_migrate.md
- docs/zh/samples/juicefs/juicefs_worker.md
> add pvc for datamigrate docs

- pkg/ddc/alluxio/operations/base_test.go
- pkg/ddc/jindofsx/transform.go
- pkg/utils/quantity.go
JindoRuntime supports Mi storage unit
fixes #2707
> JindoRuntime supports Mi storage unit

- pkg/utils/version/version_test.go
This pr is to add Apache License for pkg/utils/version/version_test.go
> add Apache License for version_test.go

- pkg/utils/slice_test.go
Add Apache License to file /pkg/utils/slice_test.go
> Task 114: Add Apache License to file /pkg/utils/slice_test.go

- pkg/utils/common_test.go
> This pr is to add copyright of task 138

- pkg/utils/errors_test.go
This pr is to add Apache License to pkg/utils/errors_test.go
fixes #XXXX
> I modified pkg/utils/errors_test.go

- pkg/utils/kubeclient/daemonset.go
I Modified file pkg/utils/kubeclient/daemonset.go, the 186 task.
fixes #XXXX
> Modified file pkg/utils/kubeclient/daemonset.go

- charts/fluid/fluid/templates/controller/juicefsruntime_controller.yaml
- charts/fluid/fluid/values.yaml
- cmd/juicefs/app/juicefs.go
add runtime-workers parameter in juicefs controller
> add runtime-workers parameter in juicefs controller

- pkg/utils/mount.go
This pr is to add.Copyright to /fluid/pkg/utils/mount.go.
fixes #XXXX
> This pr is to add Copyright to /fluid/pkg/utils/mount.go-Task164

- pkg/utils/byte_size_test.go
This pr is to add Apache License to pkg/utils/byte_size_test.go
fixes #XXXX
> This pr is to add Apache Lisence to pkg/utils/byte_size_test.go

- pkg/utils/init_user_test.go
This pr is to add license at pkg/utils/init_user_test.go
> Add license at pkg/utils/init_user_test.go

- pkg/utils/security/filter.go
This PR is to add "Copyright 2023 The Fluid Authors." to pkg/utils/security/filter.go.
> task 170: modified pkg/utils/security/filter.go

- pkg/utils/label_test.go
> This pr is to add pkg/utils/label_test.go.

- pkg/utils/annotations.go
> add Copyright to head

- pkg/utils/dataset/lifecycle/schedule.go
This pr is to add copyright to Apache License.
> Add copyright to Apache License

- pkg/ddc/jindofsx/operations/cached.go
> add statement

- pkg/utils/ufs_path_builder.go
> This PR is to add Copyright to pkg/utils/ufs_path_builder.go

- pkg/utils/dataset/lifecycle/schedule_utils_test.go
This pr is to add "Copyright 2023 The Fluid Authors." to the end of file "pkg/utils/dataset/lifecycle/schedule_utils_test.go".
fixes #XXXX
> Task 192 Case 2

- pkg/utils/excluisve.go
> This PR is to add License to pkg/utils/excluisve.go

- pkg/utils/capabilities.go
> add license in capabilities.go

- pkg/utils/label.go
add apache license to label.go
fixes #XXXX
> task144 add apache license to label.go

- charts/efc/CHANGELOG.md
- charts/efc/templates/fuse/daemonset.yaml
- charts/efc/templates/master/statefulset.yaml
- charts/efc/templates/worker/statefulset.yaml
- charts/fluid/fluid/values.yaml
- docs/zh/troubleshooting/debug-fuse.md
- pkg/common/efc.go
- pkg/ddc/base/runtime_helper.go
- pkg/ddc/efc/const.go
- pkg/ddc/efc/create_volume.go
- pkg/ddc/efc/node_test.go
- pkg/ddc/efc/operations/base_test.go
- pkg/ddc/efc/sessmgr.go
- pkg/ddc/efc/shutdown.go
- pkg/ddc/efc/transform_image_test.go
- pkg/ddc/efc/utils.go
- pkg/ddc/efc/utils_test.go
- pkg/ddc/efc/worker_test.go
Refactor eacruntime yaml to efcruntime yaml
fixes #3122
> Refactor eacruntime yaml to efcruntime yaml

- pkg/utils/yaml_test.go
This PR is to add to finish my homework
fixes #XXXX
> This PR is to add to finish my homework

- pkg/common/label.go
为`pkg/common/label.go`添加Apache License许可证
fixes #XXXX
> Task_223 add License

- charts/fluid/fluid/Chart.yaml
- charts/fluid/fluid/values.yaml
> Update docker images for refactoring efcruntime

- pkg/ddc/efc/types.go
- pkg/ddc/efc/utils.go
- pkg/ddc/efc/utils_test.go
- pkg/utils/yaml_test.go
This PR removes AK/SK related logic for EFCRuntime, which is not used by EFC system.
fixes #3147
> refactor: remove efc redundant code logic

- charts/fluid/fluid/templates/webhook/webhookconfiguration.yaml
- charts/fluid/fluid/values.yaml
> add reinvocationPolicy

- pkg/utils/dataset/volume/create.go
Shorten binding process for Fluid PV and PVCs. This PR checks PV's available status after creating a PV which can avoids  PVC reconcilation backoff and ensure that PV can be bound to PVC after PVC creation.
fixes #XXXX
> Shorten binding process for Fluid PV and PVCs

- pkg/ddc/thin/wrap_pvc.go
> No.86 添加注释权限，属于情况一

- pkg/common/deprecated/storage.go
add Copyright to pkg/common/deprecated/storage.go
fixes #3138
> add Copyright to pkg/common/deprecated/storage.go

- pkg/common/label_test.go
This PR is to add a copyright.
> add a copyright

- pkg/utils/docker/image.go
> This pr is to add License in the beginning of pkg/utils/docker/image.go

- pkg/utils/dataset/volume/deprecated.go
> This PR is to add copyright in pkg/utils/dataset/volume/deprecated.go, as described in task 199.

- pkg/utils/databackup_test.go
This pr is to correct the license in pkg/utils/databackup_test.go
> Correct a license

- pkg/controllers/v1alpha1/juicefs/suite_test.go
add "Copyright 2023 The Fluid Authors."
fixes #XXXX
> finish task 236

- pkg/utils/dataset/volume/delete_test.go
This pr is to add license to pkg/utils/dataset/volume/delete_test.go
> add Apache License to pkg/utils/dataset/volume/delete_test.go

- charts/fluid/fluid/Chart.yaml
- charts/fluid/fluid/values.yaml
> Update docker images for speeding up volume binding

- charts/fluid/fluid/values.yaml
- charts/juicefs/CHANGELOG.md
- charts/juicefs/Chart.yaml
- charts/juicefs/templates/fuse/daemonset.yaml
- charts/juicefs/values.yaml
- pkg/common/juicefs.go
- pkg/ddc/juicefs/transform_fuse.go
- pkg/ddc/juicefs/transform_fuse_test.go
- pkg/ddc/juicefs/type.go
- pkg/ddc/juicefs/utils.go
- pkg/ddc/juicefs/utils_test.go
> support subpath quota for juicefs runtime

- pkg/ddc/juicefs/data_migrate.go
- pkg/ddc/juicefs/data_migrate_test.go
- pkg/utils/docker/image_test.go
> fix subpath of dataset in datamigrate

- pkg/utils/errors.go
> add Apache License in error.go

- pkg/utils/kubeclient/volume_test.go
This pr is to add copyright to pkg/utils/kubeclient/volume_test.go.
> add copyright to pkg/utils/kubeclient/volume_test.go

- docs/zh/TOC.md
- docs/zh/samples/juicefs/juicefs_dataset.md
- docs/zh/samples/juicefs/juicefs_setup.md
> add quota docs for juicefs

- pkg/utils/kubeclient/deployment.go
This pr is to add Apache License at the beginning of file "pkg/utils/kubeclient/deployment.go".
> This pr is to add Apache License at the beginning of file "pkg/utils/kubeclient/deployment.go".

- pkg/utils/kubeclient/exec_test.go
This pr is to add pkg/utils/kubeclient/exec_test.go
fixes #XXXX
> 2023.4.25lab1

- pkg/ddc/jindofsx/transform.go
> fix fuse default args for readOnly and write

- README.md
> Update docs of overview

- pkg/common/runtime_identity.go
> This pr is to add Apache License of /pkg/common/runtime_identity.go

- pkg/utils/kubeclient/volume_claim_test.go
update license for pkg/utils/kubeclient/volume_claim_test.go
NONE
None. Just a license update.
> license update with signature (recommiting with personal signature)

- ADOPTERS.md
> add DPTechnology

- pkg/utils/kubeclient/volume.go
> Added License to pkg/utils/kubeclient/volume.go

- pkg/utils/helm/utils_test.go
This pr is to add Apache License in pkg/utils/helm/utils_test.go
fixes #XXXX
> Lab1 Task2

- docs/en/dev/how_to_develop.md
- docs/zh/dev/how_to_develop.md
add guide to debug webhook locally
fixes #3197
> doc: add guide to debug webhook locally

- charts/efc/templates/fuse/daemonset.yaml
- charts/efc/templates/master/statefulset.yaml
- charts/efc/templates/worker/statefulset.yaml
- charts/efc/values.yaml
- charts/fluid/fluid/templates/controller/efcruntime_controller.yaml
- charts/fluid/fluid/values.yaml
- docs/zh/samples/efc_runtime.md
- docs/zh/troubleshooting/debug-fuse.md
- pkg/common/efc.go
- pkg/ddc/efc/const.go
- pkg/ddc/efc/master_internal_test.go
- pkg/ddc/efc/sessmgr.go
- pkg/ddc/efc/transform.go
- pkg/ddc/efc/transform_image.go
- pkg/ddc/efc/transform_image_test.go
- pkg/ddc/efc/transform_option.go
- pkg/ddc/efc/transform_option_test.go
- pkg/ddc/efc/transform_test.go
- pkg/ddc/efc/types.go
- pkg/ddc/efc/ufs_test.go
- pkg/ddc/efc/utils.go
- pkg/ddc/efc/utils_test.go
refactor efcruntime images and support cpfs
fixes #3199
> Refactor efc images

- charts/fluid/fluid/Chart.yaml
- charts/fluid/fluid/values.yaml
- pkg/utils/kubeclient/node_test.go
> Docker build for removing metadatalist from runtime

- charts/efc/templates/fuse/daemonset.yaml
- charts/efc/templates/master/statefulset.yaml
- charts/efc/templates/worker/statefulset.yaml
- charts/fluid/fluid/values.yaml
- pkg/ddc/efc/sessmgr.go
efcruntime remove unreasonable config to support eci features
fixes #3205
> efcruntime remove unreasonable config to support eci features

- pkg/ddc/base/runtime_helper.go
Trim efc-sock volume for fuse sidecar injection
NONE
> Trim efc-sock volume for fuse sidecar injection

- charts/fluid/fluid/Chart.yaml
- charts/fluid/fluid/values.yaml
> Update docker images for efcruntime on serverless container

- charts/fluid/fluid/Chart.yaml
- charts/fluid/fluid/values.yaml
> Build docker images for fixing CSI Plugin's node related access

- charts/efc/templates/master/statefulset.yaml
remove init container and sessmgr in efc-master yaml
fixes #3215
> fix(efcruntime): remove init container and sessmgr in efc-master yaml

- charts/fluid/fluid/Chart.yaml
- charts/fluid/fluid/values.yaml
> Build docker images for default reinvocationPolicy as IfNeeded

- charts/alluxio/templates/master/statefulset.yaml
- charts/alluxio/templates/worker/statefulset.yaml
- charts/goosefs/templates/master/statefulset.yaml
- charts/goosefs/templates/worker/statefulset.yaml
- test/prow/testcases/common/dataset_pvc_subpath.py
add e2e test to validate dataset using pvc subpath
fixes #XXXX
> add e2e test to validate dataset using pvc subpath

- Makefile
- charts/fluid/fluid/Chart.yaml
> Update to 0.8.7

- docker/Dockerfile.alluxioruntime
- docker/Dockerfile.application
- docker/Dockerfile.dataset
- docker/Dockerfile.efcruntime
- docker/Dockerfile.goosefsruntime
- docker/Dockerfile.jindoruntime
- docker/Dockerfile.juicefsruntime
- docker/Dockerfile.thinruntime
update helm to 3.11.3
fixes #XXXX
> update helm to 3.11.3

- charts/efc/templates/fuse/daemonset.yaml
> fix(efcruntime): add prefix efc to /dev/shm volume when eci

- charts/fluid/fluid/Chart.yaml
- charts/fluid/fluid/templates/webhook/webhookconfiguration.yaml
- charts/fluid/fluid/values.yaml
> Change reinvocationPolicy to IfNeeded

- pkg/ddc/alluxio/transform_fuse_test.go
- pkg/ddc/alluxio/transform_optimization.go
- pkg/ddc/alluxio/transform_optimization_test.go
* fix when alluxioruntime fuse args set, add mountPath in args
Author:    sichen.zhao <sichen.zhao@outlook.com>
Date:      Thu Sep 15 22:04:13 2022 +0800
* update fuse unit test TransformFuseWithArgs
Cherry-pick #2135
NONE
> Cherry-pick bugfix for setting fuse args when using Alluxio 2.8+

- charts/fluid/fluid/Chart.yaml
- charts/fluid/fluid/values.yaml
> Build docker images for removing secret in jindoruntime

- charts/fluid/fluid/Chart.yaml
- charts/fluid/fluid/values.yaml
> Build docker images for jindoruntime secret mount enhancement

- integration/kserve/kserve-runtimes.yaml
- integration/kserve/kserve.yaml
> Integrate with KServe

- pkg/ddc/jindofsx/transform.go
> fix trun off metrics port with jindofuse

- charts/fluid/fluid/Chart.yaml
- charts/fluid/fluid/values.yaml
> Build docker images for metrics port

- CHANGELOG.md
- README-zh_CN.md
- README.md
- charts/fluid/fluid/Chart.yaml
- charts/fluid/fluid/values.yaml
- docs/en/userguide/install.md
- docs/zh/userguide/install.md
> Prepare release 0.9

- pkg/scripts/poststart/check_fuse.go
- test/prow/testcases/jindofsx/jindo_oss.py
- test/prow/testcases/jindofsx/jindo_oss_fusesidecar.py
bugfix: fix jindo-fuse postStart script to make sure fuse mountpoint is ready
NONE
> bugfix: fix jindo-fuse postStart script to make sure fuse mountpoint is ready

- addons/cephfs/dev-guide/cephfs-zh_CN.md
- addons/cephfs/dev-guide/cephfs.md
- addons/cephfs/docker/Dockerfile
- docker/Dockerfile.alluxioruntime
- docker/Dockerfile.application
- docker/Dockerfile.crds
- docker/Dockerfile.csi
- docker/Dockerfile.dataset
- docker/Dockerfile.efcruntime
- docker/Dockerfile.goosefsruntime
- docker/Dockerfile.jindoruntime
- docker/Dockerfile.juicefsruntime
- docker/Dockerfile.thinruntime
- docker/Dockerfile.webhook
> Update alpine 3.17 to 3.18

- charts/fluid/fluid/Chart.yaml
- charts/fluid/fluid/values.yaml
> Prepare docker image for alpine 3.18

- charts/fluid-dataloader/jindofsx/templates/configmap.yaml
- charts/fluid-dataloader/jindofsx/templates/dataloader.yaml
- charts/fluid/fluid/values.yaml
- charts/fluid/v0.8.0/values.yaml
- charts/jindofsx/CHANGELOG.md
- charts/jindofsx/Chart.yaml
- charts/jindofsx/values.yaml
- pkg/ddc/jindofsx/const.go
- pkg/ddc/jindofsx/transform.go
- pkg/ddc/jindofsx/transform_fuse_test.go
- pkg/ddc/jindofsx/transform_test.go
- pkg/utils/jindo/jindo.go
```yaml
kind: DataLoad
metadata:
name: test
spec:
dataset:
name: test
namespace: default
loadMetadata: true
target:
- path: /test
replicas: 1
options:
filter: "*.log"
threadNum: "2"
dryrun: "true"
```
fixes #XXXX
> fix support dataload with filter and upgrade to 4.6.8 for jindoruntime

- api/v1alpha1/dataset_types.go
- api/v1alpha1/dataset_types_test.go
- pkg/controllers/v1alpha1/datamigrate/implement.go
- pkg/ddc/base/operation_lock.go
- pkg/ddc/base/operation_lock_test.go
Delete lock of dataset in data operate. Let users to ensure data consistency.
> del lock of dataset in data operate

- charts/fluid/fluid/Chart.yaml
- charts/fluid/fluid/values.yaml
> Build docker image for data operation refactoring

- api/v1alpha1/dataset_types.go
> fix dataoperation when nil

- Makefile
- charts/fluid/fluid/Chart.yaml
> Prepare 0.9.1

- pkg/ddc/alluxio/transform_optimization.go
> Fix default Alluxio writetype config (#3262)

- charts/fluid/fluid/Chart.yaml
- charts/fluid/fluid/values.yaml
> Build docker images for cron data migrate

- pkg/utils/helm/utils.go
Fluid uses `helm install` to deploy runtime-related resources into K8s cluster. However, `helm install` may fail due to multiple causes, e.g. API Server rate limiting, helm rendering problem, rbac, etc. Currently, Fluid only prints error message in controller's log which is not friendly for users that want to know why his or her runtime fail to setup.
This PR wraps error message in the returned error when failing to helm install. Then the error will be returned and print in event so that users can easily find where it goes wrong.
For example, a chart rendering problem be like:
```
Events: …
```
> Print error message when failing to helm install

- charts/fluid-datamigrate/juicefs/templates/cronjob.yaml
- cmd/dataset/app/dataset.go
- pkg/common/constants.go
- pkg/controllers/v1alpha1/datamigrate/datamigrate_controller.go
fixes [#3264](https://github.com/fluid-cloudnative/fluid/issues/3264)
> add labelSelector of cronjob in datamigrate controller

- charts/fluid/fluid/Chart.yaml
- charts/fluid/fluid/values.yaml
> Build docker image for optimzing runtimeinfo

- charts/jindofsx/CHANGELOG.md
- charts/jindofsx/templates/fuse/daemonset.yaml
- charts/jindofsx/templates/master/statefulset.yaml
- charts/jindofsx/templates/worker/statefulset.yaml
- pkg/ddc/jindofsx/transform.go
- pkg/ddc/jindofsx/transform_test.go
- pkg/ddc/jindofsx/types.go
> fix jindoruntime support pvc subpath

- charts/fluid/fluid/templates/upgrade/crd-upgrade.yaml
- charts/fluid/fluid/values.yaml
This PR introduce enabled flag for crdUpgrade in charts，default value is true.  Skip crd upgrading when install fluid if set this flag to false 
fixes #XXXX
> Feat: add crdUpgrade enabled flag

- charts/fluid/fluid/Chart.yaml
- charts/fluid/fluid/values.yaml
> Build docker image for fixing jindoruntime subpath for pvc

- charts/fluid/fluid/Chart.yaml
- charts/fluid/fluid/values.yaml
> Build docker image for fixing  cron data migrate

- charts/fluid/fluid/Chart.yaml
- charts/fluid/fluid/values.yaml
> Build docker image for release 0.9.1

- api/v1alpha1/dataset_types.go
- api/v1alpha1/dataset_types_test.go
- pkg/ddc/base/operation_lock.go
- pkg/ddc/juicefs/dataset.go
- test/prow/testcases/juicefs/juicefs_minio.py
fix operationRef keep add the same name when using cron datamigrate
fixes #XXXX
> fix operationRef dup

- test/prow/testcases/juicefs/juicefs_minio.py
> fix keyerror in e2e test

- charts/fluid/fluid/Chart.yaml
- charts/fluid/fluid/values.yaml
> Build docker image for making csi more robust

- pkg/utils/volume_lock.go
- pkg/utils/volume_lock_test.go
add ut for volume_lock
pkg/utils/volume_lock_test.go
run unit test in pkg/utils/volume_lock_test.go
> add ut for volume_lock

- test/prow/scale_runtime.py
add e2e testcase 11, scale alluxio runtime
fixes #XXXX
> test: add e2e testcase 11, scale alluxio runtime

- charts/fluid/fluid/Chart.yaml
- charts/fluid/fluid/values.yaml
> Build docker images for removing rbac of listing secret

- pkg/ddc/alluxio/transform_optimization.go
> fix default master journal type setting (#3281)

- ADOPTERS.md
Add [Megvii](https://megvii.com) adopters
No
> feat: add megvii adopters

- charts/fluid/fluid/Chart.yaml
- charts/fluid/fluid/values.yaml
> Build docker images for removing secrets dependency of juicefs

- ADOPTERS.md
Apply fluid to production in coscene.
> docs: apply fluid to production

- charts/fluid/fluid/Chart.yaml
- charts/fluid/fluid/values.yaml
> Support configurable helm driver

- ADOPTERS.md
This pull request adds new entry in the adopters table located in ADOPTERS.md file.  
NONE
When deciding on the scope of testing for a feature or change, we typically prioritize tests that cover critical functionality, potential edge cases, and areas of higher complexity or risk. In the case of adding new entry to the adopters table, it may be considered a relatively minor change with low impact on the overall functionality of the system.
N/A
Thanks for attention.
> Add PITS Globale Datenrettungsdienste as an adopter

- ADOPTERS.md
> Add Tusen as a new adopter

- charts/fluid/fluid/Chart.yaml
- charts/fluid/fluid/values.yaml
> Build docker images for cronload

- charts/fluid-dataloader/alluxio/templates/job.yaml
- charts/fluid-dataloader/goosefs/templates/job.yaml
- charts/fluid-dataloader/jindo/templates/job.yaml
- charts/fluid-dataloader/jindofsx/templates/job.yaml
- charts/fluid-dataloader/juicefs/templates/job.yaml
- charts/fluid-datamigrate/juicefs/templates/job.yaml
- pkg/controllers/v1alpha1/dataload/status_handler.go
- pkg/controllers/v1alpha1/datamigrate/status_handler.go
- pkg/utils/dataload_test.go
- pkg/utils/datamigrate_test.go
- pkg/utils/kubeclient/job.go
- pkg/utils/kubeclient/job_test.go
fix the issues in https://github.com/fluid-cloudnative/fluid/pull/3309#discussion_r1251904809
fixes #XXXX
> add job.go in kubeclient and modify the judgement conditions for job 

- charts/fluid/fluid/Chart.yaml
- charts/fluid/fluid/values.yaml
> Build docker images for removing secrets dependency

- charts/fluid/fluid/CHANGELOG.md
- charts/fluid/fluid/templates/csi/daemonset.yaml
> Mount kubelet.conf with  HostToContainer mount propagation

- pkg/controllers/v1alpha1/dataload/dataload_controller.go
fix cron dataload for k8s 1.20
fixes #3328
> bugfix: fix cron dataload for k8s 1.20

- charts/fluid/fluid/Chart.yaml
- charts/fluid/fluid/values.yaml
> Build docker images for fixing cron dataload

- charts/fluid/fluid/templates/role/dataset/rbac.yaml
- docs/zh/samples/thinruntime.md
Related to #3323 
#3323 changes code logic when handling secrets in ThinRuntime controller, which means users must read their sensitive data from a given file path. This PR changes the thinruntime doc to show how to use ThinRuntime in the new version.
fixes #3333
> docfix: update thinruntime usage doc

- pkg/controllers/v1alpha1/dataset/dataset_controller.go
- pkg/utils/dataset_reference.go
- pkg/utils/dataset_reference_test.go
check reference dataset existence in reconcileDatasetDeletion
fixes #XXXX
> check reference dataset existence in reconcileDatasetDeletion

- pkg/controllers/runtime_controller.go
Ignore already exists error for CreateVolume
fixes #3308
> bugfix: fix error log in createvolume

- charts/fluid/fluid/Chart.yaml
- charts/fluid/fluid/values.yaml
> Build docker images for thin runtime stuck issue

- test/prow/fluid/fluidapi.py
- test/prow/testcases/common/cron_dataload.py
- test/prow/testcases/common/csi_stale_patch.py
Add e2e test to verify cron dataload. 
fixes #XXXX
test/prow/testcases/common/cron_dataload.py
Run e2e test.
> add cron dataload e2e test

- csi/shell/check_bind_mounts.sh
> Use mountinfo to check mountinfo

- charts/fluid/fluid/Chart.yaml
- charts/fluid/fluid/values.yaml
> Build docker image for jindoCache

- charts/fluid/fluid/Chart.yaml
- charts/fluid/fluid/values.yaml
- pkg/ddc/alluxio/transform_fuse_test.go
> Docker build 0.8.7

- docker/Dockerfile.jindoruntime
> fix jindoruntime dockerfile

- ADOPTERS.md
Add Dewu as a new adopter
None
> Add Dewu as a new adopter

- pkg/ddc/jindocache/transform.go
> Fix JindoCache OSS-HDFS AK Transform

- charts/fluid/fluid/templates/role/dataset/rbac.yaml
Bugfix for e2e test failure beacause of incomplete rbac.
NONE
> Fix dataprocess rbac for dataset controller

- Makefile
- charts/fluid/fluid/Chart.yaml
> Update to 0.8.8

- csi/shell/entrypoint.sh
- docs/en/userguide/install.md
- docs/zh/userguide/install.md
update install doc with configure kubelet rootdir
fixes #XXXX
> enhancement: update install doc with configure kubelet rootdir

- charts/fluid/fluid/CHANGELOG.md
- charts/fluid/fluid/templates/controller/alluxioruntime_controller.yaml
- charts/fluid/fluid/templates/controller/dataset_controller.yaml
- charts/fluid/fluid/templates/controller/efcruntime_controller.yaml
- charts/fluid/fluid/templates/controller/fluidapp_controller.yaml
- charts/fluid/fluid/templates/controller/goosefsruntime_controller.yaml
- charts/fluid/fluid/templates/controller/jindoruntime_controller.yaml
- charts/fluid/fluid/templates/controller/juicefsruntime_controller.yaml
- charts/fluid/fluid/templates/controller/thinruntime_controller.yaml
- charts/fluid/fluid/templates/csi/daemonset.yaml
- charts/fluid/fluid/templates/webhook/webhook.yaml
- charts/fluid/fluid/values.yaml
- tools/crd-upgrade/upgrade-crds.sh
make toleration configurable in helm charts
fixes #3347
> feature: make toleration configurable in helm charts

- charts/fluid/fluid/Chart.yaml
- charts/fluid/fluid/values.yaml
> Build docker image for cron data operations

- ADOPTERS.md
> ADOPTERS.md dp phase update

- pkg/controllers/v1alpha1/databackup/status_handler_test.go
- pkg/controllers/v1alpha1/dataload/status_handler_test.go
- pkg/controllers/v1alpha1/datamigrate/status_handler_test.go
- pkg/controllers/v1alpha1/dataprocess/status_handler_test.go
add unit test for status_handler.go
fixes #XXXX
pkg/controllers/v1alpha1/databackup/status_handler_test.go
pkg/controllers/v1alpha1/dataload/status_handler_test.go
pkg/controllers/v1alpha1/datamigrate/status_handler_test.go
pkg/controllers/v1alpha1/dataprocess/status_handler_test.go
> add ut for status_handler

- Makefile
- charts/fluid/fluid/Chart.yaml
> Prepare 0.9.2

- charts/fluid/fluid/Chart.yaml
- charts/fluid/fluid/values.yaml
> Build docker images for fixing controller's OOM

- charts/fluid-dataprocess/common/templates/job.yaml
- charts/fluid-dataprocess/common/values.yaml
- pkg/dataprocess/generate_values.go
- pkg/dataprocess/value.go
> Support service account name for DataProcess

- charts/fluid/fluid/templates/controller/juicefsruntime_controller.yaml
- charts/fluid/fluid/values.yaml
- pkg/common/juicefs.go
- pkg/ddc/juicefs/data_load.go
- pkg/ddc/juicefs/data_migrate.go
- pkg/ddc/juicefs/transform.go
- pkg/ddc/juicefs/transform_fuse.go
- pkg/ddc/juicefs/transform_fuse_test.go
- pkg/ddc/juicefs/transform_test.go
- pkg/ddc/juicefs/utils.go
- pkg/ddc/juicefs/utils_test.go
> [JuiceFS] split ce&ee image

- charts/fluid/fluid/Chart.yaml
- charts/fluid/fluid/values.yaml
> Build docker images for fixing juicefs startup issue

- charts/fluid/fluid/templates/role/juicefs/rbac.yaml
- charts/juicefs/templates/fuse/daemonset.yaml
- charts/juicefs/templates/role/rbac.yaml
- charts/juicefs/templates/worker/statefuleset.yaml
- cmd/juicefs/app/juicefs.go
- pkg/controllers/manager.go
- pkg/ddc/juicefs/master_internal_test.go
- pkg/ddc/juicefs/shutdown.go
- pkg/ddc/juicefs/shutdown_test.go
- pkg/ddc/juicefs/utils.go
- pkg/utils/kubeclient/pod_test.go
- pkg/utils/kubeclient/rbac.go
- pkg/utils/kubeclient/rbac_test.go
add ownerReference in resource & remove residual resource
> add ownerReference in resource & remove residual resource

- docs/en/dev/how_to_develop.md
- docs/zh/dev/how_to_develop.md
build fluid compnent
fixes #XXXX
> docs: build fluid compnent

- docs/zh/samples/juicefs/juicefs_cache_dir.md
> add fuse option doc

- pkg/ddc/juicefs/transform_resources.go
fixes https://github.com/fluid-cloudnative/fluid/issues/3413
> fix fuse memory limit when cache-size set in fuse.options

- docs/zh/troubleshooting/debug-fuse.md
> Update debug-fuse doc

- charts/fluid/fluid/Chart.yaml
- charts/fluid/fluid/values.yaml
> Docker build  for fixing juice fuse option

- charts/fluid/fluid/Chart.yaml
- charts/fluid/fluid/values.yaml
> Build docker images for refactoring alluxio

- charts/alluxio/templates/master/statefulset.yaml
alluxio using post start instead of startup probe when k8s version is less than 1.18
SEE https://github.com/fluid-cloudnative/fluid/pull/3378#discussion_r1301174164
> alluxio using post start instead of startup probe when k8s version is less than 1.18

- charts/fluid/fluid/templates/role/juicefs/rbac.yaml
- pkg/common/constants.go
- pkg/ddc/juicefs/sync_runtime.go
- pkg/ddc/juicefs/sync_runtime_test.go
- pkg/ddc/juicefs/utils.go
- pkg/ddc/juicefs/utils_test.go
support https://github.com/fluid-cloudnative/fluid/issues/3409
worker in runtime can update the following configs:
1. nodeSelector
2. image
3. volumes & volumeMounts
4. labels & annotations
5. options
6. resources
7. envs
fixes #XXXX
> support worker of juicefs can be update by runtime

- charts/fluid/fluid/Chart.yaml
- charts/fluid/fluid/values.yaml
> Build docker images for juicefsruntime

- pkg/common/constants.go
- pkg/csi/recover/recover.go
umountDuplicate mountpoint when it has been mounted larger than the recoverWarningThreshold
fixes #XXXX
> umountDuplicate larger than the threshold

- charts/fluid/fluid/Chart.yaml
- charts/fluid/fluid/values.yaml
> Fix duplicate mount issue

- pkg/ddc/jindocache/transform.go
- pkg/ddc/jindocache/transform_test.go
- pkg/ddc/jindofsx/transform.go
- pkg/ddc/jindofsx/transform_test.go
> Add conf to enable/disable memLimit

- csi/shell/entrypoint.sh
Cherry-pick #3331 to 0.9
fixes #XXXX
> fail fast with wrong kubelet rootdir (#3331)

- pkg/ddc/jindocache/const.go
- pkg/ddc/jindocache/transform.go
- pkg/ddc/jindocache/transform_test.go
> Fix JindoCache support more writePolicy

- ADOPTERS.md
add KubeDL as one of the adopters.
fixes #XXXX
None
None
> docs: add KubeDL as one of the adopters.

- charts/fluid/fluid/Chart.yaml
- charts/fluid/fluid/values.yaml
> Build docker images for release 0.9.2

- charts/fluid/fluid/Chart.yaml
- charts/fluid/fluid/values.yaml
> Build docker images for fixing shared option issue

- charts/fluid/fluid/templates/csi/daemonset.yaml
- charts/fluid/fluid/values.yaml
- pkg/common/label.go
- pkg/common/volume.go
- pkg/csi/plugins/nodeserver.go
- pkg/csi/recover/register.go
- pkg/utils/dataset/volume/create.go
- pkg/utils/symlink.go
- test/prow/fluid/fluidapi.py
- test/prow/testcases/common/csi_nodepublish_symlink.py
support csi plugin use symlink for NodePublishVolum by add annotation in runtime, such as below:
- data.fluid.io/metadataList: "[{"Labels": {"fluid.io/node-puhlish-method": "symlink"}, "selector": { "kind": "PersistentVolume"}}]"
fixes #XXXX
> Feature: support symlink for NodePublish

- charts/fluid/fluid/Chart.yaml
- charts/fluid/fluid/values.yaml
> Build docker images for symlink support

- pkg/controllers/operation_controller.go
- pkg/controllers/v1alpha1/databackup/databackup_controller.go
- pkg/controllers/v1alpha1/dataload/dataload_controller.go
- pkg/controllers/v1alpha1/datamigrate/datamigrate_controller.go
- pkg/controllers/v1alpha1/dataprocess/dataprocess_controller.go
- pkg/dataoperation/interface.go
- pkg/ddc/alluxio/operate.go
- pkg/ddc/base/engine.go
- pkg/ddc/base/mock/mock_engine.go
- pkg/ddc/base/operation.go
- pkg/ddc/base/operation_helm.go
- pkg/ddc/base/operation_lock.go
- pkg/ddc/efc/operate.go
- pkg/ddc/goosefs/operate.go
- pkg/ddc/jindo/operate.go
- pkg/ddc/jindocache/operate.go
- pkg/ddc/jindofsx/operate.go
- pkg/ddc/juicefs/operate.go
- pkg/ddc/thin/operate.go
- pkg/ddc/thin/referencedataset/engine.go
- pkg/utils/dataoperation.go
- pkg/utils/dataoperation_test.go
> Refactor ttl

- charts/fluid/fluid/Chart.yaml
- charts/fluid/fluid/values.yaml
> Build docker images for jindofuse bug fix

- charts/fluid/fluid/Chart.yaml
- charts/fluid/fluid/values.yaml
> Build docker images for tiered scheduling

- pkg/controllers/v1alpha1/databackup/implement.go
- pkg/controllers/v1alpha1/dataload/implement.go
- pkg/controllers/v1alpha1/datamigrate/implement.go
- pkg/controllers/v1alpha1/dataprocess/implement.go
- pkg/dataoperation/interface.go
- pkg/dataoperation/mock.go
- pkg/ddc/base/operation.go
- pkg/utils/dataoperation.go
- pkg/utils/dataoperation_test.go
> Refactor ttl phase 2

- charts/fluid/fluid/values.yaml
- docs/en/TOC.md
- docs/en/operation/pod_schedule_optimization.md
- docs/en/operation/tiered_locality_schedule.md
- docs/zh/TOC.md
- docs/zh/operation/pod_schedule_optimization.md
- docs/zh/operation/tiered_locality_schedule.md
- pkg/webhook/plugins/nodeaffinitywithcache/tiered_locaity.go
- pkg/webhook/plugins/nodeaffinitywithcache/tiered_locaity_test.go
Add tiered locality sceduling docs and set the default tiered locality configuration.
fixes NONE
> add tiered locality sceduling docs and set the default tiered locality configuration

- charts/fluid/fluid/Chart.yaml
- charts/fluid/fluid/values.yaml
> Build docker images for webhook refactoring

- tools/crd-upgrade/upgrade-crds.sh
> Fix helm upgrade issue due to no patch permission

- charts/fluid/fluid/Chart.yaml
- charts/fluid/fluid/values.yaml
> Build docker images for fixing helm upgrade

- charts/fluid/fluid/Chart.yaml
- charts/fluid/fluid/values.yaml
> Build docker image for crd upgrader

- pkg/ddc/jindo/health_check_test.go
Updated copyright of pkg/ddc/jindo/health_check_test.go
NONE
Just updated a license
Nothing to do
NONE
> Updated copyright

- pkg/ddc/goosefs/replicas.go
This pr is to modify the License of fluid\pkg\ddc\goosefs
> Modify the License of fluid\pkg\ddc\goosefs

- charts/fluid/fluid/templates/webhook/tiered-conf.yaml
- charts/fluid/fluid/values.yaml
Add a flag to control whether update the tiered locality configmap content or not
fixes #XXXX
> add a flag to control whether update the tiered locality configmap content or not

- pkg/ddc/jindo/operate.go
Ⅰ. This pr is to add a modification to pkg/ddc/jindo/operate.go
> modify the license of pkg/ddc/jindo/operate.go

- ADOPTERS.md
Added Happy Elements as one of the adopters
NONE
No need for change document.
Read it again.
None
> PR: docs: added Happy Elements as one of the adopters

- pkg/ddc/goosefs/operations/local_test.go
> Ⅰ: This pr is to update license in pkg/ddc/goosefs/operations/local_test.go

- pkg/ddc/jindofsx/transform.go
This pr is to update license in pkg/ddc/jindofsx/transform.go.
> This pr is to update license in pkg/ddc/jindofsx/transform.go

- pkg/ddc/goosefs/create_volume.go
This pr is to add update apache license in "pkg/ddc/goosefs/create_volume.go"
> This pr is to add update apache license in "pkg/ddc/goosefs/create_volume.go"

- pkg/ddc/efc/dataset_test.go
This PR is to update the apache license for pkg/ddc/efc/dataset_test.go
> Update apache license for pkg/ddc/efc/dataset_test.go

- pkg/ddc/juicefs/sync_runtime.go
- pkg/ddc/juicefs/utils.go
fuse in runtime can update the following configs:
1. nodeSelector
2. image
3. volumes & volumeMounts
4. labels & annotations
5. options
6. resources
7. envs
FUSE daemonset's updateStrategy is onDelete by default. FUSE pod can only be recreated when it is deleted manually.
fixes #XXXX
> juicefs: make juicefsruntime.spec.fuse configurale

- charts/fluid/fluid/Chart.yaml
- charts/fluid/fluid/values.yaml
> Build docker images for configurable juicefs runtime

- charts/fluid/fluid/templates/upgrade/crd-upgrade.yaml
> Fix upgrade job has dots issue, To #51060667

- pkg/ddc/alluxio/transform_init_users_test.go
this is pr to delete a blank line to normalize license
fixes #XXXX
> delete a blank line to normalize license

- pkg/ddc/jindocache/transform.go
- pkg/ddc/jindofsx/transform.go
> fix jindoruntime default parameter

- pkg/utils/dataset/lifecycle/node_test.go
> This pr is to add Apache License for node_test.go

- docs/en/samples/fuse_clean_policy.md
- docs/zh/samples/fuse_clean_policy.md
Fix the error in Fuse cleanPolicy document.
fixes #3552
> Fix error in fuse cleanPolicy document

- pkg/ddc/goosefs/transform_hadoop_config.go
This pr is to modify 2022 to 2023 in pkg/ddc/goosefs/transform_hadoop_config.go.
> modify 2022 to 2023 in pkg/ddc/goosefs/transform_hadoop_config.go

- pkg/ddc/jindo/transform_test.go
This pr is to update the license in pkg/ddc/jindo/transform_test.go
> Update the license in pkg/ddc/jindo/transform_test.go

- docs/en/TOC.md
- docs/en/samples/automatic_clean_up_data_operation.md
- docs/zh/TOC.md
- docs/zh/samples/automatic_clean_up_data_operation.md
Add docs for  automatic clean up data operation
fixes #XXXX
> Docs: automatic clean up data operation

- docs/en/userguide/faq.md
- docs/zh/userguide/faq.md
fixes #XXXX
This is my first PR, If there are any inaccuracies, I hope you can correct me.
> Optimize documents and synchronize English versions

- .gitignore
- .gitmodules
- api/v1alpha1/swagger.json
- hack/sdk/gen-sdk.sh
- hack/sdk/swagger_config.json
- Make [fluid-python-sdk](https://github.com/fluid-cloudnative/fluid-client-python) and [fluid-java-sdk](https://github.com/fluid-cloudnative/fluid-client-java) submodules of the main Fluid repo.
- Modify sdk package files for fast-installation (e.g. pip install fluid)
NOTE: When updating Fluid sdk packages 
1. `git clone --recurse-submodules https://github.com/fluid-cloudnative/fluid.git`.
2. `make gen-sdk`
3. `cd sdk/python && git push origin master`
NONE
See https://github.com/fluid-cloudnative/fluid-client-python for the generated files.
> enhancement: update gen-sdk tool

- hack/sdk/gen-sdk.sh
> Update gen-sdk script

- docs/zh/samples/dataset_across_namespace_with_csi.md
- docs/zh/samples/dataset_across_namespace_with_sidecar.md
- docs/zh/samples/dataset_mount_dataset_subpath.md
> docs: fix 命名空间

- pkg/utils/kubeclient/exec.go
To add license for pkg/utils/kubeclient/exec.go
fixes #NONE
> add license for exec.go

- pkg/ddc/efc/data_process_test.go
This pr is to add license in pkg/ddc/efc/data_process_test.go.
> This pr is to add license in pkg/ddc/efc/data_process_test.go. 

- pkg/utils/kubeclient/deployment.go
change Author to Authors in pkg/utils/kubeclient/deployment.go
fixes #NONE
> change Author to Authors in pkg/utils/kubeclient/deployment.go

- charts/fluid/fluid/templates/webhook/webhook.yaml
- cmd/webhook/app/webhook.go
- docs/en/operation/tiered_locality_schedule.md
- docs/zh/operation/tiered_locality_schedule.md
- pkg/common/webhook.go
- pkg/webhook/plugins/plugins_impl.go
- pkg/webhook/plugins/plugins_impl_test.go
- pkg/webhook/scheduler/mutating/schedule_pod_handler_test.go
- test/prow/testcases/common/webhook_mutating.py
use configmap volume mount instead of go client api query.
fixes #XXXX
add a prow test to verify webhook mutating.
> webhook use configmap volume mount instead of api query

- pkg/ddc/jindocache/transform.go
- pkg/ddc/jindofsx/transform.go
> enhance: Mount ufs volumes according to datasets' accessModes

- Makefile
- charts/fluid/fluid/Chart.yaml
> Prepare 0.9.3

- docs/en/dev/use_go_create_resource.md
- docs/zh/dev/use_go_create_resource.md
This PR fix some typos in the document of using Go client.
fixes #3629
> Fix typos in using Go client document

- charts/fluid/fluid/values.yaml
Temporarily remove webhook plugins for serverless
NONE
> Temporarily remove webhook plugins for serverless

- ADOPTERS.md
> Add JoinQuant as a new adopter

- pkg/utils/ufs_path_builder_test.go
> modify pkg/utils/ufs_path_builder_test.go from 'Author' to 'Authors'

- charts/fluid/fluid/Chart.yaml
- charts/fluid/fluid/values.yaml
> Docker build for fixing fsgroup issue

- charts/alluxio/templates/master/statefulset.yaml
- pkg/ddc/alluxio/ufs.go
- pkg/ddc/alluxio/ufs_test.go
Fix Alluxio master in HA mode start error.
fixes #3656
> Fix Alluxio master in HA mode start error.

- charts/fluid-dataloader/jindocache/templates/job.yaml
- charts/fluid/fluid/templates/controller/dataset_controller.yaml
> fix jindocache dataloader

- ROADMAP.md
> Add roadmap for 2022

- charts/alluxio/templates/master/statefulset.yaml
- charts/alluxio/values.yaml
Support Parallel podManagementPolicy for AlluxioRuntime HA Master
fixes #3660
> Support Parallel podManagementPolicy for AlluxioRuntime HA Master

- pkg/utils/mount.go
- pkg/utils/mount_test.go
- pkg/utils/validation/validation.go
- pkg/utils/validation/validation_test.go
This PR enhanced the validation for the environment variable `MOUN_ROOT`. 
NONE
`TestIllegalMountRoot` in `pkg/utils/mount_test.go`, `TestIsSafePathWithUnsafePath` and `TestIsSafePathWithSafePath` in `pkg/utils/security/validation_test.go`.
> Validate the env variable MOUNT_ROOT

- charts/fluid/fluid/Chart.yaml
- charts/fluid/fluid/values.yaml
> Build docker images for alluxio HA

- charts/fluid-dataloader/jindocache/CHANGELOG.md
- charts/fluid-dataloader/jindocache/templates/configmap.yaml
- charts/fluid-dataloader/jindocache/templates/job.yaml
- charts/jindocache/Chart.yaml
- charts/jindocache/values.yaml
- pkg/ddc/jindocache/const.go
- pkg/ddc/jindocache/transform.go
- pkg/ddc/jindocache/transform_fuse_test.go
- pkg/ddc/jindocache/transform_test.go
- pkg/utils/jindo/jindo.go
> upgrade jindocache to 6.2.0 and support forceload

- README-zh_CN.md
- README.md
Add Journal Paper Information into Readme.
fixes #XXXX
> Add Journal Paper Information into Readme

- ROADMAP.md
> Create roadmap for 2023

- charts/fluid/fluid/templates/controller/vineyardruntime_controller.yaml
- charts/fluid/fluid/templates/role/csi/rbac.yaml
- charts/fluid/fluid/templates/role/dataset/rbac.yaml
- charts/fluid/fluid/templates/role/vineyard/rbac.yaml
- charts/fluid/fluid/templates/role/webhook/rabc.yaml
- charts/fluid/fluid/values.yaml
As titled.   A follow-up of https://github.com/fluid-cloudnative/fluid/pull/3624
> Add the controller and rbac yaml for vineyard runtime.

- charts/jindocache/templates/config/jindofs-conf.yaml
- pkg/ddc/jindocache/transform.go
- pkg/ddc/jindocache/transform_test.go
- pkg/ddc/jindocache/types.go
> fix support readCacheReplica and writeCacheReplica with jindoruntime

- pkg/ddc/jindocache/transform.go
- pkg/ddc/jindofsx/transform.go
> fix disable compaction

- charts/fluid/fluid/Chart.yaml
- charts/fluid/fluid/values.yaml
> build docker images for disabling storage compaction

- ROADMAP.md
> Create roadmap for 2024

- pkg/utils/quantity.go
> complete license

- charts/fluid/fluid/Chart.yaml
- charts/fluid/fluid/values.yaml
> Build docker images for vineyard

- charts/fluid/fluid/Chart.yaml
- charts/fluid/fluid/values.yaml
> Build docker images for fixing incorrect conversion of integer

- charts/fluid/fluid/Chart.yaml
- charts/fluid/fluid/values.yaml
- pkg/utils/quantity.go
> Docker build 240116

- pkg/webhook/scheduler/mutating/schedule_pod_handler_test.go
This pr is to add copyright: 2021 to 2023
> pkg/webhook/scheduler/mutating/schedule_pod_handler_test.go Copyright 2021 to 2023

- pkg/ddc/thin/status_test.go
> 增加/pkg/ddc/thin/status_test.go的license

- pkg/ddc/base/engine.go
update /pkg/ddc/base/engine.go license year 2022 -> 2023(task 47)
fixes #XXXX
> update /pkg/ddc/base/engine.go license year 2022 -> 2023

- pkg/ddc/alluxio/worker_test.go
> Fix pkg/ddc/alluxio/worker_test.go: change Copyright 2022 to Copyright 2023

- pkg/ddc/efc/transform_resources.go
This is PR to update license copyright date from 2022 to 2023 in `fluid\pkg\ddc\efc\transform_resources.go` file.
> Update license copyright date from 2022 to 2023

- pkg/ctrl/watch/pod.go
This pr is to update the year of the Apache License in pkg/ctrl/watch/pod.go
> This pr is to update the year of the Apache License in pkg/ctrl/watch/pod.go

- pkg/application/inject/fuse/container_test.go
This pr is to change the year from 2022 to 2023
> Changed the year from 2022 to 2023

- pkg/ddc/efc/port_parser.go
change copyright 2022 to 2023
fixes #XXXX
> change copyright 2022 to 2023

- pkg/utils/feature/feature_gate.go
> modified 2022 to 2023

- pkg/ddc/thin/ufs_test.go
fix copyright year from 2022 to 2023
fixes #XXXX
> fix copyright year from 2022 to 2023

- pkg/ddc/thin/status.go
> Updated copyright at pkg/ddc/thin/status.go

- pkg/ddc/jindofsx/create_volume_test.go
This pr to update create_volume_test.go Apache License
NONE
NONE
> Update pkg/ddc/jindofsx/create_volume_test.go License

- pkg/utils/kubectl/configmap.go
- pkg/utils/kubectl/configmap_test.go
> Remove unused method

- pkg/ddc/vineyard/operations/base.go
- pkg/ddc/vineyard/operations/base_test.go
* Add a regex to validate the resource before sending the http request.
* Add a timeout for http get request.
fixes #XXXX
> Add a regex to validate the resource before sending the http request in the vineyard Runtime

- charts/jindocache/templates/fuse/daemonset.yaml
- charts/jindocache/templates/master/statefulset.yaml
- charts/jindocache/templates/worker/statefulset.yaml
- charts/jindofs/templates/fuse/daemonset.yaml
- charts/jindofs/templates/master/statefulset.yaml
- charts/jindofs/templates/worker/statefulset.yaml
- charts/jindofsx/templates/fuse/daemonset.yaml
- charts/jindofsx/templates/master/statefulset.yaml
- charts/jindofsx/templates/worker/statefulset.yaml
> change enableServiceLinks from true to false

- charts/efc/templates/fuse/daemonset.yaml
- charts/efc/templates/master/statefulset.yaml
- charts/efc/templates/worker/statefulset.yaml
- charts/juicefs/templates/fuse/daemonset.yaml
- charts/juicefs/templates/worker/statefuleset.yaml
Add enableServiceLinks to efc and juicefs
fixes #XXXX
> Add enableServiceLinks to efc and juicefs

- charts/fluid/fluid/Chart.yaml
- charts/fluid/fluid/values.yaml
> Build docker images for refactoring command

- charts/thin/templates/fuse/daemonset.yaml
- charts/thin/templates/worker/statefuleset.yaml
- charts/vineyard/templates/fuse/daemonset.yaml
- charts/vineyard/templates/master/statefulset.yaml
- charts/vineyard/templates/worker/statefulset.yaml
Add enableServiceLinks to thin and vineyard
fixes #XXXX
> Add enableServiceLinks to thin and vineyard

- pkg/ddc/goosefs/shutdown_test.go
This PR is to change “2022” to “2023”
fixes #XXXX
> update /pkg/ddc/goosefs/shutdown_test.go "2022" to "2023"

- pkg/utils/capabilities_test.go
this pr is to add some additional information about license.
> modify License

- cmd/dataset/app/dataset.go
- pkg/controllers/deploy/runtime_controllers.go
- pkg/controllers/v1alpha1/dataflow/dataflow_controller.go
- pkg/utils/discovery/api_discover.go
- pkg/utils/discovery/api_discover_test.go
- Fix fluid discovery init order
- Refactor fluidDiscovery as a singleton
NONE
A bugfix for #3709
> bugfix: fix fluid discovery init order

- charts/fluid/fluid/Chart.yaml
- charts/fluid/fluid/values.yaml
> Build for crd discovery

- pkg/ddc/efc/data_load.go
update license of pkg/ddc/efc/data_load.go
fixes #XXXX
> update license of pkg/ddc/efc/data_load.go

- test/prow/fluid/fluidapi.py
- test/prow/scale_runtime.py
- test/prow/testcases/alluxio/alluxio_dynamic_mountpoint.py
- test/prow/testcases/common/csi_stale_patch.py
- test/prow/testcases/common/dataset_pvc_subpath.py
- Change bit apache mirror to tsinghua apache mirror because bit apache mirror is temporarily unreachable for unknown reason.
NONE
> Fix webufs in prow e2e test

- pkg/ddc/juicefs/dataset.go
This pr is to add license for file fluid/pkg/ddc/juicefs/dataset.go
> modify license for file fluid/pkg/ddc/juicefs/dataset.go

- pkg/ddc/juicefs/type.go
this pr updates the copyright of "pkg/ddc/juicefs/replicas_test.go"
> update the comments

- charts/fluid/fluid/Chart.yaml
- charts/fluid/fluid/values.yaml
> Build docker image for vineyardRuntime

- CONTRIBUTING.md
> Add Developer Certificate Of Origin

- charts/fluid/fluid/Chart.yaml
- charts/fluid/fluid/values.yaml
- integration/kubeflow/README.md
> Docker build for data migrating

- pkg/ddc/jindocache/status.go
- pkg/ddc/jindofsx/status.go
`ValueFileConfigmap`'s name decides `engineImpl` for multi-engine runtimes (e.g. JindoRuntime). However, `ValueFileConfigmap` is not missing when using fuse-only mode for JindoRuntime, which may have potential compatibility issue in the future. 
This PR fixes this by syncing the ground-truth `ValueFileConfigmap` to runtime's status. Currently, only Jindoruntime in fuse-only mode is affected by this bug. We decide which `engineImpl` the JindoRuntime is using with the following order:
1. check if `<name>-jindocache-values` ConfigMap exists. In such case, the JindoRuntime is definitely using `jindocache` as its engineImpl.
2. With missing `<name>-jindocache-values` ConfigMap, fallback to consider it is using `jindofsx` engineImpl.
NONE
A followup fix of #3672
> bugfix: sync ValueFileConfigmap in JindoRuntime fuse-only mode

- charts/fluid/fluid/Chart.yaml
- charts/fluid/fluid/values.yaml
> Build docker images for fixing jindoruntime

- charts/fluid/fluid/templates/role/alluxio/rbac.yaml
- charts/fluid/fluid/templates/role/dataset/rbac.yaml
- charts/fluid/fluid/templates/role/efc/rbac.yaml
- charts/fluid/fluid/templates/role/fluidapp/rbac.yaml
- charts/fluid/fluid/templates/role/goosefs/rbac.yaml
- charts/fluid/fluid/templates/role/jindo/rbac.yaml
- charts/fluid/fluid/templates/role/juicefs/rbac.yaml
- charts/fluid/fluid/templates/role/thin/rbac.yaml
- charts/fluid/fluid/templates/role/vineyard/rbac.yaml
Replace wildcards with specific verbs in rbac.
no.
> Replace wildcards with specific verbs in rbac

- charts/fluid/fluid/templates/role/alluxio/rbac.yaml
- charts/fluid/fluid/templates/role/dataset/rbac.yaml
- charts/fluid/fluid/templates/role/efc/rbac.yaml
- charts/fluid/fluid/templates/role/fluidapp/rbac.yaml
- charts/fluid/fluid/templates/role/goosefs/rbac.yaml
- charts/fluid/fluid/templates/role/jindo/rbac.yaml
- charts/fluid/fluid/templates/role/juicefs/rbac.yaml
- charts/fluid/fluid/templates/role/thin/rbac.yaml
- charts/fluid/fluid/templates/role/vineyard/rbac.yaml
> Fix role rbac issue

- pkg/ddc/jindocache/transform.go
- pkg/ddc/jindocache/transform_master_test.go
- pkg/ddc/jindofsx/transform.go
- pkg/ddc/jindofsx/transform_master_test.go
> fix transformToken

- charts/fluid/fluid/templates/role/jindo/rbac.yaml
> remove unused verbs

- pkg/metrics/dataset_metrics.go
- pkg/metrics/runtime_metrics.go
#3756 is caused by concurrent writes on Fluid's metrics maps. Specifically, when there are multiple goroutines reconciling multiple Runtimes, it is possible that a deletion and a inserting happen at the same time on the same metrics map, which makes `fatal error: concurrent map writes`.
This PR fixes by adding Mutex to protect race condition on the maps.
fixes #3756
> Fix fatal error: concurrent map writes for runtime controllers

- charts/fluid/fluid/Chart.yaml
- charts/fluid/fluid/values.yaml
> Build docker images for 0.9.3

- config/fluid/bases/csi-plugin.yaml
- config/fluid/bases/csi/daemonset.yaml
- config/fluid/bases/role/alluxio/rbac.yaml
- config/fluid/bases/role/dataset/rbac.yaml
- integration/kubeflow/rbac.yaml
> Enhance config dir

- api/v1alpha1/openapi_generated.go
- api/v1alpha1/vineyardruntime_types.go
- charts/fluid/fluid/crds/data.fluid.io_vineyardruntimes.yaml
- charts/vineyard/Chart.yaml
- charts/vineyard/values.yaml
- config/crd/bases/data.fluid.io_vineyardruntimes.yaml
- docs/en/dev/api_doc.md
- docs/zh/dev/api_doc.md
- pkg/common/vineyard.go
- pkg/ddc/vineyard/utils_test.go
> Add the tag v0.21.5 for vineyard worker and vineyard fuse image.

- charts/fluid/fluid/Chart.yaml
- charts/fluid/fluid/values.yaml
> Build docker images for vineyard runtime

- charts/alluxio/CHANGELOG.md
Fixed #3769 
This pr is to  corrected 'prefered' to 'preferred' of  file charts\alluxio\CHANGELOG.md:182:26:
> Fix typo in charts\alluxio\CHANGELOG.md

- docs/en/operation/tiered_locality_schedule.md
- docs/zh/operation/tiered_locality_schedule.md
update docs for `fluid.io/fuse` .
fixes #XXXX
> update docs to add fluid.io/fuse

- docs/en/samples/vineyard/vineyard_runtime.md
- docs/zh/samples/vineyard/vineyard_runtime.md
> Add the doc about how to use vineyard runtime.

- docs/en/userguide/install.md
- docs/zh/userguide/install.md
> Update installation guide for v1.0.0

- pkg/controllers/operation_controller.go
this pr is to standardize the License information in the header of the file
> standardize the License information in the header of the file

- pkg/ddc/jindocache/transform.go
> fix jindoruntime local mount point

- charts/fluid/fluid/templates/controller/vineyardruntime_controller.yaml
- charts/fluid/fluid/values.yaml
- pkg/common/vineyard.go
- pkg/ddc/vineyard/transform.go
- pkg/ddc/vineyard/transform_test.go
- pkg/ddc/vineyard/utils.go
> Support to configure the image of vineyard component by env.

- docs/zh/operation/monitoring.md
Fixed #3785 
The pr is to fix some typo below:
docs\zh\operation\monitoring.md:132:64: corrected "Prometheous" to "Prometheus"
docs\zh\operation\monitoring.md:137:17: corrected "Prometheous" to "Prometheus"
docs\zh\operation\monitoring.md:137:61: corrected "Prometheous" to "Prometheus"
> fix typo in monitoring.md

- cmd/alluxio/app/version.go
This pr corrects the copyright date in file /cmd/alluxio/app/version.go
NONE
> Fix copyright date in comment lines

- charts/fluid/fluid/Chart.yaml
- charts/fluid/fluid/values.yaml
> Build docker images for jindocache with pvc support

- pkg/ddc/jindocache/transform.go
- pkg/ddc/jindocache/transform_test.go
> JindoCache supports user-defined names for mounting secret

- cmd/alluxio/app/init.go
This pr is to fix copyright year in ./cmd/alluxio/app/init.go
NONE
> Fix copyright year in init.go

- charts/fluid/fluid/Chart.yaml
- charts/fluid/fluid/values.yaml
> Build docker images for user specified secret

- docs/en/samples/vineyard/vineyard_runtime.md
- docs/zh/samples/vineyard/vineyard_runtime.md
> Refine the vineyard runtime doc and add a section about data sharing.

- pkg/common/label.go
- pkg/ddc/vineyard/runtime_info.go
- pkg/ddc/vineyard/runtime_info_test.go
- test/prow/testcases/common/csi_nodepublish_symlink.py
Change `fluid.io/node-puhlish-method` typo to `fluid.io/node-publish-method`, as it is a typo.
NONE
> Fix `fluid.io/node-publish-method` typo

- charts/fluid/fluid/Chart.yaml
- charts/fluid/fluid/values.yaml
> Build docker images for fixing node-publishing-method

- CHANGELOG.md
Update change log file for v1.0
fixes #XXXX
> Update change log for v1.0

- cmd/thin/app/thin.go
Fixed #3822
This pr is to corrected 'reconcilation' to 'reconciliation' of file cmd/thin/app/thin.go:89:137;
> fix type in cmd/thin/app/thin.go

- hack/sdk/post-gen.py
Fixed #3817
hack\sdk\post-gen.py:19:58: corrected "pacakge" to "package"
> fix a spell mistake--package

- charts/fluid/fluid/Chart.yaml
- charts/fluid/fluid/values.yaml
> Build docker images for fixing juicefs worker name

- README-zh_CN.md
- README.md
- SECURITY.md
> Update security info

- README-zh_CN.md
- README.md
Update What's new in ReadMe for v1.0.0 release.
fixes #XXXX
> Update What's new in ReadMe for v1.0.0 release.

- Makefile
- charts/fluid/fluid/Chart.yaml
> Prepare 1.0.1

- cmd/efc/main.go
修改 ./cmd/efc/main.go文件，Copyright时间从2022改为2023。
fixes #XXXX
> Copyright时间有误，2022改为2023

- pkg/controllers/v1alpha1/jindo/implement.go
This pr is to add specifications for License Information at fluid/pkg/controllers/v1alpha1/jindo/implement.go:2
fixes #XXXX
> Add or standardize license information

- charts/vineyard/values.yaml
Fixed #3807 
This pr is to corrected "Exmaple" to "Example" of file charts\vineyard\values.yaml:22:4 and 52:4
> fix typo:corrected Exmaple to Example

- cmd/alluxio/app/alluxio.go
Fixed #3814 
This pr is to  corrected 'reconcilation' to 'reconciliation' of file cmd\alluxio\app\alluxio.go:93:146    :94:139
> [DOC] fix typo in cmd\alluxio\app\alluxio.go

- pkg/controllers/v1alpha1/dataload/implement.go
this pr is to modify the date from 2022 to 2020
fixes #XXXX
> modify the date

- api/v1alpha1/common.go
This pr is to add modify year
fixes #XXXX
> modify year

- pkg/ddc/alluxio/delete_volume.go
This  pr is to add : finish fixed ./pkg/ddc/alluxio/delete_volume.go year 2023->2020
fixes #XXXX
>  finish  fixed ./pkg/ddc/alluxio/delete_volume.go 

- cmd/jindo/app/jindo.go
cmd\jindo\app\jindo.go:100:144: corrected "reconcilation" to "reconciliation"
cmd\jindo\app\jindo.go:101:137: corrected "reconcilation" to "reconciliation"
fixes #3830
nothing
just look at 
nothing
> spoken corrected

- charts/fluid/fluid/templates/role/jindo/rbac.yaml
> fix jindo rbac remove secret get

- charts/fluid-datamigrate/juicefs/templates/cronjob.yaml
- charts/fluid-datamigrate/juicefs/templates/statefulset.yaml
- docs/zh/samples/juicefs/juicefs_data_migrate.md
- pkg/controllers/v1alpha1/datamigrate/status_handler.go
- pkg/controllers/v1alpha1/datamigrate/status_handler_test.go
- pkg/ddc/base/operation.go
- pkg/utils/kubeclient/job.go
support parallel data migrate for cron policy.
previous pr see #3645.
fixes #XXXX
> support parallel tasks for cron datamigrate

- pkg/ddc/alluxio/types_selector.go
this pr is to add the correct time
fixes #XXXX
> lab1-2 lmy first

- api/v1alpha1/databackup_types.go
This PR is to add "Copyright" in "./api/v1alpha1/databackup_types.go".
fixes #XXXX
> Task4 - 添加或规范License信息

- pkg/dataoperation/mock.go
add licenses to mock.go since its missing of licenses
NONE
> add licenses to source code

- charts/fluid/fluid/Chart.yaml
- charts/fluid/fluid/values.yaml
> Docker build for pod metadata for vineyard

- pkg/controllers/v1alpha1/goosefs/suite_test.go
change the copyright in  ./pkg/controllers/v1alpha1/goosefs/suite_test.go from 2023 to 2021
fixes #XXXX
> from2023to2021

- api/v1alpha1/doc.go
> modify the license

- api/v1alpha1/goosefsruntime_types.go
This PR is to change the time in goosefsruntime_types.go
fixes #XXXX
> Change the time

- api/v1alpha1/dataset_types.go
This PR is to change the copyright date in file "./api/v1alpha1/dataset_types.go".
fixes #XXXX
> Change copyright date

- pkg/controllers/v1alpha1/goosefs/implement.go
This pr is to change year of License of ./pkg/controllers/v1alpha1/goosefs/implement.go
> change year

- api/v1alpha1/dataprocess_types.go
This pr is to standardize the License in ./api/v1alpha1/dataprocess_types.go
fixes #XXXX
> task6-添加或规范License信息

- cmd/efc/app/version.go
> fix copyright year infomation of ./cmd/efc/app/version.go

- pkg/controllers/v1alpha1/alluxio/alluxio_runtime_controller.go
This PR is to change the copyright date in file "./pkg/controllers/v1alpha1/alluxio/alluxio_runtime_controller.go".
NONE
> correct Copyright data

- cmd/efc/app/efc.go
This pr is to modify copyright year
fixes #XXXX
> modify year 

- api/v1alpha1/zz_generated.deepcopy.go
This pr is to complete license in zz_generated.deepcopy.go.
fixes #XXXX
> complete license in zz_generated.deepcopy.go

- docs/en/samples/data_warmup.md
Fixed #3862
This pr is to corrected 'controll' to 'control' of file
docs\en\samples\data_warmup.md:8:123:
docs\en\samples\data_warmup.md:104:83:
> controll->control

- pkg/ddc/base/base_suite_test.go
This PR is to update the year of Copyright in ./pkg/ddc/base/base_suite_test.go.
> Update Copyright Date

- pkg/common/label.go
> fix copyright year

- pkg/controllers/v1alpha1/goosefs/goosefs_runtime_controller.go
add licence in ./pkg/controllers/v1alpha1/goosefs/goosefs_runtime_controller.go
> fix licence in ./pkg/controllers/v1alpha1/goosefs/goosefs_runtime_controller.go

- pkg/ddc/alluxio/utils_test.go
> Specify License for./pkg/ddc/alluxio/utils_test.go

- pkg/ddc/alluxio/transform_test.go
the Copyright date of ./pkg/ddc/alluxio/transform_test.go is incorrect, I just replaced "2023" with "2020"
NONE
NONE
NONE
NONE
> correct the date of Copyright

- pkg/controllers/v1alpha1/jindo/suite_test.go
This pr is to add Copyright to ./pkg/controllers/v1alpha1/jindo/suite_test.go
> Add Copyright to ./pkg/controllers/v1alpha1/jindo/suite_test.go

- pkg/ddc/alluxio/transform_ufs_test.go
This pr is to add "change the year in  the file whose path is ./pkg/ddc/alluxio/transform_ufs_test.go"
fixes #XXXX
> 有Apache License的通告声明，也有Copyright，但 Copyright时间有误

- pkg/ddc/base/operation.go
Fixed #3904 
this pr is to correct "reconcilation" to "reconciliation" of file pkg\ddc\base\operation.go:121:53:
> fix typo of file operation.go

- pkg/ddc/alluxio/backup_data.go
modify the license info in pkg/ddc/alluxio/backup_data.go
> modify the license info in pkg/ddc/alluxio/backup_data.go

- pkg/dataload/constants.go
this pr is to fix copyright year of a file
fixes #XXXX
> fix copyright year of a file

- cmd/alluxio/main.go
modify copyright year in cmd/alluxio/main.go
NONE
> modify copyright year in cmd/alluxio/main.go

- pkg/controllers/v1alpha1/dataload/implement_test.go
This pr is to fix copyright date error
fixes #XXXX
> fix copyright date error

- pkg/common/critical_fuse_pod_test.go
> Modify Apache License CopyRight

- pkg/ddc/efc/create_volume.go
> My dev pull

- pkg/dataload/value.go
this pr is to modify the lisence to finish task 111
fixes #XXXX
> modified the lisence

- cmd/jindo/main.go
fix Copyright time in cmd/jindo/main.go
> fix Copyright time in cmd/jindo/main.go

- pkg/utils/webhook/generator/util.go
modify the year in ./pkg/utils/webhook/generator/util.go
fixes #XXXX
> modify the year

- pkg/application/inject/fuse/poststart/check_fuse_default.go
modified:   check_fuse_default.go  2021 --> 2023
> modified:   check_fuse_default.go  2021 --> 2023

- pkg/utils/mountinfo/mountinfo.go
> Modify theCopyRight

- cmd/dataset/app/dataset.go
Fixed  #3961 
This PR is to do:
1. corrected "reconcilation" to "reconciliation" in cmd\dataset\app\dataset.go:99:146
2. corrected "reconcilation" to "reconciliation" in cmd\dataset\app\dataset.go:100:139
> Fix typo in cmd\dataset\app\dataset.go

- pkg/ddc/alluxio/master_internal.go
modify year in Copyright 2023->2020 in ./pkg/ddc/alluxio/master_internal.go
fixes #XXXX
> modify year in Copyright 2023->2020

- cmd/dataset/app/init.go
The pr is to fix copyright year in ./cmd/dataset/app/init.go。
fixes #XXXX
> Fix copyright year in ./cmd/dataset/app/init.go

- pkg/common/storage.go
modified the copyright year in pkg/common/storage.go
fixes #XXXX
> modified the copyright year

- cmd/csi/main.go
> 211220171  马旭佳

- cmd/dataset/app/dataset.go
task 26: change cmd/dataset/app/dataset.go the time from 2021 to 2022
fixes #XXXX
> Task 26: Changing the time from 2021 to 2022

- pkg/ddc/alluxio/transform_resources_test.go
> add copyright condition2

- cmd/vineyard/app/vineyard.go
> correct reconcilation to reconciliation in 84:144 and 85:137

- pkg/ddc/goosefs/hcfs.go
> corrected "Compatiable" to "Compatible"

- pkg/ddc/alluxio/deprecated_label_test.go
This PR is to correct copyright  in ./pkg/ddc/alluxio/deprecated_label_test.go
fixes #XXXX
> correct copyright  in ./pkg/ddc/alluxio/deprecated_label_test.go

- cmd/dataset/app/version.go
Completed Task 28:
This PR is to modify the Copyright Date in the license of file "./cmd/dataset/app/version.go" corresponding to line 2.
NONE
> Modified the copyright date 2021 -> 2022

- pkg/ddc/alluxio/health_check_test.go
> this pr is to add change the year of copyright from 2023 to 2021

- cmd/csi/app/init.go
modify Copyright <year> from 2021 to 2022
fixes #XXXX
> modify <year> from 2021 to 2022

- pkg/ddc/alluxio/operations/cached.go
This pr is to add normalized license information of “pkg/ddc/alluxio/operations/cached.go"
fixes #XXXX
> Standard Licence Information of No.138

- pkg/ddc/alluxio/status.go
This pr is to Fix wrong time of Copyright
NONE
> This pr is to Fix wrong time of Copyright

- docs/en/operation/monitoring.md
Fixed #4029 
This pr is to  corrected "Prometheous" to "Prometheus" of file docs\en\operation\monitoring.md:129:49, docs\en\operation\monitoring.md:134:8 and docs\en\operation\monitoring.md:134:69
> corrected 'Prometheous' to 'Prometheus'

- pkg/ddc/alluxio/operations/local_test.go
This pr is to add  ./pkg/ddc/alluxio/operations/local_test.go的license信息中copyright时间有误的问题
fixes #XXXX
> 更改 ./pkg/ddc/alluxio/operations/local_test.go文件中license信息

- docs/en/samples/juicefs_for_s3.md
docs\en\samples\juicefs_for_s3.md:3:79: corrected "seperates" to "separates"
fixes #XXXX
> modify "seperates" to "separates"

- ROADMAP.md
Fixed #3935 
This pr is to corrected  "produciton" to "production"
fixes #3935
> corrected  "produciton" to "production"

- pkg/controllers/v1alpha1/dataset/dataset_controller.go
> have changed the year to the right one

- .circleci/config.yml
- .github/workflows/go.yml
- .travis.yml
- docker/Dockerfile.alluxioruntime
- docker/Dockerfile.application
- docker/Dockerfile.csi
- docker/Dockerfile.dataset
- docker/Dockerfile.efcruntime
- docker/Dockerfile.goosefsruntime
- docker/Dockerfile.jindoruntime
- docker/Dockerfile.juicefsruntime
- docker/Dockerfile.thinruntime
- docker/Dockerfile.vineyardruntime
- docker/Dockerfile.webhook
- go.mod
- pkg/ddc/vineyard/operations/base_test.go
- pkg/utils/kubeclient/pod_test.go
- pkg/utils/webhook_test.go
- pkg/webhook/plugins/plugins_impl_test.go
> Upgrade to golang 1.21.8

- api/v1alpha1/juicefsruntime_types.go
This pr is to add to fix typo in juicefsruntime_types.go
fixes #XXXX
> 2022->2021

- pkg/controllers/runtime_controller.go
> Add copyright in rumtime_controller.go

- pkg/ddc/alluxio/transform_fuse.go
This pr is to change the COPYRIGHT time from "2023" to "2020" in the file located at pkg/ddc/alluxio/transform_fuse.go.
fixes #XXXX
> change COPYRIGHT 2023 to 2020

- pkg/utils/volume_lock.go
> Use generic Set for volumeLock

- charts/fluid/fluid/Chart.yaml
- charts/fluid/fluid/values.yaml
> Build docker images for K8s 1.26.10 , controller-runtime 0.14.7, golang 1.21

- pkg/csi/plugins/controller.go
Task 99 :modified the copyright year in ./pkg/csi/plugins/controller.go
> modify the time of copyright

- pkg/csi/plugins/driver.go
This pr is to modify <year> form 2023 to 2022
fixes #XXXX
> modify <year> from 2023 to 2022

- pkg/application/inject/fuse/poststart/check_fuse_app.go
This pr is to corretct Copyright time for "fluid/pkg/application/inject/fuse/poststart/check_fuse_app.go".
fixes #XXXX
> correct Copyright

- pkg/ctrl/watch/pod.go
> Add or standardize license information at the beginning of the file.

- pkg/ddc/alluxio/transform_optimization_test.go
This pr is to modify the copyright time in /pkg/ddc/alluxio/transform_optimization_test.go
fixes #XXXX
> 在文件头部添加或规范License信息  Task-156

- pkg/application/inject/fuse/mutator/mutator.go
添加license
fixes #pkg/application/inject/fuse/mutator/muta
tor.go
> Add or normalize License information

- pkg/dataload/constants.go
this pr is to fix copyright year fo a file
fixes #XXXX
> fix copyright year fo a file

- cmd/vineyard/app/vineyard.go
> correct  reconcilation to reconciliation in 84:144 and 85:137

- pkg/ddc/alluxio/transform_ufs.go
finish task 1; corrected copyright info
> corrected copyright info in /pkg/ddc/alluxio/transform_ufs.go

- addons/dynamic-mount/ossfs/docker/Dockerfile
- api/v1alpha1/juicefsruntime_types.go
- docker/Dockerfile.alluxioruntime
- docker/Dockerfile.application
- docker/Dockerfile.crds
- docker/Dockerfile.csi
- docker/Dockerfile.dataset
- docker/Dockerfile.efcruntime
- docker/Dockerfile.goosefsruntime
- docker/Dockerfile.jindoruntime
- docker/Dockerfile.juicefsruntime
- docker/Dockerfile.thinruntime
- docker/Dockerfile.vineyardruntime
- docker/Dockerfile.webhook
- pkg/controllers/v1alpha1/dataset/dataset_controller.go
> Update docker file golang 1.12.10

- charts/fluid/fluid/Chart.yaml
- charts/fluid/fluid/values.yaml
> Build docker images for golang 1.12.10

- pkg/common/efc.go
modify <year> from 2022 to 2023 in pkg/common/efc.go
fixes #XXXX
> modify <year> 2022 to 2023 in pkg/common/efc.go

- pkg/ddc/alluxio/operations/local.go
This pr is to add normalized license information of “pkg/ddc/alluxio/operations/local.go"
fixes #XXXX
> Standard Licence Information of No.140

- pkg/ddc/base/engine.go
This pr is to standardize Apache License for ./pkg/ddc/engine.go.
> Standardize Apache License for ./pkg/ddc/engine.go.

- samples/vineyard/preprocess-data/preprocess-data.py
> Add the random_state for train_test_split in vineyard samples.

- pkg/ddc/alluxio/ufs_test.go
This pr is to modify the date of copyright.
fixes #XXXX
> fix: modify the date

- cmd/jindo/app/jindo.go
> Fix the date error in License for cmd/jindo/app/jindo.go

- charts/fluid/fluid/values.yaml
- charts/jindocache/CHANGELOG.md
- charts/jindocache/Chart.yaml
- charts/jindocache/values.yaml
- pkg/ddc/jindocache/const.go
- pkg/ddc/jindocache/transform.go
- pkg/ddc/jindocache/transform_fuse_test.go
- pkg/ddc/jindocache/transform_test.go
- pkg/utils/jindo/jindo.go
> upgrade jindocache to 6.4.0 version

- charts/fluid/fluid/Chart.yaml
- charts/fluid/fluid/values.yaml
> Build docker images for dataflow,

- cmd/goosefs/app/version.go
add Copyright `Copyright 2021 The Fluid Authors.`
> modify License of cmd/goosefs/app/version.go

- charts/fluid/fluid/Chart.yaml
- charts/fluid/fluid/values.yaml
> Build docker image for code refactoring

- pkg/controllers/runtime_controller.go
> Fix NPE of runtime controller

- pkg/ddc/alluxio/types_test.go
> correct the year of copyright

- cmd/webhook/app/version.go
This pr is to add a Copyright to normalize the License.
fixes #XXXX
> This pr is to add a Copyright to normalize the License

- pkg/ddc/alluxio/create_volume.go
This pr is to standardize License information
fixes #XXXX
> Standardize License Information

- pkg/ddc/base/operation_lock.go
This pr is to add the modification of the time of pkg/base/base/operation_lock.go.
> the modification of the time

- pkg/ddc/goosefs/transform_api_gateway_test.go
Fixed #4058 
This pr is to correct "beacuse" to "because" of file pkg\ddc\goosefs\transform_api_gateway_test.go:85:34:
> corrected a word

- pkg/ddc/alluxio/engine.go
> modify year of license in pkg/ddc/alluxio/engine.go

- pkg/ddc/alluxio/transform.go
Ⅰ. This pr is to change the time of Copyright
> This pr is to change the time of Copyright

- pkg/ddc/alluxio/const.go
This pr is to correct the year of the License
fixes #XXXX
> This pr is to correct the year of the License

- pkg/ddc/alluxio/dataset.go
> Changed Copyright date from 2023 to 2020.

- cmd/thin/app/thin.go
Standardized license information of cmd/thin/app/thin.go
> Standardized license information of cmd/thin/app/thin.go

- pkg/common/alluxio.go
This PR is to add License to ./pkg/common/alluxio.go
fixes #XXXX
> add License to ./pkg/common/alluxio.go

- pkg/ddc/alluxio/api_gateway.go
Fix copyright year in api_gateway.go
NONE
> Fix copyright year in api_gateway.go

- pkg/ddc/alluxio/transform_fuse_test.go
> This pr is to change the time  in pkg/ddc/alluxio/transform_fuse_test.go in lab1 task 151

- pkg/ddc/alluxio/transform_hadoop_config.go
This pr is to change the time of the file ./pkg/ddc/alluxio/transform_hadoop_config.go in task 152.
> This pr is to change the time of the file transform_hadoop_config.go in task 152.

- charts/fluid/fluid/Chart.yaml
- charts/fluid/fluid/values.yaml
> Build docker image for fixing NPE

- pkg/ddc/alluxio/transform_permission_test.go
Normalize License information of Task158 which is in ./pkg/ddc/alluxio/transform_permission_test.go. The time of copyright is wrong in the original version.
fixes License information of Task158 which is in ./pkg/ddc/alluxio/transform_permission_test.go.
please open ./pkg/ddc/alluxio/transform_permission_test.go to find my modification.
> Add or normalize License information of Task158

- pkg/ddc/alluxio/health_check.go
This Pull Request makes the following changes to the `health_check.go` file in the fluid repository:
Corrected the Copyright year from [incorrect year] to [correct year].
These changes ensure that the proper licensing information is included and that the Copyright year is accurate.
Please review these changes and let me know if any further adjustments are needed.
> Add license information to health_check.go

- charts/fluid/fluid/Chart.yaml
- charts/fluid/fluid/values.yaml
> Build docker images for fixing jindo cache performance issue

- api/v1alpha1/openapi_generated.go
- api/v1alpha1/swagger.json
- api/v1alpha1/vineyardruntime_types.go
- charts/fluid/fluid/crds/data.fluid.io_vineyardruntimes.yaml
- charts/fluid/fluid/values.yaml
- charts/vineyard/values.yaml
- config/crd/bases/data.fluid.io_vineyardruntimes.yaml
- docs/en/dev/api_doc.md
- docs/zh/dev/api_doc.md
- docs/zh/samples/vineyard/vineyard_runtime.md
- pkg/common/vineyard.go
- pkg/ddc/vineyard/utils_test.go
> Bump up the vineyard to v0.22.2

- pkg/common/fluid_ufs_scheme_test.go
- pkg/utils/runtimes_test.go
- pkg/utils/webhook.go
> Add apache license_format in fluid_ufs_scheme_test.go

- charts/fluid/fluid/Chart.yaml
- charts/fluid/fluid/values.yaml
> Build docker images for vineyard 0.22

- charts/fluid/fluid/Chart.yaml
- charts/fluid/fluid/values.yaml
> Build docker images for fixing transformers

- pkg/utils/symlink.go
Code changes:
- Check corrupted mount point error in `utils.RemoveSymlink()`
fixes #4002
> bugfix: check corrupted mount point in utils.RemoveSymlink

- pkg/ddc/base/template_engine_test.go
This PR is to correct error in copyright description.
fixes #XXXX
> modify copyright time

- pkg/ddc/base/template_engine.go
> change time from 2022 to 2020

- pkg/ddc/base/operation.go
> changed the time of Copyright in the operation.go file to 2023

- pkg/webhook/handler/register.go
> Refactor admission webhook handler registration for better error handling

- charts/fluid/fluid/Chart.yaml
- charts/fluid/fluid/values.yaml
> Build docker images for refactoring webhook

- pkg/ddc/base/interface.go
this pr is to add Apache License
fixes #XXXX
> add Apache License ./pkg/ddc/base/interface.go

- CONTRIBUTING.md
When I followed the CONTABUTING.md document, I found that the "cd fluid" operation should be performed before the second step. Otherwise, when executing the second step command, I would be prompted with "false: not a git repository (or any of the parent directories):. git"
Therefore, this PR corrected this operation and adjusted the "cd fluid" in step 3 to be executed at the beginning of step 2
fixes #XXXX
> docs: Correcting the usage steps of the CONTABUTING.md document

- charts/fluid/fluid/Chart.yaml
- charts/fluid/fluid/values.yaml
> Build docker images for specifying pvc storage size

- docs/en/dev/how_to_develop.md
dev guide for en missing GOPATH setup
fixes #XXXX
nothing issue fixed
just docs improvment, no tests needed
run cmd follow by get start guid
> docs: dev guide for en missing GOPATH setup

- charts/fluid/fluid/Chart.yaml
- charts/fluid/fluid/values.yaml
> Build docker images for fixing juicefs timeout

- charts/fluid/fluid/values.yaml
- charts/jindocache/CHANGELOG.md
- charts/jindocache/Chart.yaml
- charts/jindocache/values.yaml
- pkg/ddc/jindocache/const.go
- pkg/ddc/jindocache/transform.go
- pkg/ddc/jindocache/transform_fuse_test.go
- pkg/ddc/jindocache/transform_test.go
- pkg/utils/jindo/jindo.go
revert: "upgrade jindocache to 6.4.0 version (#4126)" and downgrade JindoCache to 6.2.0
This reverts commit a3c7b09650cdcdd902346ba1fac8ce025d88c0a2.
NONE
> revert: "upgrade jindocache to 6.4.0 version (#4126)"

- charts/fluid/fluid/Chart.yaml
- charts/fluid/fluid/values.yaml
> Build docker images for reverting jindoruntime from 6.4 to 6.2

- Makefile
- charts/fluid/fluid/Chart.yaml
> Prepare 1.0.2

- charts/fluid/fluid/Chart.yaml
- charts/fluid/fluid/values.yaml
> Update docker image to fluid 1.0.2

- charts/fluid/fluid/templates/role/juicefs/rbac.yaml
- charts/juicefs/templates/role/rbac.yaml
del create pod role of juicefs runtime
fixes #XXXX
> del create pod role of juicefs runtime

- charts/fluid/fluid/Chart.yaml
- charts/fluid/fluid/values.yaml
> Docker build for  juicefs runtime refactor

- Makefile
> Add no cache option to Makefile

- README-zh_CN.md
- README.md
> update scorecard link

- pkg/ddc/jindo/const.go
- pkg/ddc/jindo/transform.go
fix Variable Naming Convention for DEFAULT_MASTER_RPC_PORT in CamelCase, including its definition and reference.
fixes #4233
> fix Variable Naming Convention for DEFAULT_MASTER_RPC_PORT in CamelCase

- .github/scripts/deploy-fluid-to-kind.sh
> bugfix: fix version replace in gha-e2e

- pkg/ddc/juicefs/transform.go
- pkg/ddc/juicefs/transform_fuse.go
- pkg/ddc/juicefs/transform_fuse_test.go
- pkg/ddc/juicefs/transform_test.go
> juicefs: use exec in juicefs pod to avoid ignore signal

- charts/fluid/fluid/values.yaml
update juicefs default image
fixes #XXXX
> update juicefs default image

- docs/en/TOC.md
- docs/en/samples/dataflow_affinity.md
- docs/zh/TOC.md
- docs/zh/samples/dataflow_affinity.md
add dataflow affinity doc.
fixes #XXXX
> add dataflow affinity doc

- charts/fluid/fluid/Chart.yaml
- charts/fluid/fluid/values.yaml
> Build docker images for upgrading K8s to 1.29

- charts/fluid/fluid/Chart.yaml
- charts/fluid/fluid/values.yaml
> Build docker images for adding validation for runtime

- pkg/dataprocess/processor_types.go
bugfix: support setting resources for dataprocess
NONE
> bugfix: support setting resources for dataprocess

- charts/fluid/fluid/Chart.yaml
- charts/fluid/fluid/values.yaml
> Build docker images for fixing resources of data process

- Makefile
- docker/Dockerfile.alluxioruntime
- docker/Dockerfile.application
- docker/Dockerfile.dataset
- docker/Dockerfile.efcruntime
- docker/Dockerfile.goosefsruntime
- docker/Dockerfile.jindoruntime
- docker/Dockerfile.juicefsruntime
- docker/Dockerfile.thinruntime
- docker/Dockerfile.vineyardruntime
Add an option to set the helm version in Makefile ( one place ).
fixes #3307
Run make build using the Makefile and check it works.
> Add helm version option in Makefile

- .circleci/config.yml
> Fix circleci issue

- docs/en/samples/dataflow_affinity.md
- docs/zh/samples/dataflow_affinity.md
add customized label affinity demo for data flow
fixes #XXXX
> add customized label affinity demo for data flow

- charts/fluid/fluid/Chart.yaml
- charts/fluid/fluid/values.yaml
> Build docker imagews for fixing sync ufs issue

- charts/fluid/fluid/Chart.yaml
- charts/fluid/fluid/values.yaml
> Build docker images for fix calculating ufs total size

- pkg/common/file_utils_exec.go
- pkg/ddc/alluxio/hcfs_test.go
- pkg/ddc/alluxio/load_data_test.go
- pkg/ddc/alluxio/operations/base.go
- pkg/ddc/alluxio/operations/base_test.go
- pkg/ddc/alluxio/operations/conf_test.go
- pkg/ddc/alluxio/operations/local.go
- pkg/ddc/alluxio/operations/local_test.go
- pkg/ddc/alluxio/ufs_test.go
- pkg/ddc/alluxio/utils_test.go
- pkg/ddc/efc/operations/base.go
- pkg/ddc/efc/operations/base_test.go
- pkg/ddc/jindocache/operations/base.go
- pkg/ddc/jindocache/operations/base_test.go
- pkg/ddc/jindocache/operations/cached.go
- pkg/ddc/juicefs/operations/base.go
- pkg/ddc/juicefs/operations/base_test.go
- pkg/ddc/juicefs/ufs_test.go
- pkg/ddc/thin/operations/base.go
- pkg/ddc/thin/operations/base_test.go
- pkg/ddc/thin/ufs_test.go
- pkg/utils/kubeclient/exec.go
> refactor: kubeclient exec utils package

- charts/fluid/fluid/Chart.yaml
- charts/fluid/fluid/values.yaml
> Build docker images for refecator exec

- pkg/controllers/runtime_controller.go
Adds a context timeout mechanism to all controllers' `Reconcile` functions.
fixes #1144
1. Timeout Value: Please verify that the 10-minute timeout duration is appropriate for the reconciliation process.
2. Logging Suggestion: Consider adding logs to the reconcile function that include the timeout value for better traceability.
> Bind all reconcile loops with limited context.Context

- api/v1alpha1/databackup_types.go
- api/v1alpha1/dataprocess_types.go
- api/v1alpha1/swagger.json
- api/v1alpha1/thinruntime_types.go
- docs/en/dev/api_doc.md
- docs/zh/dev/api_doc.md
- tools/api-doc-gen/example-config.json
- tools/api-doc-gen/template/type.tpl
- Update `api_doc.md` to match the latest version of Fluid APIs.
- Additionally auto-generate api doc for DataProcess and ThinRuntime CRD.
- Deprecate DataBackup from `api_doc.md`
NONE
> doc: update api doc to v1.0.2

- charts/fluid/fluid/Chart.yaml
- charts/fluid/fluid/values.yaml
> Build docker images for adding info of  dataset in use

- pkg/ddc/alluxio/transform.go
- pkg/ddc/efc/transform.go
- pkg/ddc/goosefs/transform.go
- pkg/ddc/jindocache/transform.go
- pkg/ddc/jindofsx/transform.go
- pkg/ddc/juicefs/transform.go
- pkg/ddc/thin/transform.go
- pkg/ddc/vineyard/transform.go
Remove TODO comment which already implemented
fixes #4291
> cleanup: Remove unnecessary comment

- Makefile
Fixed warning in Makefile ( unused build args )
fixes #4298
> Chore: Fixed docker build command in Makefile

- pkg/ddc/jindocache/transform.go
> add fuse properties with default xengine

- charts/fluid/fluid/Chart.yaml
- charts/fluid/fluid/values.yaml
> Build docker images for releasing v1.0.2

- Makefile
- charts/fluid/fluid/Chart.yaml
> Prepare for v1.0.3

- charts/fluid/fluid/Chart.yaml
- charts/fluid/fluid/values.yaml
- pkg/common/label.go
- pkg/ddc/alluxio/transform.go
- pkg/ddc/efc/transform.go
> Docker build for fixing fuse properties of jindocache

- addons/dynamic-mount/ossfs/docker/Dockerfile
Sorting package names alphabetically for better readability and combining RUN commands to reduce Docker image layers
fixes #4308 
I see this ENV: https://github.com/fluid-cloudnative/fluid/blob/master/addons/dynamic-mount/ossfs/docker/Dockerfile#L3
Do we want to set this as ARG (instead of hard coded ENV)?
> Sort packages, optimize Dockerfile

- pkg/csi/plugins/nodeserver.go
> enhance: NodeUnpublishVolume returns early when target path is not existed

- charts/fluid/fluid/templates/_helpers.tpl
- charts/fluid/fluid/templates/controller/alluxioruntime_controller.yaml
- charts/fluid/fluid/templates/controller/dataset_controller.yaml
- charts/fluid/fluid/templates/controller/efcruntime_controller.yaml
- charts/fluid/fluid/templates/controller/fluidapp_controller.yaml
- charts/fluid/fluid/templates/controller/goosefsruntime_controller.yaml
- charts/fluid/fluid/templates/controller/jindoruntime_controller.yaml
- charts/fluid/fluid/templates/controller/juicefsruntime_controller.yaml
- charts/fluid/fluid/templates/controller/thinruntime_controller.yaml
- charts/fluid/fluid/templates/controller/vineyardruntime_controller.yaml
- charts/fluid/fluid/templates/csi/daemonset.yaml
- charts/fluid/fluid/templates/upgrade/crd-upgrade.yaml
- charts/fluid/fluid/templates/webhook/webhook.yaml
- charts/fluid/fluid/values.yaml
- Add root context to imageTransform helm function 
- Allow configurable resources for each runtime controller
- Extract `"fluid.controlplane.affinity"` helm function for all controlplane components.
NONE
> enhance: optimize fluid helm chart

- docs/en/userguide/install.md
- docs/zh/userguide/install.md
> doc: fix installation guide for how to set resources for controllers

- Makefile
As part of #4297 , adding .PHONY for non-file targets helps avoid conflicts with files of the same name.
Part of #4297
> Refactor Makefile: Add .PHONY declarations

- pkg/ddc/jindocache/transform.go
- pkg/ddc/jindocache/transform_worker_test.go
> bugfix: avoid setting "storage.data-dirs.capacity" when using MEM as tieredstore's medium type

- charts/fluid/fluid/Chart.yaml
- charts/fluid/fluid/values.yaml
> Build docker image for supporting dataflow affinity

- pkg/ddc/jindocache/transform.go
- pkg/ddc/jindocache/transform_worker_test.go
This reverts commit e1cac4d22188e360ae3e11ec519d467142d8e827.
Revert PR #4339 because it's a required property.
NONE
> Revert PR #4339

- test/gha-e2e/jindo/minio.yaml
Fix temporary github actions e2e failure caused by minio setup.
NONE
> bugfix: add startup probe to gha-e2e minio setup

- charts/fluid/fluid/Chart.yaml
- charts/fluid/fluid/values.yaml
- pkg/controllers/runtime_controller.go
- pkg/controllers/v1alpha1/dataset/dataset_controller.go
> Docker build for fixing the skipping check mount ready

- CONTRIBUTING.md
- README.md
- docs/en/dev/api_doc.md
- docs/en/dev/pprof.md
> docs updated

- pkg/dataflow/affinity.go
- pkg/dataflow/affinity_test.go
dataflow ensure the dependent operation was completed.
fixes #XXXX
> dataflow ensure the dependent operation was completed

- charts/fluid/fluid/Chart.yaml
- charts/fluid/fluid/values.yaml
> Build docker images for fixing cron dataload with annotations

- Makefile
- charts/fluid/fluid/Chart.yaml
> Prepare for v1.0.4

- Makefile
- charts/fluid/fluid/Chart.yaml
> Revert to v1.0.3

- charts/fluid/fluid/Chart.yaml
- charts/fluid/fluid/values.yaml
> Docker build for fixing NodeUnpublishVolume when checking corrupted

- charts/fluid/fluid/Chart.yaml
> Build docker images for changing ADD to COPY

- pkg/ddc/alluxio/const.go
- pkg/ddc/alluxio/report.go
- pkg/ddc/goosefs/const.go
- pkg/ddc/goosefs/report.go
- pkg/ddc/jindo/cache.go
- pkg/ddc/jindo/const.go
- pkg/ddc/jindocache/cache.go
- pkg/ddc/jindocache/const.go
- pkg/ddc/jindofsx/cache.go
- pkg/ddc/jindofsx/const.go
- pkg/ddc/types/constants.go
> Refactor constraints to improve reuse

- charts/fluid/fluid/Chart.yaml
- charts/fluid/fluid/values.yaml
> Build docker images for fixing CSI no check mount point issue

- Makefile
> Add missing build arg to buildx Makefile targets

- addons/readme-zh_CN.md
- addons/readme.md
> add some file system integration case

- charts/fluid/fluid/templates/controller/thinruntime_controller.yaml
- charts/fluid/fluid/values.yaml
- cmd/thin/app/thin.go
> Support to set the num of maxConcurrentReconciles for ThinRuntimeController

- pkg/ddc/goosefs/cache.go
- pkg/ddc/goosefs/const.go
- pkg/ddc/goosefs/metadata.go
- pkg/ddc/goosefs/report.go
- pkg/ddc/goosefs/transform.go
- pkg/ddc/goosefs/transform_hadoop_config.go
- pkg/ddc/goosefs/ufs_internal.go
- pkg/ddc/goosefs/worker.go
Optimize the naming of goodefs variables
NONE
Just changed the naming of the variables, without altering the code logic
> refactor: Optimize goosefs variable naming

- docs/en/dev/how_to_develop.md
- docs/zh/dev/how_to_develop.md
Correct the development document
NONE
There is an example of an operation command that is missing double quotation marks, causing the use of blocking
> refactor: Correct the development document

- Makefile
> Support docker buildx for vineyard

- pkg/csi/recover/recover.go
- pkg/utils/mountinfo/mountpoint.go
1. sort broken mountpoints orders.
2. fix unexpected variable capture in for-loop.
fixes #XXXX
> fix: sort broken mountpoint and put subpaths at the end.

- pkg/csi/recover/recover.go
- pkg/utils/mountinfo/mountpoint.go
Reverts fluid-cloudnative/fluid#4416
> Revert "fix: sort broken mountpoint and put subpaths at the end."

- charts/goosefs/templates/fuse/daemonset.yaml
- charts/goosefs/templates/master/statefulset.yaml
- charts/goosefs/templates/worker/statefulset.yaml
>   Annotation "sidecar.istio.io/inject" has been deprecated in favor of the "sidecar.istio.io/inject" label and may not work in future Istio versions.
> refactor: Optimize goosefs usage of istio

- MAINTAINERS_COMMITTERS.md
Update committer list. The new committers are voted by TOC members.
fixes the following issues:
https://github.com/fluid-cloudnative/community/issues/59
https://github.com/fluid-cloudnative/community/issues/60
https://github.com/fluid-cloudnative/community/issues/61
https://github.com/fluid-cloudnative/community/issues/62
https://github.com/fluid-cloudnative/community/issues/63
https://github.com/fluid-cloudnative/community/issues/64
https://github.com/fluid-cloudnative/community/issues/65
https://github.com/fluid-cloudnative/community/issues/66
https://github.com/fluid-cloudnative/community/issues/67
see the vote results in the above links.
> Update committer list

- charts/alluxio/templates/fuse/daemonset.yaml
- charts/alluxio/templates/master/statefulset.yaml
- charts/alluxio/templates/worker/statefulset.yaml
> Annotation "sidecar.istio.io/inject" has been deprecated in favor of the "sidecar.istio.io/inject" label and may not work in future Istio versions.
> refactor: Optimize alluxio usage of istio

- charts/juicefs/templates/fuse/daemonset.yaml
- charts/juicefs/templates/worker/statefulset.yaml
> Annotation "sidecar.istio.io/inject" has been deprecated in favor of the "sidecar.istio.io/inject" label and may not work in future Istio versions.
> refactor: Optimize juicefs usage of istio

- charts/fluid/fluid/Chart.yaml
- charts/fluid/fluid/values.yaml
> Build docker images for fixing istio label issue

- addons/dynamic-mount/ossfs/docker/Dockerfile
- docker/Dockerfile.crds
- samples/vineyard/Dockerfile
> Fix LegacyKeyValueFormat issue

- charts/fluid/fluid/Chart.yaml
- charts/fluid/fluid/values.yaml
> Update docker images with github.com/onsi/gomega

- charts/efc/templates/fuse/daemonset.yaml
- charts/efc/templates/master/statefulset.yaml
- charts/efc/templates/worker/statefulset.yaml
> Annotation "sidecar.istio.io/inject" has been deprecated in favor of the "sidecar.istio.io/inject" label and may not work in future Istio versions.
> refactor: Optimize etc usage of istio

- cmd/webhook/app/webhook.go
Support configuration of client QPS and burst in webhooks. Adjust according to the cluster size, apiserver resources, and load conditions.
```
containers:
- args:
- --development=false
- --full-go-profile=false
- --pprof-addr=:6060
- --kube-api-qps=20
- --kube-api-burst=30
```
The following configuration can be applied when deploying the webhook to configure the k8sClient QPS and burst settings.
> Support configuration of k8s client QPS and burst in webhooks.

- charts/fluid/fluid/Chart.yaml
- charts/fluid/fluid/values.yaml
> Build docker images for webhook with QPS configuration

- Makefile
- charts/fluid/fluid/Chart.yaml
> Prepare for v1.0.5

- .circleci/config.yml
- .github/workflows/kind-e2e.yml
- .github/workflows/project-check.yml
- .travis.yml
- docker/Dockerfile.alluxioruntime
- docker/Dockerfile.application
- docker/Dockerfile.csi
- docker/Dockerfile.dataset
- docker/Dockerfile.efcruntime
- docker/Dockerfile.goosefsruntime
- docker/Dockerfile.jindoruntime
- docker/Dockerfile.juicefsruntime
- docker/Dockerfile.thinruntime
- docker/Dockerfile.vineyardruntime
- docker/Dockerfile.webhook
- go.mod
> Update golang v1.22.10

- charts/fluid/fluid/Chart.yaml
- charts/fluid/fluid/values.yaml
> Build docker images for skipping resource check

- pkg/application/inject/fuse/poststart/check_fuse_default.go
- Print timestamp before logging messages in post start script
NONE
> enhance: prettify post start script log for sidecar

- charts/fluid/fluid/Chart.yaml
- charts/fluid/fluid/values.yaml
> Build docker images for enhancing the logging of post start script

- ROADMAP.md
> Roadmap 2025

- charts/fluid/fluid/Chart.yaml
- charts/fluid/fluid/values.yaml
> Build docker images for grpc upgrade

- charts/fluid/fluid/Chart.yaml
- charts/fluid/fluid/values.yaml
> Build docker images for enhancing health check

- charts/fluid/fluid/Chart.yaml
- charts/fluid/fluid/values.yaml
> docker build for enhancing performance in large scale

- Makefile
- charts/fluid/fluid/Chart.yaml
> Prepare for v1.0.6

- charts/fluid/fluid/Chart.yaml
- charts/fluid/fluid/values.yaml
> Build docker images for moving discovering batch job api out of init

- docs/en/samples/juicefs_runtime.md
- docs/zh/samples/juicefs/juicefs_runtime.md
> juicefs docs: more explain in non-required config

- pkg/ddc/alluxio/transform_resources.go
Add comments to transformResourcesForWorker in pkg\ddc\alluxio\transform_resources.go.
fixes #4525
Ⅲ.Special notes for reviews
nothing.
> This PR is to add comments to transformResourcesForWorker in pkg\ddc\alluxio\transform_resources.go.

- charts/fluid/fluid/values.yaml
- pkg/webhook/plugins/fileprefetcher/const.go
- pkg/webhook/plugins/fileprefetcher/file_prefetcher.go
- pkg/webhook/plugins/fileprefetcher/file_prefetcher_test.go
- pkg/webhook/plugins/fileprefetcher/labels.go
- pkg/webhook/plugins/plugins_impl.go
- tools/file-prefetcher/Dockerfile
- tools/file-prefetcher/entrypoint.sh
- tools/file-prefetcher/main.py
> feat: support injecting file prefetcher sidecar to app pods

- charts/fluid/fluid/Chart.yaml
- charts/fluid/fluid/values.yaml
> Docker build for prefetching file

- pkg/ddc/jindo/metadata.go
This PR is to add comments to SyncMetadata in pkg\ddc\jindo\metadata.go.
fixes #4545 
No tests are needed as this PR only adds comments and does not modify functionality.  
This PR only adds documentation comments. No verification is required. 
None.
> Add comments to SyncMetadata in pkg\ddc\jindo\metadata.go

- pkg/ddc/juicefs/delete_volume_test.go
…elete_volume_test.go.
Add comments to TestJuiceFSEngine_DeleteVolume() in pkg/ddc/juicefs/delete_volume_test.go. 
fixes #[4553]
Explain the function and relative parameters, test cases.
> This PR is to add comments to TestJuiceFSEngine_DeleteVolume() in pkg/ddc/juicefs/delete_volume_test.go.

- pkg/ddc/alluxio/master_test.go
Add comments to TestShouldSetupMaster in pkg/ddc/alluxio/master_test.go.
fixes #4596 
> This PR is to add comments to TestShouldSetupMaster in pkg/ddc/alluxio/master_test.go.

- pkg/ddc/alluxio/transform_resources_test.go
…/ddc/alluxio/transform_resources_test.go.
This PR is to add comments to TestTransformResourcesForWorkerWithTieredStore in pkg\ddc\alluxio\transform_resources_test.go.
fixes #4618
> This PR is to add comments to TestTransformResourcesForWorkerWithTieredStore in pkg\ddc\alluxio\transform_resources_test.go.

- pkg/ddc/alluxio/utils_test.go
This PR is to add comments to TestGetMasterPodInfo in pkg\ddc\alluxio\utils_test.go.
fixes #4635
nothing
> This PR is to add comments to TestGetMasterPodInfo in pkg\ddc\alluxio\utils_test.go.

- pkg/ddc/jindo/dataset_test.go
> This PR is to add comments to TestUpdateDatasetStatus  in pkg\ddc\jindo\dataset_test.go

- pkg/ddc/alluxio/replicas_test.go
add description to TestSyncReplicas(t   *testing.T) in pkg\ddc\alluxio\replicas_test.go
fixes #4643
> finish BigData Lab1, fix issue #4643

- pkg/ddc/alluxio/master_test.go
This PR is to add comments to TestSetupMaster in pkg\ddc\alluxio\master_test.go.
fixes #4671
> This PR is to add comments to TestSetupMaster in pkg\ddc\alluxio\master_test.go.

- pkg/ddc/alluxio/utils_test.go
Add detailed comments to the UpdateDatasetStatus function for better code readability.
fixes #4681
> This PR is to add comments to UpdateDatasetStatus in pkj/ddc/alluxio/utils_test.go.

- pkg/ddc/alluxio/transform_ufs_test.go
Add comments to TestTransformDatasetToPVC in pkg/ddc/alluxio/transform_ufs_test.go
fixes #4686
Please review and merge. Thanks!
> This PR is to add comments to TestTransformDatasetToPVC in pkg/ddc/alluxio/transform_ufs_test.go.

- pkg/ddc/alluxio/ufs_test.go
Add comments to TestTotalStorageBytes in pkg\ddc\alluxio\ufs_test.go
fixes #4692
> This PR is to add comments to TestTotalStorageBytes in pkg\ddc\alluxio\ufs_test.go. 

- pkg/ddc/jindo/load_data_test.go
Ⅰ. Describe what this PR does  
Added function comments for TestGenerateDataLoadValueFileWithRuntimeHDD in pkg/ddc/jindo/load_data_test.go.  
Ⅱ. Does this pull request fix one issue?  
fixes #4747  
Ⅲ. Special notes for reviews  
This PR only adds function comments. No logic changes.
> This PR is to add comments to TestGenerateDataLoadValueFileWithRuntimeHDD in pkg/ddc/jindo/load_data_test.go.

- pkg/ddc/alluxio/delete_volume_test.go
Add comments to newTestAlluxioEngine in pkg/ddc/alluxio/delete_volume_test.go
fixes #4719
> This PR is to add comments to newTestAlluxioEngine in pkg/ddc/alluxio/delete_volume_test.go

- pkg/ddc/alluxio/transform_volumes_test.go
…nsform_volumes_test.go.
add comments to TestTransformFuseVolumes in fluid/pkg/ddc/alluxio/transform_volumes_test.go.
fixes #4723
> This PR is add comments to TestTransformFuseVolumes in fluid/pkg/ddc/alluxio/transform_volumes_test.go.

- pkg/ddc/alluxio/load_data_test.go
add comments Test_genDataLoadValue in /pkg/ddc/alluxio/load_data_test.go
fixes #4755
> This PR is to add comments Test_genDataLoadValue in /pkg/ddc/alluxio/load_data_test.go

- .github/workflows/project-check.yml
- charts/fluid/fluid/Chart.yaml
- charts/fluid/fluid/values.yaml
- pkg/ddc/alluxio/delete_volume_test.go
- pkg/ddc/alluxio/transform_ufs_test.go
- pkg/ddc/alluxio/transform_volumes_test.go
- pkg/ddc/alluxio/ufs_test.go
- pkg/ddc/alluxio/utils_test.go
- pkg/ddc/jindo/load_data_test.go
- pkg/ddc/juicefs/datasetinfo_parser.go
> Docker build 250322

- charts/fluid/fluid/Chart.yaml
- charts/fluid/fluid/values.yaml
> docker build for golang 1.23.7

- pkg/ddc/juicefs/create_volume_test.go
…dc\juicefs\create_volume_test.go
Add notation to TestJuiceFSEngine_createFusePersistentVolume in pkg\ddc\juicefs\create_volume_test.go
fixes #4758
> Add notation to TestJuiceFSEngine_createFusePersistentVolume in pkg\ddc\juicefs\create_volume_test.go

- pkg/ddc/alluxio/utils_test.go
…_test.go
Add comments to TestGetMasterStatefulsetName in pkg\ddc\alluxio\utils_test.go.
fixes #4771
> This PR is to add comments to TestGetMasterStatefulsetName in pkg\ddc\alluxio\utils_test.go.

- pkg/ddc/juicefs/dataset_test.go
Add comments to TestBindToDataset in pkg/ddc/juicefs/dataset_test.go.
fixes #4784
> This PR is to add comments to TestBindToDataset in pkg/ddc/juicefs/dataset_test.go.

- pkg/ddc/alluxio/hcfs_test.go
This PR is to add comments to TestQueryHCFSEndpoint(t *testing.T) in pkg\ddc\alluxio\hcfs_test.go
fixes #4787
> This PR is to add comments to TestQueryHCFSEndpoint(t *testing.T) in pkg\ddc\alluxio\hcfs_test.go

- pkg/dataprocess/generate_values.go
- pkg/ddc/alluxio/transform_test.go
- pkg/ddc/alluxio/utils_test.go
- pkg/ddc/base/template_engine_test.go
- pkg/ddc/goosefs/utils_test.go
- pkg/ddc/jindo/utils_test.go
- pkg/ddc/jindocache/transform_test.go
- pkg/ddc/jindocache/utils_test.go
- pkg/ddc/jindofsx/transform_test.go
- pkg/ddc/jindofsx/utils_test.go
- pkg/ddc/vineyard/operations/base.go
- pkg/ddc/vineyard/transform_test.go
- pkg/utils/crtl_utils_test.go
- pkg/utils/mount_test.go
- pkg/utils/mountinfo/mountinfo.go
- pkg/utils/yaml.go
> Fix not checking return value issue

- hack/sdk/main.go
- pkg/utils/crtl_utils_test.go
> Use replace all instead

- pkg/ddc/alluxio/metadata_test.go
I. Describe what this PR does
This PR is to add comments to TestRestoreMetadataInternal in pkg\ddc\alluxio\metadata_test.go.
II. Does this pull request fix one issue?
fixes #4793
IlI. Special notes for reviews
>  This PR is to add comments to TestRestoreMetadataInternal in pkg\ddc\alluxio\metadata_test.go.

- pkg/ddc/juicefs/datasetinfo_parser_test.go
Add comments to Test_parseCacheInfoFromConfigMap in pkg\ddc\juicefs\datasetinfo_parser_test.go.
fixes #4797
> This PR is to add comments to Test_parseCacheInfoFromConfigMap in pkg\ddc\juicefs\datasetinfo_parser_test.go.

- test/prow/fluid/fluidapi.py
- test/prow/scale_runtime.py
- test/prow/testcases/alluxio/alluxio_dynamic_mountpoint.py
- test/prow/testcases/common/csi_stale_patch.py
- test/prow/testcases/common/dataset_pvc_subpath.py
> minorfix: change web ufs url to ustc mirror

- pkg/ddc/alluxio/transform_optimization_test.go
Add comments to TestOptimizeDefaultForFuseNoValue in pkg\ddc\alluxio\transform_optimization_test.go.
fixes #4805
> This PR is to add comments to TestOptimizeDefaultForFuseNoValue in pkg\ddc\alluxio\transform_optimization_test.go.

- pkg/ddc/alluxio/node_test.go
add comments to getTestAlluxioEngineNode in pkg\ddc\alluxio\node_test.go
fixes #4820
> This PR is to add comments to getTestAlluxioEngineNode in pkg\ddc\alluxio\node_test.go

- charts/fluid/fluid/templates/controller/alluxioruntime_controller.yaml
- charts/fluid/fluid/templates/controller/dataset_controller.yaml
- charts/fluid/fluid/templates/controller/efcruntime_controller.yaml
- charts/fluid/fluid/templates/controller/goosefsruntime_controller.yaml
- charts/fluid/fluid/templates/controller/jindoruntime_controller.yaml
- charts/fluid/fluid/templates/controller/juicefsruntime_controller.yaml
- charts/fluid/fluid/templates/controller/thinruntime_controller.yaml
- charts/fluid/fluid/templates/controller/vineyardruntime_controller.yaml
- charts/fluid/fluid/values.yaml
> Feat: add helm config

- charts/fluid/fluid/Chart.yaml
- charts/fluid/fluid/values.yaml
> Build docker images for supporting vineyard customization

- charts/fluid/fluid/Chart.yaml
- charts/fluid/fluid/values.yaml
> Build Docker images to support transparent FUSE upgrade

- pkg/ddc/alluxio/cache_test.go
…c\alluxio\cache_test.go.
Add comments to TestAlluxioEngine_getGracefulShutdownLimits in pkg\ddc\alluxio\cache_test.go.
fixes #4532
> This PR is to add comments to TestAlluxioEngine_getGracefulShutdownLimits in pkg\ddc\alluxio\cache_test.go.

- pkg/ddc/jindo/load_data_test.go
This PR is to add comments to Test_genDataLoadValue in pkg\ddc\jindo\load_data_test.go
fixes #4581 
> This PR is to add comments to Test_genDataLoadValue in pkg\ddc\jindo\load_data_test.go

- pkg/ddc/alluxio/transform_resources.go
- pkg/ddc/jindo/load_data_test.go
This PR is to add comments to transformResoursesForMaster in pkg\ddc\alluxio\transform_resources.go
fixes #4607
Please check if the comments clearly describe the function's purpose and test process.
Any suggestions for better clarity are welcome.
> This PR is to add comments to transformResoursesForMaster in pkg\ddc\alluxio\transform_resources.go

- pkg/ddc/alluxio/create_volume_test.go
This PR adds detailed comments to the TestCreateFusePersistentVolumeClaim unit test in create_volume_test.go under the pkg/ddc/alluxio package.
The comment block now follows the documentation style used in other functions, providing a clearer explanation of the test’s purpose, setup, and validation logic. This enhancement improves the readability and maintainability of the test code for future contributors.
fixes #4857
> This PR is to add comments to TestCreateFusePersistentVolumeClaim in pkg/ddc/alluxio/create_volume_test.go

- charts/fluid/fluid/Chart.yaml
- charts/fluid/fluid/values.yaml
> Build docker images for lightweight thinRuntime

- charts/fluid/fluid/Chart.yaml
- charts/fluid/fluid/values.yaml
> Build docker images for lightweighting thin runtime resource

- pkg/ddc/juicefs/data_migrate_test.go
Add Notation to TestJuiceFSEngine_generateDataMigrateValueFile in pkg\ddc\juicefs\data_migrate_test.go.
fixes #4874
> This PR is to add comments to TestJuiceFSEngine_generateDataMigrateValueFile in pkg\ddc\juicefs\data_migrate_test.go.

- pkg/ddc/jindo/dataset.go
- pkg/ddc/jindo/load_data_test.go
This PR adds comments to the `TestCheckRuntimeReady` function in `.pkg/ddc/jindo/load_data_test.go`, providing a detailed explanation of its purpose, parameters, and return values. This improves code readability and maintainability.
fixes #4753
> This PR is to add comments to TestCheckRuntimeReady in pkg/ddc/jindo/load_data_test.go

- charts/fluid/fluid/Chart.yaml
- charts/fluid/fluid/values.yaml
> Build docker images for fixing juicefsruntime frequent update issue

- pkg/ddc/alluxio/ufs_test.go
Add comments to TestTotalFileNums in pkg\ddc\alluxio\ufs_test.go.
fixes #4910
> This PR is to add comments to TestTotalFileNums in pkg\ddc\alluxio\ufs_test.go.

- pkg/ddc/alluxio/transform_volumes_test.go
add comments to TestTransformMasterVolumes(t *testing.T) in pkg\ddc\alluxio\transform_volumes_test.go
fixes #4984
> This PR is to add comments to TestTransformMasterVolumes(t *testing.T) in pkg\ddc\alluxio\transform_volumes_test.go

- pkg/ddc/alluxio/report_test.go
add  comments to TestParseReportMetric in pkg/ddc/alluxio/report_test.go
fixes #5050
> This PR is to add  comments to TestParseReportMetric in pkg/ddc/alluxio/report_test.go

- pkg/ddc/alluxio/transform_test.go
This PR is to add comments to TestTransformFuse in pkg/ddc/alluxio/transform_test.go
fixes #5040
> This PR is to add comments to TestTransformFuse in pkg/ddc/alluxio/transform_test.go

- pkg/ddc/alluxio/transform_test.go
This PR is to add comments to TestTransformPodMetadata(t *testing.T) in pkg\ddc\alluxio\transform_test.go.
fixes #5043
> This PR is to add comments to TestTransformPodMetadata(t *testing.T) in pkg\ddc\alluxio\transform_test.go. 

- pkg/ddc/alluxio/metadata_test.go
This PR adds detailed comments to the TestSyncMetadata function to improve code documentation and maintainability.
fixes #5047
> This PR is to add comments to TestSyncMetadata in pkg/ddc/alluxio/metadata_test.go

- pkg/ddc/alluxio/health_check_test.go
add comments to TestCheckWorkersHealthy in pkg\ddc\alluxio\health_check_test.go.
fixes #5022
> This PR is to add comments to TestCheckWorkersHealthy in pkg\ddc\alluxio\health_check_test.go.

- pkg/ddc/alluxio/ufs_test.go
Add comments to TestFreeStorageBytes in pkg\ddc\alluxio\ufs_test.go.
fixes #5067
> This PR is to add comments to TestFreeStorageBytes in pkg\ddc\alluxio\ufs_test.go.

- pkg/ddc/juicefs/create_volume_test.go
Add comments to TestJuiceFSEngine_CreateVolume in pkg/ddc/juicefs/create_volume_test.go.
fixes #4774
> This PR is to add comments to TestJuiceFSEngine_CreateVolume in pkg/ddc/juicefs/create_volume_test.go.

- pkg/ddc/alluxio/hcfs_test.go
This PR is to add comments to TestGetHCFSStatus in pkg/ddc/alluxio/hcfs_test.go.
fixes #5075
> Add Notation to TestGetHCFSStatus in pkg/ddc/alluxio/hcfs_test.go.

- pkg/ddc/alluxio/ufs_test.go
Add comments to TestCheckRuntimeHealthy in pkg/ddc/alluxio/health_check_test.go
fixes #4927
> This PR is to add comments to TestCheckRuntimeHealthy in pkg/ddc/alluxio/health_check_test.go.

- docker/Dockerfile.alluxioruntime
- docker/Dockerfile.application
- docker/Dockerfile.crds
- docker/Dockerfile.csi
- docker/Dockerfile.dataset
- docker/Dockerfile.efcruntime
- docker/Dockerfile.goosefsruntime
- docker/Dockerfile.jindoruntime
- docker/Dockerfile.juicefsruntime
- docker/Dockerfile.thinruntime
- docker/Dockerfile.vineyardruntime
- docker/Dockerfile.webhook
Bump alpine to 3.20.6 and golang to 1.23.10
NONE
> Bump alpine to 3.20.6 and golang to 1.23.10

- pkg/utils/dataset/volume/create.go
> enhance: optimize volume binding efficiency

- .circleci/config.yml
- charts/fluid/fluid/Chart.yaml
- charts/fluid/fluid/values.yaml
> Build candidate Docker image for version 1.0.6

- charts/fluid/fluid/Chart.yaml
- charts/fluid/fluid/values.yaml
> Build docker images for fixing reference dataset volume binding failure

- charts/fluid/fluid/templates/webhook/webhook.yaml
> typofix: typo fix for FILE_PREFETCHER_IMAGE env variable

- charts/fluid/fluid/Chart.yaml
- charts/fluid/fluid/values.yaml
> Build docker images for supporting unique hostpath in sidecar mode

- CONTRIBUTING.md
> Fix broken link issue of CoC

- Makefile
> chore: bump helm version to v3.18.4

- .github/workflows/kind-e2e.yml
> chore: update github actions e2e k8s version

- charts/fluid/fluid/Chart.yaml
- charts/fluid/fluid/values.yaml
- pkg/ddc/jindo/delete_volume_test.go
> Build docker images for updating golang.org/x/oauth2

- CHANGELOG.md
- Makefile
- README-zh_CN.md
- README.md
- charts/fluid/fluid/Chart.yaml
Update Chart.yaml to v1.0.8
Update changelog
fixes #XXXX
> Update Makefile/Chart to v1.0.8

- pkg/application/inject/fuse/mutator/mutator_default_test.go
- pkg/application/inject/fuse/mutator/mutator_suite_test.go
- pkg/application/inject/fuse/mutator/mutator_unprivileged_test.go
- Add unit tests for DefaultMutator behavior
- Add unit tests for UnprivilegedMutator behavior
NONE
> add unit tests for default and unprivileged fuse sidecar mutators

- samples/accelerate/app.yaml
- samples/accelerate/nginx.yaml
- samples/juicefs/minio.yaml
- samples/juicefs/redis.yaml
- samples/ufspath/app.yaml
- test/gha-e2e/alluxio/job.yaml
- test/gha-e2e/jindo/job.yaml
- test/gha-e2e/jindo/minio.yaml
Fix sa restriction vulnerability in code scan 
fixes #XXXX
Code scan result
> Fix sa restriction in samples

- charts/fluid/fluid/Chart.yaml
- charts/fluid/fluid/values.yaml
> Build docker images for  v1.0.8 alpha version
